

#include "subgroup_transformations.hpp"
// DO NOT MODIFY, autogenerated from the /scripts directory
namespace wmtk::autogen::subgroup {

const int8_t subgroup_indices_0_0[2] = {0, 1};

const int8_t subgroup_indices_1_0[6] = {-1, 0, -1, 1, -1, -1};

const int8_t subgroup_indices_0_1[2] = {1, 3};

const int8_t subgroup_indices_1_1[6] = {0, 1, 2, 3, 4, 5};

const int8_t subgroup_indices_2_0[24] = {-1, 0,  -1, -1, -1, -1, -1, 1,  -1, -1, -1, -1,
                                         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

const int8_t subgroup_indices_0_2[2] = {1, 7};

const int8_t subgroup_indices_2_1[24] = {-1, 1, -1, 0, -1, -1, -1, 3,  -1, 2,  -1, -1,
                                         -1, 5, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1};

const int8_t subgroup_indices_1_2[6] = {3, 1, 9, 7, 15, 13};

const int8_t subgroup_indices_2_2[24] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};


const int8_t* remap_table[3][3] = {

    {

        subgroup_indices_0_0,

        subgroup_indices_0_1,

        subgroup_indices_0_2,

    },

    {

        subgroup_indices_1_0,

        subgroup_indices_1_1,

        subgroup_indices_1_2,

    },

    {

        subgroup_indices_2_0,

        subgroup_indices_2_1,

        subgroup_indices_2_2,

    },

};
} // namespace wmtk::autogen::subgroup
