#pragma once

// DO NOT MODIFY, autogenerated from the /scripts directory

#include <cstdint>
namespace wmtk::autogen::subgroup {

extern const int8_t subgroup_indices_0_0[2];

extern const int8_t subgroup_indices_1_0[6];

extern const int8_t subgroup_indices_0_1[2];

extern const int8_t subgroup_indices_1_1[6];

extern const int8_t subgroup_indices_2_0[24];

extern const int8_t subgroup_indices_0_2[2];

extern const int8_t subgroup_indices_2_1[24];

extern const int8_t subgroup_indices_1_2[6];

extern const int8_t subgroup_indices_2_2[24];

extern const int8_t* remap_table[3][3];

} // namespace wmtk::autogen::subgroup
