#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include <array>
#include <cstdint>
#include <wmtk/PrimitiveType.hpp>

namespace wmtk::autogen::utils {
int8_t subdart_maximal_action_to_face_action(
    PrimitiveType mesh_type,
    int8_t dart_index,
    PrimitiveType primitive_type,
    int8_t simplex_index);
int8_t subdart_maximal_action_to_face_action(
    PrimitiveType mesh_type,
    int8_t dart_index,
    int8_t simplex_dimension,
    int8_t simplex_index);

int8_t subdart_maximal_action_to_face_size(
    PrimitiveType mesh_type,
    int8_t dart_index,
    PrimitiveType primitive_type,
    int8_t simplex_index);
int8_t subdart_maximal_action_to_face_size(
    PrimitiveType mesh_type,
    int8_t dart_index,
    int8_t simplex_dimension,
    int8_t simplex_index);


std::array<int8_t, 2> subdart_maximal_action_to_face(
    PrimitiveType mesh_type,
    int8_t dart_index,
    PrimitiveType primitive_type,
    int8_t simplex_index);
std::array<int8_t, 2> subdart_maximal_action_to_face(
    PrimitiveType mesh_type,
    int8_t dart_index,
    int8_t simplex_dimension,
    int8_t simplex_index);
} // namespace wmtk::autogen::utils
