Wildmeshing Toolkit: wmtk::operations::composite::TetEdgeSwap Class Reference
wmtk::operations::composite::TetEdgeSwap Class Reference
Performs an edge swap, implemented as a combination of swap and collapse.
#include <TetEdgeSwap.hpp>
Public Member Functions
TetEdgeSwap (Mesh &m, int64_t collapse_index=0)
PrimitiveType primitive_type () const override
EdgeSplit & split ()
EdgeCollapse & collapse ()
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
virtual std::vector< simplex::Simplex > operator() (const simplex::Simplex &simplex)
virtual double priority (const simplex::Simplex &simplex) const
virtual bool use_random_priority () const
virtual bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< double(const simplex::Simplex &)> &func)
std::shared_ptr< operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandle &attribute)
void add_transfer_strategy (const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
virtual void reserve_enough_simplices ()
Protected Member Functions
std::vector< simplex::Simplex > unmodified_primitives (const simplex::Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
std::vector< simplex::Simplex > execute (const simplex::Simplex &simplex) override
returns an empty vector in case of failure
Protected Member Functions inherited from wmtk::operations::Operation
virtual bool before (const simplex::Simplex &simplex) const
virtual bool after (const std::vector< simplex::Simplex > &unmods, const std::vector< simplex::Simplex > &mods) const
void apply_attribute_transfer (const std::vector< simplex::Simplex > &direct_mods)
Private Attributes
EdgeSplit m_split
EdgeCollapse m_collapse
int64_t m_collapse_index
Additional Inherited Members
Protected Attributes inherited from wmtk::operations::Operation
std::function< double(const simplex::Simplex &)> m_priority = nullptr
invariants::InvariantCollection m_invariants
std::vector< std::shared_ptr< operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Performs an edge swap, implemented as a combination of swap and collapse.
When swapping an edge, one first split the edge (that splits all the tets incident to that edge), then collapse the edge with index collapse_index.)
Edge swap cannot be performed on boundary edges.
Definition at line 18 of file TetEdgeSwap.hpp.
Constructor & Destructor Documentation
TetEdgeSwap()
wmtk::operations::composite::TetEdgeSwap::TetEdgeSwap (Mesh & m, int64_t collapse_index = 0)
Definition at line 10 of file TetEdgeSwap.cpp.
Member Function Documentation
collapse()
EdgeCollapse& wmtk::operations::composite::TetEdgeSwap::collapse () inline
Definition at line 26 of file TetEdgeSwap.hpp.
References m_collapse.
execute()
std::vector< simplex::Simplex > wmtk::operations::composite::TetEdgeSwap::execute (const simplex::Simplex & simplex) override protected virtual
returns an empty vector in case of failure
Implements wmtk::operations::Operation.
Definition at line 17 of file TetEdgeSwap.cpp.
References wmtk::simplex::closed_star(), wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::simplex::Simplex::face(), wmtk::simplex::SimplexCollection::get_intersection(), wmtk::get_primitive_type_id(), wmtk::simplex::utils::SimplexComparisons::less(), m_collapse, m_collapse_index, m_split, wmtk::operations::Operation::mesh(), wmtk::simplex::open_star(), wmtk::operations::EdgeCollapse::primitive_type(), wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::simplex::Simplex::vertex().
primitive_type()
PrimitiveType wmtk::operations::composite::TetEdgeSwap::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 23 of file TetEdgeSwap.hpp.
References wmtk::Edge.
split()
EdgeSplit& wmtk::operations::composite::TetEdgeSwap::split () inline
Definition at line 25 of file TetEdgeSwap.hpp.
References m_split.
unmodified_primitives()
std::vector< simplex::Simplex > wmtk::operations::composite::TetEdgeSwap::unmodified_primitives (const simplex::Simplex & simplex) const override protected virtual
Returns all simplices that will be potentially affected by the operation.
Implements wmtk::operations::Operation.
Definition at line 159 of file TetEdgeSwap.cpp.
Member Data Documentation
m_collapse
EdgeCollapse wmtk::operations::composite::TetEdgeSwap::m_collapse private
Definition at line 36 of file TetEdgeSwap.hpp.
Referenced by collapse(), and execute().
m_collapse_index
int64_t wmtk::operations::composite::TetEdgeSwap::m_collapse_index private
Definition at line 37 of file TetEdgeSwap.hpp.
Referenced by execute().
m_split
EdgeSplit wmtk::operations::composite::TetEdgeSwap::m_split private
Definition at line 35 of file TetEdgeSwap.hpp.
Referenced by execute(), and split().
The documentation for this class was generated from the following files:
src/wmtk/operations/composite/TetEdgeSwap.hpp
src/wmtk/operations/composite/TetEdgeSwap.cpp