Wildmeshing Toolkit: wmtk::components::input::MeshCollection Class Reference
wmtk::components::input::MeshCollection Class Reference
#include <MeshCollection.hpp>
Public Member Functions
NamedMultiMesh & add_mesh (NamedMultiMesh o)
NamedMultiMesh & add_mesh (const InputOptions &opts)
const NamedMultiMesh & get_named_multimesh (const std::string_view &path) const
const Mesh & get_mesh (const std::string_view &path) const
NamedMultiMesh & get_named_multimesh (const std::string_view &path)
Mesh & get_mesh (const std::string_view &path)
Private Attributes
std::map< std::string_view, NamedMultiMesh > m_meshes
Detailed Description
Definition at line 8 of file MeshCollection.hpp.
Member Function Documentation
add_mesh() [1/2]
NamedMultiMesh & wmtk::components::input::MeshCollection::add_mesh (const InputOptions & opts)
Definition at line 17 of file MeshCollection.cpp.
References add_mesh(), and wmtk::components::input::input().
add_mesh() [2/2]
NamedMultiMesh & wmtk::components::input::MeshCollection::add_mesh (NamedMultiMesh o)
Definition at line 11 of file MeshCollection.cpp.
References m_meshes, and wmtk::components::input::NamedMultiMesh::root_name().
Referenced by add_mesh().
get_mesh() [1/2]
Mesh & wmtk::components::input::MeshCollection::get_mesh (const std::string_view & path)
Definition at line 38 of file MeshCollection.cpp.
References wmtk::components::input::NamedMultiMesh::get_mesh(), and get_named_multimesh().
get_mesh() [2/2]
const Mesh & wmtk::components::input::MeshCollection::get_mesh (const std::string_view & path) const
Definition at line 33 of file MeshCollection.cpp.
References wmtk::components::input::NamedMultiMesh::get_mesh(), and get_named_multimesh().
Referenced by wmtk::components::input::utils::get_attribute().
get_named_multimesh() [1/2]
NamedMultiMesh & wmtk::components::input::MeshCollection::get_named_multimesh (const std::string_view & path)
Definition at line 42 of file MeshCollection.cpp.
References wmtk::logger(), m_meshes, and wmtk::components::input::internal::split_path().
get_named_multimesh() [2/2]
const NamedMultiMesh & wmtk::components::input::MeshCollection::get_named_multimesh (const std::string_view & path) const
Definition at line 23 of file MeshCollection.cpp.
References wmtk::logger(), m_meshes, and wmtk::components::input::internal::split_path().
Referenced by get_mesh().
Member Data Documentation
m_meshes
std::map<std::string_view, NamedMultiMesh> wmtk::components::input::MeshCollection::m_meshes private
Definition at line 23 of file MeshCollection.hpp.
Referenced by add_mesh(), and get_named_multimesh().
The documentation for this class was generated from the following files:
components/input/src/wmtk/components/input/MeshCollection.hpp
components/input/src/wmtk/components/input/MeshCollection.cpp