Wildmeshing Toolkit: wmtk::autogen::Dart Class Reference
wmtk::autogen::Dart Class Reference
#include <Dart.hpp>
Public Types
using tuple_type = std::tuple< int64_t, int8_t >
Public Member Functions
Dart ()
int64_t & global_id ()
int64_t global_id () const
int8_t & local_orientation ()
int8_t local_orientation () const
bool is_null () const
operator std::string () const
const tuple_type & as_tuple () const
Detailed Description
Definition at line 7 of file Dart.hpp.
Member Typedef Documentation
tuple_type
using wmtk::autogen::Dart::tuple_type = std::tuple<int64_t, int8_t>
Definition at line 10 of file Dart.hpp.
Constructor & Destructor Documentation
Dart()
wmtk::autogen::Dart::Dart () inline
Definition at line 12 of file Dart.hpp.
Member Function Documentation
as_tuple()
const tuple_type& wmtk::autogen::Dart::as_tuple () const inline
Definition at line 25 of file Dart.hpp.
global_id() [1/2]
int64_t& wmtk::autogen::Dart::global_id () inline
Definition at line 15 of file Dart.hpp.
Referenced by wmtk::autogen::SimplexDart::act(), is_null(), wmtk::autogen::local_dart_action(), and wmtk::autogen::SimplexDart::tuple_from_dart().
global_id() [2/2]
int64_t wmtk::autogen::Dart::global_id () const inline
Definition at line 16 of file Dart.hpp.
is_null()
bool wmtk::autogen::Dart::is_null () const inline
Definition at line 21 of file Dart.hpp.
References global_id().
local_orientation() [1/2]
int8_t& wmtk::autogen::Dart::local_orientation () inline
Definition at line 18 of file Dart.hpp.
Referenced by wmtk::autogen::SimplexDart::act(), wmtk::multimesh::utils::find_local_dart_action(), wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action(), wmtk::autogen::local_dart_action(), wmtk::autogen::SimplexDart::simplex_index(), and wmtk::autogen::SimplexDart::tuple_from_dart().
local_orientation() [2/2]
int8_t wmtk::autogen::Dart::local_orientation () const inline
Definition at line 19 of file Dart.hpp.
operator std::string()
wmtk::autogen::Dart::operator std::string () const
Definition at line 6 of file Dart.cpp.
The documentation for this class was generated from the following files:
src/wmtk/autogen/Dart.hpp
src/wmtk/autogen/Dart.cpp