Wildmeshing Toolkit: wmtk::simplex::utils::SimplexComparisons Class Reference
wmtk::simplex::utils::SimplexComparisons Class Reference
#include <SimplexComparisons.hpp>
Static Public Member Functions
static bool equal (const Mesh &m, const Simplex &s0, const Simplex &s1)
static bool equal (const Mesh &m, const Tuple &a, PrimitiveType a_pt, const Tuple &b, PrimitiveType b_pt)
static bool equal (const Mesh &m, PrimitiveType primitive_type, const Tuple &a, const Tuple &b)
static bool equal (const Mesh &m, const IdSimplex &s0, const IdSimplex &s1)
static bool less (const Mesh &m, const Simplex &s0, const Simplex &s1)
static bool less (const Mesh &m, const IdSimplex &s0, const IdSimplex &s1)
static bool less (const Mesh &m, const Tuple &a, PrimitiveType a_pt, const Tuple &b, PrimitiveType b_pt)
static bool less (const Mesh &m, PrimitiveType primitive_type, const Tuple &a, const Tuple &b)
Detailed Description
Definition at line 11 of file SimplexComparisons.hpp.
Member Function Documentation
equal() [1/4]
bool wmtk::simplex::utils::SimplexComparisons::equal (const Mesh & m, const IdSimplex & s0, const IdSimplex & s1) inline static
Definition at line 39 of file SimplexComparisons.hxx.
equal() [2/4]
bool wmtk::simplex::utils::SimplexComparisons::equal (const Mesh & m, const Simplex & s0, const Simplex & s1) inline static
Definition at line 8 of file SimplexComparisons.hxx.
References wmtk::Mesh::id(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::invariants::CollapseEnergyBeforeInvariant::before(), wmtk::invariants::CollapseEnergyBeforeInvariantDouble::before(), wmtk::invariants::CollapseSoftEnergyBeforeInvariant::before(), equal(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute(), wmtk::TriMesh::TriMeshOperationExecutor::get_incident_face_data(), wmtk::function::utils::get_simplex_attributes(), wmtk::simplex::link_condition(), wmtk::simplex::utils::MeshSimplexComparator::Equal::operator()(), wmtk::simplex::internal::SimplexEqualFunctor::operator()(), and wmtk::simplex::internal::HomogeneousSimplexEqualFunctor::operator()().
equal() [3/4]
bool wmtk::simplex::utils::SimplexComparisons::equal (const Mesh & m, const Tuple & a, PrimitiveType a_pt, const Tuple & b, PrimitiveType b_pt) inline static
Definition at line 21 of file SimplexComparisons.hxx.
References equal().
equal() [4/4]
bool wmtk::simplex::utils::SimplexComparisons::equal (const Mesh & m, PrimitiveType primitive_type, const Tuple & a, const Tuple & b) inline static
Definition at line 30 of file SimplexComparisons.hxx.
References wmtk::Mesh::id().
less() [1/4]
bool wmtk::simplex::utils::SimplexComparisons::less (const Mesh & m, const IdSimplex & s0, const IdSimplex & s1) inline static
Definition at line 58 of file SimplexComparisons.hxx.
less() [2/4]
bool wmtk::simplex::utils::SimplexComparisons::less (const Mesh & m, const Simplex & s0, const Simplex & s1) inline static
Definition at line 44 of file SimplexComparisons.hxx.
References wmtk::Mesh::id(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::operations::composite::TetEdgeSwap::execute(), less(), wmtk::simplex::utils::MeshSimplexComparator::Less::operator()(), wmtk::simplex::internal::SimplexLessFunctor::operator()(), and wmtk::simplex::internal::HomogeneousSimplexLessFunctor::operator()().
less() [3/4]
bool wmtk::simplex::utils::SimplexComparisons::less (const Mesh & m, const Tuple & a, PrimitiveType a_pt, const Tuple & b, PrimitiveType b_pt) inline static
Definition at line 63 of file SimplexComparisons.hxx.
References less().
less() [4/4]
bool wmtk::simplex::utils::SimplexComparisons::less (const Mesh & m, PrimitiveType primitive_type, const Tuple & a, const Tuple & b) inline static
Definition at line 76 of file SimplexComparisons.hxx.
References wmtk::Mesh::id().
The documentation for this class was generated from the following files:
src/wmtk/simplex/utils/SimplexComparisons.hpp
src/wmtk/simplex/utils/SimplexComparisons.hxx