Wildmeshing Toolkit: wmtk::attribute::MeshAttributeHandle Class Reference
wmtk::attribute::MeshAttributeHandle Class Reference
#include <MeshAttributeHandle.hpp>
Public Types
using HandleVariant = std::variant< TypedAttributeHandle< char >, TypedAttributeHandle< int64_t >, TypedAttributeHandle< double >, TypedAttributeHandle< wmtk::Rational > >
using ValueVariant = std::variant< char, int64_t, double, wmtk::Rational, std::tuple< char, wmtk::Rational, double > >
using HeldType = AttributeType
template<HeldType Type>
using held_handle_type = std::variant_alternative_t< size_t(Type), HandleVariant >
template<HeldType Type>
using held_primitive_type = typename held_handle_type< Type >::Type
Public Member Functions
MeshAttributeHandle ()=default
MeshAttributeHandle (Mesh &m, const HandleVariant &h)
MeshAttributeHandle (const MeshAttributeHandle &o)=default
MeshAttributeHandle (MeshAttributeHandle &&o)=default
MeshAttributeHandle & operator= (const MeshAttributeHandle &o)=default
MeshAttributeHandle & operator= (MeshAttributeHandle &&o)=default
bool operator== (const MeshAttributeHandle &o) const
bool is_same_mesh (const Mesh &) const
bool is_valid () const
PrimitiveType primitive_type () const
template<typename T >
PrimitiveType primitive_typeT () const
template<typename T >
auto as () const -> const held_handle_type< held_type_from_primitive< T >()> &
template<HeldType Type>
auto as_from_held_type () const -> const held_handle_type< Type > &
template<typename T >
bool holds () const
bool holds_basic_type () const
template<HeldType Type>
bool holds_from_held_type () const
HeldType held_type () const
Mesh & mesh ()
const Mesh & mesh () const
HandleVariant & handle ()
const HandleVariant & handle () const
int64_t dimension () const
std::string name () const
template<typename T >
constexpr auto held_type_from_primitive () -> HeldType
template<typename T >
constexpr auto held_type_from_handle () -> HeldType
Static Public Member Functions
template<typename T >
static constexpr HeldType held_type_from_primitive ()
template<typename T >
static constexpr HeldType held_type_from_handle ()
template<typename T >
static constexpr bool handle_type_is_basic ()
Private Attributes
Mesh * m_mesh = nullptr
HandleVariant m_handle
Friends
class wmtk::Mesh
class wmtk::hash< MeshAttributeHandle >
Detailed Description
Definition at line 27 of file MeshAttributeHandle.hpp.
Member Typedef Documentation
HandleVariant
using wmtk::attribute::MeshAttributeHandle::HandleVariant = std::variant< TypedAttributeHandle<char>, TypedAttributeHandle<int64_t>, TypedAttributeHandle<double>, TypedAttributeHandle<wmtk::Rational> >
Definition at line 34 of file MeshAttributeHandle.hpp.
held_handle_type
template<HeldType Type> using wmtk::attribute::MeshAttributeHandle::held_handle_type = std::variant_alternative_t<size_t(Type), HandleVariant>
Definition at line 47 of file MeshAttributeHandle.hpp.
held_primitive_type
template<HeldType Type> using wmtk::attribute::MeshAttributeHandle::held_primitive_type = typename held_handle_type<Type>::Type
Definition at line 50 of file MeshAttributeHandle.hpp.
HeldType
using wmtk::attribute::MeshAttributeHandle::HeldType = AttributeType
Definition at line 44 of file MeshAttributeHandle.hpp.
ValueVariant
using wmtk::attribute::MeshAttributeHandle::ValueVariant = std:: variant<char, int64_t, double, wmtk::Rational, std::tuple<char, wmtk::Rational, double> >
Definition at line 41 of file MeshAttributeHandle.hpp.
Constructor & Destructor Documentation
MeshAttributeHandle() [1/4]
wmtk::attribute::MeshAttributeHandle::MeshAttributeHandle () default
MeshAttributeHandle() [2/4]
wmtk::attribute::MeshAttributeHandle::MeshAttributeHandle (Mesh & m, const HandleVariant & h)
Definition at line 7 of file MeshAttributeHandle.cpp.
MeshAttributeHandle() [3/4]
wmtk::attribute::MeshAttributeHandle::MeshAttributeHandle (const MeshAttributeHandle & o) default
MeshAttributeHandle() [4/4]
wmtk::attribute::MeshAttributeHandle::MeshAttributeHandle (MeshAttributeHandle && o) default
Member Function Documentation
as()
template<typename T > auto wmtk::attribute::MeshAttributeHandle::as () const -> const held_handle_type<held_type_from_primitive<T>()>& inline
Definition at line 161 of file MeshAttributeHandle.hpp.
Referenced by wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::MeshCRTP< Derived >::create_const_accessor(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute(), wmtk::components::output::output(), wmtk::components::Marching::process(), wmtk::HDF5Reader::set_attribute(), wmtk::mesh_utils::set_matrix_attribute(), and TEST_CASE().
as_from_held_type()
template<MeshAttributeHandle::HeldType Type> auto wmtk::attribute::MeshAttributeHandle::as_from_held_type () const -> const held_handle_type<Type>& inline
Definition at line 202 of file MeshAttributeHandle.hpp.
References m_handle.
dimension()
int64_t wmtk::attribute::MeshAttributeHandle::dimension () const
Definition at line 44 of file MeshAttributeHandle.cpp.
References wmtk::Mesh::get_attribute_dimension(), m_handle, and mesh().
Referenced by wmtk::components::internal::MultiMeshFromTag::build_adjacency_matrix(), wmtk::utils::cast_attribute(), wmtk::function::Function::embedded_dimension(), wmtk::function::PerSimplexFunction::embedded_dimension(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute(), wmtk::components::longest_edge_split::longest_edge_split(), wmtk::components::multimesh::multimesh(), and wmtk::components::shortest_edge_collapse::shortest_edge_collapse().
handle() [1/2]
HandleVariant & wmtk::attribute::MeshAttributeHandle::handle () inline
Definition at line 132 of file MeshAttributeHandle.hpp.
References m_handle.
Referenced by wmtk::operations::AttributeTransferConfiguration::add_collapse_new(), wmtk::operations::AttributeTransferConfiguration::add_split_new(), wmtk::utils::cast_attribute(), wmtk::Mesh::delete_attribute(), wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag(), wmtk::operations::attribute_update::make_cast_attribute_transfer_strategy(), wmtk::operations::VertexLaplacianSmooth::operator()(), wmtk::components::internal::RegularSpace::regularize_tags(), wmtk::components::internal::SimplicialEmbedding::regularize_tags(), wmtk::operations::EdgeCollapse::set_new_attribute_strategy(), wmtk::operations::EdgeSplit::set_new_attribute_strategy(), wmtk::multimesh::utils::transfer_attribute(), and wmtk::multimesh::utils::transfer_attribute().
handle() [2/2]
const HandleVariant & wmtk::attribute::MeshAttributeHandle::handle () const inline
Definition at line 133 of file MeshAttributeHandle.hpp.
References m_handle.
handle_type_is_basic()
template<typename T > constexpr bool wmtk::attribute::MeshAttributeHandle::handle_type_is_basic () inline static constexpr
Definition at line 188 of file MeshAttributeHandle.hpp.
Referenced by holds_basic_type().
held_type()
auto wmtk::attribute::MeshAttributeHandle::held_type () const
Definition at line 28 of file MeshAttributeHandle.cpp.
References m_handle.
Referenced by wmtk::components::multimesh::multimesh(), and wmtk::operations::VertexLaplacianSmooth::VertexLaplacianSmooth().
held_type_from_handle() [1/2]
template<typename T > static constexpr HeldType wmtk::attribute::MeshAttributeHandle::held_type_from_handle () static constexpr
held_type_from_handle() [2/2]
template<typename T > constexpr auto wmtk::attribute::MeshAttributeHandle::held_type_from_handle () -> HeldType inline constexpr
Definition at line 219 of file MeshAttributeHandle.hpp.
held_type_from_primitive() [1/2]
template<typename T > static constexpr HeldType wmtk::attribute::MeshAttributeHandle::held_type_from_primitive () static constexpr
held_type_from_primitive() [2/2]
template<typename T > constexpr auto wmtk::attribute::MeshAttributeHandle::held_type_from_primitive () -> HeldType inline constexpr
Definition at line 214 of file MeshAttributeHandle.hpp.
holds()
template<typename T > bool wmtk::attribute::MeshAttributeHandle::holds () const inline
Definition at line 169 of file MeshAttributeHandle.hpp.
Referenced by wmtk::operations::CollapseNewAttributeStrategy< T >::CollapseNewAttributeStrategy(), wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::MeshCRTP< Derived >::create_const_accessor(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::function::Function::Function(), wmtk::function::PerSimplexFunction::PerSimplexFunction(), wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy(), and wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle().
holds_basic_type()
bool wmtk::attribute::MeshAttributeHandle::holds_basic_type () const inline
Definition at line 193 of file MeshAttributeHandle.hpp.
References handle_type_is_basic(), and m_handle.
holds_from_held_type()
template<MeshAttributeHandle::HeldType Type> bool wmtk::attribute::MeshAttributeHandle::holds_from_held_type () const inline
Definition at line 208 of file MeshAttributeHandle.hpp.
References m_handle.
is_same_mesh()
bool wmtk::attribute::MeshAttributeHandle::is_same_mesh (const Mesh & m) const
Definition at line 12 of file MeshAttributeHandle.cpp.
References m_mesh.
Referenced by wmtk::function::Function::Function(), wmtk::operations::Operation::get_transfer_strategy(), wmtk::function::PerSimplexFunction::PerSimplexFunction(), and wmtk::operations::Operation::set_transfer_strategy().
is_valid()
bool wmtk::attribute::MeshAttributeHandle::is_valid () const
Definition at line 38 of file MeshAttributeHandle.cpp.
References m_handle, and m_mesh.
Referenced by wmtk::function::PerSimplexFunction::attribute_handle(), wmtk::function::Function::embedded_dimension(), and wmtk::components::multimesh::utils::detail::get_attribute().
mesh() [1/2]
Mesh & wmtk::attribute::MeshAttributeHandle::mesh ()
Definition at line 18 of file MeshAttributeHandle.cpp.
References m_mesh.
Referenced by wmtk::operations::CollapseNewAttributeStrategy< T >::CollapseNewAttributeStrategy(), wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::MeshCRTP< Derived >::create_const_accessor(), wmtk::Mesh::delete_attribute(), dimension(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag(), wmtk::operations::AttributeTransferStrategyBase::get_parent_simplices(), wmtk::components::longest_edge_split::longest_edge_split(), wmtk::components::marching(), name(), wmtk::components::isotropic_remeshing::relative_to_absolute_length(), wmtk::operations::AttributeTransferStrategyBase::run_on_all(), wmtk::operations::EdgeCollapse::set_new_attribute_strategy(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy(), and wmtk::multimesh::utils::transfer_attribute().
mesh() [2/2]
const Mesh & wmtk::attribute::MeshAttributeHandle::mesh () const
Definition at line 23 of file MeshAttributeHandle.cpp.
References m_mesh.
name()
std::string wmtk::attribute::MeshAttributeHandle::name () const
Definition at line 51 of file MeshAttributeHandle.cpp.
References wmtk::Mesh::get_attribute_name(), m_handle, and mesh().
operator=() [1/2]
MeshAttributeHandle & wmtk::attribute::MeshAttributeHandle::operator= (const MeshAttributeHandle & o) default
operator=() [2/2]
MeshAttributeHandle & wmtk::attribute::MeshAttributeHandle::operator= (MeshAttributeHandle && o) default
operator==()
bool wmtk::attribute::MeshAttributeHandle::operator== (const MeshAttributeHandle & o) const inline
Definition at line 77 of file MeshAttributeHandle.hpp.
References m_handle, and m_mesh.
primitive_type()
PrimitiveType wmtk::attribute::MeshAttributeHandle::primitive_type () const inline
Definition at line 224 of file MeshAttributeHandle.hpp.
References m_handle.
Referenced by wmtk::components::Marching::add_filter(), wmtk::function::Function::attribute_type(), wmtk::utils::cast_attribute(), wmtk::operations::AttributeTransferStrategyBase::get_parent_simplices(), wmtk::operations::AttributeTransferStrategyBase::run_on_all(), and wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy().
primitive_typeT()
template<typename T > PrimitiveType wmtk::attribute::MeshAttributeHandle::primitive_typeT () const inline
Definition at line 229 of file MeshAttributeHandle.hpp.
References m_handle.
Friends And Related Symbol Documentation
wmtk::hash< MeshAttributeHandle >
friend class wmtk::hash< MeshAttributeHandle > friend
Definition at line 68 of file MeshAttributeHandle.hpp.
wmtk::Mesh
friend class wmtk::Mesh friend
Definition at line 68 of file MeshAttributeHandle.hpp.
Member Data Documentation
m_handle
HandleVariant wmtk::attribute::MeshAttributeHandle::m_handle private
Definition at line 157 of file MeshAttributeHandle.hpp.
Referenced by as_from_held_type(), dimension(), handle(), handle(), held_type(), holds_basic_type(), holds_from_held_type(), is_valid(), name(), operator==(), primitive_type(), and primitive_typeT().
m_mesh
Mesh* wmtk::attribute::MeshAttributeHandle::m_mesh = nullptr private
Definition at line 156 of file MeshAttributeHandle.hpp.
Referenced by is_same_mesh(), is_valid(), mesh(), mesh(), and operator==().
The documentation for this class was generated from the following files:
src/wmtk/attribute/MeshAttributeHandle.hpp
src/wmtk/attribute/MeshAttributeHandle.cpp