Wildmeshing Toolkit: wmtk::SchedulerStats Class Reference
wmtk::SchedulerStats Class Reference
#include <Scheduler.hpp>
Public Member Functions
int64_t number_of_successful_operations () const
Returns the number of successful operations performed by the scheduler.
int64_t number_of_failed_operations () const
Returns the number of failed operations performed by the scheduler.
int64_t number_of_performed_operations () const
Returns the number of performed operations performed by the scheduler.
double total_time () const
void succeed ()
void fail ()
void operator+= (const SchedulerStats &s)
double avg_sub_collecting_time () const
double avg_sub_sorting_time () const
double avg_sub_executing_time () const
void print_update_log (size_t total, spdlog::level::level_enum=spdlog::level::info) const
Public Attributes
double collecting_time = 0
double sorting_time = 0
double executing_time = 0
std::vector< SchedulerStats > sub_stats
int64_t m_num_op_success = 0
int64_t m_num_op_fail = 0
Detailed Description
Definition at line 8 of file Scheduler.hpp.
Member Function Documentation
avg_sub_collecting_time()
double wmtk::SchedulerStats::avg_sub_collecting_time () const inline
Definition at line 54 of file Scheduler.hpp.
References sub_stats.
avg_sub_executing_time()
double wmtk::SchedulerStats::avg_sub_executing_time () const inline
Definition at line 72 of file Scheduler.hpp.
References sub_stats.
avg_sub_sorting_time()
double wmtk::SchedulerStats::avg_sub_sorting_time () const inline
Definition at line 63 of file Scheduler.hpp.
References sub_stats.
fail()
void wmtk::SchedulerStats::fail () inline
Definition at line 35 of file Scheduler.hpp.
References m_num_op_fail.
Referenced by wmtk::Scheduler::run_operation_on_all(), and wmtk::Scheduler::run_operation_on_all().
number_of_failed_operations()
int64_t wmtk::SchedulerStats::number_of_failed_operations () const inline
Returns the number of failed operations performed by the scheduler.
The value is reset to 0 when calling run_operation_on_all.
Definition at line 23 of file Scheduler.hpp.
References m_num_op_fail.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::longest_edge_split::longest_edge_split(), wmtk::components::internal::periodic_optimization(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
number_of_performed_operations()
int64_t wmtk::SchedulerStats::number_of_performed_operations () const inline
Returns the number of performed operations performed by the scheduler.
The value is reset to 0 when calling run_operation_on_all.
Definition at line 30 of file Scheduler.hpp.
References m_num_op_fail, and m_num_op_success.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::Scheduler::log(), wmtk::components::longest_edge_split::longest_edge_split(), wmtk::components::internal::periodic_optimization(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
number_of_successful_operations()
int64_t wmtk::SchedulerStats::number_of_successful_operations () const inline
Returns the number of successful operations performed by the scheduler.
The value is reset to 0 when calling run_operation_on_all.
Definition at line 16 of file Scheduler.hpp.
References m_num_op_success.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::longest_edge_split::longest_edge_split(), wmtk::components::internal::periodic_optimization(), wmtk::components::internal::SimplicialEmbedding::regularize_tags(), wmtk::Scheduler::run_operation_on_all(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
operator+=()
void wmtk::SchedulerStats::operator+= (const SchedulerStats & s) inline
Definition at line 37 of file Scheduler.hpp.
References collecting_time, executing_time, m_num_op_fail, m_num_op_success, and sorting_time.
print_update_log()
void wmtk::SchedulerStats::print_update_log (size_t total, spdlog::level::level_enum level = spdlog::level::info) const
Definition at line 399 of file Scheduler.cpp.
References wmtk::logger().
Referenced by wmtk::Scheduler::log(), and wmtk::Scheduler::run_operation_on_all().
succeed()
void wmtk::SchedulerStats::succeed () inline
Definition at line 34 of file Scheduler.hpp.
References m_num_op_success.
Referenced by wmtk::Scheduler::run_operation_on_all(), and wmtk::Scheduler::run_operation_on_all().
total_time()
double wmtk::SchedulerStats::total_time () const inline
Definition at line 32 of file Scheduler.hpp.
References collecting_time, executing_time, and sorting_time.
Member Data Documentation
collecting_time
double wmtk::SchedulerStats::collecting_time = 0
Definition at line 48 of file Scheduler.hpp.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::longest_edge_split::longest_edge_split(), operator+=(), wmtk::components::internal::periodic_optimization(), wmtk::Scheduler::run_operation_on_all(), wmtk::Scheduler::run_operation_on_all(), wmtk::Scheduler::run_operation_on_all_coloring(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), total_time(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
executing_time
double wmtk::SchedulerStats::executing_time = 0
Definition at line 50 of file Scheduler.hpp.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::longest_edge_split::longest_edge_split(), operator+=(), wmtk::components::internal::periodic_optimization(), wmtk::Scheduler::run_operation_on_all(), wmtk::Scheduler::run_operation_on_all(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), total_time(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
m_num_op_fail
int64_t wmtk::SchedulerStats::m_num_op_fail = 0
Definition at line 83 of file Scheduler.hpp.
Referenced by fail(), number_of_failed_operations(), number_of_performed_operations(), and operator+=().
m_num_op_success
int64_t wmtk::SchedulerStats::m_num_op_success = 0
Definition at line 82 of file Scheduler.hpp.
Referenced by number_of_performed_operations(), number_of_successful_operations(), operator+=(), and succeed().
sorting_time
double wmtk::SchedulerStats::sorting_time = 0
Definition at line 49 of file Scheduler.hpp.
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::longest_edge_split::longest_edge_split(), operator+=(), wmtk::components::internal::periodic_optimization(), wmtk::Scheduler::run_operation_on_all(), wmtk::Scheduler::run_operation_on_all(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), total_time(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
sub_stats
std::vector<SchedulerStats> wmtk::SchedulerStats::sub_stats
Definition at line 52 of file Scheduler.hpp.
Referenced by avg_sub_collecting_time(), avg_sub_executing_time(), avg_sub_sorting_time(), and wmtk::Scheduler::run_operation_on_all().
The documentation for this class was generated from the following files:
src/wmtk/Scheduler.hpp
src/wmtk/Scheduler.cpp