Wildmeshing Toolkit: wmtk::MultiMeshManager Class Reference
wmtk::MultiMeshManager Class Reference
Implementation details for how the Mesh class implements multiple meshes.
#include <MultiMeshManager.hpp>
Classes
struct ChildData
Public Member Functions
MultiMeshManager (int64_t dimension)
~MultiMeshManager ()
MultiMeshManager (const MultiMeshManager &o)
MultiMeshManager (MultiMeshManager &&o)
MultiMeshManager & operator= (const MultiMeshManager &o)
MultiMeshManager & operator= (MultiMeshManager &&o)
std::map< std::string, const wmtk::utils::Hashable * > child_hashables () const override
std::map< std::string, std::size_t > child_hashes () const override
std::vector< TypedAttributeHandle< int64_t > > map_handles () const
bool is_root () const
Specifies whether this structure is the root of a multi-mesh tree.
int64_t child_id () const
Specifies the child id of this mesh if it a child mesh in a mult-mesh tree.
std::vector< int64_t > absolute_id () const
Mesh & get_mesh (Mesh &m, const std::vector< int64_t > &absolute_id)
const Mesh & get_mesh (const Mesh &m, const std::vector< int64_t > &absolute_id) const
Mesh & get_child_mesh (Mesh &m, const std::vector< int64_t > &relative_id)
const Mesh & get_child_mesh (const Mesh &m, const std::vector< int64_t > &relative_id) const
void register_child_mesh (Mesh &my_mesh, const std::shared_ptr< Mesh > &child_mesh, const std::vector< std::array< Tuple, 2 >> &child_tuple_my_tuple_map)
register a another mesh as a child of this mesh.
std::vector< simplex::Simplex > map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh
std::vector< Tuple > lub_map_tuples (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
std::vector< simplex::Simplex > lub_map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
std::vector< Tuple > map_tuples (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh
simplex::Simplex map_to_parent (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Tuple map_to_parent_tuple (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
optimized map from a simplex from this mesh to its direct parent
simplex::Simplex map_to_root (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to the root mesh
Tuple map_to_root_tuple (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to the root mesh
std::vector< simplex::Simplex > map_to_child (const Mesh &my_mesh, const Mesh &child_mesh, const simplex::Simplex &my_simplex) const
optimized map fromsimplex from this mesh to one of its direct children
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, const Mesh &child_mesh, const simplex::Simplex &my_simplex) const
bool can_map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
bool can_map_child (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
const Mesh & get_root_mesh (const Mesh &my_mesh) const
Mesh & get_root_mesh (Mesh &my_mesh)
std::vector< std::shared_ptr< Mesh > > get_child_meshes () const
void serialize (MeshWriter &writer, const Mesh *local_root=nullptr) const
bool has_child_mesh_in_dimension (int64_t dimension) const
std::vector< int64_t > relative_id (const Mesh &my_mesh, const Mesh &parent_mesh) const
bool is_child (const Mesh &my_mesh, const Mesh &parent_mesh) const
void check_map_valid (const Mesh &my_mesh) const
void check_child_map_valid (const Mesh &my_mesh, const ChildData &child_data) const
Public Member Functions inherited from wmtk::utils::MerkleTreeInteriorNode
std::map< std::string, std::size_t > child_hashes () const override
Public Member Functions inherited from wmtk::utils::Hashable
Hashable ()
Hashable (const Hashable &)
Hashable (Hashable &&)
Hashable & operator= (const Hashable &)
Hashable & operator= (Hashable &&)
virtual ~Hashable ()
virtual std::size_t hash () const
Static Public Member Functions
static bool is_child (const std::vector< int64_t > &child, const std::vector< int64_t > &parent)
static void update_vertex_operation_hashes_internal (Mesh &m, const Tuple &vertex, Accessor< int64_t > &hash_accessor)
update all the hashes of the top-simplces of the parent mesh around a vertex hashes of the parent tuples in the maps for all child meshes
static void update_vertex_operation_multimesh_map_hash_internal (Mesh &m, const simplex::SimplexCollection &vertex_closed_star, Accessor< int64_t > &parent_hash_accessor)
Protected Member Functions
Tuple map_tuple_to_parent_tuple (const Mesh &my_mesh, const Tuple &my_tuple) const
Tuple map_tuple_to_root_tuple (const Mesh &my_mesh, const Tuple &my_tuple) const
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, const ChildData &child_data, const simplex::Simplex &simplex) const
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, int64_t child_id, const simplex::Simplex &simplex) const
const std::vector< ChildData > & children () const
std::vector< ChildData > & children ()
std::array< attribute::MutableAccessor< int64_t >, 2 > get_map_accessors (Mesh &my_mesh, ChildData &c)
std::array< attribute::ConstAccessor< int64_t >, 2 > get_map_const_accessors (const Mesh &my_mesh, const ChildData &c) const
void update_map_tuple_hashes (Mesh &my_mesh, PrimitiveType primitive_type, const std::vector< std::tuple< int64_t, std::vector< Tuple >>> &simplices_to_update, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> &split_cell_maps={})
std::optional< Tuple > find_valid_tuple (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> &split_cell_maps={}) const
std::optional< Tuple > find_valid_tuple_from_alternatives (Mesh &my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > &tuple_alternatives) const
std::optional< Tuple > find_valid_tuple_from_split (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> &split_cell_maps) const
std::optional< Tuple > try_updating_map_tuple_from_split (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::tuple< int64_t, std::array< int64_t, 2 >> &split_cell_maps) const
std::pair< const Mesh &, Tuple > map_up_to_tuples (const Mesh &my_mesh, const simplex::Simplex &simplex, int64_t depth) const
std::vector< Tuple > map_down_relative_tuples (const Mesh &my_mesh, const simplex::Simplex &my_simplex, const std::vector< int64_t > &local_id_path) const
Static Protected Member Functions
static Tuple map_tuple_between_meshes (const Mesh &source_mesh, const Mesh &target_mesh, const ConstAccessor< int64_t > &source_to_target_map_accessor, const Tuple &source_tuple)
static std::string parent_to_child_map_attribute_name (int64_t index)
static std::string child_to_parent_map_attribute_name ()
static std::optional< Tuple > find_tuple_from_gid (const Mesh &my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > &tuples, int64_t gid)
static int64_t child_global_cid (const attribute::ConstAccessor< int64_t > &parent_to_child, int64_t parent_gid)
static int64_t parent_global_cid (const attribute::ConstAccessor< int64_t > &child_to_parent, int64_t child_gid)
static int64_t parent_local_fid (const attribute::ConstAccessor< int64_t > &child_to_parent, int64_t child_gid)
static std::vector< int64_t > least_upper_bound_id (const std::vector< int64_t > &a, const std::vector< int64_t > &b)
static std::vector< int64_t > relative_id (const std::vector< int64_t > &parent, const std::vector< int64_t > &child)
Protected Attributes
Mesh * m_parent = nullptr
TypedAttributeHandle< int64_t > map_to_parent_handle
int64_t m_child_id = -1
std::vector< ChildData > m_children
std::vector< bool > m_has_child_mesh_in_dimension
Static Private Member Functions
static std::vector< std::array< Tuple, 2 > > same_simplex_dimension_surjection (const Mesh &parent, const Mesh &child, const std::vector< int64_t > &parent_simplices)
Friends
template<int64_t cell_dimension, typename NodeFunctor >
class multimesh::MultiMeshSimplexVisitor
class Mesh
template<typename Visitor >
class multimesh::MultiMeshSimplexVisitorExecutor
class operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
template<typename NodeFunctor >
class multimesh::MultiMeshVisitor
template<typename Visitor >
class multimesh::MultiMeshVisitorExecutor
class HDF5Reader
std::vector< std::array< Tuple, 2 > > multimesh::same_simplex_dimension_surjection (const Mesh &parent, const Mesh &child, const std::vector< int64_t > &parent_simplices)
void operations::utils::update_vertex_operation_multimesh_map_hash (Mesh &m, const simplex::SimplexCollection &vertex_closed_star, attribute::MutableAccessor< int64_t > &parent_hash_accessor)
Detailed Description
Implementation details for how the Mesh class implements multiple meshes.
Definition at line 41 of file MultiMeshManager.hpp.
Constructor & Destructor Documentation
MultiMeshManager() [1/3]
wmtk::MultiMeshManager::MultiMeshManager (int64_t dimension)
Definition at line 90 of file MultiMeshManager.cpp.
~MultiMeshManager()
wmtk::MultiMeshManager::~MultiMeshManager () default
MultiMeshManager() [2/3]
wmtk::MultiMeshManager::MultiMeshManager (const MultiMeshManager & o) default
MultiMeshManager() [3/3]
wmtk::MultiMeshManager::MultiMeshManager (MultiMeshManager && o) default
Member Function Documentation
absolute_id()
std::vector< int64_t > wmtk::MultiMeshManager::absolute_id () const
Definition at line 150 of file MultiMeshManager.cpp.
References absolute_id(), is_root(), m_child_id, wmtk::Mesh::m_multi_mesh_manager, and m_parent.
Referenced by absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), can_map_child(), check_child_map_valid(), get_mesh(), lub_map_tuples(), map_tuples(), and wmtk::Mesh::serialize().
can_map()
bool wmtk::MultiMeshManager::can_map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
Definition at line 1216 of file MultiMeshManager.cpp.
References can_map_child(), wmtk::Mesh::get_multi_mesh_root(), wmtk::Mesh::m_multi_mesh_manager, map_to_root_tuple(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::Mesh::can_map().
can_map_child()
bool wmtk::MultiMeshManager::can_map_child (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
Definition at line 1227 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), map_up_to_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::Mesh::top_simplex_type().
Referenced by can_map().
check_child_map_valid()
void wmtk::MultiMeshManager::check_child_map_valid (const Mesh & my_mesh, const ChildData & child_data) const
Definition at line 1058 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), wmtk::utils::TupleInspector::as_string(), child_to_parent_map_attribute_name(), wmtk::Mesh::create_const_accessor(), wmtk::Edge, wmtk::Mesh::get_all(), wmtk::Mesh::get_attribute_handle(), wmtk::Mesh::get_flag_accessor(), wmtk::Mesh::has_attribute(), wmtk::Mesh::is_boundary(), wmtk::Mesh::is_valid_slow(), wmtk::logger(), wmtk::MultiMeshManager::ChildData::map_handle, map_tuple_between_meshes(), wmtk::MultiMeshManager::ChildData::mesh, wmtk::multimesh::utils::read_tuple_map_attribute_slow(), wmtk::Mesh::switch_edge(), wmtk::Mesh::switch_face(), wmtk::Mesh::switch_vertex(), wmtk::Mesh::top_simplex_type(), and wmtk::Triangle.
Referenced by check_map_valid().
check_map_valid()
void wmtk::MultiMeshManager::check_map_valid (const Mesh & my_mesh) const
Definition at line 1048 of file MultiMeshManager.cpp.
References check_child_map_valid(), and children().
child_global_cid()
int64_t wmtk::MultiMeshManager::child_global_cid (const attribute::ConstAccessor< int64_t > & parent_to_child, int64_t parent_gid) static protected
Definition at line 917 of file MultiMeshManager.cpp.
References wmtk::Mesh::get_index_access().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::child_global_cid().
child_hashables()
std::map< std::string, const wmtk::utils::Hashable * > wmtk::MultiMeshManager::child_hashables () const override virtual
Implements wmtk::utils::MerkleTreeInteriorNode.
Definition at line 101 of file MultiMeshManager.cpp.
References m_children.
child_hashes()
std::map< std::string, std::size_t > wmtk::MultiMeshManager::child_hashes () const override virtual
Reimplemented from wmtk::utils::Hashable.
Definition at line 112 of file MultiMeshManager.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), wmtk::utils::MerkleTreeInteriorNode::child_hashes(), m_child_id, m_children, m_parent, map_to_parent_handle, and wmtk::utils::vector_hash().
child_id()
int64_t wmtk::MultiMeshManager::child_id () const
Specifies the child id of this mesh if it a child mesh in a mult-mesh tree.
throws if it not a child
Returns
the local index of this manager's mesh in its parent's array
Definition at line 142 of file MultiMeshManager.cpp.
References is_root(), and m_child_id.
Referenced by map_to_child_tuples().
child_to_parent_map_attribute_name()
std::string wmtk::MultiMeshManager::child_to_parent_map_attribute_name () static protected
Definition at line 653 of file MultiMeshManager.cpp.
Referenced by check_child_map_valid(), and register_child_mesh().
children() [1/2]
std::vector<ChildData>& wmtk::MultiMeshManager::children () inline protected
Definition at line 385 of file MultiMeshManager.hpp.
References m_children.
children() [2/2]
const std::vector<ChildData>& wmtk::MultiMeshManager::children () const inline protected
Definition at line 384 of file MultiMeshManager.hpp.
References m_children.
Referenced by check_map_valid(), and update_map_tuple_hashes().
find_tuple_from_gid()
std::optional< Tuple > wmtk::MultiMeshManager::find_tuple_from_gid (const Mesh & my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > & tuples, int64_t gid) static protected
Definition at line 898 of file MultiMeshManager.cpp.
Referenced by find_valid_tuple_from_split(), and update_map_tuple_hashes().
find_valid_tuple()
std::optional< Tuple > wmtk::MultiMeshManager::find_valid_tuple (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> & split_cell_maps = {}) const protected
Definition at line 812 of file MultiMeshManager.cpp.
References find_valid_tuple_from_alternatives(), find_valid_tuple_from_split(), and wmtk::Mesh::top_simplex_type().
Referenced by update_map_tuple_hashes().
find_valid_tuple_from_alternatives()
std::optional< Tuple > wmtk::MultiMeshManager::find_valid_tuple_from_alternatives (Mesh & my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > & tuple_alternatives) const protected
Definition at line 839 of file MultiMeshManager.cpp.
References wmtk::Mesh::get_const_flag_accessor().
Referenced by find_valid_tuple().
find_valid_tuple_from_split()
std::optional< Tuple > wmtk::MultiMeshManager::find_valid_tuple_from_split (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> & split_cell_maps) const protected
Definition at line 859 of file MultiMeshManager.cpp.
References find_tuple_from_gid(), wmtk::Mesh::get_cell_hash_slow(), wmtk::Mesh::id(), wmtk::Mesh::is_valid_slow(), wmtk::Tuple::m_global_cid, wmtk::Tuple::m_local_eid, wmtk::Tuple::m_local_fid, wmtk::Tuple::m_local_vid, wmtk::simplex::Simplex::primitive_type(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::Simplex::tuple().
Referenced by find_valid_tuple().
get_child_mesh() [1/2]
const Mesh & wmtk::MultiMeshManager::get_child_mesh (const Mesh & m, const std::vector< int64_t > & relative_id) const
Definition at line 294 of file MultiMeshManager.cpp.
References m_child_id, m_children, wmtk::Mesh::m_multi_mesh_manager, wmtk::MultiMeshManager::ChildData::mesh, and relative_id().
get_child_mesh() [2/2]
Mesh & wmtk::MultiMeshManager::get_child_mesh (Mesh & m, const std::vector< int64_t > & relative_id)
Definition at line 315 of file MultiMeshManager.cpp.
References relative_id().
Referenced by get_mesh(), and wmtk::Mesh::get_multi_mesh_child_mesh().
get_child_meshes()
std::vector< std::shared_ptr< Mesh > > wmtk::MultiMeshManager::get_child_meshes () const
Definition at line 331 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::get_child_meshes().
get_map_accessors()
std::array< attribute::MutableAccessor< int64_t >, 2 > wmtk::MultiMeshManager::get_map_accessors (Mesh & my_mesh, ChildData & c) protected
Definition at line 627 of file MultiMeshManager.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Mesh::m_multi_mesh_manager, wmtk::MultiMeshManager::ChildData::map_handle, map_to_parent_handle, and wmtk::MultiMeshManager::ChildData::mesh.
Referenced by update_map_tuple_hashes(), wmtk::operations::utils::update_vertex_operation_multimesh_map_hash(), and update_vertex_operation_multimesh_map_hash_internal().
get_map_const_accessors()
std::array< attribute::ConstAccessor< int64_t >, 2 > wmtk::MultiMeshManager::get_map_const_accessors (const Mesh & my_mesh, const ChildData & c) const protected
Definition at line 640 of file MultiMeshManager.cpp.
References wmtk::Mesh::create_const_accessor(), wmtk::Mesh::m_multi_mesh_manager, wmtk::MultiMeshManager::ChildData::map_handle, map_to_parent_handle, and wmtk::MultiMeshManager::ChildData::mesh.
get_mesh() [1/2]
const Mesh & wmtk::MultiMeshManager::get_mesh (const Mesh & m, const std::vector< int64_t > & absolute_id) const
Definition at line 319 of file MultiMeshManager.cpp.
References absolute_id(), get_child_mesh(), get_root_mesh(), and wmtk::Mesh::m_multi_mesh_manager.
get_mesh() [2/2]
Mesh & wmtk::MultiMeshManager::get_mesh (Mesh & m, const std::vector< int64_t > & absolute_id)
Definition at line 326 of file MultiMeshManager.cpp.
References absolute_id(), get_child_mesh(), get_root_mesh(), and wmtk::Mesh::m_multi_mesh_manager.
Referenced by wmtk::Mesh::get_multi_mesh_mesh().
get_root_mesh() [1/2]
const Mesh & wmtk::MultiMeshManager::get_root_mesh (const Mesh & my_mesh) const
Definition at line 277 of file MultiMeshManager.cpp.
References get_root_mesh(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
Referenced by get_mesh(), wmtk::Mesh::get_multi_mesh_root(), and get_root_mesh().
get_root_mesh() [2/2]
Mesh & wmtk::MultiMeshManager::get_root_mesh (Mesh & my_mesh)
Definition at line 285 of file MultiMeshManager.cpp.
References get_root_mesh(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
has_child_mesh_in_dimension()
bool wmtk::MultiMeshManager::has_child_mesh_in_dimension (int64_t dimension) const inline
Definition at line 319 of file MultiMeshManager.hpp.
References m_has_child_mesh_in_dimension.
Referenced by wmtk::Mesh::has_child_mesh_in_dimension().
is_child() [1/2]
bool wmtk::MultiMeshManager::is_child (const Mesh & my_mesh, const Mesh & parent_mesh) const
Definition at line 173 of file MultiMeshManager.cpp.
References is_child(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
is_child() [2/2]
bool wmtk::MultiMeshManager::is_child (const std::vector< int64_t > & child, const std::vector< int64_t > & parent) static
Definition at line 1194 of file MultiMeshManager.cpp.
Referenced by is_child(), lub_map_tuples(), and relative_id().
is_root()
bool wmtk::MultiMeshManager::is_root () const
Specifies whether this structure is the root of a multi-mesh tree.
Returns
true if this is the root, false otherwise
Definition at line 137 of file MultiMeshManager.cpp.
References m_parent.
Referenced by absolute_id(), child_id(), get_root_mesh(), is_child(), wmtk::Mesh::is_multi_mesh_root(), map_tuple_to_parent_tuple(), map_tuple_to_root_tuple(), map_up_to_tuples(), and relative_id().
least_upper_bound_id()
std::vector< int64_t > wmtk::MultiMeshManager::least_upper_bound_id (const std::vector< int64_t > & a, const std::vector< int64_t > & b) static protected
Definition at line 1170 of file MultiMeshManager.cpp.
Referenced by lub_map_tuples().
lub_map()
std::vector< simplex::Simplex > wmtk::MultiMeshManager::lub_map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
Satisfies the same properties of standard map, but uses a the LUB as the root
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 351 of file MultiMeshManager.cpp.
References lub_map_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::lub_map().
lub_map_tuples()
std::vector< Tuple > wmtk::MultiMeshManager::lub_map_tuples (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
Satisfies the same properties of standard map, but uses a the LUB as the root
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 443 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), is_child(), least_upper_bound_id(), wmtk::Mesh::m_multi_mesh_manager, map_up_to_tuples(), wmtk::simplex::Simplex::primitive_type(), and relative_id().
Referenced by lub_map(), and wmtk::Mesh::lub_map_tuples().
map()
std::vector< simplex::Simplex > wmtk::MultiMeshManager::map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh
Generic interface for mapping between two arbitrary meshes in a multi-mesh structure Note that this finds ALL versions of a simplex, potentially crossing over topological features above the pairs of simplices being mapped. For instance, if we map a trimesh seam edge to itself using this interface it will find the edge on the other side of the seam. If more granular mappings are required consider manually navigating the tree with map_to_parent and map_to_child, which of course require a more particular understanding on how a simplex is mapped. throws if two meshes are not part of the same multi-mesh structure
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex
Definition at line 341 of file MultiMeshManager.cpp.
References map_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::map().
map_down_relative_tuples()
std::vector< Tuple > wmtk::MultiMeshManager::map_down_relative_tuples (const Mesh & my_mesh, const simplex::Simplex & my_simplex, const std::vector< int64_t > & local_id_path) const protected
Definition at line 385 of file MultiMeshManager.cpp.
References m_child_id, m_children, wmtk::Mesh::m_multi_mesh_manager, map_to_child_tuples(), wmtk::MultiMeshManager::ChildData::mesh, wmtk::simplex::Simplex::primitive_type(), relative_id(), and wmtk::simplex::Simplex::tuple().
map_handles()
std::vector< attribute::TypedAttributeHandle< int64_t > > wmtk::MultiMeshManager::map_handles () const
Definition at line 244 of file MultiMeshManager.cpp.
References wmtk::attribute::TypedAttributeHandle< T >::is_valid(), m_children, and map_to_parent_handle.
Referenced by wmtk::Mesh::builtin_attributes().
map_to_child()
std::vector< simplex::Simplex > wmtk::MultiMeshManager::map_to_child (const Mesh & my_mesh, const Mesh & child_mesh, const simplex::Simplex & my_simplex) const
optimized map fromsimplex from this mesh to one of its direct children
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
child mesh the simplex shoudl be mapped to
the simplex being mapped to the child mesh
the set of child mesh's simplices that are equivalent to the input simplex
Definition at line 575 of file MultiMeshManager.cpp.
References map_to_child_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::map_to_child().
map_to_child_tuples() [1/3]
std::vector< Tuple > wmtk::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, const ChildData & child_data, const simplex::Simplex & simplex) const protected
Definition at line 517 of file MultiMeshManager.cpp.
References wmtk::simplex::cofaces_single_dimension_tuples(), wmtk::Mesh::create_accessor(), wmtk::Mesh::m_multi_mesh_manager, wmtk::simplex::utils::make_unique_tuples(), wmtk::MultiMeshManager::ChildData::map_handle, map_tuple_between_meshes(), wmtk::MultiMeshManager::ChildData::mesh, wmtk::simplex::Simplex::primitive_type(), and wmtk::Mesh::top_simplex_type().
map_to_child_tuples() [2/3]
std::vector< Tuple > wmtk::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, const Mesh & child_mesh, const simplex::Simplex & my_simplex) const
Definition at line 557 of file MultiMeshManager.cpp.
References child_id(), and wmtk::Mesh::m_multi_mesh_manager.
Referenced by map_down_relative_tuples(), map_to_child(), wmtk::Mesh::map_to_child_tuples(), and map_to_child_tuples().
map_to_child_tuples() [3/3]
std::vector< Tuple > wmtk::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, int64_t child_id, const simplex::Simplex & simplex) const protected
Definition at line 565 of file MultiMeshManager.cpp.
References child_id(), m_children, and map_to_child_tuples().
map_to_parent()
simplex::Simplex wmtk::MultiMeshManager::map_to_parent (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Maps a simplex to its direct parent in the multi-mesh structure. Cannot be used outside of applications with guaranteed multi-mesh structures
throws if this is the root
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique parent mesh's simplex that is parent to the input one
Definition at line 488 of file MultiMeshManager.cpp.
References map_tuple_to_parent_tuple(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::Simplex::tuple().
Referenced by wmtk::Mesh::map_to_parent().
map_to_parent_tuple()
Tuple wmtk::MultiMeshManager::map_to_parent_tuple (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Maps a simplex to its direct parent in the multi-mesh structure. Cannot be used outside of applications with guaranteed multi-mesh structures
throws if this is the root
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique parent mesh's simplex that is parent to the input one, without the dimension encoded
Definition at line 496 of file MultiMeshManager.cpp.
References map_tuple_to_parent_tuple(), and wmtk::simplex::Simplex::tuple().
Referenced by wmtk::Mesh::map_to_parent_tuple().
map_to_root()
simplex::Simplex wmtk::MultiMeshManager::map_to_root (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to the root mesh
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique root mesh's simplex that is the root to the input one
Definition at line 466 of file MultiMeshManager.cpp.
References map_to_root_tuple(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::Mesh::map_to_root().
map_to_root_tuple()
Tuple wmtk::MultiMeshManager::map_to_root_tuple (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to the root mesh
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique root mesh's simplex that is the root to the input one, without the dimension encoded
Definition at line 473 of file MultiMeshManager.cpp.
References map_tuple_to_root_tuple(), and wmtk::simplex::Simplex::tuple().
Referenced by can_map(), map_to_root(), and wmtk::Mesh::map_to_root_tuple().
map_tuple_between_meshes()
Tuple wmtk::MultiMeshManager::map_tuple_between_meshes (const Mesh & source_mesh, const Mesh & target_mesh, const ConstAccessor< int64_t > & source_to_target_map_accessor, const Tuple & source_tuple) static protected
Definition at line 24 of file MultiMeshManager.cpp.
References wmtk::Edge, wmtk::Mesh::is_valid_slow(), wmtk::Tuple::m_global_cid, wmtk::multimesh::utils::read_tuple_map_attribute(), wmtk::Mesh::switch_face(), wmtk::Tetrahedron, wmtk::simplex::top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), and wmtk::multimesh::utils::transport_tuple().
Referenced by check_child_map_valid(), map_to_child_tuples(), and map_tuple_to_parent_tuple().
map_tuple_to_parent_tuple()
Tuple wmtk::MultiMeshManager::map_tuple_to_parent_tuple (const Mesh & my_mesh, const Tuple & my_tuple) const protected
Definition at line 502 of file MultiMeshManager.cpp.
References wmtk::Mesh::create_accessor(), is_root(), wmtk::Mesh::m_multi_mesh_manager, m_parent, map_to_parent_handle, and map_tuple_between_meshes().
Referenced by map_to_parent(), map_to_parent_tuple(), map_tuple_to_root_tuple(), and map_up_to_tuples().
map_tuple_to_root_tuple()
Tuple wmtk::MultiMeshManager::map_tuple_to_root_tuple (const Mesh & my_mesh, const Tuple & my_tuple) const protected
Definition at line 478 of file MultiMeshManager.cpp.
References is_root(), wmtk::Mesh::m_multi_mesh_manager, m_parent, and map_tuple_to_parent_tuple().
Referenced by map_to_root_tuple().
map_tuples()
std::vector< Tuple > wmtk::MultiMeshManager::map_tuples (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh
Generic interface for mapping between two arbitrary meshes in a multi-mesh structure Note that this finds ALL versions of a simplex, potentially crossing over topological features above the pairs of simplices being mapped. For instance, if we map a trimesh seam edge to itself using this interface it will find the edge on the other side of the seam. If more granular mappings are required consider manually navigating the tree with map_to_parent and map_to_child, which of course require a more particular understanding on how a simplex is mapped. throws if two meshes are not part of the same multi-mesh structure
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 427 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), map_up_to_tuples(), and wmtk::simplex::Simplex::primitive_type().
Referenced by map(), and wmtk::Mesh::map_tuples().
map_up_to_tuples()
std::pair< const Mesh &, Tuple > wmtk::MultiMeshManager::map_up_to_tuples (const Mesh & my_mesh, const simplex::Simplex & simplex, int64_t depth) const protected
Definition at line 362 of file MultiMeshManager.cpp.
References is_root(), wmtk::Mesh::m_multi_mesh_manager, m_parent, map_tuple_to_parent_tuple(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::Simplex::tuple().
Referenced by can_map_child(), lub_map_tuples(), and map_tuples().
operator=() [1/2]
MultiMeshManager & wmtk::MultiMeshManager::operator= (const MultiMeshManager & o) default
operator=() [2/2]
MultiMeshManager & wmtk::MultiMeshManager::operator= (MultiMeshManager && o) default
parent_global_cid()
int64_t wmtk::MultiMeshManager::parent_global_cid (const attribute::ConstAccessor< int64_t > & child_to_parent, int64_t child_gid) static protected
Definition at line 928 of file MultiMeshManager.cpp.
References wmtk::Mesh::get_index_access().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_global_cid().
parent_local_fid()
int64_t wmtk::MultiMeshManager::parent_local_fid (const attribute::ConstAccessor< int64_t > & child_to_parent, int64_t child_gid) static protected
Definition at line 940 of file MultiMeshManager.cpp.
References wmtk::Mesh::get_index_access().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_local_fid().
parent_to_child_map_attribute_name()
std::string wmtk::MultiMeshManager::parent_to_child_map_attribute_name (int64_t index) static protected
Definition at line 623 of file MultiMeshManager.cpp.
Referenced by register_child_mesh().
register_child_mesh()
void wmtk::MultiMeshManager::register_child_mesh (Mesh & my_mesh, const std::shared_ptr< Mesh > & child_mesh, const std::vector< std::array< Tuple, 2 >> & child_tuple_my_tuple_map)
register a another mesh as a child of this mesh.
Parameters
my_mesh the mesh that this structure is owned by
child_mesh the mesh that will be added a child of this mesh
the set of tuples {A,B} where A is from "this mesh" and B represents a top-dimension simplex in the child_mesh. Every top dimension tuple of the child mesh must be represented here
Definition at line 187 of file MultiMeshManager.cpp.
References child_to_parent_map_attribute_name(), wmtk::Mesh::create_accessor(), wmtk::Mesh::is_valid_slow(), m_child_id, m_children, m_has_child_mesh_in_dimension, wmtk::Mesh::m_multi_mesh_manager, m_parent, map_to_parent_handle, parent_to_child_map_attribute_name(), wmtk::Mesh::register_attribute_typed(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::Mesh::top_cell_dimension(), and wmtk::Mesh::top_simplex_type().
Referenced by wmtk::Mesh::register_child_mesh().
relative_id() [1/2]
std::vector< int64_t > wmtk::MultiMeshManager::relative_id (const Mesh & my_mesh, const Mesh & parent_mesh) const
Definition at line 160 of file MultiMeshManager.cpp.
References is_child(), is_root(), m_child_id, wmtk::Mesh::m_multi_mesh_manager, m_parent, and relative_id().
relative_id() [2/2]
std::vector< int64_t > wmtk::MultiMeshManager::relative_id (const std::vector< int64_t > & parent, const std::vector< int64_t > & child) static protected
Definition at line 1185 of file MultiMeshManager.cpp.
References is_child().
Referenced by get_child_mesh(), lub_map_tuples(), map_down_relative_tuples(), relative_id(), and wmtk::Mesh::serialize().
same_simplex_dimension_surjection()
std::vector< std::array< Tuple, 2 > > wmtk::MultiMeshManager::same_simplex_dimension_surjection (const Mesh & parent, const Mesh & child, const std::vector< int64_t > & parent_simplices) static private
Definition at line 587 of file MultiMeshManager.cpp.
References wmtk::Mesh::capacity(), wmtk::Mesh::get_const_flag_accessor(), wmtk::Mesh::top_simplex_type(), and wmtk::Mesh::tuple_from_id().
Referenced by wmtk::multimesh::same_simplex_dimension_surjection().
serialize()
void wmtk::MultiMeshManager::serialize (MeshWriter & writer, const Mesh * local_root = nullptr) const
Definition at line 1209 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::serialize().
try_updating_map_tuple_from_split()
std::optional<Tuple> wmtk::MultiMeshManager::try_updating_map_tuple_from_split (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::tuple< int64_t, std::array< int64_t, 2 >> & split_cell_maps) const protected
update_map_tuple_hashes()
void wmtk::MultiMeshManager::update_map_tuple_hashes (Mesh & my_mesh, PrimitiveType primitive_type, const std::vector< std::tuple< int64_t, std::vector< Tuple >>> & simplices_to_update, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> & split_cell_maps = {}) protected
Definition at line 658 of file MultiMeshManager.cpp.
References wmtk::Mesh::capacity(), children(), find_tuple_from_gid(), find_valid_tuple(), wmtk::Mesh::get_const_cell_hash_accessor(), wmtk::Mesh::get_const_flag_accessor(), wmtk::Mesh::get_index_access(), get_map_accessors(), wmtk::Tuple::is_null(), wmtk::Mesh::is_valid_slow(), wmtk::logger(), wmtk::Tuple::m_global_cid, wmtk::Mesh::resurrect_tuple(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::Mesh::top_simplex_type(), wmtk::multimesh::utils::transport_tuple(), wmtk::simplex::Simplex::tuple(), wmtk::multimesh::utils::vector_to_tuple(), and wmtk::multimesh::utils::vectors_to_tuples().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_all_hashes().
update_vertex_operation_hashes_internal()
void wmtk::MultiMeshManager::update_vertex_operation_hashes_internal (Mesh & m, const Tuple & vertex, Accessor< int64_t > & hash_accessor) static
update all the hashes of the top-simplces of the parent mesh around a vertex hashes of the parent tuples in the maps for all child meshes
Parameters
m mesh the tuple belongs to
vertex operating vertex tuple
hash_accessor hash accessor of m
Definition at line 958 of file MultiMeshManager.cpp.
References wmtk::simplex::closed_star(), wmtk::Edge, wmtk::Mesh::resurrect_tuple(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, wmtk::Mesh::update_cell_hashes(), update_vertex_operation_multimesh_map_hash_internal(), wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
Referenced by wmtk::Mesh::update_vertex_operation_hashes().
update_vertex_operation_multimesh_map_hash_internal()
void wmtk::MultiMeshManager::update_vertex_operation_multimesh_map_hash_internal (Mesh & m, const simplex::SimplexCollection & vertex_closed_star, Accessor< int64_t > & parent_hash_accessor) static
Definition at line 1013 of file MultiMeshManager.cpp.
References get_map_accessors(), wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::utils::read_tuple_map_attribute(), wmtk::Mesh::resurrect_tuple(), wmtk::simplex::SimplexCollection::simplex_vector(), and wmtk::multimesh::utils::symmetric_write_tuple_map_attributes().
Referenced by update_vertex_operation_hashes_internal().
Friends And Related Function Documentation
HDF5Reader
friend class HDF5Reader friend
Definition at line 65 of file MultiMeshManager.hpp.
Mesh
friend class Mesh friend
Definition at line 53 of file MultiMeshManager.hpp.
multimesh::MultiMeshSimplexVisitor
template<int64_t cell_dimension, typename NodeFunctor > friend class multimesh::MultiMeshSimplexVisitor friend
Definition at line 52 of file MultiMeshManager.hpp.
multimesh::MultiMeshSimplexVisitorExecutor
template<typename Visitor > friend class multimesh::MultiMeshSimplexVisitorExecutor friend
Definition at line 55 of file MultiMeshManager.hpp.
multimesh::MultiMeshVisitor
template<typename NodeFunctor > friend class multimesh::MultiMeshVisitor friend
Definition at line 62 of file MultiMeshManager.hpp.
multimesh::MultiMeshVisitorExecutor
template<typename Visitor > friend class multimesh::MultiMeshVisitorExecutor friend
Definition at line 64 of file MultiMeshManager.hpp.
multimesh::same_simplex_dimension_surjection
std::vector<std::array<Tuple, 2> > multimesh::same_simplex_dimension_surjection (const Mesh & parent, const Mesh & child, const std::vector< int64_t > & parent_simplices) friend
operations::utils::update_vertex_operation_multimesh_map_hash
void operations::utils::update_vertex_operation_multimesh_map_hash (Mesh & m, const simplex::SimplexCollection & vertex_closed_star, attribute::MutableAccessor< int64_t > & parent_hash_accessor) friend
operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
friend class operations::utils::UpdateEdgeOperationMultiMeshMapFunctor friend
Definition at line 56 of file MultiMeshManager.hpp.
Member Data Documentation
m_child_id
int64_t wmtk::MultiMeshManager::m_child_id = -1 protected
Definition at line 343 of file MultiMeshManager.hpp.
Referenced by absolute_id(), child_hashes(), child_id(), get_child_mesh(), map_down_relative_tuples(), register_child_mesh(), and relative_id().
m_children
std::vector<ChildData> wmtk::MultiMeshManager::m_children protected
Definition at line 347 of file MultiMeshManager.hpp.
Referenced by child_hashables(), child_hashes(), children(), get_child_mesh(), get_child_meshes(), map_down_relative_tuples(), map_handles(), map_to_child_tuples(), register_child_mesh(), and serialize().
m_has_child_mesh_in_dimension
std::vector<bool> wmtk::MultiMeshManager::m_has_child_mesh_in_dimension protected
Definition at line 350 of file MultiMeshManager.hpp.
Referenced by has_child_mesh_in_dimension(), and register_child_mesh().
m_parent
Mesh* wmtk::MultiMeshManager::m_parent = nullptr protected
Definition at line 337 of file MultiMeshManager.hpp.
Referenced by absolute_id(), child_hashes(), get_root_mesh(), is_child(), is_root(), map_tuple_to_parent_tuple(), map_tuple_to_root_tuple(), map_up_to_tuples(), register_child_mesh(), and relative_id().
map_to_parent_handle
TypedAttributeHandle<int64_t> wmtk::MultiMeshManager::map_to_parent_handle protected
Definition at line 340 of file MultiMeshManager.hpp.
Referenced by child_hashes(), get_map_accessors(), get_map_const_accessors(), map_handles(), map_tuple_to_parent_tuple(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), and register_child_mesh().
The documentation for this class was generated from the following files:
src/wmtk/MultiMeshManager.hpp
src/wmtk/MultiMeshManager.cpp