Wildmeshing Toolkit: wmtk::operations::NewAttributeStrategy Class Reference
wmtk::operations::NewAttributeStrategy Class Reference abstract
#include <NewAttributeStrategy.hpp>
Classes
struct OpSettings
Public Types
enum class CollapseBasicStrategy {
Default , CopyTuple , CopyOther , CopyFromPredicate ,
Mean , Throw , None
}
enum class SplitBasicStrategy {
Default , Copy , Half , Throw ,
None
}
enum class BasicSimplexPredicate { Default , IsInterior }
using SplitRibBasicStrategy = CollapseBasicStrategy
template<typename T >
using VecType = VectorX< T >
template<typename T , typename VT = VecType<T>>
using SplitFuncType = std::function< std::array< VT, 2 >(const VT &)>
template<typename T , typename VT = VecType<T>>
using SplitRibFuncType = std::function< VT(const VT &, const VT &)>
using SimplexPredicateType = std::function< bool(const simplex::Simplex &)>
template<typename T , typename VT = VecType<T>>
using CollapseFuncType = std::function< VT(const VT &, const VT &)>
Public Member Functions
virtual ~NewAttributeStrategy ()
virtual bool matches_attribute (const attribute::MeshAttributeHandleVariant &) const =0
virtual void update_handle_mesh (Mesh &)=0
virtual PrimitiveType primitive_type () const =0
virtual Mesh & mesh ()=0
const Mesh & mesh () const
template<typename T >
auto standard_collapse_strategy (CollapseBasicStrategy optype) -> CollapseFuncType< T >
template<typename T >
auto standard_split_strategy (SplitBasicStrategy optype) -> SplitFuncType< T >
template<typename T >
auto standard_split_rib_strategy (SplitRibBasicStrategy optype) -> SplitRibFuncType< T >
Static Public Member Functions
template<typename T >
static CollapseFuncType< T > standard_collapse_strategy (CollapseBasicStrategy=CollapseBasicStrategy::Default)
template<typename T >
static SplitFuncType< T > standard_split_strategy (SplitBasicStrategy=SplitBasicStrategy::Default)
template<typename T >
static SplitRibFuncType< T > standard_split_rib_strategy (SplitRibBasicStrategy=SplitRibBasicStrategy::Default)
Detailed Description
Definition at line 17 of file NewAttributeStrategy.hpp.
Member Typedef Documentation
CollapseFuncType
template<typename T , typename VT = VecType<T>> using wmtk::operations::NewAttributeStrategy::CollapseFuncType = std::function<VT(const VT&, const VT&)>
Definition at line 62 of file NewAttributeStrategy.hpp.
SimplexPredicateType
using wmtk::operations::NewAttributeStrategy::SimplexPredicateType = std::function<bool(const simplex::Simplex&)>
Definition at line 57 of file NewAttributeStrategy.hpp.
SplitFuncType
template<typename T , typename VT = VecType<T>> using wmtk::operations::NewAttributeStrategy::SplitFuncType = std::function<std::array<VT, 2>(const VT&)>
Definition at line 51 of file NewAttributeStrategy.hpp.
SplitRibBasicStrategy
using wmtk::operations::NewAttributeStrategy::SplitRibBasicStrategy = CollapseBasicStrategy
Definition at line 37 of file NewAttributeStrategy.hpp.
SplitRibFuncType
template<typename T , typename VT = VecType<T>> using wmtk::operations::NewAttributeStrategy::SplitRibFuncType = std::function<VT(const VT&, const VT&)>
Definition at line 55 of file NewAttributeStrategy.hpp.
VecType
template<typename T > using wmtk::operations::NewAttributeStrategy::VecType = VectorX<T>
Definition at line 46 of file NewAttributeStrategy.hpp.
Member Enumeration Documentation
BasicSimplexPredicate
enum wmtk::operations::NewAttributeStrategy::BasicSimplexPredicate strong
Enumerator
Default
IsInterior
Definition at line 33 of file NewAttributeStrategy.hpp.
CollapseBasicStrategy
enum wmtk::operations::NewAttributeStrategy::CollapseBasicStrategy strong
Enumerator
Default
CopyTuple
CopyOther
CopyFromPredicate
Mean
Throw
None
Definition at line 21 of file NewAttributeStrategy.hpp.
SplitBasicStrategy
enum wmtk::operations::NewAttributeStrategy::SplitBasicStrategy strong
Enumerator
Default
Copy
Half
Throw
None
Definition at line 31 of file NewAttributeStrategy.hpp.
Constructor & Destructor Documentation
~NewAttributeStrategy()
wmtk::operations::NewAttributeStrategy::~NewAttributeStrategy () virtual default
Member Function Documentation
matches_attribute()
virtual bool wmtk::operations::NewAttributeStrategy::matches_attribute (const attribute::MeshAttributeHandleVariant &) const pure virtual
Implemented in wmtk::operations::tri_mesh::PredicateAwareSplitNewAttributeStrategy< T >, wmtk::operations::tri_mesh::PredicateAwareCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BoundaryAwayCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >, and wmtk::operations::tri_mesh::BasicCollapseNewAttributeStrategy< T >.
mesh() [1/2]
const Mesh & wmtk::operations::NewAttributeStrategy::mesh () const
Definition at line 10 of file NewAttributeStrategy.cpp.
References mesh().
mesh() [2/2]
virtual Mesh& wmtk::operations::NewAttributeStrategy::mesh () pure virtual
Implemented in wmtk::operations::tri_mesh::PredicateAwareSplitNewAttributeStrategy< T >, wmtk::operations::tri_mesh::PredicateAwareCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BoundaryAwayCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >, and wmtk::operations::tri_mesh::BasicCollapseNewAttributeStrategy< T >.
Referenced by wmtk::operations::edge_mesh::CollapseNewAttributeStrategy::edge_mesh(), wmtk::operations::edge_mesh::SplitNewAttributeStrategy::edge_mesh(), wmtk::operations::edge_mesh::SplitNewAttributeStrategy::input_ear_simplices(), wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_ear_simplices(), wmtk::operations::tri_mesh::SplitNewAttributeStrategy::input_ear_simplices(), wmtk::operations::edge_mesh::SplitNewAttributeStrategy::input_split_simplices(), wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_split_simplices(), wmtk::operations::tri_mesh::SplitNewAttributeStrategy::input_split_simplices(), wmtk::operations::edge_mesh::CollapseNewAttributeStrategy::merged_simplices(), wmtk::operations::tet_mesh::CollapseNewAttributeStrategy::merged_simplices(), wmtk::operations::tri_mesh::CollapseNewAttributeStrategy::merged_simplices(), mesh(), wmtk::operations::edge_mesh::CollapseNewAttributeStrategy::new_simplices(), wmtk::operations::tet_mesh::CollapseNewAttributeStrategy::new_simplices(), wmtk::operations::tri_mesh::CollapseNewAttributeStrategy::new_simplices(), wmtk::operations::edge_mesh::SplitNewAttributeStrategy::output_rib_simplices(), wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_rib_simplices(), wmtk::operations::tri_mesh::SplitNewAttributeStrategy::output_rib_simplices(), wmtk::operations::edge_mesh::SplitNewAttributeStrategy::output_split_simplices(), wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_split_simplices(), wmtk::operations::tri_mesh::SplitNewAttributeStrategy::output_split_simplices(), wmtk::operations::tet_mesh::CollapseNewAttributeStrategy::tet_mesh(), wmtk::operations::tet_mesh::SplitNewAttributeStrategy::tet_mesh(), wmtk::operations::tri_mesh::CollapseNewAttributeStrategy::tri_mesh(), wmtk::operations::tri_mesh::SplitNewAttributeStrategy::tri_mesh(), wmtk::operations::SplitNewAttributeStrategy::update(), and wmtk::operations::CollapseNewAttributeStrategy::update().
primitive_type()
virtual PrimitiveType wmtk::operations::NewAttributeStrategy::primitive_type () const pure virtual
Implemented in wmtk::operations::tri_mesh::PredicateAwareSplitNewAttributeStrategy< T >, wmtk::operations::tri_mesh::PredicateAwareCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BoundaryAwayCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >, and wmtk::operations::tri_mesh::BasicCollapseNewAttributeStrategy< T >.
standard_collapse_strategy() [1/2]
template<typename T > auto wmtk::operations::NewAttributeStrategy::standard_collapse_strategy (CollapseBasicStrategy optype) -> CollapseFuncType<T>
Definition at line 27 of file NewAttributeStrategy.cpp.
standard_collapse_strategy() [2/2]
template<typename T > static CollapseFuncType<T> wmtk::operations::NewAttributeStrategy::standard_collapse_strategy (CollapseBasicStrategy = CollapseBasicStrategy::Default) static
standard_split_rib_strategy() [1/2]
template<typename T > auto wmtk::operations::NewAttributeStrategy::standard_split_rib_strategy (SplitRibBasicStrategy optype) -> SplitRibFuncType<T>
Definition at line 75 of file NewAttributeStrategy.cpp.
standard_split_rib_strategy() [2/2]
template<typename T > static SplitRibFuncType<T> wmtk::operations::NewAttributeStrategy::standard_split_rib_strategy (SplitRibBasicStrategy = SplitRibBasicStrategy::Default) static
standard_split_strategy() [1/2]
template<typename T > auto wmtk::operations::NewAttributeStrategy::standard_split_strategy (SplitBasicStrategy optype) -> SplitFuncType<T>
Definition at line 54 of file NewAttributeStrategy.cpp.
standard_split_strategy() [2/2]
template<typename T > static SplitFuncType<T> wmtk::operations::NewAttributeStrategy::standard_split_strategy (SplitBasicStrategy = SplitBasicStrategy::Default) static
update_handle_mesh()
virtual void wmtk::operations::NewAttributeStrategy::update_handle_mesh (Mesh &) pure virtual
Implemented in wmtk::operations::SplitNewAttributeStrategy, wmtk::operations::CollapseNewAttributeStrategy, wmtk::operations::tri_mesh::PredicateAwareSplitNewAttributeStrategy< T >, wmtk::operations::tri_mesh::PredicateAwareCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BoundaryAwayCollapseNewAttributeStrategy< T >, wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >, and wmtk::operations::tri_mesh::BasicCollapseNewAttributeStrategy< T >.
The documentation for this class was generated from the following files:
src/wmtk/operations/NewAttributeStrategy.hpp
src/wmtk/operations/NewAttributeStrategy.cpp