Wildmeshing Toolkit: wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ > Class Template Reference
wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ > Class Template Reference
#include <MultiMeshVisitor.hpp>
Public Types
using MeshVariantTraits = wmtk::utils::metaprogramming::MeshVariantTraits
using NodeFunctor = NodeFunctor_
using ReturnDataType = wmtk::utils::metaprogramming::ReferenceWrappedFunctorReturnCache< NodeFunctor, MeshVariantTraits >
using CacheType = ReturnDataType
using TypeHelper = wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnType< NodeFunctor, MeshVariantTraits::AllReferenceTuple >
using Executor = MultiMeshVisitorExecutor< MultiMeshVisitor< NodeFunctor > >
Public Member Functions
MultiMeshVisitor (NodeFunctor &&f)
template<typename MeshType >
void execute_mesh (MeshType &&mesh)
void execute_from_root (Mesh &mesh)
Protected Attributes
NodeFunctor m_node_functor
Friends
template<typename MMVisitor_ >
class MultiMeshVisitorExecutor
Detailed Description
template<typename NodeFunctor_>
class wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >
Definition at line 28 of file MultiMeshVisitor.hpp.
Member Typedef Documentation
CacheType
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::CacheType = ReturnDataType
Definition at line 36 of file MultiMeshVisitor.hpp.
Executor
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::Executor = MultiMeshVisitorExecutor<MultiMeshVisitor<NodeFunctor> >
Definition at line 53 of file MultiMeshVisitor.hpp.
MeshVariantTraits
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::MeshVariantTraits = wmtk::utils::metaprogramming::MeshVariantTraits
Definition at line 31 of file MultiMeshVisitor.hpp.
NodeFunctor
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::NodeFunctor = NodeFunctor_
Definition at line 32 of file MultiMeshVisitor.hpp.
ReturnDataType
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::ReturnDataType = wmtk::utils::metaprogramming:: ReferenceWrappedFunctorReturnCache<NodeFunctor, MeshVariantTraits>
Definition at line 34 of file MultiMeshVisitor.hpp.
TypeHelper
template<typename NodeFunctor_ > using wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::TypeHelper = wmtk::utils::metaprogramming::detail:: ReferenceWrappedFunctorReturnType<NodeFunctor, MeshVariantTraits::AllReferenceTuple>
Definition at line 38 of file MultiMeshVisitor.hpp.
Constructor & Destructor Documentation
MultiMeshVisitor()
template<typename NodeFunctor_ > wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::MultiMeshVisitor (NodeFunctor && f) inline
Definition at line 46 of file MultiMeshVisitor.hpp.
Member Function Documentation
execute_from_root()
template<typename NodeFunctor_ > void wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root (Mesh & mesh) inline
Definition at line 79 of file MultiMeshVisitor.hpp.
References wmtk::utils::metaprogramming::as_mesh_variant(), wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_mesh(), and wmtk::Mesh::get_multi_mesh_root().
Referenced by wmtk::multimesh::consolidate(), wmtk::operations::EdgeCollapse::EdgeCollapse(), wmtk::operations::EdgeSplit::EdgeSplit(), wmtk::components::get_all_meshes(), wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::operations::Operation::reserve_enough_simplices(), wmtk::components::shortestedge_collapse(), wmtk::multimesh::attribute::UseParentScopeRAII::UseParentScopeRAII(), and wmtk::multimesh::attribute::UseParentScopeRAII::~UseParentScopeRAII().
execute_mesh()
template<typename NodeFunctor_ > template<typename MeshType > void wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_mesh (MeshType && mesh) inline
Definition at line 63 of file MultiMeshVisitor.hpp.
References wmtk::multimesh::MultiMeshVisitorExecutor< MMVisitor >::execute().
Referenced by wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root().
Friends And Related Function Documentation
MultiMeshVisitorExecutor
template<typename NodeFunctor_ > template<typename MMVisitor_ > friend class MultiMeshVisitorExecutor friend
Definition at line 52 of file MultiMeshVisitor.hpp.
Member Data Documentation
m_node_functor
template<typename NodeFunctor_ > NodeFunctor wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::m_node_functor protected
Definition at line 90 of file MultiMeshVisitor.hpp.
The documentation for this class was generated from the following files:
src/wmtk/Mesh.hpp
src/wmtk/multimesh/MultiMeshVisitor.hpp