Wildmeshing Toolkit: wmtk::Scheduler Class Reference
wmtk::Scheduler Class Reference
#include <Scheduler.hpp>
Public Member Functions
Scheduler ()
~Scheduler ()
SchedulerStats run_operation_on_all (operations::Operation &op)
SchedulerStats run_operation_on_all (operations::Operation &op, const TypedAttributeHandle< char > &flag_handle)
SchedulerStats run_operation_on_all_coloring (operations::Operation &op, const TypedAttributeHandle< int64_t > &color_handle)
const SchedulerStats & stats () const
void set_update_frequency (std::optional< size_t > &&freq={})
Private Member Functions
void log (const size_t total)
void log (const SchedulerStats &stats, const size_t total)
Private Attributes
SchedulerStats m_stats
std::optional< size_t > m_update_frequency = {}
Detailed Description
Definition at line 88 of file Scheduler.hpp.
Constructor & Destructor Documentation
Scheduler()
wmtk::Scheduler::Scheduler () default
~Scheduler()
wmtk::Scheduler::~Scheduler () default
Member Function Documentation
log() [1/2]
void wmtk::Scheduler::log (const SchedulerStats & stats, const size_t total) private
Definition at line 376 of file Scheduler.cpp.
References wmtk::SchedulerStats::number_of_performed_operations(), and wmtk::SchedulerStats::print_update_log().
log() [2/2]
void wmtk::Scheduler::log (const size_t total) private
Definition at line 372 of file Scheduler.cpp.
Referenced by run_operation_on_all().
run_operation_on_all() [1/2]
SchedulerStats wmtk::Scheduler::run_operation_on_all (operations::Operation & op)
Definition at line 29 of file Scheduler.cpp.
References wmtk::SchedulerStats::collecting_time, wmtk::SchedulerStats::executing_time, wmtk::SchedulerStats::fail(), wmtk::Mesh::get_all(), wmtk::utils::get_random_seed(), log(), wmtk::logger(), m_stats, m_update_frequency, wmtk::operations::Operation::mesh(), wmtk::operations::Operation::primitive_type(), wmtk::SchedulerStats::print_update_log(), wmtk::operations::Operation::priority(), wmtk::SchedulerStats::sorting_time, wmtk::SchedulerStats::succeed(), wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector(), and wmtk::operations::Operation::use_random_priority().
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::internal::periodic_optimization(), wmtk::components::Marching::process(), wmtk::components::internal::RegularSpace::regularize_tags(), run_operation_on_all(), wmtk::components::shortestedge_collapse(), TEST_CASE(), wmtk::components::triangle_insertion::triangle_insertion(), and wmtk::components::wildmeshing().
run_operation_on_all() [2/2]
SchedulerStats wmtk::Scheduler::run_operation_on_all (operations::Operation & op, const TypedAttributeHandle< char > & flag_handle)
Definition at line 106 of file Scheduler.cpp.
References wmtk::SchedulerStats::collecting_time, wmtk::Mesh::create_accessor(), wmtk::SchedulerStats::executing_time, wmtk::SchedulerStats::fail(), wmtk::Mesh::get_all(), wmtk::utils::get_random_seed(), log(), wmtk::logger(), m_stats, wmtk::operations::Operation::mesh(), wmtk::SchedulerStats::number_of_successful_operations(), wmtk::operations::Operation::primitive_type(), wmtk::operations::Operation::priority(), run_operation_on_all(), wmtk::SchedulerStats::sorting_time, wmtk::SchedulerStats::sub_stats, wmtk::SchedulerStats::succeed(), wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector(), and wmtk::operations::Operation::use_random_priority().
run_operation_on_all_coloring()
SchedulerStats wmtk::Scheduler::run_operation_on_all_coloring (operations::Operation & op, const TypedAttributeHandle< int64_t > & color_handle)
Definition at line 237 of file Scheduler.cpp.
References wmtk::SchedulerStats::collecting_time, wmtk::Mesh::create_accessor(), wmtk::first_available_color(), wmtk::Mesh::get_all(), wmtk::simplex::k_ring(), wmtk::simplex::link(), wmtk::logger(), wmtk::operations::Operation::mesh(), wmtk::operations::Operation::primitive_type(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
set_update_frequency()
void wmtk::Scheduler::set_update_frequency (std::optional< size_t > && freq = {})
Definition at line 388 of file Scheduler.cpp.
Referenced by wmtk::components::wildmeshing().
stats()
const SchedulerStats& wmtk::Scheduler::stats () const inline
Definition at line 102 of file Scheduler.hpp.
References m_stats.
Member Data Documentation
m_stats
SchedulerStats wmtk::Scheduler::m_stats private
Definition at line 107 of file Scheduler.hpp.
Referenced by run_operation_on_all(), and stats().
m_update_frequency
std::optional<size_t> wmtk::Scheduler::m_update_frequency = {} private
Definition at line 108 of file Scheduler.hpp.
Referenced by run_operation_on_all().
The documentation for this class was generated from the following files:
src/wmtk/Scheduler.hpp
src/wmtk/Scheduler.cpp