Wildmeshing Toolkit: wmtk::autogen::edge_mesh::SimplexDart Class Reference
wmtk::autogen::edge_mesh::SimplexDart Class Reference
#include <SimplexDart.hpp>
Public Member Functions
SimplexDart ()
Static Public Member Functions
static int8_t product (int8_t a, int8_t b)
static int8_t inverse (int8_t a)
static int8_t primitive_to_index (wmtk::PrimitiveType pt)
static int8_t identity ()
static int8_t opposite ()
static constexpr size_t size ()
static auto valid_indices ()
static auto valid_indices_dynamic ()
static int8_t simplex_index (wmtk::PrimitiveType type, int8_t valid_index)
Detailed Description
Definition at line 10 of file SimplexDart.hpp.
Constructor & Destructor Documentation
SimplexDart()
wmtk::autogen::edge_mesh::SimplexDart::SimplexDart ()
Member Function Documentation
identity()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::identity () inline static
Definition at line 21 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuple_switch_indices, wmtk::Edge, and wmtk::get_primitive_type_id().
Referenced by wmtk::autogen::edge_mesh::subdart_maximal_action_to_face(), and wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_action().
inverse()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::inverse (int8_t a) inline static
Definition at line 16 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_switch_inverse_table.
opposite()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::opposite () inline static
Definition at line 25 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuple_switch_indices, wmtk::Edge, and wmtk::get_primitive_type_id().
primitive_to_index()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::primitive_to_index (wmtk::PrimitiveType pt) inline static
Definition at line 17 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuple_switch_indices, and wmtk::get_primitive_type_id().
product()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::product (int8_t a, int8_t b) inline static
Definition at line 15 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_switch_product_table.
simplex_index()
static int8_t wmtk::autogen::edge_mesh::SimplexDart::simplex_index (wmtk::PrimitiveType type, int8_t valid_index) inline static
Definition at line 38 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuples, and wmtk::get_primitive_type_id().
size()
static constexpr size_t wmtk::autogen::edge_mesh::SimplexDart::size () inline static constexpr
Definition at line 30 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuple_indices.
Referenced by valid_indices_dynamic().
valid_indices()
static auto wmtk::autogen::edge_mesh::SimplexDart::valid_indices () inline static
Definition at line 32 of file SimplexDart.hpp.
References wmtk::utils::array_to_map(), and wmtk::autogen::edge_mesh::auto_valid_tuple_indices.
valid_indices_dynamic()
static auto wmtk::autogen::edge_mesh::SimplexDart::valid_indices_dynamic () inline static
Definition at line 33 of file SimplexDart.hpp.
References wmtk::autogen::edge_mesh::auto_valid_tuple_indices, and size().
The documentation for this class was generated from the following file:
src/wmtk/autogen/edge_mesh/SimplexDart.hpp