Wildmeshing Toolkit: wmtk::components::multimesh::MeshCollection Class Reference
wmtk::components::multimesh::MeshCollection Class Reference
#include <MeshCollection.hpp>
Public Member Functions
NamedMultiMesh & add_mesh (NamedMultiMesh o)
template<typename... Args>
NamedMultiMesh & emplace_mesh (Args &&... args)
const NamedMultiMesh & get_named_multimesh (const std::string_view &path) const
const Mesh & get_mesh (const std::string_view &path) const
bool has_mesh (const std::string_view &path) const
bool has_named_multimesh (const std::string_view &path) const
NamedMultiMesh & get_named_multimesh (const std::string_view &path)
Mesh & get_mesh (const std::string_view &path)
void make_canonical ()
std::map< std::string, const Mesh & > all_meshes () const
Private Attributes
std::map< std::string_view, std::unique_ptr< NamedMultiMesh > > m_meshes
Detailed Description
Definition at line 9 of file MeshCollection.hpp.
Member Function Documentation
add_mesh()
NamedMultiMesh & wmtk::components::multimesh::MeshCollection::add_mesh (NamedMultiMesh o)
Definition at line 11 of file MeshCollection.cpp.
References m_meshes.
Referenced by emplace_mesh().
all_meshes()
std::map< std::string, const Mesh & > wmtk::components::multimesh::MeshCollection::all_meshes () const
Definition at line 85 of file MeshCollection.cpp.
References m_meshes.
emplace_mesh()
template<typename... Args> NamedMultiMesh& wmtk::components::multimesh::MeshCollection::emplace_mesh (Args &&... args) inline
Definition at line 14 of file MeshCollection.hpp.
References add_mesh().
get_mesh() [1/2]
Mesh & wmtk::components::multimesh::MeshCollection::get_mesh (const std::string_view & path)
Definition at line 30 of file MeshCollection.cpp.
References wmtk::components::multimesh::NamedMultiMesh::get_mesh(), and get_named_multimesh().
get_mesh() [2/2]
const Mesh & wmtk::components::multimesh::MeshCollection::get_mesh (const std::string_view & path) const
Definition at line 25 of file MeshCollection.cpp.
References wmtk::components::multimesh::NamedMultiMesh::get_mesh(), and get_named_multimesh().
Referenced by wmtk::components::multimesh::utils::get_attribute().
get_named_multimesh() [1/2]
NamedMultiMesh & wmtk::components::multimesh::MeshCollection::get_named_multimesh (const std::string_view & path)
Definition at line 68 of file MeshCollection.cpp.
References wmtk::logger(), m_meshes, and wmtk::components::multimesh::internal::split_path().
get_named_multimesh() [2/2]
const NamedMultiMesh & wmtk::components::multimesh::MeshCollection::get_named_multimesh (const std::string_view & path) const
Definition at line 52 of file MeshCollection.cpp.
References wmtk::logger(), m_meshes, and wmtk::components::multimesh::internal::split_path().
Referenced by get_mesh(), and has_mesh().
has_mesh()
bool wmtk::components::multimesh::MeshCollection::has_mesh (const std::string_view & path) const
Definition at line 42 of file MeshCollection.cpp.
References get_named_multimesh(), and has_named_multimesh().
has_named_multimesh()
bool wmtk::components::multimesh::MeshCollection::has_named_multimesh (const std::string_view & path) const
Definition at line 34 of file MeshCollection.cpp.
References m_meshes, and wmtk::components::multimesh::internal::split_path().
Referenced by has_mesh().
make_canonical()
void wmtk::components::multimesh::MeshCollection::make_canonical ()
Definition at line 97 of file MeshCollection.cpp.
References m_meshes.
Member Data Documentation
m_meshes
std::map<std::string_view, std::unique_ptr<NamedMultiMesh> > wmtk::components::multimesh::MeshCollection::m_meshes private
Definition at line 35 of file MeshCollection.hpp.
Referenced by add_mesh(), all_meshes(), get_named_multimesh(), has_named_multimesh(), and make_canonical().
The documentation for this class was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/MeshCollection.hpp
components/multimesh/src/wmtk/components/multimesh/MeshCollection.cpp