Wildmeshing Toolkit: wmtk::Swap32EnergyBeforeInvariantDouble Class Reference
wmtk::Swap32EnergyBeforeInvariantDouble Class Reference
#include <Swap32EnergyBeforeInvariantDouble.hpp>
Public Member Functions
Swap32EnergyBeforeInvariantDouble (const Mesh &m, const attribute::TypedAttributeHandle< double > &coordinate, double eps=1.0001)
bool before (const simplex::Simplex &t) const override
Invariant (const Mesh &m)
Invariant (const Mesh &m, bool use_before, bool use_old_state_in_after, bool use_new_state_in_after)
Public Member Functions inherited from wmtk::invariants::Invariant
virtual bool after (const std::vector< Tuple > &top_dimension_tuples_before, const std::vector< Tuple > &top_dimension_tuples_after) const
Invariant (const Mesh &m)
Invariant (const Mesh &m, bool use_before, bool use_old_state_in_after, bool use_new_state_in_after)
virtual ~Invariant ()
const Mesh & mesh () const
virtual bool directly_modified_after (const std::vector< simplex::Simplex > &simplices_before, const std::vector< simplex::Simplex > &simplices_after) const
bool use_before () const
bool use_after () const
bool use_old_state_in_after () const
bool use_new_state_in_after () const
Private Attributes
const attribute::TypedAttributeHandle< double > m_coordinate_handle
const double m_eps
Detailed Description
Definition at line 7 of file Swap32EnergyBeforeInvariantDouble.hpp.
Constructor & Destructor Documentation
Swap32EnergyBeforeInvariantDouble()
wmtk::Swap32EnergyBeforeInvariantDouble::Swap32EnergyBeforeInvariantDouble (const Mesh & m, const attribute::TypedAttributeHandle< double > & coordinate, double eps = 1.0001)
Definition at line 7 of file Swap32EnergyBeforeInvariantDouble.cpp.
Member Function Documentation
before()
bool wmtk::Swap32EnergyBeforeInvariantDouble::before (const simplex::Simplex & t) const override virtual
Reimplemented from wmtk::invariants::Invariant.
Definition at line 16 of file Swap32EnergyBeforeInvariantDouble.cpp.
References wmtk::Mesh::create_const_accessor(), wmtk::Edge, m_coordinate_handle, m_eps, wmtk::invariants::Invariant::mesh(), wmtk::PE, PF, PT, wmtk::PV, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::function::utils::Tet_AMIPS_energy(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), wmtk::Vertex, and wmtk::utils::wmtk_orient3d().
Invariant() [1/2]
wmtk::invariants::Invariant::Invariant
Definition at line 23 of file Invariant.cpp.
Invariant() [2/2]
wmtk::invariants::Invariant::Invariant
Definition at line 24 of file Invariant.cpp.
Member Data Documentation
m_coordinate_handle
const attribute::TypedAttributeHandle<double> wmtk::Swap32EnergyBeforeInvariantDouble::m_coordinate_handle private
Definition at line 19 of file Swap32EnergyBeforeInvariantDouble.hpp.
Referenced by before().
m_eps
const double wmtk::Swap32EnergyBeforeInvariantDouble::m_eps private
Definition at line 20 of file Swap32EnergyBeforeInvariantDouble.hpp.
Referenced by before().
The documentation for this class was generated from the following files:
src/wmtk/invariants/Swap32EnergyBeforeInvariantDouble.hpp
src/wmtk/invariants/Swap32EnergyBeforeInvariantDouble.cpp