Wildmeshing Toolkit: wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S > Class Template Reference
wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S > Class Template Reference
Public Member Functions
WMTKAMIPSProblem (std::vector< std::array< double, S >> &cells)
TVector initial_value () const
double value (const TVector &x) override
void gradient (const TVector &x, TVector &gradv) override
void hessian (const TVector &x, THessian &hessian) override
void hessian (const TVector &x, Eigen::MatrixXd &hessian) override
void solution_changed (const TVector &new_x) override
bool is_step_valid (const TVector &x0, const TVector &x1) override
Private Attributes
std::vector< std::array< double, S > > m_cells
Detailed Description
template<int S>
class wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >
Definition at line 19 of file AMIPSOptimizationSmoothingPeriodic.cpp.
Constructor & Destructor Documentation
WMTKAMIPSProblem()
template<int S> wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::WMTKAMIPSProblem (std::vector< std::array< double, S >> & cells)
Definition at line 52 of file AMIPSOptimizationSmoothingPeriodic.cpp.
Member Function Documentation
gradient()
template<int S> void wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::gradient (const TVector & x, TVector & gradv) override
Definition at line 103 of file AMIPSOptimizationSmoothingPeriodic.cpp.
References wmtk::pow(), wmtk::function::Tet_AMIPS_energy(), wmtk::function::Tet_AMIPS_jacobian(), wmtk::function::Tri_AMIPS_energy(), and wmtk::function::Tri_AMIPS_jacobian().
hessian() [1/2]
template<int S> void wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::hessian (const TVector & x, Eigen::MatrixXd & hessian) override
Definition at line 143 of file AMIPSOptimizationSmoothingPeriodic.cpp.
References wmtk::pow(), wmtk::function::Tet_AMIPS_energy(), wmtk::function::Tet_AMIPS_hessian(), wmtk::function::Tet_AMIPS_jacobian(), wmtk::function::Tri_AMIPS_energy(), wmtk::function::Tri_AMIPS_hessian(), and wmtk::function::Tri_AMIPS_jacobian().
hessian() [2/2]
template<int S> void wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::hessian (const TVector & x, THessian & hessian) inline override
Definition at line 32 of file AMIPSOptimizationSmoothingPeriodic.cpp.
initial_value()
template<int S> Eigen::Matrix< double, -1, 1 > wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::initial_value () const
Definition at line 59 of file AMIPSOptimizationSmoothingPeriodic.cpp.
Referenced by wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute().
is_step_valid()
template<int S> bool wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::is_step_valid (const TVector & x0, const TVector & x1) override
Definition at line 193 of file AMIPSOptimizationSmoothingPeriodic.cpp.
References wmtk::utils::wmtk_orient2d(), and wmtk::utils::wmtk_orient3d().
Referenced by wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute().
solution_changed()
template<int S> void wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::solution_changed (const TVector & new_x) override
Definition at line 189 of file AMIPSOptimizationSmoothingPeriodic.cpp.
value()
template<int S> double wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::value (const TVector & x) override
Definition at line 72 of file AMIPSOptimizationSmoothingPeriodic.cpp.
References wmtk::pow(), wmtk::function::Tet_AMIPS_energy(), and wmtk::function::Tri_AMIPS_energy().
Member Data Documentation
m_cells
template<int S> std::vector<std::array<double, S> > wmtk::operations::AMIPSOptimizationSmoothingPeriodic::WMTKAMIPSProblem< S >::m_cells private
Definition at line 43 of file AMIPSOptimizationSmoothingPeriodic.cpp.
The documentation for this class was generated from the following file:
src/wmtk/operations/AMIPSOptimizationSmoothingPeriodic.cpp