Wildmeshing Toolkit: wmtk::components::utils::PathResolver Class Reference
wmtk::components::utils::PathResolver Class Reference
#include <PathResolver.hpp>
Classes
struct Impl
Public Member Functions
PathResolver ()
PathResolver (const std::filesystem::path &path)
~PathResolver ()
PathResolver (PathResolver &&)
PathResolver (const PathResolver &)
PathResolver & operator= (PathResolver &&)
PathResolver & operator= (const PathResolver &)
void add_path (const std::filesystem::path &path)
void clear_paths ()
std::pair< std::filesystem::path, bool > resolve (const std::filesystem::path &path) const
std::vector< std::filesystem::path > get_paths () const
Static Public Member Functions
static std::pair< std::filesystem::path, bool > try_resolving_path (const std::filesystem::path &potential_base, const std::filesystem::path &path)
Private Attributes
std::unique_ptr< Impl > m_impl
Detailed Description
Definition at line 12 of file PathResolver.hpp.
Constructor & Destructor Documentation
PathResolver() [1/4]
wmtk::components::utils::PathResolver::PathResolver ()
Definition at line 55 of file PathResolver.cpp.
PathResolver() [2/4]
wmtk::components::utils::PathResolver::PathResolver (const std::filesystem::path & path)
Definition at line 59 of file PathResolver.cpp.
References m_impl.
~PathResolver()
wmtk::components::utils::PathResolver::~PathResolver () default
PathResolver() [3/4]
wmtk::components::utils::PathResolver::PathResolver (PathResolver &&) default
PathResolver() [4/4]
wmtk::components::utils::PathResolver::PathResolver (const PathResolver & o)
Definition at line 65 of file PathResolver.cpp.
Member Function Documentation
add_path()
void wmtk::components::utils::PathResolver::add_path (const std::filesystem::path & path)
Definition at line 81 of file PathResolver.cpp.
References m_impl.
clear_paths()
void wmtk::components::utils::PathResolver::clear_paths ()
Definition at line 77 of file PathResolver.cpp.
References m_impl.
get_paths()
std::vector< std::filesystem::path > wmtk::components::utils::PathResolver::get_paths () const
Definition at line 92 of file PathResolver.cpp.
References m_impl.
Referenced by wmtk::components::input::input().
operator=() [1/2]
PathResolver & wmtk::components::utils::PathResolver::operator= (const PathResolver & o)
Definition at line 69 of file PathResolver.cpp.
References m_impl.
operator=() [2/2]
PathResolver & wmtk::components::utils::PathResolver::operator= (PathResolver &&) default
resolve()
std::pair< std::filesystem::path, bool > wmtk::components::utils::PathResolver::resolve (const std::filesystem::path & path) const
Definition at line 86 of file PathResolver.cpp.
References m_impl.
Referenced by wmtk::components::input::input().
try_resolving_path()
std::pair< std::filesystem::path, bool > wmtk::components::utils::PathResolver::try_resolving_path (const std::filesystem::path & potential_base, const std::filesystem::path & path) static
Definition at line 8 of file PathResolver.cpp.
Referenced by wmtk::components::utils::PathResolver::Impl::resolve().
Member Data Documentation
m_impl
std::unique_ptr<Impl> wmtk::components::utils::PathResolver::m_impl private
Definition at line 42 of file PathResolver.hpp.
Referenced by add_path(), clear_paths(), get_paths(), operator=(), PathResolver(), and resolve().
The documentation for this class was generated from the following files:
components/utils/wmtk/components/utils/PathResolver.hpp
components/utils/wmtk/components/utils/PathResolver.cpp