Wildmeshing Toolkit: wmtk::attribute::internal::AttributeFlatCache< T > Class Template Reference
wmtk::attribute::internal::AttributeFlatCache< T > Class Template Reference
#include <AttributeFlatCache.hpp>
Public Types
using Data = AttributeCacheData< T >
using MapResult = internal::MapResult< T >
using ConstMapResult = internal::ConstMapResult< T >
Public Member Functions
AttributeFlatCache ()
~AttributeFlatCache ()
AttributeFlatCache (const AttributeFlatCache &)=delete
AttributeFlatCache & operator= (const AttributeFlatCache &)=delete
AttributeFlatCache (AttributeFlatCache &&)=default
AttributeFlatCache & operator= (AttributeFlatCache &&)=default
template<typename Derived >
void try_caching (int64_t index, const Eigen::MatrixBase< Derived > &value)
void try_caching (int64_t index, const T &value)
const T * get_value (int64_t index, size_t dim) const
void clear ()
size_t size () const
void apply_to (Attribute< T > &attribute) const
void apply_to (AttributeFlatCache< T > &other) const
void apply_to (const Attribute< T > &attribute, std::vector< T > &other) const
const std::vector< T > & buffer () const
const std::vector< std::pair< size_t, size_t > > & indices () const
Protected Attributes
std::vector< T > m_buffer
std::vector< std::pair< size_t, size_t > > m_indices
Detailed Description
template<typename T>
class wmtk::attribute::internal::AttributeFlatCache< T >
Definition at line 16 of file AttributeFlatCache.hpp.
Member Typedef Documentation
ConstMapResult
template<typename T > using wmtk::attribute::internal::AttributeFlatCache< T >::ConstMapResult = internal::ConstMapResult<T>
Definition at line 22 of file AttributeFlatCache.hpp.
Data
template<typename T > using wmtk::attribute::internal::AttributeFlatCache< T >::Data = AttributeCacheData<T>
Definition at line 19 of file AttributeFlatCache.hpp.
MapResult
template<typename T > using wmtk::attribute::internal::AttributeFlatCache< T >::MapResult = internal::MapResult<T>
Definition at line 21 of file AttributeFlatCache.hpp.
Constructor & Destructor Documentation
AttributeFlatCache() [1/3]
template<typename T > wmtk::attribute::internal::AttributeFlatCache< T >::AttributeFlatCache inline
Definition at line 10 of file AttributeFlatCache.hxx.
~AttributeFlatCache()
template<typename T > wmtk::attribute::internal::AttributeFlatCache< T >::~AttributeFlatCache () inline default
AttributeFlatCache() [2/3]
template<typename T > wmtk::attribute::internal::AttributeFlatCache< T >::AttributeFlatCache (const AttributeFlatCache< T > &) delete
AttributeFlatCache() [3/3]
template<typename T > wmtk::attribute::internal::AttributeFlatCache< T >::AttributeFlatCache (AttributeFlatCache< T > &&) default
Member Function Documentation
apply_to() [1/3]
template<typename T > void wmtk::attribute::internal::AttributeFlatCache< T >::apply_to (Attribute< T > & attribute) const inline
Definition at line 59 of file AttributeFlatCache.hxx.
References wmtk::attribute::Attribute< T >::const_vector_attribute_from_start(), and wmtk::attribute::Attribute< T >::vector_attribute().
Referenced by wmtk::attribute::AttributeScope< T >::apply().
apply_to() [2/3]
template<typename T > void wmtk::attribute::internal::AttributeFlatCache< T >::apply_to (AttributeFlatCache< T > & other) const inline
Definition at line 69 of file AttributeFlatCache.hxx.
References wmtk::attribute::internal::AttributeFlatCache< T >::m_buffer, and wmtk::attribute::internal::AttributeFlatCache< T >::m_indices.
apply_to() [3/3]
template<typename T > void wmtk::attribute::internal::AttributeFlatCache< T >::apply_to (const Attribute< T > & attribute, std::vector< T > & other) const inline
Definition at line 84 of file AttributeFlatCache.hxx.
References wmtk::attribute::Attribute< T >::const_vector_attribute_from_start(), and wmtk::attribute::Attribute< T >::vector_attribute().
buffer()
template<typename T > const std::vector<T>& wmtk::attribute::internal::AttributeFlatCache< T >::buffer () const inline
Definition at line 49 of file AttributeFlatCache.hpp.
References wmtk::attribute::internal::AttributeFlatCache< T >::m_buffer.
clear()
template<typename T > void wmtk::attribute::internal::AttributeFlatCache< T >::clear inline
Definition at line 19 of file AttributeFlatCache.hxx.
get_value()
template<typename T > auto wmtk::attribute::internal::AttributeFlatCache< T >::get_value (int64_t index, size_t dim) const inline
Definition at line 96 of file AttributeFlatCache.hxx.
indices()
template<typename T > const std::vector<std::pair<size_t, size_t> >& wmtk::attribute::internal::AttributeFlatCache< T >::indices () const inline
Definition at line 50 of file AttributeFlatCache.hpp.
References wmtk::attribute::internal::AttributeFlatCache< T >::m_indices.
operator=() [1/2]
template<typename T > AttributeFlatCache& wmtk::attribute::internal::AttributeFlatCache< T >::operator= (AttributeFlatCache< T > &&) default
operator=() [2/2]
template<typename T > AttributeFlatCache& wmtk::attribute::internal::AttributeFlatCache< T >::operator= (const AttributeFlatCache< T > &) delete
size()
template<typename T > size_t wmtk::attribute::internal::AttributeFlatCache< T >::size () const inline
Definition at line 41 of file AttributeFlatCache.hpp.
References wmtk::attribute::internal::AttributeFlatCache< T >::m_indices.
try_caching() [1/2]
template<typename T > template<typename Derived > void wmtk::attribute::internal::AttributeFlatCache< T >::try_caching (int64_t index, const Eigen::MatrixBase< Derived > & value) inline
Definition at line 28 of file AttributeFlatCache.hxx.
try_caching() [2/2]
template<typename T > void wmtk::attribute::internal::AttributeFlatCache< T >::try_caching (int64_t index, const T & value) inline
Definition at line 49 of file AttributeFlatCache.hxx.
Member Data Documentation
m_buffer
template<typename T > std::vector<T> wmtk::attribute::internal::AttributeFlatCache< T >::m_buffer protected
Definition at line 53 of file AttributeFlatCache.hpp.
Referenced by wmtk::attribute::internal::AttributeFlatCache< T >::apply_to(), and wmtk::attribute::internal::AttributeFlatCache< T >::buffer().
m_indices
template<typename T > std::vector<std::pair<size_t, size_t> > wmtk::attribute::internal::AttributeFlatCache< T >::m_indices protected
Definition at line 54 of file AttributeFlatCache.hpp.
Referenced by wmtk::attribute::internal::AttributeFlatCache< T >::apply_to(), wmtk::attribute::internal::AttributeFlatCache< T >::indices(), and wmtk::attribute::internal::AttributeFlatCache< T >::size().
The documentation for this class was generated from the following files:
src/wmtk/attribute/internal/AttributeFlatCache.hpp
src/wmtk/attribute/internal/AttributeFlatCache.hxx