Wildmeshing Toolkit: wmtk::attribute::IndexFlagAccessor< MeshType > Class Template Reference
wmtk::attribute::IndexFlagAccessor< MeshType > Class Template Reference
#include <FlagAccessor.hpp>
Public Types
enum class FlagBit : char { Active = 0x1 }
using BaseAccessor = Accessor< char, MeshType, 1 >
Public Member Functions
IndexFlagAccessor (BaseAccessor acc)
template<typename MeshType2 >
IndexFlagAccessor (const IndexFlagAccessor< MeshType2 > &o)
bool is_active (int64_t t) const
void activate (int64_t t)
void deactivate (int64_t t)
BaseAccessor & base_accessor ()
const BaseAccessor & base_accessor () const
operator BaseAccessor () const
Static Public Member Functions
static bool _is_active (char value)
static void _activate (char &value)
static void _deactivate (char &value)
static constexpr char inverse_mask (FlagBit bit)
Protected Member Functions
IndexFlagAccessor index_access () const
Protected Attributes
BaseAccessor m_base_accessor
Detailed Description
template<typename MeshType = wmtk::Mesh>
class wmtk::attribute::IndexFlagAccessor< MeshType >
Definition at line 8 of file FlagAccessor.hpp.
Member Typedef Documentation
BaseAccessor
template<typename MeshType = wmtk::Mesh> using wmtk::attribute::IndexFlagAccessor< MeshType >::BaseAccessor = Accessor<char, MeshType, 1>
Definition at line 15 of file FlagAccessor.hpp.
Member Enumeration Documentation
FlagBit
template<typename MeshType = wmtk::Mesh> enum class wmtk::attribute::IndexFlagAccessor::FlagBit : char strong
Enumerator
Active
Definition at line 11 of file FlagAccessor.hpp.
Constructor & Destructor Documentation
IndexFlagAccessor() [1/2]
template<typename MeshType = wmtk::Mesh> wmtk::attribute::IndexFlagAccessor< MeshType >::IndexFlagAccessor (BaseAccessor acc) inline
Definition at line 18 of file FlagAccessor.hpp.
IndexFlagAccessor() [2/2]
template<typename MeshType = wmtk::Mesh> template<typename MeshType2 > wmtk::attribute::IndexFlagAccessor< MeshType >::IndexFlagAccessor (const IndexFlagAccessor< MeshType2 > & o) inline
Definition at line 22 of file FlagAccessor.hpp.
Member Function Documentation
_activate()
template<typename MeshType = wmtk::Mesh> static void wmtk::attribute::IndexFlagAccessor< MeshType >::_activate (char & value) inline static
Definition at line 13 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::Active.
Referenced by wmtk::attribute::FlagAccessor< MeshType >::activate(), and wmtk::attribute::IndexFlagAccessor< MeshType >::activate().
_deactivate()
template<typename MeshType = wmtk::Mesh> static void wmtk::attribute::IndexFlagAccessor< MeshType >::_deactivate (char & value) inline static
Definition at line 14 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::Active, and wmtk::attribute::IndexFlagAccessor< MeshType >::inverse_mask().
Referenced by wmtk::attribute::FlagAccessor< MeshType >::deactivate(), and wmtk::attribute::IndexFlagAccessor< MeshType >::deactivate().
_is_active()
template<typename MeshType = wmtk::Mesh> static bool wmtk::attribute::IndexFlagAccessor< MeshType >::_is_active (char value) inline static
Definition at line 12 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::Active.
Referenced by wmtk::attribute::FlagAccessor< MeshType >::is_active(), and wmtk::attribute::IndexFlagAccessor< MeshType >::is_active().
activate()
template<typename MeshType = wmtk::Mesh> void wmtk::attribute::IndexFlagAccessor< MeshType >::activate (int64_t t) inline
Definition at line 30 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_activate(), wmtk::attribute::Accessor< T, MeshType, Dim >::index_access(), wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor, and wmtk::attribute::CachingAccessor< T, Dim >::scalar_attribute().
Referenced by wmtk::EdgeMesh::initialize(), wmtk::TriMesh::initialize(), wmtk::TetMesh::initialize(), wmtk::PointMesh::initialize(), and wmtk::Mesh::request_simplex_indices().
base_accessor() [1/2]
template<typename MeshType = wmtk::Mesh> BaseAccessor & wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor () inline
Definition at line 42 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
base_accessor() [2/2]
template<typename MeshType = wmtk::Mesh> const BaseAccessor & wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor () const inline
Definition at line 43 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
deactivate()
template<typename MeshType = wmtk::Mesh> void wmtk::attribute::IndexFlagAccessor< MeshType >::deactivate (int64_t t) inline
Definition at line 34 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_deactivate(), wmtk::attribute::Accessor< T, MeshType, Dim >::index_access(), wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor, and wmtk::attribute::CachingAccessor< T, Dim >::scalar_attribute().
index_access()
template<typename MeshType = wmtk::Mesh> IndexFlagAccessor wmtk::attribute::IndexFlagAccessor< MeshType >::index_access () const inline protected
Definition at line 50 of file FlagAccessor.hpp.
inverse_mask()
template<typename MeshType = wmtk::Mesh> static constexpr char wmtk::attribute::IndexFlagAccessor< MeshType >::inverse_mask (FlagBit bit) inline static constexpr
Definition at line 39 of file FlagAccessor.hpp.
Referenced by wmtk::attribute::IndexFlagAccessor< MeshType >::_deactivate().
is_active()
template<typename MeshType = wmtk::Mesh> bool wmtk::attribute::IndexFlagAccessor< MeshType >::is_active (int64_t t) const inline
Definition at line 26 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_is_active(), wmtk::attribute::CachingAccessor< T, Dim >::const_scalar_attribute(), wmtk::attribute::Accessor< T, MeshType, Dim >::index_access(), and wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
Referenced by wmtk::Mesh::consolidate(), wmtk::Mesh::get_all(), wmtk::Mesh::get_all_id_simplex(), wmtk::TetMesh::is_connectivity_valid(), wmtk::TriMesh::is_connectivity_valid(), and wmtk::EdgeMesh::is_connectivity_valid().
operator BaseAccessor()
template<typename MeshType = wmtk::Mesh> wmtk::attribute::IndexFlagAccessor< MeshType >::operator BaseAccessor () const inline
Definition at line 44 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
Member Data Documentation
m_base_accessor
template<typename MeshType = wmtk::Mesh> BaseAccessor wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor protected
Definition at line 47 of file FlagAccessor.hpp.
Referenced by wmtk::attribute::FlagAccessor< MeshType >::activate(), wmtk::attribute::IndexFlagAccessor< MeshType >::activate(), wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor(), wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor(), wmtk::attribute::FlagAccessor< MeshType >::deactivate(), wmtk::attribute::IndexFlagAccessor< MeshType >::deactivate(), wmtk::attribute::FlagAccessor< MeshType >::is_active(), wmtk::attribute::IndexFlagAccessor< MeshType >::is_active(), and wmtk::attribute::IndexFlagAccessor< MeshType >::operator BaseAccessor().
The documentation for this class was generated from the following file:
src/wmtk/attribute/FlagAccessor.hpp