Wildmeshing Toolkit: wmtk::operations::EdgeSplit Class Reference
wmtk::operations::EdgeSplit Class Reference
#include <EdgeSplit.hpp>
Public Member Functions
EdgeSplit (Mesh &m)
PrimitiveType primitive_type () const override
std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > get_new_attribute_strategy (const attribute::MeshAttributeHandle &attribute) const
void set_new_attribute_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > &other)
void set_new_attribute_strategy (const attribute::MeshAttributeHandle &attribute, const wmtk::operations::SplitBasicStrategy &spine=wmtk::operations::SplitBasicStrategy::Default, const wmtk::operations::SplitRibBasicStrategy &rib=wmtk::operations::SplitRibBasicStrategy::Default)
std::vector< simplex::Simplex > execute (const simplex::Simplex &simplex) override
std::vector< simplex::Simplex > unmodified_primitives (const simplex::Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
void clear_attribute_new_strategies ()
bool attribute_new_all_configured () const
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
virtual std::vector< simplex::Simplex > operator() (const simplex::Simplex &simplex)
virtual double priority (const simplex::Simplex &simplex) const
virtual bool use_random_priority () const
virtual bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< double(const simplex::Simplex &)> &func)
std::shared_ptr< const operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandle &attribute)
void add_transfer_strategy (const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void clear_attribute_transfer_strategies ()
virtual void reserve_enough_simplices ()
Static Public Member Functions
static std::pair< Tuple, Tuple > new_spine_edges (const Mesh &mesh, const Tuple &new_vertex)
Private Attributes
std::vector< std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > > m_new_attr_strategies
Additional Inherited Members
Protected Member Functions inherited from wmtk::operations::Operation
virtual bool before (const simplex::Simplex &simplex) const
virtual bool after (const std::vector< simplex::Simplex > &unmods, const std::vector< simplex::Simplex > &mods) const
void apply_attribute_transfer (const std::vector< simplex::Simplex > &direct_mods)
Protected Attributes inherited from wmtk::operations::Operation
std::function< double(const simplex::Simplex &)> m_priority = nullptr
invariants::InvariantCollection m_invariants
std::vector< std::shared_ptr< const operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Definition at line 8 of file EdgeSplit.hpp.
Constructor & Destructor Documentation
EdgeSplit()
wmtk::operations::EdgeSplit::EdgeSplit (Mesh & m)
Definition at line 29 of file EdgeSplit.cpp.
References wmtk::Mesh::custom_attributes(), wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root(), m_new_attr_strategies, and wmtk::operations::Operation::mesh().
Member Function Documentation
attribute_new_all_configured()
bool wmtk::operations::EdgeSplit::attribute_new_all_configured () const
Definition at line 17 of file EdgeSplit.cpp.
References wmtk::logger(), and m_new_attr_strategies.
clear_attribute_new_strategies()
void wmtk::operations::EdgeSplit::clear_attribute_new_strategies ()
Definition at line 81 of file EdgeSplit.cpp.
References m_new_attr_strategies.
Referenced by wmtk::operations::AttributeTransferConfiguration::apply().
execute()
std::vector< simplex::Simplex > wmtk::operations::EdgeSplit::execute (const simplex::Simplex & simplex) override virtual
Returns
the new simplex, toward to the next simplex along the splited line
Implements wmtk::operations::Operation.
Definition at line 56 of file EdgeSplit.cpp.
References m_new_attr_strategies, wmtk::operations::Operation::mesh(), and wmtk::operations::utils::multi_mesh_edge_split_with_modified_simplices().
get_new_attribute_strategy()
std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > wmtk::operations::EdgeSplit::get_new_attribute_strategy (const attribute::MeshAttributeHandle & attribute) const
Definition at line 71 of file EdgeSplit.cpp.
References m_new_attr_strategies.
new_spine_edges()
std::pair< Tuple, Tuple > wmtk::operations::EdgeSplit::new_spine_edges (const Mesh & mesh, const Tuple & new_vertex) static
Definition at line 122 of file EdgeSplit.cpp.
References wmtk::Edge, wmtk::operations::Operation::mesh(), wmtk::PE, PF, PT, wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
primitive_type()
PrimitiveType wmtk::operations::EdgeSplit::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 13 of file EdgeSplit.hpp.
References wmtk::Edge.
set_new_attribute_strategy() [1/2]
void wmtk::operations::EdgeSplit::set_new_attribute_strategy (const attribute::MeshAttributeHandle & attribute, const std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > & other)
Definition at line 85 of file EdgeSplit.cpp.
References m_new_attr_strategies.
Referenced by wmtk::operations::AttributeTransferConfiguration::apply(), wmtk::components::internal::edge_insertion(), wmtk::components::Marching::process(), wmtk::components::internal::RegularSpace::regularize_tags(), and set_new_attribute_strategy().
set_new_attribute_strategy() [2/2]
void wmtk::operations::EdgeSplit::set_new_attribute_strategy (const attribute::MeshAttributeHandle & attribute, const wmtk::operations::SplitBasicStrategy & spine = wmtk::operations::SplitBasicStrategy::Default, const wmtk::operations::SplitRibBasicStrategy & rib = wmtk::operations::SplitRibBasicStrategy::Default)
Definition at line 99 of file EdgeSplit.cpp.
References wmtk::attribute::MeshAttributeHandle::handle(), and set_new_attribute_strategy().
unmodified_primitives()
std::vector< simplex::Simplex > wmtk::operations::EdgeSplit::unmodified_primitives (const simplex::Simplex & simplex) const override virtual
Returns all simplices that will be potentially affected by the operation.
Implements wmtk::operations::Operation.
Definition at line 63 of file EdgeSplit.cpp.
Member Data Documentation
m_new_attr_strategies
std::vector<std::shared_ptr<const operations::BaseSplitNewAttributeStrategy> > wmtk::operations::EdgeSplit::m_new_attr_strategies private
Definition at line 47 of file EdgeSplit.hpp.
Referenced by attribute_new_all_configured(), clear_attribute_new_strategies(), EdgeSplit(), execute(), get_new_attribute_strategy(), and set_new_attribute_strategy().
The documentation for this class was generated from the following files:
src/wmtk/operations/EdgeSplit.hpp
src/wmtk/operations/EdgeSplit.cpp