Wildmeshing Toolkit: wmtk::operations::VertexTangentialLaplacianSmooth Class Reference
wmtk::operations::VertexTangentialLaplacianSmooth Class Reference
#include <VertexTangentialLaplacianSmooth.hpp>
Public Member Functions
VertexTangentialLaplacianSmooth (attribute::MeshAttributeHandle &handle, double damping_factor=DEFAULT_DAMPING_FACTOR)
bool operator() (Mesh &m, const simplex::Simplex &s) override
Public Member Functions inherited from wmtk::operations::VertexLaplacianSmooth
VertexLaplacianSmooth (const attribute::MeshAttributeHandle &handle)
virtual ~VertexLaplacianSmooth ()=default
Static Public Attributes
constexpr static double DEFAULT_DAMPING_FACTOR = 1.0
Private Attributes
double m_damping_factor
Additional Inherited Members
Protected Attributes inherited from wmtk::operations::VertexLaplacianSmooth
attribute::MeshAttributeHandle m_attibute_handle
Detailed Description
Definition at line 7 of file VertexTangentialLaplacianSmooth.hpp.
Constructor & Destructor Documentation
VertexTangentialLaplacianSmooth()
wmtk::operations::VertexTangentialLaplacianSmooth::VertexTangentialLaplacianSmooth (attribute::MeshAttributeHandle & handle, double damping_factor = DEFAULT_DAMPING_FACTOR)
Definition at line 9 of file VertexTangentialLaplacianSmooth.cpp.
Member Function Documentation
operator()()
bool wmtk::operations::VertexTangentialLaplacianSmooth::operator() (Mesh & m, const simplex::Simplex & s) override virtual
Reimplemented from wmtk::operations::VertexLaplacianSmooth.
Definition at line 16 of file VertexTangentialLaplacianSmooth.cpp.
References wmtk::mesh_utils::compute_vertex_normal(), wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::Mesh::is_boundary(), wmtk::Mesh::is_valid(), wmtk::operations::VertexLaplacianSmooth::m_attibute_handle, m_damping_factor, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Member Data Documentation
DEFAULT_DAMPING_FACTOR
constexpr static double wmtk::operations::VertexTangentialLaplacianSmooth::DEFAULT_DAMPING_FACTOR = 1.0 static constexpr
Definition at line 10 of file VertexTangentialLaplacianSmooth.hpp.
m_damping_factor
double wmtk::operations::VertexTangentialLaplacianSmooth::m_damping_factor private
Definition at line 19 of file VertexTangentialLaplacianSmooth.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
src/wmtk/operations/utils/VertexTangentialLaplacianSmooth.hpp
src/wmtk/operations/utils/VertexTangentialLaplacianSmooth.cpp