Wildmeshing Toolkit: wmtk::HDF5Writer Class Reference
wmtk::HDF5Writer Class Reference
#include <HDF5Writer.hpp>
Public Member Functions
HDF5Writer (const std::filesystem::path &filename)
void write_top_simplex_type (const PrimitiveType type) override
void write_absolute_id (const std::vector< int64_t > &id) override
bool write (const int) override
void write_capacities (const std::vector< int64_t > &capacities) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< char > &val, const char default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< int64_t > &val, const int64_t default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< double > &val, const double default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< Rational > &val, const Rational &default_val) override
Public Member Functions inherited from wmtk::MeshWriter
virtual ~MeshWriter ()
Private Member Functions
std::string dataset_path () const
template<typename Data , typename T >
void write_internal (const std::string &name, const int64_t type, const int64_t stride, const Data &val, const T &default_val)
Private Attributes
std::shared_ptr< h5pp::File > m_hdf5_file
std::string m_name
Additional Inherited Members
Protected Attributes inherited from wmtk::MeshWriter
int64_t m_mm_level = 0
Detailed Description
Definition at line 12 of file HDF5Writer.hpp.
Constructor & Destructor Documentation
HDF5Writer()
wmtk::HDF5Writer::HDF5Writer (const std::filesystem::path & filename)
Definition at line 52 of file HDF5Writer.cpp.
References m_hdf5_file.
Member Function Documentation
dataset_path()
std::string wmtk::HDF5Writer::dataset_path () const private
Definition at line 161 of file HDF5Writer.cpp.
References m_name.
Referenced by write_absolute_id(), write_capacities(), write_internal(), and write_top_simplex_type().
write() [1/5]
bool wmtk::HDF5Writer::write (const int) inline override virtual
Implements wmtk::MeshWriter.
Definition at line 20 of file HDF5Writer.hpp.
write() [2/5]
void wmtk::HDF5Writer::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< char > & val, const char default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 77 of file HDF5Writer.cpp.
References write_internal().
write() [3/5]
void wmtk::HDF5Writer::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< double > & val, const double default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 67 of file HDF5Writer.cpp.
References write_internal().
write() [4/5]
void wmtk::HDF5Writer::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< int64_t > & val, const int64_t default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 57 of file HDF5Writer.cpp.
References write_internal().
write() [5/5]
void wmtk::HDF5Writer::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< Rational > & val, const Rational & default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 92 of file HDF5Writer.cpp.
References wmtk::Rational::to_binary(), and write_internal().
write_absolute_id()
void wmtk::HDF5Writer::write_absolute_id (const std::vector< int64_t > & id) override virtual
Implements wmtk::MeshWriter.
Definition at line 146 of file HDF5Writer.cpp.
References dataset_path(), m_hdf5_file, wmtk::MeshWriter::m_mm_level, and m_name.
write_capacities()
void wmtk::HDF5Writer::write_capacities (const std::vector< int64_t > & capacities) override virtual
Implements wmtk::MeshWriter.
Definition at line 118 of file HDF5Writer.cpp.
References dataset_path(), and m_hdf5_file.
write_internal()
template<typename Data , typename T > void wmtk::HDF5Writer::write_internal (const std::string & name, const int64_t type, const int64_t stride, const Data & val, const T & default_val) private
Definition at line 124 of file HDF5Writer.cpp.
References dataset_path(), and m_hdf5_file.
Referenced by write().
write_top_simplex_type()
void wmtk::HDF5Writer::write_top_simplex_type (const PrimitiveType type) override virtual
Implements wmtk::MeshWriter.
Definition at line 141 of file HDF5Writer.cpp.
References dataset_path(), and m_hdf5_file.
Member Data Documentation
m_hdf5_file
std::shared_ptr<h5pp::File> wmtk::HDF5Writer::m_hdf5_file private
Definition at line 53 of file HDF5Writer.hpp.
Referenced by HDF5Writer(), write_absolute_id(), write_capacities(), write_internal(), and write_top_simplex_type().
m_name
std::string wmtk::HDF5Writer::m_name private
Definition at line 54 of file HDF5Writer.hpp.
Referenced by dataset_path(), and write_absolute_id().
The documentation for this class was generated from the following files:
src/wmtk/io/HDF5Writer.hpp
src/wmtk/io/HDF5Writer.cpp