Wildmeshing Toolkit: wmtk::multimesh::utils::MapValidator Class Reference
wmtk::multimesh::utils::MapValidator Class Reference
#include <MapValidator.hpp>
Public Member Functions
MapValidator (const Mesh &m)
bool check_child_map_attributes_valid () const
bool check_parent_map_attribute_valid () const
bool check_all () const
bool check_switch_homomorphism () const
bool check_child_switch_homomorphism (const Mesh &child) const
Private Attributes
const Mesh & m_mesh
Detailed Description
Definition at line 11 of file MapValidator.hpp.
Constructor & Destructor Documentation
MapValidator()
wmtk::multimesh::utils::MapValidator::MapValidator (const Mesh & m)
Definition at line 11 of file MapValidator.cpp.
Member Function Documentation
check_all()
bool wmtk::multimesh::utils::MapValidator::check_all () const
Definition at line 14 of file MapValidator.cpp.
References check_child_map_attributes_valid(), check_parent_map_attribute_valid(), and check_switch_homomorphism().
Referenced by wmtk::multimesh::utils::check_maps_valid().
check_child_map_attributes_valid()
bool wmtk::multimesh::utils::MapValidator::check_child_map_attributes_valid () const
Definition at line 27 of file MapValidator.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), wmtk::Mesh::create_const_accessor(), wmtk::Mesh::get_all(), wmtk::logger(), wmtk::multimesh::MultiMeshManager::m_children, m_mesh, wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::utils::read_tuple_map_attribute(), and wmtk::simplex::top_dimension_cofaces_tuples().
Referenced by check_all(), wmtk::multimesh::utils::check_child_maps_valid(), and wmtk::multimesh::utils::check_parent_map_valid().
check_child_switch_homomorphism()
bool wmtk::multimesh::utils::MapValidator::check_child_switch_homomorphism (const Mesh & child) const
Definition at line 138 of file MapValidator.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), wmtk::Tuple::as_string(), wmtk::simplex::utils::SimplexComparisons::equal(), wmtk::Mesh::get_all(), wmtk::Mesh::id(), wmtk::Mesh::is_boundary(), wmtk::logger(), m_mesh, wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::m_parent, wmtk::Mesh::map_to_parent_tuple(), wmtk::utils::primitive_below(), wmtk::primitive_type_name(), wmtk::Mesh::switch_tuple(), wmtk::Mesh::top_cell_dimension(), and wmtk::Mesh::top_simplex_type().
Referenced by check_switch_homomorphism().
check_parent_map_attribute_valid()
bool wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid () const
Definition at line 82 of file MapValidator.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), wmtk::Mesh::create_const_accessor(), wmtk::Mesh::get_all(), wmtk::logger(), m_mesh, wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::m_parent, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, wmtk::multimesh::utils::read_tuple_map_attribute(), wmtk::Mesh::top_cell_dimension(), and wmtk::Mesh::top_simplex_type().
Referenced by check_all().
check_switch_homomorphism()
bool wmtk::multimesh::utils::MapValidator::check_switch_homomorphism () const
Definition at line 130 of file MapValidator.cpp.
References check_child_switch_homomorphism(), wmtk::Mesh::get_child_meshes(), and m_mesh.
Referenced by check_all().
Member Data Documentation
m_mesh
const Mesh& wmtk::multimesh::utils::MapValidator::m_mesh private
Definition at line 22 of file MapValidator.hpp.
Referenced by check_child_map_attributes_valid(), check_child_switch_homomorphism(), check_parent_map_attribute_valid(), and check_switch_homomorphism().
The documentation for this class was generated from the following files:
src/wmtk/multimesh/utils/MapValidator.hpp
src/wmtk/multimesh/utils/MapValidator.cpp