Wildmeshing Toolkit: wmtk::components::internal::MultiMeshFromTag Class Reference
wmtk::components::internal::MultiMeshFromTag Class Reference
This class generates a multi-mesh from a mesh where the substructure is represented by a tag.
#include <MultiMeshFromTag.hpp>
Public Member Functions
MultiMeshFromTag (Mesh &mesh, const attribute::MeshAttributeHandle &tag_handle, const int64_t tag_value)
Eigen::MatrixX< int64_t > get_new_id_matrix (const PrimitiveType ptype) const
VectorXl get_new_top_coface_vector (const PrimitiveType ptype) const
Eigen::MatrixX< int64_t > adjacency_matrix () const
std::shared_ptr< Mesh > substructure_soup () const
Returns a pointer to the substructure soup.
std::shared_ptr< Mesh > substructure () const
Returns a pointer to the manifold substructure mesh.
void compute_substructure_mesh ()
Create a manifold mesh from the substructure.
bool is_substructure_simplex_manifold (const simplex::Simplex &s) const
bool is_root_simplex_manifold (const simplex::Simplex &s) const
void remove_soup ()
Remove the substructure soup from the multimesh.
Private Member Functions
void compute_substructure_ids ()
Compute the ids of the manifold substructure.
void create_substructure_soup ()
Create a multimesh where the child-mesh is just a soup (no connectivity) of m_mesh.
std::vector< Tuple > get_connected_region (const Tuple &t, const PrimitiveType ptype)
Get tuples with different global_cid that all represent simplex(t_in, ptype) and are in the same tag-region.
void build_adjacency_matrix ()
Create the adjacency (stored as attribute) of the substructure.
Private Attributes
Mesh & m_mesh
const attribute::Accessor< int64_t > m_tag_acc
const int64_t m_tag_value
const PrimitiveType m_tag_ptype
std::map< PrimitiveType, attribute::MeshAttributeHandle > m_new_id_handles
attribute::MeshAttributeHandle m_adjacency_handle
Eigen::MatrixX< int64_t > m_adjacency_matrix
std::map< PrimitiveType, Eigen::MatrixX< int64_t > > m_new_id_matrices
std::map< PrimitiveType, VectorXl > m_new_top_coface_vectors
std::shared_ptr< Mesh > m_soup_ptr
std::shared_ptr< Mesh > m_substructure_ptr
Detailed Description
This class generates a multi-mesh from a mesh where the substructure is represented by a tag.
Definition at line 11 of file MultiMeshFromTag.hpp.
Constructor & Destructor Documentation
MultiMeshFromTag()
wmtk::components::internal::MultiMeshFromTag::MultiMeshFromTag (Mesh & mesh, const attribute::MeshAttributeHandle & tag_handle, const int64_t tag_value)
Definition at line 23 of file MultiMeshFromTag.cpp.
Member Function Documentation
adjacency_matrix()
Eigen::MatrixX< int64_t > wmtk::components::internal::MultiMeshFromTag::adjacency_matrix () const
Definition at line 45 of file MultiMeshFromTag.cpp.
References m_adjacency_matrix.
Referenced by compute_substructure_mesh().
build_adjacency_matrix()
void wmtk::components::internal::MultiMeshFromTag::build_adjacency_matrix () private
Create the adjacency (stored as attribute) of the substructure.
Definition at line 212 of file MultiMeshFromTag.cpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_vector_attribute(), wmtk::Mesh::create_accessor(), wmtk::attribute::MeshAttributeHandle::dimension(), wmtk::Edge, wmtk::simplex::faces_single_dimension_tuples(), wmtk::Mesh::get_all(), wmtk::get_primitive_type_from_id(), wmtk::get_primitive_type_id(), m_adjacency_handle, m_adjacency_matrix, m_mesh, m_soup_ptr, m_tag_ptype, wmtk::Mesh::map_to_child(), wmtk::Mesh::map_to_parent(), wmtk::Mesh::register_attribute(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::vector_attribute(), and wmtk::Vertex.
Referenced by compute_substructure_mesh().
compute_substructure_ids()
void wmtk::components::internal::MultiMeshFromTag::compute_substructure_ids () private
Compute the ids of the manifold substructure.
This function utilizes the substructure soup to store the ids.
Definition at line 65 of file MultiMeshFromTag.cpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_vector_attribute(), wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::faces_single_dimension_tuples(), wmtk::Mesh::get_all(), get_connected_region(), m_new_id_handles, m_new_id_matrices, m_new_top_coface_vectors, m_soup_ptr, m_tag_ptype, wmtk::utils::primitive_below(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::vector_attribute(), and wmtk::Vertex.
Referenced by compute_substructure_mesh().
compute_substructure_mesh()
void wmtk::components::internal::MultiMeshFromTag::compute_substructure_mesh ()
Create a manifold mesh from the substructure.
Definition at line 377 of file MultiMeshFromTag.cpp.
References adjacency_matrix(), build_adjacency_matrix(), compute_substructure_ids(), wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_scalar_attribute(), create_substructure_soup(), wmtk::Edge, wmtk::Mesh::get_all(), get_new_id_matrix(), get_new_top_coface_vector(), wmtk::get_primitive_type_id(), wmtk::EdgeMesh::initialize(), wmtk::TriMesh::initialize(), wmtk::TetMesh::initialize(), wmtk::PointMesh::initialize(), wmtk::TetMesh::is_connectivity_valid(), wmtk::TriMesh::is_connectivity_valid(), wmtk::EdgeMesh::is_connectivity_valid(), wmtk::log_and_throw_error(), m_mesh, m_new_id_handles, m_soup_ptr, m_substructure_ptr, m_tag_acc, m_tag_ptype, m_tag_value, wmtk::utils::primitive_below(), wmtk::Mesh::register_attribute(), wmtk::Mesh::register_child_mesh(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::components::edge_insertion(), wmtk::components::multimesh_from_tag(), wmtk::components::periodic_optimization(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and wmtk::components::triangle_insertion::triangle_insertion().
create_substructure_soup()
void wmtk::components::internal::MultiMeshFromTag::create_substructure_soup () private
Create a multimesh where the child-mesh is just a soup (no connectivity) of m_mesh.
The soup is required as an intermediate step to construct the proper manifold substructure.
Definition at line 320 of file MultiMeshFromTag.cpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_scalar_attribute(), wmtk::Edge, wmtk::Mesh::get_all(), wmtk::get_primitive_type_id(), wmtk::PointMesh::initialize(), wmtk::EdgeMesh::initialize_free(), wmtk::TetMesh::initialize_free(), wmtk::TriMesh::initialize_free(), wmtk::log_and_throw_error(), m_mesh, m_soup_ptr, m_tag_acc, m_tag_ptype, m_tag_value, wmtk::Mesh::register_child_mesh(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by compute_substructure_mesh().
get_connected_region()
std::vector< Tuple > wmtk::components::internal::MultiMeshFromTag::get_connected_region (const Tuple & t, const PrimitiveType ptype) private
Get tuples with different global_cid that all represent simplex(t_in, ptype) and are in the same tag-region.
To find the tag-region a breadth-first-search is utilized where it is not allowed to cross non-manifold d-1-simplices.
Definition at line 157 of file MultiMeshFromTag.cpp.
References wmtk::get_primitive_type_from_id(), wmtk::get_primitive_type_id(), m_mesh, m_soup_ptr, m_tag_ptype, wmtk::Mesh::map_to_child(), wmtk::Mesh::map_to_parent(), and wmtk::simplex::tuples_preserving_primitive_types().
Referenced by compute_substructure_ids().
get_new_id_matrix()
Eigen::MatrixX< int64_t > wmtk::components::internal::MultiMeshFromTag::get_new_id_matrix (const PrimitiveType ptype) const
Definition at line 35 of file MultiMeshFromTag.cpp.
References m_new_id_matrices.
Referenced by compute_substructure_mesh().
get_new_top_coface_vector()
VectorXl wmtk::components::internal::MultiMeshFromTag::get_new_top_coface_vector (const PrimitiveType ptype) const
Definition at line 40 of file MultiMeshFromTag.cpp.
References m_new_top_coface_vectors.
Referenced by compute_substructure_mesh().
is_root_simplex_manifold()
bool wmtk::components::internal::MultiMeshFromTag::is_root_simplex_manifold (const simplex::Simplex & s) const
Definition at line 476 of file MultiMeshFromTag.cpp.
References m_mesh, m_substructure_ptr, and wmtk::Mesh::map_to_child().
Referenced by is_substructure_simplex_manifold(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
is_substructure_simplex_manifold()
bool wmtk::components::internal::MultiMeshFromTag::is_substructure_simplex_manifold (const simplex::Simplex & s) const
Definition at line 469 of file MultiMeshFromTag.cpp.
References is_root_simplex_manifold(), and m_substructure_ptr.
remove_soup()
void wmtk::components::internal::MultiMeshFromTag::remove_soup ()
Remove the substructure soup from the multimesh.
The substructure soup is used as an intermediate representation to construct the manifold substructure mesh. This method removes the soup from the multimesh and is therefore necessary to get a clean multimesh.
Definition at line 60 of file MultiMeshFromTag.cpp.
References wmtk::Mesh::deregister_child_mesh(), m_mesh, and m_soup_ptr.
Referenced by wmtk::components::edge_insertion(), wmtk::components::multimesh_from_tag(), wmtk::components::periodic_optimization(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and wmtk::components::triangle_insertion::triangle_insertion().
substructure()
std::shared_ptr< Mesh > wmtk::components::internal::MultiMeshFromTag::substructure () const
Returns a pointer to the manifold substructure mesh.
This mesh is the substructure that is represented by tags in the input mesh. Any non-manifold simplices were duplicated to make the substructure manifold. Besides that, no topological changes were performed.
Definition at line 55 of file MultiMeshFromTag.cpp.
References m_substructure_ptr.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
substructure_soup()
std::shared_ptr< Mesh > wmtk::components::internal::MultiMeshFromTag::substructure_soup () const
Returns a pointer to the substructure soup.
The soup is merely an intermediate representation and should not be used. The function substructure() is most likely what you are looking for.
Definition at line 50 of file MultiMeshFromTag.cpp.
References m_soup_ptr.
Member Data Documentation
m_adjacency_handle
attribute::MeshAttributeHandle wmtk::components::internal::MultiMeshFromTag::m_adjacency_handle private
Definition at line 99 of file MultiMeshFromTag.hpp.
Referenced by build_adjacency_matrix().
m_adjacency_matrix
Eigen::MatrixX<int64_t> wmtk::components::internal::MultiMeshFromTag::m_adjacency_matrix private
Definition at line 100 of file MultiMeshFromTag.hpp.
Referenced by adjacency_matrix(), and build_adjacency_matrix().
m_mesh
Mesh& wmtk::components::internal::MultiMeshFromTag::m_mesh private
Definition at line 91 of file MultiMeshFromTag.hpp.
Referenced by build_adjacency_matrix(), compute_substructure_mesh(), create_substructure_soup(), get_connected_region(), is_root_simplex_manifold(), and remove_soup().
m_new_id_handles
std::map<PrimitiveType, attribute::MeshAttributeHandle> wmtk::components::internal::MultiMeshFromTag::m_new_id_handles private
Definition at line 97 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_ids(), and compute_substructure_mesh().
m_new_id_matrices
std::map<PrimitiveType, Eigen::MatrixX<int64_t> > wmtk::components::internal::MultiMeshFromTag::m_new_id_matrices private
Definition at line 101 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_ids(), and get_new_id_matrix().
m_new_top_coface_vectors
std::map<PrimitiveType, VectorXl> wmtk::components::internal::MultiMeshFromTag::m_new_top_coface_vectors private
Definition at line 102 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_ids(), and get_new_top_coface_vector().
m_soup_ptr
std::shared_ptr<Mesh> wmtk::components::internal::MultiMeshFromTag::m_soup_ptr private
Definition at line 103 of file MultiMeshFromTag.hpp.
Referenced by build_adjacency_matrix(), compute_substructure_ids(), compute_substructure_mesh(), create_substructure_soup(), get_connected_region(), remove_soup(), and substructure_soup().
m_substructure_ptr
std::shared_ptr<Mesh> wmtk::components::internal::MultiMeshFromTag::m_substructure_ptr private
Definition at line 104 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_mesh(), is_root_simplex_manifold(), is_substructure_simplex_manifold(), and substructure().
m_tag_acc
const attribute::Accessor<int64_t> wmtk::components::internal::MultiMeshFromTag::m_tag_acc private
Definition at line 93 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_mesh(), and create_substructure_soup().
m_tag_ptype
const PrimitiveType wmtk::components::internal::MultiMeshFromTag::m_tag_ptype private
Definition at line 95 of file MultiMeshFromTag.hpp.
Referenced by build_adjacency_matrix(), compute_substructure_ids(), compute_substructure_mesh(), create_substructure_soup(), and get_connected_region().
m_tag_value
const int64_t wmtk::components::internal::MultiMeshFromTag::m_tag_value private
Definition at line 94 of file MultiMeshFromTag.hpp.
Referenced by compute_substructure_mesh(), and create_substructure_soup().
The documentation for this class was generated from the following files:
components/multimesh_from_tag/wmtk/components/multimesh_from_tag/internal/MultiMeshFromTag.hpp
components/multimesh_from_tag/wmtk/components/multimesh_from_tag/internal/MultiMeshFromTag.cpp