Wildmeshing Toolkit: wmtk::simplex::NavigatableSimplex Class Reference
wmtk::simplex::NavigatableSimplex Class Reference
#include <NavigatableSimplex.hpp>
Public Member Functions
NavigatableSimplex (const Mesh &m, const Simplex &s)
NavigatableSimplex (const Mesh &m, const PrimitiveType &ptype, const Tuple &t)
operator Simplex () const
const Tuple & tuple () const
Public Member Functions inherited from wmtk::simplex::IdSimplex
IdSimplex ()=default
IdSimplex (const NavigatableSimplex &s)
bool valid () const
PrimitiveType primitive_type () const
int64_t dimension () const
bool operator< (const IdSimplex &o) const
bool operator== (const IdSimplex &o) const
bool operator!= (const IdSimplex &o) const
Protected Member Functions
NavigatableSimplex (const PrimitiveType &ptype, const Tuple &t, int64_t index)
Protected Member Functions inherited from wmtk::simplex::IdSimplex
int64_t index () const
IdSimplex (PrimitiveType pt, int64_t index)
Private Attributes
Tuple m_tuple
Friends
class wmtk::Mesh
Additional Inherited Members
Static Protected Member Functions inherited from wmtk::simplex::IdSimplex
static int64_t id (const Mesh &m, PrimitiveType pt, const Tuple &t)
Detailed Description
Definition at line 15 of file NavigatableSimplex.hpp.
Constructor & Destructor Documentation
NavigatableSimplex() [1/3]
wmtk::simplex::NavigatableSimplex::NavigatableSimplex (const Mesh & m, const Simplex & s)
Definition at line 7 of file NavigatableSimplex.cpp.
NavigatableSimplex() [2/3]
wmtk::simplex::NavigatableSimplex::NavigatableSimplex (const Mesh & m, const PrimitiveType & ptype, const Tuple & t)
Definition at line 13 of file NavigatableSimplex.cpp.
NavigatableSimplex() [3/3]
wmtk::simplex::NavigatableSimplex::NavigatableSimplex (const PrimitiveType & ptype, const Tuple & t, int64_t index) inline protected
Definition at line 27 of file NavigatableSimplex.hpp.
Member Function Documentation
operator Simplex()
wmtk::simplex::NavigatableSimplex::operator Simplex () const
Definition at line 17 of file NavigatableSimplex.cpp.
tuple()
const Tuple& wmtk::simplex::NavigatableSimplex::tuple () const inline
Definition at line 24 of file NavigatableSimplex.hpp.
References m_tuple.
Referenced by wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::execute_from_root(), wmtk::multimesh::MultiMeshSimplexVisitorExecutor< MMVisitor >::run(), wmtk::operations::SplitNewAttributeStrategy< T >::update(), and wmtk::operations::CollapseNewAttributeStrategy< T >::update().
Friends And Related Function Documentation
wmtk::Mesh
friend class wmtk::Mesh friend
Definition at line 18 of file NavigatableSimplex.hpp.
Member Data Documentation
m_tuple
Tuple wmtk::simplex::NavigatableSimplex::m_tuple private
Definition at line 34 of file NavigatableSimplex.hpp.
Referenced by tuple().
The documentation for this class was generated from the following files:
src/wmtk/simplex/NavigatableSimplex.hpp
src/wmtk/simplex/NavigatableSimplex.cpp