Wildmeshing Toolkit: wmtk::components::input::NamedMultiMesh Class Reference
wmtk::components::input::NamedMultiMesh Class Reference
#include <NamedMultiMesh.hpp>
Classes
struct Node
Public Member Functions
NamedMultiMesh ()
NamedMultiMesh (const NamedMultiMesh &)
~NamedMultiMesh ()
auto operator= (const NamedMultiMesh &) -> NamedMultiMesh &
void set_name (const std::string_view &root_name="")
void set_names (const nlohmann::json &js)
void set_root (Mesh &m)
std::string_view root_name () const
std::string name (const std::vector< int64_t > &id) const
void set_mesh (Mesh &m)
Navigates to the root of the multimesh.
Mesh & get_mesh (const std::string_view &path) const
std::vector< int64_t > get_id (const std::string_view &path) const
Mesh & root ()
const Mesh & root () const
Private Attributes
std::shared_ptr< Mesh > m_root
std::unique_ptr< Node > m_name_root
Detailed Description
Definition at line 16 of file NamedMultiMesh.hpp.
Constructor & Destructor Documentation
NamedMultiMesh() [1/2]
wmtk::components::input::NamedMultiMesh::NamedMultiMesh () default
NamedMultiMesh() [2/2]
wmtk::components::input::NamedMultiMesh::NamedMultiMesh (const NamedMultiMesh & o)
Definition at line 146 of file NamedMultiMesh.cpp.
~NamedMultiMesh()
wmtk::components::input::NamedMultiMesh::~NamedMultiMesh () default
Member Function Documentation
get_id()
auto wmtk::components::input::NamedMultiMesh::get_id (const std::string_view & path) const
Definition at line 75 of file NamedMultiMesh.cpp.
References wmtk::components::input::NamedMultiMesh::Node::m_child_indexer, wmtk::components::input::NamedMultiMesh::Node::m_children, wmtk::components::input::NamedMultiMesh::Node::name, and wmtk::components::input::internal::split_path().
Referenced by get_mesh(), and TEST_CASE().
get_mesh()
Mesh & wmtk::components::input::NamedMultiMesh::get_mesh (const std::string_view & path) const
Definition at line 69 of file NamedMultiMesh.cpp.
References get_id(), and m_root.
Referenced by wmtk::components::input::MeshCollection::get_mesh(), and TEST_CASE().
name()
std::string wmtk::components::input::NamedMultiMesh::name (const std::vector< int64_t > & id) const
Definition at line 125 of file NamedMultiMesh.cpp.
References wmtk::components::input::NamedMultiMesh::Node::m_children, m_name_root, wmtk::components::input::NamedMultiMesh::Node::name, and root_name().
operator=()
auto wmtk::components::input::NamedMultiMesh::operator= (const NamedMultiMesh & o) -> NamedMultiMesh&
Definition at line 141 of file NamedMultiMesh.cpp.
References m_root.
root() [1/2]
Mesh& wmtk::components::input::NamedMultiMesh::root () inline
Definition at line 38 of file NamedMultiMesh.hpp.
References m_root.
Referenced by TEST_CASE().
root() [2/2]
const Mesh& wmtk::components::input::NamedMultiMesh::root () const inline
Definition at line 39 of file NamedMultiMesh.hpp.
References m_root.
root_name()
std::string_view wmtk::components::input::NamedMultiMesh::root_name () const
Definition at line 119 of file NamedMultiMesh.cpp.
References m_name_root.
Referenced by wmtk::components::input::MeshCollection::add_mesh(), name(), and set_name().
set_mesh()
void wmtk::components::input::NamedMultiMesh::set_mesh (Mesh & m)
Navigates to the root of the multimesh.
Definition at line 63 of file NamedMultiMesh.cpp.
References wmtk::Mesh::get_multi_mesh_root(), and set_root().
Referenced by wmtk::components::input::input(), and TEST_CASE().
set_name()
void wmtk::components::input::NamedMultiMesh::set_name (const std::string_view & root_name = "")
Definition at line 96 of file NamedMultiMesh.cpp.
References root_name(), and set_names().
Referenced by TEST_CASE().
set_names()
void wmtk::components::input::NamedMultiMesh::set_names (const nlohmann::json & js)
Definition at line 100 of file NamedMultiMesh.cpp.
References m_name_root.
Referenced by wmtk::components::input::input(), set_name(), and TEST_CASE().
set_root()
void wmtk::components::input::NamedMultiMesh::set_root (Mesh & m)
Definition at line 58 of file NamedMultiMesh.cpp.
References m_root.
Referenced by set_mesh().
Member Data Documentation
m_name_root
std::unique_ptr<Node> wmtk::components::input::NamedMultiMesh::m_name_root private
Definition at line 44 of file NamedMultiMesh.hpp.
Referenced by name(), root_name(), and set_names().
m_root
std::shared_ptr<Mesh> wmtk::components::input::NamedMultiMesh::m_root private
Definition at line 43 of file NamedMultiMesh.hpp.
Referenced by get_mesh(), operator=(), root(), and set_root().
The documentation for this class was generated from the following files:
components/input/src/wmtk/components/input/NamedMultiMesh.hpp
components/input/src/wmtk/components/input/NamedMultiMesh.cpp