Wildmeshing Toolkit: wmtk::io::ParaviewWriter Class Reference
wmtk::io::ParaviewWriter Class Reference
#include <ParaviewWriter.hpp>
Classes
class ParaviewInternalWriter
Public Member Functions
ParaviewWriter (const std::filesystem::path &filename, const std::string &vertices_name, const Mesh &mesh, bool write_points=true, bool write_edges=true, bool write_faces=true, bool write_tetrahedra=true)
bool write (const int dim) override
void write_top_simplex_type (const PrimitiveType) override
void write_capacities (const std::vector< int64_t > &capacities) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< char > &val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< int64_t > &val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< double > &val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< Rational > &val) override
Public Member Functions inherited from wmtk::MeshWriter
virtual ~MeshWriter ()
Private Member Functions
void write_internal (const std::string &name, const int64_t type, const int64_t stride, const std::vector< double > &val)
Private Attributes
std::array< ParaviewInternalWriter, 4 > m_writers
std::array< bool, 4 > m_enabled
std::string m_vertices_name
Detailed Description
Definition at line 16 of file ParaviewWriter.hpp.
Constructor & Destructor Documentation
ParaviewWriter()
wmtk::io::ParaviewWriter::ParaviewWriter (const std::filesystem::path & filename, const std::string & vertices_name, const Mesh & mesh, bool write_points = true, bool write_edges = true, bool write_faces = true, bool write_tetrahedra = true)
Definition at line 67 of file ParaviewWriter.cpp.
References wmtk::Edge, wmtk::Face, wmtk::Mesh::get_all(), wmtk::Mesh::id(), m_enabled, m_writers, wmtk::Mesh::switch_tuple(), and wmtk::Vertex.
Member Function Documentation
write() [1/5]
bool wmtk::io::ParaviewWriter::write (const int dim) inline override virtual
Implements wmtk::MeshWriter.
Definition at line 59 of file ParaviewWriter.hpp.
References m_enabled.
write() [2/5]
void wmtk::io::ParaviewWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< char > & val) override virtual
Implements wmtk::MeshWriter.
Definition at line 151 of file ParaviewWriter.cpp.
References write_internal().
write() [3/5]
void wmtk::io::ParaviewWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< double > & val) override virtual
Implements wmtk::MeshWriter.
Definition at line 142 of file ParaviewWriter.cpp.
References write_internal().
write() [4/5]
void wmtk::io::ParaviewWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< int64_t > & val) override virtual
Implements wmtk::MeshWriter.
Definition at line 129 of file ParaviewWriter.cpp.
References write_internal().
write() [5/5]
void wmtk::io::ParaviewWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< Rational > & val) override virtual
Implements wmtk::MeshWriter.
Definition at line 165 of file ParaviewWriter.cpp.
References write_internal().
write_capacities()
void wmtk::io::ParaviewWriter::write_capacities (const std::vector< int64_t > & capacities) inline override virtual
Implements wmtk::MeshWriter.
Definition at line 64 of file ParaviewWriter.hpp.
write_internal()
void wmtk::io::ParaviewWriter::write_internal (const std::string & name, const int64_t type, const int64_t stride, const std::vector< double > & val) private
Definition at line 178 of file ParaviewWriter.cpp.
References m_enabled, m_vertices_name, and m_writers.
Referenced by write().
write_top_simplex_type()
void wmtk::io::ParaviewWriter::write_top_simplex_type (const PrimitiveType) inline override virtual
Implements wmtk::MeshWriter.
Definition at line 61 of file ParaviewWriter.hpp.
Member Data Documentation
m_enabled
std::array<bool, 4> wmtk::io::ParaviewWriter::m_enabled private
Definition at line 93 of file ParaviewWriter.hpp.
Referenced by ParaviewWriter(), write(), and write_internal().
m_vertices_name
std::string wmtk::io::ParaviewWriter::m_vertices_name private
Definition at line 94 of file ParaviewWriter.hpp.
Referenced by write_internal().
m_writers
std::array<ParaviewInternalWriter, 4> wmtk::io::ParaviewWriter::m_writers private
Definition at line 92 of file ParaviewWriter.hpp.
Referenced by ParaviewWriter(), and write_internal().
The documentation for this class was generated from the following files:
src/wmtk/io/ParaviewWriter.hpp
src/wmtk/io/ParaviewWriter.cpp