Wildmeshing Toolkit: wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes > Class Template Reference
wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes > Class Template Reference
#include <ReferenceWrappedFunctorReturnCache.hpp>
Public Types
using TypeHelper = detail::ReferenceWrappedFunctorReturnType< Functor, typename BaseVariantTraitsType::AllReferenceTuple, OtherArgumentTypes... >
using ReturnVariant = typename TypeHelper::type
using RefVariantType = typename BaseVariantTraitsType::ReferenceVariant
using BaseType = typename BaseVariantTraitsType::BaseType
using TupleType = typename BaseVariantTraitsType::DerivedTypesTuple
using RefTupleType = typename BaseVariantTraitsType::ReferenceTuple
using KeyType = std::tuple< const BaseType *, OtherArgumentTypes... >
Public Member Functions
template<typename InputType , typename ReturnType >
void add (ReturnType &&return_data, const InputType &input, const OtherArgumentTypes &... args)
template<typename InputType >
auto get (const InputType &input, const OtherArgumentTypes &... ts) const -> typename TypeHelper::template ReturnTypeConstRef< InputType >
const auto & get_variant (const BaseType &input, const OtherArgumentTypes &... ts) const
std::vector< KeyType > keys () const
auto get_id (const BaseType &input, const OtherArgumentTypes &... ts) const
const auto & get_variant (const KeyType &key) const
auto begin () const
auto end () const
void set_enable_overwrites (bool value)
Private Attributes
std::map< KeyType, ReturnVariant, typename ComparatorType::Less > m_data
bool m_enable_overwrites = false
Detailed Description
template<typename Functor, typename BaseVariantTraitsType, typename ComparatorType, typename... OtherArgumentTypes>
class wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >
Definition at line 41 of file ReferenceWrappedFunctorReturnCache.hpp.
Member Typedef Documentation
BaseType
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::BaseType = typename BaseVariantTraitsType::BaseType
Definition at line 52 of file ReferenceWrappedFunctorReturnCache.hpp.
KeyType
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::KeyType = std::tuple<const BaseType*, OtherArgumentTypes...>
Definition at line 140 of file ReferenceWrappedFunctorReturnCache.hpp.
RefTupleType
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::RefTupleType = typename BaseVariantTraitsType::ReferenceTuple
Definition at line 54 of file ReferenceWrappedFunctorReturnCache.hpp.
RefVariantType
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::RefVariantType = typename BaseVariantTraitsType::ReferenceVariant
Definition at line 51 of file ReferenceWrappedFunctorReturnCache.hpp.
ReturnVariant
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::ReturnVariant = typename TypeHelper::type
Definition at line 49 of file ReferenceWrappedFunctorReturnCache.hpp.
TupleType
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::TupleType = typename BaseVariantTraitsType::DerivedTypesTuple
Definition at line 53 of file ReferenceWrappedFunctorReturnCache.hpp.
TypeHelper
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> using wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::TypeHelper = detail::ReferenceWrappedFunctorReturnType< Functor, typename BaseVariantTraitsType::AllReferenceTuple, OtherArgumentTypes...>
Definition at line 44 of file ReferenceWrappedFunctorReturnCache.hpp.
Member Function Documentation
add()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> template<typename InputType , typename ReturnType > void wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::add (ReturnType && return_data, const InputType & input, const OtherArgumentTypes &... args) inline
Definition at line 61 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_id(), wmtk::components::input(), wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data, and wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_enable_overwrites.
begin()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> auto wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::begin () const inline
Definition at line 162 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data.
end()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> auto wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::end () const inline
Definition at line 163 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data.
get()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> template<typename InputType > auto wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get (const InputType & input, const OtherArgumentTypes &... ts) const -> typename TypeHelper::template ReturnTypeConstRef<InputType> inline
Definition at line 101 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_variant(), and wmtk::components::input().
get_id()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> auto wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_id (const BaseType & input, const OtherArgumentTypes &... ts) const inline
Definition at line 152 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::components::input().
Referenced by wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::add(), and wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_variant().
get_variant() [1/2]
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> const auto& wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_variant (const BaseType & input, const OtherArgumentTypes &... ts) const inline
Definition at line 133 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_id(), wmtk::components::input(), and wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data.
Referenced by wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get().
get_variant() [2/2]
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> const auto& wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_variant (const KeyType & key) const inline
Definition at line 159 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data.
keys()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> std::vector<KeyType> wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::keys () const inline
Definition at line 142 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data.
set_enable_overwrites()
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> void wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::set_enable_overwrites (bool value) inline
Definition at line 165 of file ReferenceWrappedFunctorReturnCache.hpp.
References wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_enable_overwrites.
Member Data Documentation
m_data
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> std::map<KeyType, ReturnVariant, typename ComparatorType::Less> wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_data private
Definition at line 168 of file ReferenceWrappedFunctorReturnCache.hpp.
Referenced by wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::add(), wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::begin(), wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::end(), wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::get_variant(), and wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::keys().
m_enable_overwrites
template<typename Functor , typename BaseVariantTraitsType , typename ComparatorType , typename... OtherArgumentTypes> bool wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::m_enable_overwrites = false private
Definition at line 169 of file ReferenceWrappedFunctorReturnCache.hpp.
Referenced by wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::add(), and wmtk::utils::metaprogramming::detail::ReferenceWrappedFunctorReturnCache< Functor, BaseVariantTraitsType, ComparatorType, OtherArgumentTypes >::set_enable_overwrites().
The documentation for this class was generated from the following file:
src/wmtk/utils/metaprogramming/ReferenceWrappedFunctorReturnCache.hpp