Wildmeshing Toolkit: wmtk::attribute::AttributeCache< T > Class Template Reference
wmtk::attribute::AttributeCache< T > Class Template Reference
#include <AttributeCache.hpp>
Public Types
using Data = AttributeCacheData< T >
using DataStorage = std::map< int64_t, Data, std::less< int64_t > >
using MapResult = internal::MapResult< T >
using ConstMapResult = internal::ConstMapResult< T >
Public Member Functions
AttributeCache ()
~AttributeCache ()
AttributeCache (const AttributeCache &)=delete
AttributeCache & operator= (const AttributeCache &)=delete
AttributeCache (AttributeCache &&)=default
AttributeCache & operator= (AttributeCache &&)=default
template<typename Derived >
void try_caching (int64_t index, const Eigen::MatrixBase< Derived > &value)
void try_caching (int64_t index, const T &value)
DataStorage::const_iterator find_value (int64_t index) const
bool is_value (const typename DataStorage::const_iterator &it) const
void clear ()
size_t size () const
void apply_to (Attribute< T > &attribute) const
void apply_to (AttributeCache< T > &other) const
void apply_to (const Attribute< T > &attribute, std::vector< T > &other) const
Protected Attributes
DataStorage m_data
Detailed Description
template<typename T>
class wmtk::attribute::AttributeCache< T >
Definition at line 19 of file AttributeCache.hpp.
Member Typedef Documentation
ConstMapResult
template<typename T > using wmtk::attribute::AttributeCache< T >::ConstMapResult = internal::ConstMapResult<T>
Definition at line 34 of file AttributeCache.hpp.
Data
template<typename T > using wmtk::attribute::AttributeCache< T >::Data = AttributeCacheData<T>
Definition at line 22 of file AttributeCache.hpp.
DataStorage
template<typename T > using wmtk::attribute::AttributeCache< T >::DataStorage = std::map< int64_t, Data, std::less<int64_t> >
Definition at line 23 of file AttributeCache.hpp.
MapResult
template<typename T > using wmtk::attribute::AttributeCache< T >::MapResult = internal::MapResult<T>
Definition at line 33 of file AttributeCache.hpp.
Constructor & Destructor Documentation
AttributeCache() [1/3]
template<typename T > wmtk::attribute::AttributeCache< T >::AttributeCache inline
Definition at line 10 of file AttributeCache.hxx.
~AttributeCache()
template<typename T > wmtk::attribute::AttributeCache< T >::~AttributeCache () inline default
AttributeCache() [2/3]
template<typename T > wmtk::attribute::AttributeCache< T >::AttributeCache (const AttributeCache< T > &) delete
AttributeCache() [3/3]
template<typename T > wmtk::attribute::AttributeCache< T >::AttributeCache (AttributeCache< T > &&) default
Member Function Documentation
apply_to() [1/3]
template<typename T > void wmtk::attribute::AttributeCache< T >::apply_to (Attribute< T > & attribute) const inline
Definition at line 62 of file AttributeCache.hxx.
References wmtk::attribute::Attribute< T >::vector_attribute().
Referenced by wmtk::attribute::AttributeScope< T >::apply().
apply_to() [2/3]
template<typename T > void wmtk::attribute::AttributeCache< T >::apply_to (AttributeCache< T > & other) const inline
Definition at line 73 of file AttributeCache.hxx.
References wmtk::attribute::AttributeCache< T >::m_data.
apply_to() [3/3]
template<typename T > void wmtk::attribute::AttributeCache< T >::apply_to (const Attribute< T > & attribute, std::vector< T > & other) const inline
Definition at line 87 of file AttributeCache.hxx.
References wmtk::attribute::Attribute< T >::vector_attribute().
clear()
template<typename T > void wmtk::attribute::AttributeCache< T >::clear inline
Definition at line 33 of file AttributeCache.hxx.
find_value()
template<typename T > auto wmtk::attribute::AttributeCache< T >::find_value (int64_t index) const inline
Definition at line 21 of file AttributeCache.hxx.
is_value()
template<typename T > bool wmtk::attribute::AttributeCache< T >::is_value (const typename DataStorage::const_iterator & it) const inline
Definition at line 27 of file AttributeCache.hxx.
operator=() [1/2]
template<typename T > AttributeCache& wmtk::attribute::AttributeCache< T >::operator= (AttributeCache< T > &&) default
operator=() [2/2]
template<typename T > AttributeCache& wmtk::attribute::AttributeCache< T >::operator= (const AttributeCache< T > &) delete
size()
template<typename T > size_t wmtk::attribute::AttributeCache< T >::size () const inline
Definition at line 53 of file AttributeCache.hpp.
References wmtk::attribute::AttributeCache< T >::m_data.
try_caching() [1/2]
template<typename T > template<typename Derived > void wmtk::attribute::AttributeCache< T >::try_caching (int64_t index, const Eigen::MatrixBase< Derived > & value) inline
Definition at line 41 of file AttributeCache.hxx.
try_caching() [2/2]
template<typename T > void wmtk::attribute::AttributeCache< T >::try_caching (int64_t index, const T & value) inline
Definition at line 51 of file AttributeCache.hxx.
Member Data Documentation
m_data
template<typename T > DataStorage wmtk::attribute::AttributeCache< T >::m_data protected
Definition at line 67 of file AttributeCache.hpp.
Referenced by wmtk::attribute::AttributeCache< T >::apply_to(), and wmtk::attribute::AttributeCache< T >::size().
The documentation for this class was generated from the following files:
src/wmtk/attribute/Attribute.hpp
src/wmtk/attribute/AttributeCache.hpp
src/wmtk/attribute/AttributeCache.hxx