Wildmeshing Toolkit: wmtk::operations::OptimizationSmoothing Class Reference
wmtk::operations::OptimizationSmoothing Class Reference
#include <OptimizationSmoothing.hpp>
Classes
class WMTKProblem
Public Member Functions
OptimizationSmoothing (std::shared_ptr< wmtk::function::Function > energy)
std::vector< simplex::Simplex > execute (const simplex::Simplex &simplex) override
returns an empty vector in case of failure
const polysolve::json & linear_solver_params () const
const polysolve::json & nonlinear_solver_params () const
void set_linear_solver_params (const polysolve::json &params)
void set_nonlinear_solver_params (const polysolve::json &params)
Public Member Functions inherited from wmtk::operations::AttributesUpdate
AttributesUpdate (Mesh &m)
virtual PrimitiveType primitive_type () const override
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
std::vector< simplex::Simplex > operator() (const simplex::Simplex &simplex)
virtual std::vector< double > priority (const simplex::Simplex &simplex) const
bool use_random_priority () const
bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< std::vector< double >(const simplex::Simplex &)> &func)
std::shared_ptr< operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandle &attribute)
void add_transfer_strategy (const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
virtual void reserve_enough_simplices ()
Private Member Functions
void create_solver ()
Private Attributes
std::shared_ptr< wmtk::function::Function > m_energy
std::shared_ptr< polysolve::nonlinear::Solver > m_solver
polysolve::json m_linear_solver_params
polysolve::json m_nonlinear_solver_params
Additional Inherited Members
Protected Member Functions inherited from wmtk::operations::AttributesUpdate
virtual std::vector< simplex::Simplex > unmodified_primitives (const simplex::Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
Protected Member Functions inherited from wmtk::operations::Operation
virtual bool before (const simplex::Simplex &simplex) const
virtual bool after (const std::vector< simplex::Simplex > &unmods, const std::vector< simplex::Simplex > &mods) const
Tuple resurrect_tuple (const Tuple &tuple) const
utility for subclasses
Accessor< int64_t > hash_accessor ()
utility for subclasses
ConstAccessor< int64_t > hash_accessor () const
utility for subclasses
void apply_attribute_transfer (const std::vector< simplex::Simplex > &direct_mods)
Protected Attributes inherited from wmtk::operations::Operation
invariants::InvariantCollection m_invariants
std::vector< std::shared_ptr< operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Definition at line 18 of file OptimizationSmoothing.hpp.
Constructor & Destructor Documentation
OptimizationSmoothing()
wmtk::operations::OptimizationSmoothing::OptimizationSmoothing (std::shared_ptr< wmtk::function::Function > energy)
Definition at line 121 of file OptimizationSmoothing.cpp.
References create_solver(), m_linear_solver_params, and m_nonlinear_solver_params.
Member Function Documentation
create_solver()
void wmtk::operations::OptimizationSmoothing::create_solver () private
Definition at line 131 of file OptimizationSmoothing.cpp.
References m_linear_solver_params, m_nonlinear_solver_params, m_solver, and wmtk::opt_logger().
Referenced by OptimizationSmoothing(), set_linear_solver_params(), and set_nonlinear_solver_params().
execute()
std::vector< simplex::Simplex > wmtk::operations::OptimizationSmoothing::execute (const simplex::Simplex & simplex) override virtual
returns an empty vector in case of failure
Reimplemented from wmtk::operations::AttributesUpdate.
Definition at line 141 of file OptimizationSmoothing.cpp.
References wmtk::Mesh::create_accessor(), wmtk::operations::AttributesUpdate::execute(), wmtk::operations::OptimizationSmoothing::WMTKProblem::initial_value(), m_energy, wmtk::operations::Operation::m_invariants, m_solver, wmtk::operations::Operation::mesh(), and wmtk::simplex::Simplex::tuple().
linear_solver_params()
const polysolve::json& wmtk::operations::OptimizationSmoothing::linear_solver_params () const inline
Definition at line 28 of file OptimizationSmoothing.hpp.
References m_linear_solver_params.
nonlinear_solver_params()
const polysolve::json& wmtk::operations::OptimizationSmoothing::nonlinear_solver_params () const inline
Definition at line 29 of file OptimizationSmoothing.hpp.
References m_nonlinear_solver_params.
set_linear_solver_params()
void wmtk::operations::OptimizationSmoothing::set_linear_solver_params (const polysolve::json & params) inline
Definition at line 32 of file OptimizationSmoothing.hpp.
References create_solver(), and m_linear_solver_params.
set_nonlinear_solver_params()
void wmtk::operations::OptimizationSmoothing::set_nonlinear_solver_params (const polysolve::json & params) inline
Definition at line 38 of file OptimizationSmoothing.hpp.
References create_solver(), and m_nonlinear_solver_params.
Member Data Documentation
m_energy
std::shared_ptr<wmtk::function::Function> wmtk::operations::OptimizationSmoothing::m_energy private
Definition at line 45 of file OptimizationSmoothing.hpp.
Referenced by execute(), wmtk::operations::OptimizationSmoothing::WMTKProblem::gradient(), wmtk::operations::OptimizationSmoothing::WMTKProblem::hessian(), wmtk::operations::OptimizationSmoothing::WMTKProblem::is_step_valid(), and wmtk::operations::OptimizationSmoothing::WMTKProblem::value().
m_linear_solver_params
polysolve::json wmtk::operations::OptimizationSmoothing::m_linear_solver_params private
Definition at line 49 of file OptimizationSmoothing.hpp.
Referenced by create_solver(), linear_solver_params(), OptimizationSmoothing(), and set_linear_solver_params().
m_nonlinear_solver_params
polysolve::json wmtk::operations::OptimizationSmoothing::m_nonlinear_solver_params private
Definition at line 50 of file OptimizationSmoothing.hpp.
Referenced by create_solver(), nonlinear_solver_params(), OptimizationSmoothing(), and set_nonlinear_solver_params().
m_solver
std::shared_ptr<polysolve::nonlinear::Solver> wmtk::operations::OptimizationSmoothing::m_solver private
Definition at line 46 of file OptimizationSmoothing.hpp.
Referenced by create_solver(), and execute().
The documentation for this class was generated from the following files:
src/wmtk/operations/OptimizationSmoothing.hpp
src/wmtk/operations/OptimizationSmoothing.cpp