Wildmeshing Toolkit: wmtk::Primitive Class Reference
wmtk::Primitive Class Reference
#include <Primitive.hpp>
Public Member Functions
Primitive (const PrimitiveType &primitive_type, const Tuple &t)
Primitive (const simplex::Simplex &simplex)
Primitive (const Cell &cell)
PrimitiveType primitive_type () const
const Tuple & tuple () const
bool operator== (const Primitive &o) const
bool operator< (const Primitive &o) const
Static Public Member Functions
static Primitive vertex (const Tuple &t)
static Primitive edge (const Tuple &t)
static Primitive face (const Tuple &t)
static Primitive tetrahedron (const Tuple &t)
static Primitive halfedge (const Tuple &t)
Private Attributes
PrimitiveType m_primitive_type
Tuple m_tuple
Detailed Description
Definition at line 10 of file Primitive.hpp.
Constructor & Destructor Documentation
Primitive() [1/3]
wmtk::Primitive::Primitive (const PrimitiveType & primitive_type, const Tuple & t)
Definition at line 7 of file Primitive.cpp.
Referenced by edge(), face(), tetrahedron(), and vertex().
Primitive() [2/3]
wmtk::Primitive::Primitive (const simplex::Simplex & simplex)
Definition at line 11 of file Primitive.cpp.
Primitive() [3/3]
wmtk::Primitive::Primitive (const Cell & cell)
Definition at line 15 of file Primitive.cpp.
Member Function Documentation
edge()
Primitive wmtk::Primitive::edge (const Tuple & t) static
Definition at line 33 of file Primitive.cpp.
References wmtk::Edge, and Primitive().
face()
Primitive wmtk::Primitive::face (const Tuple & t) static
Definition at line 37 of file Primitive.cpp.
References Primitive(), and wmtk::Triangle.
halfedge()
static Primitive wmtk::Primitive::halfedge (const Tuple & t) static
operator<()
bool wmtk::Primitive::operator< (const Primitive & o) const
Definition at line 51 of file Primitive.cpp.
References m_primitive_type, and m_tuple.
operator==()
bool wmtk::Primitive::operator== (const Primitive & o) const
Definition at line 46 of file Primitive.cpp.
References m_primitive_type, and m_tuple.
primitive_type()
PrimitiveType wmtk::Primitive::primitive_type () const
Definition at line 20 of file Primitive.cpp.
References m_primitive_type.
tetrahedron()
Primitive wmtk::Primitive::tetrahedron (const Tuple & t) static
Definition at line 41 of file Primitive.cpp.
References Primitive(), and wmtk::Tetrahedron.
tuple()
const Tuple & wmtk::Primitive::tuple () const
Definition at line 24 of file Primitive.cpp.
References m_tuple.
vertex()
Primitive wmtk::Primitive::vertex (const Tuple & t) static
Definition at line 29 of file Primitive.cpp.
References Primitive(), and wmtk::Vertex.
Member Data Documentation
m_primitive_type
PrimitiveType wmtk::Primitive::m_primitive_type private
Definition at line 12 of file Primitive.hpp.
Referenced by operator<(), operator==(), and primitive_type().
m_tuple
Tuple wmtk::Primitive::m_tuple private
Definition at line 13 of file Primitive.hpp.
Referenced by operator<(), operator==(), and tuple().
The documentation for this class was generated from the following files:
src/wmtk/Primitive.hpp
src/wmtk/Primitive.cpp