Wildmeshing Toolkit: wmtk::operations::Rounding Class Reference
wmtk::operations::Rounding Class Reference
#include <Rounding.hpp>
Public Member Functions
Rounding (Mesh &m, TypedAttributeHandle< Rational > &coordinate)
std::vector< simplex::Simplex > execute (const simplex::Simplex &simplex) override
returns an empty vector in case of failure
Public Member Functions inherited from wmtk::operations::AttributesUpdate
AttributesUpdate (Mesh &m)
virtual PrimitiveType primitive_type () const override
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
virtual std::vector< simplex::Simplex > operator() (const simplex::Simplex &simplex)
virtual double priority (const simplex::Simplex &simplex) const
virtual bool use_random_priority () const
virtual bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< double(const simplex::Simplex &)> &func)
std::shared_ptr< const operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandle &attribute)
void add_transfer_strategy (const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void clear_attribute_transfer_strategies ()
virtual void reserve_enough_simplices ()
Private Attributes
TypedAttributeHandle< Rational > & m_coordinate_handle
Additional Inherited Members
Protected Member Functions inherited from wmtk::operations::AttributesUpdate
virtual std::vector< simplex::Simplex > unmodified_primitives (const simplex::Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
Protected Member Functions inherited from wmtk::operations::Operation
virtual bool before (const simplex::Simplex &simplex) const
virtual bool after (const std::vector< simplex::Simplex > &unmods, const std::vector< simplex::Simplex > &mods) const
void apply_attribute_transfer (const std::vector< simplex::Simplex > &direct_mods)
Protected Attributes inherited from wmtk::operations::Operation
std::function< double(const simplex::Simplex &)> m_priority = nullptr
invariants::InvariantCollection m_invariants
std::vector< std::shared_ptr< const operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Definition at line 9 of file Rounding.hpp.
Constructor & Destructor Documentation
Rounding()
wmtk::operations::Rounding::Rounding (Mesh & m, TypedAttributeHandle< Rational > & coordinate)
Definition at line 11 of file Rounding.cpp.
Member Function Documentation
execute()
std::vector< simplex::Simplex > wmtk::operations::Rounding::execute (const simplex::Simplex & simplex) override virtual
returns an empty vector in case of failure
Reimplemented from wmtk::operations::AttributesUpdate.
Definition at line 16 of file Rounding.cpp.
References wmtk::Mesh::create_accessor(), wmtk::operations::AttributesUpdate::execute(), wmtk::Mesh::get_attribute_dimension(), m_coordinate_handle, wmtk::operations::Operation::mesh(), wmtk::simplex::Simplex::primitive_type(), wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Member Data Documentation
m_coordinate_handle
TypedAttributeHandle<Rational>& wmtk::operations::Rounding::m_coordinate_handle private
Definition at line 17 of file Rounding.hpp.
Referenced by execute().
The documentation for this class was generated from the following files:
src/wmtk/operations/Rounding.hpp
src/wmtk/operations/Rounding.cpp