Wildmeshing Toolkit: wmtk::operations::internal::CollapseAlternateFacetOptionData Class Reference
wmtk::operations::internal::CollapseAlternateFacetOptionData Class Reference
#include <CollapseAlternateFacetOptionData.hpp>
Public Types
using Dart = autogen::Dart
Public Member Functions
CollapseAlternateFacetOptionData (const Mesh &m, const Tuple &input_tuple)
CollapseAlternateFacetOptionData (const Mesh &m, const autogen::SimplexDart &sd, const Tuple &input_tuple)
Dart convert (const Dart &d, size_t index) const
Public Attributes
autogen::Dart input
std::array< autogen::Dart, 2 > alts
std::array< int8_t, 2 > local_boundary_indices
Private Member Functions
Dart left_switches (const Mesh &m, const Tuple &t) const
Dart right_switches (const Mesh &m, const Tuple &t) const
Dart get_neighbor_action (const Mesh &m, const Tuple &t, int8_t local_action) const
Detailed Description
Definition at line 12 of file CollapseAlternateFacetOptionData.hpp.
Member Typedef Documentation
Dart
using wmtk::operations::internal::CollapseAlternateFacetOptionData::Dart = autogen::Dart
Definition at line 15 of file CollapseAlternateFacetOptionData.hpp.
Constructor & Destructor Documentation
CollapseAlternateFacetOptionData() [1/2]
wmtk::operations::internal::CollapseAlternateFacetOptionData::CollapseAlternateFacetOptionData (const Mesh & m, const Tuple & input_tuple)
Definition at line 22 of file CollapseAlternateFacetOptionData.cpp.
CollapseAlternateFacetOptionData() [2/2]
wmtk::operations::internal::CollapseAlternateFacetOptionData::CollapseAlternateFacetOptionData (const Mesh & m, const autogen::SimplexDart & sd, const Tuple & input_tuple)
Definition at line 10 of file CollapseAlternateFacetOptionData.cpp.
References left_switches(), and right_switches().
Member Function Documentation
convert()
Dart wmtk::operations::internal::CollapseAlternateFacetOptionData::convert (const Dart & d, size_t index) const
get_neighbor_action()
auto wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action (const Mesh & m, const Tuple & t, int8_t local_action) const private
Definition at line 42 of file CollapseAlternateFacetOptionData.cpp.
References wmtk::autogen::find_local_dart_action(), wmtk::autogen::SimplexDart::get_singleton(), wmtk::autogen::Dart::local_orientation(), and wmtk::autogen::local_switch_tuple().
left_switches()
auto wmtk::operations::internal::CollapseAlternateFacetOptionData::left_switches (const Mesh & m, const Tuple & t) const private
Definition at line 31 of file CollapseAlternateFacetOptionData.cpp.
References wmtk::operations::internal::left_ear_action().
Referenced by CollapseAlternateFacetOptionData().
right_switches()
auto wmtk::operations::internal::CollapseAlternateFacetOptionData::right_switches (const Mesh & m, const Tuple & t) const private
Definition at line 36 of file CollapseAlternateFacetOptionData.cpp.
References wmtk::operations::internal::right_ear_action().
Referenced by CollapseAlternateFacetOptionData().
Member Data Documentation
alts
std::array<autogen::Dart, 2> wmtk::operations::internal::CollapseAlternateFacetOptionData::alts
Definition at line 34 of file CollapseAlternateFacetOptionData.hpp.
input
autogen::Dart wmtk::operations::internal::CollapseAlternateFacetOptionData::input
Definition at line 21 of file CollapseAlternateFacetOptionData.hpp.
local_boundary_indices
std::array<int8_t, 2> wmtk::operations::internal::CollapseAlternateFacetOptionData::local_boundary_indices
Definition at line 35 of file CollapseAlternateFacetOptionData.hpp.
The documentation for this class was generated from the following files:
src/wmtk/operations/internal/CollapseAlternateFacetOptionData.hpp
src/wmtk/operations/internal/CollapseAlternateFacetOptionData.cpp