Wildmeshing Toolkit: wmtk::attribute::AccessorBase< _T > Class Template Reference
wmtk::attribute::AccessorBase< _T > Class Template Reference
#include <AccessorBase.hpp>
Public Types
using T = _T
using MeshAttributesType = MeshAttributes< T >
using AttributeType = Attribute< T >
template<int D = Eigen::Dynamic>
using MapResult = internal::MapResult< T, D >
template<int D = Eigen::Dynamic>
using ConstMapResult = internal::ConstMapResult< T, D >
Public Member Functions
int64_t reserved_size () const
int64_t dimension () const
void set_attribute (std::vector< T > value)
template<int D = Eigen::Dynamic>
ConstMapResult< D > const_vector_attribute (const int64_t index) const
template<int D = Eigen::Dynamic>
MapResult< D > vector_attribute (const int64_t index)
T const_scalar_attribute (const int64_t index) const
T & scalar_attribute (const int64_t index)
T const_scalar_attribute (const int64_t index, const int8_t offset) const
T & scalar_attribute (const int64_t index, const int8_t offset)
MeshAttributes< T > & attributes ()
const MeshAttributes< T > & attributes () const
Attribute< T > & attribute ()
const Attribute< T > & attribute () const
~AccessorBase ()
AccessorBase (Mesh &m, const TypedAttributeHandle< T > &handle)
AccessorBase (const Mesh &m, const TypedAttributeHandle< T > &handle)
MeshAttributeHandle handle () const
const TypedAttributeHandle< T > & typed_handle () const
PrimitiveType primitive_type () const
Mesh & mesh ()
const Mesh & mesh () const
template<int D>
auto const_vector_attribute (const int64_t index) const -> ConstMapResult< D >
template<int D>
auto vector_attribute (const int64_t index) -> MapResult< D >
Protected Member Functions
const AttributeManager & attribute_manager () const
AttributeManager & attribute_manager ()
Protected Attributes
TypedAttributeHandle< T > m_handle
Mesh & m_mesh
Attribute< T > & m_attribute
Friends
class AccessorCache< T >
template<typename U , typename MeshType >
class Accessor
Detailed Description
template<typename _T>
class wmtk::attribute::AccessorBase< _T >
Definition at line 30 of file AccessorBase.hpp.
Member Typedef Documentation
AttributeType
template<typename _T > using wmtk::attribute::AccessorBase< _T >::AttributeType = Attribute<T>
Definition at line 38 of file AccessorBase.hpp.
ConstMapResult
template<typename _T > template<int D = Eigen::Dynamic> using wmtk::attribute::AccessorBase< _T >::ConstMapResult = internal::ConstMapResult<T, D>
Definition at line 43 of file AccessorBase.hpp.
MapResult
template<typename _T > template<int D = Eigen::Dynamic> using wmtk::attribute::AccessorBase< _T >::MapResult = internal::MapResult<T, D>
Definition at line 41 of file AccessorBase.hpp.
MeshAttributesType
template<typename _T > using wmtk::attribute::AccessorBase< _T >::MeshAttributesType = MeshAttributes<T>
Definition at line 35 of file AccessorBase.hpp.
T
template<typename _T > using wmtk::attribute::AccessorBase< _T >::T = _T
Definition at line 33 of file AccessorBase.hpp.
Constructor & Destructor Documentation
~AccessorBase()
template<typename T > wmtk::attribute::AccessorBase< T >::~AccessorBase () inline default
AccessorBase() [1/2]
template<typename T > wmtk::attribute::AccessorBase< T >::AccessorBase (Mesh & m, const TypedAttributeHandle< T > & handle) inline
Definition at line 11 of file AccessorBase.hxx.
AccessorBase() [2/2]
template<typename T > wmtk::attribute::AccessorBase< T >::AccessorBase (const Mesh & m, const TypedAttributeHandle< T > & handle)
Definition at line 17 of file AccessorBase.hxx.
Member Function Documentation
attribute() [1/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::attribute inline
Definition at line 71 of file AccessorBase.hxx.
Referenced by wmtk::Mesh::consolidate().
attribute() [2/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::attribute inline
Definition at line 76 of file AccessorBase.hxx.
attribute_manager() [1/2]
template<typename T > AttributeManager & wmtk::attribute::AccessorBase< T >::attribute_manager inline protected
Definition at line 38 of file AccessorBase.hxx.
attribute_manager() [2/2]
template<typename T > const AttributeManager & wmtk::attribute::AccessorBase< T >::attribute_manager inline protected
Definition at line 32 of file AccessorBase.hxx.
attributes() [1/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::attributes inline
Definition at line 61 of file AccessorBase.hxx.
attributes() [2/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::attributes inline
Definition at line 66 of file AccessorBase.hxx.
const_scalar_attribute() [1/2]
template<typename T > T wmtk::attribute::AccessorBase< T >::const_scalar_attribute (const int64_t index) const inline
Definition at line 116 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::const_scalar_attribute().
Referenced by wmtk::attribute::AccessorBase< _T >::const_scalar_attribute().
const_scalar_attribute() [2/2]
template<typename T > T wmtk::attribute::AccessorBase< T >::const_scalar_attribute (const int64_t index, const int8_t offset) const inline
Definition at line 129 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::const_scalar_attribute().
const_vector_attribute() [1/2]
template<typename _T > template<int D = Eigen::Dynamic> ConstMapResult<D> wmtk::attribute::AccessorBase< _T >::const_vector_attribute (const int64_t index) const
const_vector_attribute() [2/2]
template<typename _T > template<int D> auto wmtk::attribute::AccessorBase< _T >::const_vector_attribute (const int64_t index) const -> ConstMapResult<D> inline
Definition at line 99 of file AccessorBase.hxx.
dimension()
template<typename T > int64_t wmtk::attribute::AccessorBase< T >::dimension inline
Definition at line 55 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::dimension().
Referenced by wmtk::invariants::EnvelopeInvariant::after(), wmtk::attribute::AccessorBase< _T >::dimension(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), and wmtk::operations::composite::ProjectOperation::ProjectOperation().
handle()
template<typename T > MeshAttributeHandle wmtk::attribute::AccessorBase< T >::handle inline
Definition at line 86 of file AccessorBase.hxx.
mesh() [1/2]
template<typename T > Mesh & wmtk::attribute::AccessorBase< T >::mesh inline
Definition at line 21 of file AccessorBase.hxx.
Referenced by wmtk::operations::composite::ProjectOperation::execute(), and wmtk::operations::composite::ProjectOperation::ProjectOperation().
mesh() [2/2]
template<typename T > const Mesh & wmtk::attribute::AccessorBase< T >::mesh inline
Definition at line 26 of file AccessorBase.hxx.
primitive_type()
template<typename T > PrimitiveType wmtk::attribute::AccessorBase< T >::primitive_type inline
Definition at line 92 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::primitive_type().
Referenced by wmtk::attribute::AccessorBase< _T >::primitive_type().
reserved_size()
template<typename T > int64_t wmtk::attribute::AccessorBase< T >::reserved_size inline
Definition at line 49 of file AccessorBase.hxx.
Referenced by wmtk::attribute::AccessorBase< T >::dimension(), wmtk::Mesh::request_simplex_indices(), and wmtk::Mesh::set_capacities_from_flags().
scalar_attribute() [1/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::scalar_attribute (const int64_t index) inline
Definition at line 122 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::scalar_attribute().
Referenced by wmtk::attribute::AccessorBase< _T >::scalar_attribute().
scalar_attribute() [2/2]
template<typename T > auto wmtk::attribute::AccessorBase< T >::scalar_attribute (const int64_t index, const int8_t offset) inline
Definition at line 135 of file AccessorBase.hxx.
References wmtk::attribute::AccessorBase< _T >::scalar_attribute().
set_attribute()
template<typename T > void wmtk::attribute::AccessorBase< T >::set_attribute (std::vector< T > value) inline
Definition at line 142 of file AccessorBase.hxx.
typed_handle()
template<typename T > const TypedAttributeHandle< T > & wmtk::attribute::AccessorBase< T >::typed_handle inline
Definition at line 81 of file AccessorBase.hxx.
vector_attribute() [1/2]
template<typename _T > template<int D = Eigen::Dynamic> MapResult<D> wmtk::attribute::AccessorBase< _T >::vector_attribute (const int64_t index)
vector_attribute() [2/2]
template<typename _T > template<int D> auto wmtk::attribute::AccessorBase< _T >::vector_attribute (const int64_t index) -> MapResult<D> inline
Definition at line 107 of file AccessorBase.hxx.
Friends And Related Function Documentation
Accessor
template<typename _T > template<typename U , typename MeshType > friend class Accessor friend
Definition at line 37 of file AccessorBase.hpp.
AccessorCache< T >
template<typename _T > friend class AccessorCache< T > friend
Definition at line 1 of file AccessorBase.hpp.
Member Data Documentation
m_attribute
template<typename _T > Attribute<T>& wmtk::attribute::AccessorBase< _T >::m_attribute protected
Definition at line 87 of file AccessorBase.hpp.
m_handle
template<typename _T > TypedAttributeHandle<T> wmtk::attribute::AccessorBase< _T >::m_handle protected
Definition at line 85 of file AccessorBase.hpp.
m_mesh
template<typename _T > Mesh& wmtk::attribute::AccessorBase< _T >::m_mesh protected
Definition at line 86 of file AccessorBase.hpp.
The documentation for this class was generated from the following files:
src/wmtk/attribute/AccessorBase.hpp
src/wmtk/attribute/AccessorBase.hxx