Wildmeshing Toolkit: wmtk::components::internal::RegularSpace Class Reference
wmtk::components::internal::RegularSpace Class Reference
#include <RegularSpace.hpp>
Public Member Functions
RegularSpace (MeshAttributeHandle< double > &position_handle, MeshAttributeHandle< int64_t > &vertex_tag, MeshAttributeHandle< int64_t > &edge_tag, const int64_t input_tag_value, const int64_t embedding_tag_value, const int64_t split_tag_value)
void process_vertex_simplicity_in_2d (TriMesh &m_mesh)
void process_edge_simplicity_in_2d (TriMesh &m_mesh)
void process_vertex_simplicity_in_3d (TetMesh &m_mesh)
void process_edge_simplicity_in_3d (TetMesh &m_mesh)
Private Attributes
MeshAttributeHandle< double > m_position_handle
MeshAttributeHandle< int64_t > m_vertex_tag
MeshAttributeHandle< int64_t > m_edge_tag
int64_t m_input_tag_value
int64_t m_embedding_tag_value
int64_t m_split_tag_value
Detailed Description
Definition at line 13 of file RegularSpace.hpp.
Constructor & Destructor Documentation
RegularSpace()
wmtk::components::internal::RegularSpace::RegularSpace (MeshAttributeHandle< double > & position_handle, MeshAttributeHandle< int64_t > & vertex_tag, MeshAttributeHandle< int64_t > & edge_tag, const int64_t input_tag_value, const int64_t embedding_tag_value, const int64_t split_tag_value)
Definition at line 13 of file RegularSpace.cpp.
Member Function Documentation
process_edge_simplicity_in_2d()
void wmtk::components::internal::RegularSpace::process_edge_simplicity_in_2d (TriMesh & m_mesh)
Definition at line 81 of file RegularSpace.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::edges(), wmtk::Face, wmtk::simplex::faces(), wmtk::Mesh::get_all(), m_edge_tag, m_embedding_tag_value, m_input_tag_value, wmtk::operations::m_mesh, m_position_handle, m_split_tag_value, m_vertex_tag, wmtk::Mesh::register_attribute(), wmtk::Scheduler::run_operation_on_all(), wmtk::Mesh::switch_edge(), and wmtk::Mesh::switch_vertex().
process_edge_simplicity_in_3d()
void wmtk::components::internal::RegularSpace::process_edge_simplicity_in_3d (TetMesh & m_mesh)
Definition at line 238 of file RegularSpace.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::edges(), wmtk::Mesh::get_all(), m_edge_tag, m_input_tag_value, wmtk::operations::m_mesh, m_position_handle, m_split_tag_value, m_vertex_tag, wmtk::Mesh::register_attribute(), wmtk::Scheduler::run_operation_on_all(), wmtk::Mesh::switch_edge(), wmtk::Mesh::switch_face(), wmtk::Mesh::switch_vertex(), and wmtk::Tetrahedron.
process_vertex_simplicity_in_2d()
void wmtk::components::internal::RegularSpace::process_vertex_simplicity_in_2d (TriMesh & m_mesh)
Definition at line 28 of file RegularSpace.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::edges(), wmtk::Mesh::get_all(), m_edge_tag, m_embedding_tag_value, m_input_tag_value, wmtk::operations::m_mesh, m_position_handle, m_split_tag_value, m_vertex_tag, wmtk::Mesh::register_attribute(), wmtk::Scheduler::run_operation_on_all(), and wmtk::Mesh::switch_vertex().
process_vertex_simplicity_in_3d()
void wmtk::components::internal::RegularSpace::process_vertex_simplicity_in_3d (TetMesh & m_mesh)
Definition at line 187 of file RegularSpace.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::edges(), wmtk::Mesh::get_all(), m_edge_tag, m_input_tag_value, wmtk::operations::m_mesh, m_position_handle, m_split_tag_value, m_vertex_tag, wmtk::Mesh::register_attribute(), wmtk::Scheduler::run_operation_on_all(), and wmtk::Mesh::switch_vertex().
Member Data Documentation
m_edge_tag
MeshAttributeHandle<int64_t> wmtk::components::internal::RegularSpace::m_edge_tag private
Definition at line 17 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), process_edge_simplicity_in_3d(), process_vertex_simplicity_in_2d(), and process_vertex_simplicity_in_3d().
m_embedding_tag_value
int64_t wmtk::components::internal::RegularSpace::m_embedding_tag_value private
Definition at line 19 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), and process_vertex_simplicity_in_2d().
m_input_tag_value
int64_t wmtk::components::internal::RegularSpace::m_input_tag_value private
Definition at line 18 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), process_edge_simplicity_in_3d(), process_vertex_simplicity_in_2d(), and process_vertex_simplicity_in_3d().
m_position_handle
MeshAttributeHandle<double> wmtk::components::internal::RegularSpace::m_position_handle private
Definition at line 15 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), process_edge_simplicity_in_3d(), process_vertex_simplicity_in_2d(), and process_vertex_simplicity_in_3d().
m_split_tag_value
int64_t wmtk::components::internal::RegularSpace::m_split_tag_value private
Definition at line 20 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), process_edge_simplicity_in_3d(), process_vertex_simplicity_in_2d(), and process_vertex_simplicity_in_3d().
m_vertex_tag
MeshAttributeHandle<int64_t> wmtk::components::internal::RegularSpace::m_vertex_tag private
Definition at line 16 of file RegularSpace.hpp.
Referenced by process_edge_simplicity_in_2d(), process_edge_simplicity_in_3d(), process_vertex_simplicity_in_2d(), and process_vertex_simplicity_in_3d().
The documentation for this class was generated from the following files:
components/wmtk_components/regular_space/internal/RegularSpace.hpp
components/wmtk_components/regular_space/internal/RegularSpace.cpp