Wildmeshing Toolkit: wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor > Class Template Reference
wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor > Class Template Reference
#include <MultiMeshSimplexEventVisitor.hpp>
Public Types
using VisitorType = MultiMeshSimplexVisitor< cell_dimension, Functor >
template<typename T >
using GetReturnType_t = typename VisitorType::template GetReturnType_t< T >
Public Member Functions
MultiMeshSimplexEventVisitor (const MultiMeshSimplexVisitor< cell_dimension, Functor > &visitor)
auto node_events () const
const auto & edge_events () const
template<typename NodeFunctor >
void run_on_nodes (NodeFunctor &&node_functor)
template<typename EdgeFunctor >
void run_on_edges (EdgeFunctor &&edge_functor)
template<typename MeshType , typename... OtherArgumentTypes>
const auto & get_cached_return (const MeshType &m, OtherArgumentTypes &&... args) const
Private Attributes
const VisitorType & m_visitor
Detailed Description
template<int64_t cell_dimension, typename Functor>
class wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >
Definition at line 7 of file MultiMeshSimplexEventVisitor.hpp.
Member Typedef Documentation
GetReturnType_t
template<int64_t cell_dimension, typename Functor > template<typename T > using wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::GetReturnType_t = typename VisitorType::template GetReturnType_t<T>
Definition at line 15 of file MultiMeshSimplexEventVisitor.hpp.
VisitorType
template<int64_t cell_dimension, typename Functor > using wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::VisitorType = MultiMeshSimplexVisitor<cell_dimension, Functor>
Definition at line 10 of file MultiMeshSimplexEventVisitor.hpp.
Constructor & Destructor Documentation
MultiMeshSimplexEventVisitor()
template<int64_t cell_dimension, typename Functor > wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::MultiMeshSimplexEventVisitor (const MultiMeshSimplexVisitor< cell_dimension, Functor > & visitor) inline
Definition at line 11 of file MultiMeshSimplexEventVisitor.hpp.
Member Function Documentation
edge_events()
template<int64_t cell_dimension, typename Functor > const auto& wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::edge_events () const inline
Definition at line 18 of file MultiMeshSimplexEventVisitor.hpp.
References wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::edge_events(), and wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::m_visitor.
get_cached_return()
template<int64_t cell_dimension, typename Functor > template<typename MeshType , typename... OtherArgumentTypes> const auto& wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::get_cached_return (const MeshType & m, OtherArgumentTypes &&... args) const inline
Definition at line 26 of file MultiMeshSimplexEventVisitor.hpp.
References wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::cache(), and wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::m_visitor.
node_events()
template<int64_t cell_dimension, typename Functor > auto wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::node_events () const inline
Definition at line 17 of file MultiMeshSimplexEventVisitor.hpp.
References wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::m_visitor, and wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::node_events().
run_on_edges()
template<int64_t cell_dimension, typename Functor > template<typename EdgeFunctor > void wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::run_on_edges (EdgeFunctor && edge_functor)
Definition at line 40 of file MultiMeshSimplexEventVisitor.hpp.
References wmtk::utils::metaprogramming::as_mesh_variant().
Referenced by wmtk::operations::utils::multi_mesh_edge_split().
run_on_nodes()
template<int64_t cell_dimension, typename Functor > template<typename NodeFunctor > void wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::run_on_nodes (NodeFunctor && node_functor)
Definition at line 98 of file MultiMeshSimplexEventVisitor.hpp.
References wmtk::utils::metaprogramming::as_mesh_variant().
Referenced by wmtk::operations::utils::multi_mesh_edge_collapse(), and wmtk::operations::utils::multi_mesh_edge_split().
Member Data Documentation
m_visitor
template<int64_t cell_dimension, typename Functor > const VisitorType& wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::m_visitor private
Definition at line 32 of file MultiMeshSimplexEventVisitor.hpp.
Referenced by wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::edge_events(), wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::get_cached_return(), and wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::node_events().
The documentation for this class was generated from the following file:
src/wmtk/multimesh/MultiMeshSimplexEventVisitor.hpp