Wildmeshing Toolkit: wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo Class Reference
wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo Class Reference
#include <SplitNewAttributeTopoInfo.hpp>
Public Member Functions
SplitNewAttributeTopoInfo (TetMesh &m)
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
std::vector< Tuple > output_rib_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< std::array< Tuple, 2 > > output_split_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< Tuple > input_split_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
Public Member Functions inherited from wmtk::operations::SplitNewAttributeTopoInfo
virtual ~SplitNewAttributeTopoInfo ()=default
Private Member Functions
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
std::vector< Tuple > output_rib_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< std::array< Tuple, 2 > > output_split_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< Tuple > input_split_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
Private Attributes
TetMesh & m_mesh
Additional Inherited Members
Public Types inherited from wmtk::operations::SplitNewAttributeTopoInfo
using ReturnData = wmtk::multimesh::operations::SplitReturnData
using ReturnVariant = ReturnData::ReturnVariant
Detailed Description
Definition at line 7 of file SplitNewAttributeTopoInfo.hpp.
Constructor & Destructor Documentation
SplitNewAttributeTopoInfo()
wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::SplitNewAttributeTopoInfo (TetMesh & m)
Definition at line 4 of file SplitNewAttributeTopoInfo.cpp.
Member Function Documentation
input_ear_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::input_ear_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 97 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::operations::tet_mesh::EdgeOperationData::ear_edges(), wmtk::operations::tet_mesh::EdgeOperationData::ear_faces(), wmtk::get_primitive_type_id(), wmtk::operations::tet_mesh::EdgeOperationData::input_endpoints(), m_mesh, and wmtk::Mesh::parent_scope().
input_ear_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::input_ear_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 18 of file SplitNewAttributeTopoInfo.cpp.
input_split_simplices() [1/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::input_split_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 75 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::tet_mesh::EdgeOperationData::input_faces(), wmtk::operations::tet_mesh::EdgeOperationData::input_tets(), and m_mesh.
input_split_simplices() [2/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::input_split_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 43 of file SplitNewAttributeTopoInfo.cpp.
output_rib_simplices() [1/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::output_rib_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 119 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), m_mesh, wmtk::operations::tet_mesh::EdgeOperationData::split_new_rib_edges(), and wmtk::operations::tet_mesh::EdgeOperationData::split_new_rib_faces().
output_rib_simplices() [2/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::output_rib_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 27 of file SplitNewAttributeTopoInfo.cpp.
output_split_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::output_split_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 52 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), m_mesh, wmtk::operations::tet_mesh::EdgeOperationData::split_output_edges(), wmtk::operations::tet_mesh::EdgeOperationData::split_output_faces(), and wmtk::operations::tet_mesh::EdgeOperationData::split_output_tets().
output_split_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::output_split_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 34 of file SplitNewAttributeTopoInfo.cpp.
Member Data Documentation
m_mesh
TetMesh& wmtk::operations::tet_mesh::SplitNewAttributeTopoInfo::m_mesh private
Definition at line 71 of file SplitNewAttributeTopoInfo.hpp.
Referenced by input_ear_simplices(), input_split_simplices(), output_rib_simplices(), and output_split_simplices().
The documentation for this class was generated from the following files:
src/wmtk/operations/tet_mesh/SplitNewAttributeTopoInfo.hpp
src/wmtk/operations/tet_mesh/SplitNewAttributeTopoInfo.cpp