Wildmeshing Toolkit: wmtk::MeshWriter Class Reference
wmtk::MeshWriter Class Reference abstract
#include <MeshWriter.hpp>
Public Member Functions
virtual ~MeshWriter ()
virtual bool write (const int dim)=0
virtual void write_top_simplex_type (const PrimitiveType type)=0
virtual void write_absolute_id (const std::vector< int64_t > &id)=0
virtual void write_capacities (const std::vector< int64_t > &capacities)=0
virtual void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< char > &val, const char default_val)=0
virtual void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< int64_t > &val, const int64_t default_val)=0
virtual void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< double > &val, const double default_val)=0
virtual void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< Rational > &val, const Rational &default_val)=0
Protected Attributes
int64_t m_mm_level = 0
Detailed Description
Definition at line 10 of file MeshWriter.hpp.
Constructor & Destructor Documentation
~MeshWriter()
virtual wmtk::MeshWriter::~MeshWriter () inline virtual
Definition at line 13 of file MeshWriter.hpp.
Member Function Documentation
write() [1/5]
virtual bool wmtk::MeshWriter::write (const int dim) pure virtual
Implemented in wmtk::HDF5Writer, wmtk::utils::EigenMatrixWriter, and wmtk::io::ParaviewWriter.
Referenced by wmtk::attribute::Attribute< T >::serialize(), and wmtk::attribute::AttributeManager::serialize().
write() [2/5]
virtual void wmtk::MeshWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< char > & val, const char default_val) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
write() [3/5]
virtual void wmtk::MeshWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< double > & val, const double default_val) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
write() [4/5]
virtual void wmtk::MeshWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< int64_t > & val, const int64_t default_val) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
write() [5/5]
virtual void wmtk::MeshWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< Rational > & val, const Rational & default_val) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
write_absolute_id()
virtual void wmtk::MeshWriter::write_absolute_id (const std::vector< int64_t > & id) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
Referenced by wmtk::Mesh::serialize().
write_capacities()
virtual void wmtk::MeshWriter::write_capacities (const std::vector< int64_t > & capacities) pure virtual
Implemented in wmtk::utils::EigenMatrixWriter, wmtk::io::ParaviewWriter, and wmtk::HDF5Writer.
Referenced by wmtk::attribute::AttributeManager::serialize().
write_top_simplex_type()
virtual void wmtk::MeshWriter::write_top_simplex_type (const PrimitiveType type) pure virtual
Implemented in wmtk::io::ParaviewWriter, wmtk::utils::EigenMatrixWriter, and wmtk::HDF5Writer.
Referenced by wmtk::Mesh::serialize().
Member Data Documentation
m_mm_level
int64_t wmtk::MeshWriter::m_mm_level = 0 protected
Definition at line 51 of file MeshWriter.hpp.
Referenced by wmtk::HDF5Writer::write_absolute_id(), wmtk::io::ParaviewWriter::write_absolute_id(), wmtk::utils::EigenMatrixWriter::write_absolute_id(), and wmtk::utils::EigenMatrixWriter::write_internal().
The documentation for this class was generated from the following file:
src/wmtk/io/MeshWriter.hpp