Wildmeshing Toolkit: wmtk::function::PerSimplexFunction Class Reference
wmtk::function::PerSimplexFunction Class Reference abstract
#include <PerSimplexFunction.hpp>
Public Member Functions
PerSimplexFunction (const Mesh &mesh, const PrimitiveType primitive_type, const attribute::MeshAttributeHandle< double > &variable_attribute_handle)
virtual ~PerSimplexFunction ()
virtual double get_value (const simplex::Simplex &domain_simplex) const =0
This function is defined over a simplex (normally a triangle or tetrahedron).
virtual Eigen::VectorXd get_gradient (const Simplex &domain_simplex, const Simplex &variable_simplex) const
virtual Eigen::MatrixXd get_hessian (const Simplex &domain_simplex, const Simplex &variable_simplex) const
const Mesh & mesh () const
const MeshAttributeHandle< double > & attribute_handle () const
long embedded_dimension () const
Protected Attributes
const PrimitiveType m_primitive_type
Private Attributes
MeshAttributeHandle< double > m_handle
const Mesh & m_mesh
Detailed Description
Definition at line 11 of file PerSimplexFunction.hpp.
Constructor & Destructor Documentation
PerSimplexFunction()
wmtk::function::PerSimplexFunction::PerSimplexFunction (const Mesh & mesh, const PrimitiveType primitive_type, const attribute::MeshAttributeHandle< double > & variable_attribute_handle)
Definition at line 6 of file PerSimplexFunction.cpp.
~PerSimplexFunction()
virtual wmtk::function::PerSimplexFunction::~PerSimplexFunction () inline virtual
Definition at line 18 of file PerSimplexFunction.hpp.
Member Function Documentation
attribute_handle()
const MeshAttributeHandle<double>& wmtk::function::PerSimplexFunction::attribute_handle () const inline
Definition at line 42 of file PerSimplexFunction.hpp.
References wmtk::attribute::MeshAttributeHandle< T >::is_valid(), and m_handle.
Referenced by embedded_dimension(), wmtk::function::PerSimplexAutodiffFunction::get_coordinates(), and wmtk::function::AMIPS::get_raw_coordinates().
embedded_dimension()
long wmtk::function::PerSimplexFunction::embedded_dimension () const
Definition at line 16 of file PerSimplexFunction.cpp.
References attribute_handle(), wmtk::Mesh::get_attribute_dimension(), and mesh().
Referenced by wmtk::function::TriangleAMIPS::eval(), wmtk::function::PerSimplexAutodiffFunction::get_gradient(), wmtk::function::LocalNeighborsSumFunction::get_gradient(), wmtk::function::PerSimplexAutodiffFunction::get_hessian(), wmtk::function::LocalNeighborsSumFunction::get_hessian(), wmtk::function::AMIPS::get_raw_coordinates(), wmtk::function::PerSimplexAutodiffFunction::get_value(), and wmtk::function::LocalNeighborsSumFunction::get_value().
get_gradient()
virtual Eigen::VectorXd wmtk::function::PerSimplexFunction::get_gradient (const Simplex & domain_simplex, const Simplex & variable_simplex) const inline virtual
Reimplemented in wmtk::function::PerSimplexAutodiffFunction, and wmtk::function::AMIPS.
Definition at line 28 of file PerSimplexFunction.hpp.
Referenced by wmtk::function::LocalNeighborsSumFunction::get_gradient().
get_hessian()
virtual Eigen::MatrixXd wmtk::function::PerSimplexFunction::get_hessian (const Simplex & domain_simplex, const Simplex & variable_simplex) const inline virtual
Reimplemented in wmtk::function::PerSimplexAutodiffFunction, and wmtk::function::AMIPS.
Definition at line 34 of file PerSimplexFunction.hpp.
Referenced by wmtk::function::LocalNeighborsSumFunction::get_hessian().
get_value()
virtual double wmtk::function::PerSimplexFunction::get_value (const simplex::Simplex & domain_simplex) const pure virtual
This function is defined over a simplex (normally a triangle or tetrahedron).
And the domain of the function is represented by the input argument domain_simplex.
Parameters
domain_simplex The domain that the function is defined over.
Returns
double The numerical value of the function at the input domain.
Implemented in wmtk::function::AMIPS, wmtk::function::PerSimplexAutodiffFunction, and wmtk::function::EdgeValenceEnergy.
Referenced by wmtk::function::LocalNeighborsSumFunction::get_value().
mesh()
const Mesh& wmtk::function::PerSimplexFunction::mesh () const inline
Definition at line 41 of file PerSimplexFunction.hpp.
References m_mesh.
Referenced by embedded_dimension(), wmtk::function::PerSimplexAutodiffFunction::get_coordinates(), wmtk::function::LocalNeighborsSumFunction::get_gradient(), wmtk::function::LocalNeighborsSumFunction::get_hessian(), wmtk::function::AMIPS::get_raw_coordinates(), wmtk::function::LocalNeighborsSumFunction::get_value(), and wmtk::function::EdgeValenceEnergy::tri_mesh().
Member Data Documentation
m_handle
MeshAttributeHandle<double> wmtk::function::PerSimplexFunction::m_handle private
Definition at line 51 of file PerSimplexFunction.hpp.
Referenced by attribute_handle().
m_mesh
const Mesh& wmtk::function::PerSimplexFunction::m_mesh private
Definition at line 52 of file PerSimplexFunction.hpp.
Referenced by mesh().
m_primitive_type
const PrimitiveType wmtk::function::PerSimplexFunction::m_primitive_type protected
Definition at line 55 of file PerSimplexFunction.hpp.
Referenced by wmtk::function::PerSimplexAutodiffFunction::get_coordinates(), and wmtk::function::AMIPS::get_raw_coordinates().
The documentation for this class was generated from the following files:
src/wmtk/function/PerSimplexFunction.hpp
src/wmtk/function/PerSimplexFunction.cpp