Wildmeshing Toolkit: wmtk::utils::Hashable Class Reference
wmtk::utils::Hashable Class Reference
#include <Hashable.hpp>
Public Member Functions
Hashable ()
Hashable (const Hashable &)
Hashable (Hashable &&)
Hashable & operator= (const Hashable &)
Hashable & operator= (Hashable &&)
virtual ~Hashable ()
virtual std::size_t hash () const
virtual std::map< std::string, size_t > child_hashes () const
Detailed Description
Definition at line 7 of file Hashable.hpp.
Constructor & Destructor Documentation
Hashable() [1/3]
wmtk::utils::Hashable::Hashable () default
Hashable() [2/3]
wmtk::utils::Hashable::Hashable (const Hashable &) default
Hashable() [3/3]
wmtk::utils::Hashable::Hashable (Hashable &&) default
~Hashable()
wmtk::utils::Hashable::~Hashable () virtual default
Member Function Documentation
child_hashes()
std::map< std::string, size_t > wmtk::utils::Hashable::child_hashes () const virtual
Reimplemented in wmtk::utils::MerkleTreeInteriorNode, wmtk::multimesh::MultiMeshManager, wmtk::Mesh, wmtk::attribute::MeshAttributes< T >, wmtk::attribute::AttributeManager, and wmtk::attribute::Attribute< T >.
Definition at line 32 of file Hashable.cpp.
Referenced by hash(), wmtk::utils::merkle_tree(), and wmtk::utils::merkle_tree_diff().
hash()
std::size_t wmtk::utils::Hashable::hash () const virtual
Definition at line 15 of file Hashable.cpp.
References child_hashes().
Referenced by wmtk::utils::merkle_tree_diff().
operator=() [1/2]
Hashable & wmtk::utils::Hashable::operator= (const Hashable &) default
operator=() [2/2]
Hashable & wmtk::utils::Hashable::operator= (Hashable &&) default
The documentation for this class was generated from the following files:
src/wmtk/utils/Hashable.hpp
src/wmtk/utils/Hashable.cpp