Wildmeshing Toolkit: wmtk::autogen::SimplexDart Class Reference
wmtk::autogen::SimplexDart Class Reference
#include <SimplexDart.hpp>
Public Types
using binary_op_type = int8_t(*)(int8_t, int8_t)
using unary_op_type = int8_t(*)(int8_t)
using primitive_to_index_type = int8_t(*)(PrimitiveType)
using nullary_op_type = int8_t(*)()
Public Member Functions
SimplexDart (wmtk::PrimitiveType simplex_type)
int8_t product (int8_t a, int8_t b) const
int8_t inverse (int8_t a) const
int8_t primitive_as_index (wmtk::PrimitiveType pt) const
int8_t identity () const
int8_t opposite () const
Dart act (const Dart &d, int8_t action) const
wmtk::Tuple tuple_from_valid_index (int64_t gid, int8_t valid_index) const
wmtk::Tuple update_tuple_from_valid_index (const Tuple &t, int8_t valid_index) const
wmtk::Tuple tuple_from_dart (const Dart &dart) const
Dart dart_from_tuple (const wmtk::Tuple &t) const
int8_t valid_index_from_tuple (const wmtk::Tuple &t) const
int8_t simplex_index (const int8_t valid_index, PrimitiveType simplex_type) const
int8_t simplex_index (const Dart &dart, PrimitiveType simplex_type) const
size_t size () const
VectorX< int8_t >::ConstMapType valid_indices () const
int8_t convert (int8_t valid_index, const SimplexDart &target) const
wmtk::PrimitiveType simplex_type () const
Static Public Member Functions
static const SimplexDart & get_singleton (wmtk::PrimitiveType simplex_type)
Private Attributes
const wmtk::PrimitiveType m_simplex_type
const binary_op_type m_product
const unary_op_type m_inverse
const primitive_to_index_type m_primitive_to_index
const nullary_op_type m_identity
const nullary_op_type m_opposite
Detailed Description
Definition at line 10 of file SimplexDart.hpp.
Member Typedef Documentation
binary_op_type
using wmtk::autogen::SimplexDart::binary_op_type = int8_t (*)(int8_t, int8_t)
Definition at line 45 of file SimplexDart.hpp.
nullary_op_type
using wmtk::autogen::SimplexDart::nullary_op_type = int8_t (*)()
Definition at line 48 of file SimplexDart.hpp.
primitive_to_index_type
using wmtk::autogen::SimplexDart::primitive_to_index_type = int8_t (*)(PrimitiveType)
Definition at line 47 of file SimplexDart.hpp.
unary_op_type
using wmtk::autogen::SimplexDart::unary_op_type = int8_t (*)(int8_t)
Definition at line 46 of file SimplexDart.hpp.
Constructor & Destructor Documentation
SimplexDart()
wmtk::autogen::SimplexDart::SimplexDart (wmtk::PrimitiveType simplex_type)
Definition at line 75 of file SimplexDart.cpp.
Referenced by get_singleton().
Member Function Documentation
act()
Dart wmtk::autogen::SimplexDart::act (const Dart & d, int8_t action) const
Definition at line 101 of file SimplexDart.cpp.
References wmtk::autogen::Dart::global_id(), wmtk::autogen::Dart::local_orientation(), and product().
convert()
int8_t wmtk::autogen::SimplexDart::convert (int8_t valid_index, const SimplexDart & target) const
Definition at line 134 of file SimplexDart.cpp.
References wmtk::autogen::subgroup::convert(), identity(), m_simplex_type, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::transport_tuple().
dart_from_tuple()
Dart wmtk::autogen::SimplexDart::dart_from_tuple (const wmtk::Tuple & t) const
Definition at line 149 of file SimplexDart.cpp.
References wmtk::utils::TupleInspector::global_cid(), m_simplex_type, and wmtk::autogen::valid_index_from_tuple().
Referenced by wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives().
get_singleton()
const SimplexDart & wmtk::autogen::SimplexDart::get_singleton (wmtk::PrimitiveType simplex_type) static
Definition at line 83 of file SimplexDart.cpp.
References wmtk::Edge, wmtk::get_primitive_type_id(), simplex_type(), SimplexDart(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::operations::internal::SplitAlternateFacetData::add_facet(), wmtk::operations::internal::SplitAlternateFacetOptionData::boundary_indices(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action(), and wmtk::operations::internal::SplitAlternateFacetOptionData::new_gid().
identity()
int8_t wmtk::autogen::SimplexDart::identity () const
Definition at line 110 of file SimplexDart.cpp.
References m_identity.
Referenced by convert().
inverse()
int8_t wmtk::autogen::SimplexDart::inverse (int8_t a) const
Definition at line 97 of file SimplexDart.cpp.
References m_inverse.
Referenced by wmtk::autogen::find_local_dart_action(), and wmtk::autogen::utils::relative_face_index().
opposite()
int8_t wmtk::autogen::SimplexDart::opposite () const
Definition at line 114 of file SimplexDart.cpp.
References m_opposite.
primitive_as_index()
int8_t wmtk::autogen::SimplexDart::primitive_as_index (wmtk::PrimitiveType pt) const
Definition at line 106 of file SimplexDart.cpp.
References m_primitive_to_index.
product()
int8_t wmtk::autogen::SimplexDart::product (int8_t a, int8_t b) const
Definition at line 93 of file SimplexDart.cpp.
References m_product.
Referenced by act(), wmtk::autogen::find_local_dart_action(), wmtk::autogen::local_dart_action(), wmtk::autogen::utils::relative_face_index(), and wmtk::multimesh::utils::transport_tuple().
simplex_index() [1/2]
int8_t wmtk::autogen::SimplexDart::simplex_index (const Dart & dart, PrimitiveType simplex_type) const
Definition at line 156 of file SimplexDart.cpp.
References wmtk::autogen::Dart::local_orientation(), simplex_index(), and simplex_type().
simplex_index() [2/2]
int8_t wmtk::autogen::SimplexDart::simplex_index (const int8_t valid_index, PrimitiveType simplex_type) const
Definition at line 160 of file SimplexDart.cpp.
References m_simplex_type, wmtk::autogen::simplex_index_from_valid_index(), and simplex_type().
Referenced by wmtk::autogen::utils::relative_face_index(), and simplex_index().
simplex_type()
wmtk::PrimitiveType wmtk::autogen::SimplexDart::simplex_type () const inline
Definition at line 58 of file SimplexDart.hpp.
References m_simplex_type.
Referenced by get_singleton(), and simplex_index().
size()
size_t wmtk::autogen::SimplexDart::size () const
tuple_from_dart()
wmtk::Tuple wmtk::autogen::SimplexDart::tuple_from_dart (const Dart & dart) const
Definition at line 145 of file SimplexDart.cpp.
References wmtk::autogen::Dart::global_id(), wmtk::autogen::Dart::local_orientation(), and tuple_from_valid_index().
tuple_from_valid_index()
wmtk::Tuple wmtk::autogen::SimplexDart::tuple_from_valid_index (int64_t gid, int8_t valid_index) const
Definition at line 118 of file SimplexDart.cpp.
References m_simplex_type, and wmtk::autogen::tuple_from_valid_index().
Referenced by tuple_from_dart().
update_tuple_from_valid_index()
wmtk::Tuple wmtk::autogen::SimplexDart::update_tuple_from_valid_index (const Tuple & t, int8_t valid_index) const
Definition at line 122 of file SimplexDart.cpp.
References wmtk::utils::TupleInspector::global_cid(), m_simplex_type, and wmtk::autogen::tuple_from_valid_index().
Referenced by wmtk::multimesh::utils::transport_tuple().
valid_index_from_tuple()
int8_t wmtk::autogen::SimplexDart::valid_index_from_tuple (const wmtk::Tuple & t) const
Definition at line 129 of file SimplexDart.cpp.
References m_simplex_type, and wmtk::autogen::valid_index_from_tuple().
Referenced by wmtk::multimesh::utils::find_local_dart_action(), and wmtk::multimesh::utils::transport_tuple().
valid_indices()
VectorX<int8_t>::ConstMapType wmtk::autogen::SimplexDart::valid_indices () const
Member Data Documentation
m_identity
const nullary_op_type wmtk::autogen::SimplexDart::m_identity private
Definition at line 65 of file SimplexDart.hpp.
Referenced by identity().
m_inverse
const unary_op_type wmtk::autogen::SimplexDart::m_inverse private
Definition at line 63 of file SimplexDart.hpp.
Referenced by inverse().
m_opposite
const nullary_op_type wmtk::autogen::SimplexDart::m_opposite private
Definition at line 66 of file SimplexDart.hpp.
Referenced by opposite().
m_primitive_to_index
const primitive_to_index_type wmtk::autogen::SimplexDart::m_primitive_to_index private
Definition at line 64 of file SimplexDart.hpp.
Referenced by primitive_as_index().
m_product
const binary_op_type wmtk::autogen::SimplexDart::m_product private
Definition at line 62 of file SimplexDart.hpp.
Referenced by product().
m_simplex_type
const wmtk::PrimitiveType wmtk::autogen::SimplexDart::m_simplex_type private
Definition at line 61 of file SimplexDart.hpp.
Referenced by convert(), dart_from_tuple(), simplex_index(), simplex_type(), tuple_from_valid_index(), update_tuple_from_valid_index(), and valid_index_from_tuple().
The documentation for this class was generated from the following files:
src/wmtk/autogen/SimplexDart.hpp
src/wmtk/autogen/SimplexDart.cpp