Wildmeshing Toolkit: wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor Class Reference
wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor Class Reference
#include <UpdateEdgeOperationMultiMeshMapFunctor.hpp>
Public Member Functions
void operator() (EdgeMesh &, const simplex::Simplex &, const edge_mesh::EdgeOperationData &parent_tmoe, EdgeMesh &, const simplex::Simplex &, const edge_mesh::EdgeOperationData &) const
void operator() (TriMesh &, const simplex::Simplex &, const tri_mesh::EdgeOperationData &, EdgeMesh &, const simplex::Simplex &, const edge_mesh::EdgeOperationData &) const
void operator() (TriMesh &, const simplex::Simplex &, const tri_mesh::EdgeOperationData &, TriMesh &, const simplex::Simplex &, const tri_mesh::EdgeOperationData &) const
void operator() (TetMesh &, const simplex::Simplex &, const tet_mesh::EdgeOperationData &, EdgeMesh &, const simplex::Simplex &, const edge_mesh::EdgeOperationData &) const
void operator() (TetMesh &, const simplex::Simplex &, const tet_mesh::EdgeOperationData &, TriMesh &, const simplex::Simplex &, const tri_mesh::EdgeOperationData &) const
void operator() (TetMesh &, const simplex::Simplex &, const tet_mesh::EdgeOperationData &, TetMesh &, const simplex::Simplex &, const tet_mesh::EdgeOperationData &) const
void operator() (EdgeMesh &, const simplex::Simplex &, const edge_mesh::EdgeOperationData &)
void operator() (TriMesh &, const simplex::Simplex &, const tri_mesh::EdgeOperationData &)
void operator() (TetMesh &, const simplex::Simplex &, const tet_mesh::EdgeOperationData &)
Private Member Functions
int64_t parent_global_cid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > &parent_to_child, int64_t parent_gid) const
int64_t child_global_cid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > &parent_to_child, int64_t parent_gid) const
void update_all_hashes (Mesh &m, const std::vector< std::vector< std::tuple< int64_t, std::vector< Tuple >>>> &simplices_to_update, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> &split_cell_maps={}) const
void update_ear_replacement (TriMesh &m, const tri_mesh::EdgeOperationData &fmoe) const
int64_t parent_local_fid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > &parent_to_child, int64_t parent_gid) const
void update_ear_replacement (TetMesh &m, const tet_mesh::EdgeOperationData &tmoe) const
Detailed Description
Definition at line 36 of file UpdateEdgeOperationMultiMeshMapFunctor.hpp.
Member Function Documentation
child_global_cid()
int64_t wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::child_global_cid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > & parent_to_child, int64_t parent_gid) const private
Definition at line 817 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::multimesh::MultiMeshManager::child_global_cid().
operator()() [1/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (EdgeMesh & parent_mesh, const simplex::Simplex & , const edge_mesh::EdgeOperationData & parent_emoe)
Definition at line 757 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::Mesh::get_child_meshes(), and wmtk::logger().
operator()() [2/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (EdgeMesh & , const simplex::Simplex & , const edge_mesh::EdgeOperationData & parent_tmoe, EdgeMesh & , const simplex::Simplex & , const edge_mesh::EdgeOperationData &) const
Definition at line 334 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
operator()() [3/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TetMesh & parent_mesh, const simplex::Simplex & , const tet_mesh::EdgeOperationData & parent_tmoe)
Definition at line 796 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::operations::EdgeOperationData::global_ids_to_potential_tuples, wmtk::operations::tet_mesh::EdgeOperationData::incident_tet_datas(), wmtk::operations::tet_mesh::EdgeOperationData::is_collapse, update_all_hashes(), and update_ear_replacement().
operator()() [4/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TetMesh & parent_mesh, const simplex::Simplex & , const tet_mesh::EdgeOperationData & parent_tmoe, EdgeMesh & child_mesh, const simplex::Simplex & , const edge_mesh::EdgeOperationData & child_emoe) const
Definition at line 524 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::operations::tet_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_tet_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_vids(), wmtk::EdgeMesh::is_valid(), wmtk::TetMesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::operations::edge_mesh::EdgeOperationData::m_operating_edge_id, wmtk::operations::edge_mesh::EdgeOperationData::m_spine_vids, wmtk::operations::edge_mesh::EdgeOperationData::m_split_e, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, wmtk::operations::tet_mesh::EdgeOperationData::new_spine_eids(), parent_global_cid(), parent_local_fid(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::EdgeMesh::tuple_from_global_ids(), and wmtk::TetMesh::tuple_from_global_ids().
operator()() [5/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TetMesh & parent_mesh, const simplex::Simplex & , const tet_mesh::EdgeOperationData & parent_tmoe, TetMesh & child_mesh, const simplex::Simplex & , const tet_mesh::EdgeOperationData & child_tmoe) const
Definition at line 682 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::operations::tet_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_tet_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_vids(), wmtk::TetMesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, parent_global_cid(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), and wmtk::TetMesh::tuple_from_global_ids().
operator()() [6/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TetMesh & parent_mesh, const simplex::Simplex & , const tet_mesh::EdgeOperationData & parent_tmoe, TriMesh & child_mesh, const simplex::Simplex & , const tri_mesh::EdgeOperationData & child_fmoe) const
Definition at line 597 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::operations::tet_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tri_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_tet_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_vids(), wmtk::operations::tri_mesh::EdgeOperationData::incident_vids(), wmtk::TetMesh::is_valid(), wmtk::TriMesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, parent_global_cid(), parent_local_fid(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::TriMesh::tuple_from_global_ids(), and wmtk::TetMesh::tuple_from_global_ids().
operator()() [7/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TriMesh & parent_mesh, const simplex::Simplex & , const tri_mesh::EdgeOperationData & parent_fmoe)
Definition at line 773 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::operations::EdgeOperationData::global_ids_to_potential_tuples, wmtk::operations::tri_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tri_mesh::EdgeOperationData::is_collapse, update_all_hashes(), and update_ear_replacement().
operator()() [8/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TriMesh & parent_mesh, const simplex::Simplex & , const tri_mesh::EdgeOperationData & parent_tmoe, EdgeMesh & child_mesh, const simplex::Simplex & , const edge_mesh::EdgeOperationData & child_emoe) const
Definition at line 346 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::operations::tri_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tri_mesh::EdgeOperationData::incident_vids(), wmtk::EdgeMesh::is_valid(), wmtk::TriMesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::operations::edge_mesh::EdgeOperationData::m_spine_vids, wmtk::operations::edge_mesh::EdgeOperationData::m_split_e, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, wmtk::operations::tri_mesh::EdgeOperationData::split_spine_eids, wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::EdgeMesh::tuple_from_global_ids(), and wmtk::TriMesh::tuple_from_global_ids().
operator()() [9/9]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator() (TriMesh & parent_mesh, const simplex::Simplex & , const tri_mesh::EdgeOperationData & parent_tmoe, TriMesh & child_mesh, const simplex::Simplex & , const tri_mesh::EdgeOperationData & child_tmoe) const
Definition at line 395 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::operations::tri_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tri_mesh::EdgeOperationData::incident_vids(), wmtk::TriMesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::map_to_parent_handle, parent_global_cid(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), and wmtk::TriMesh::tuple_from_global_ids().
parent_global_cid()
int64_t wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_global_cid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > & parent_to_child, int64_t parent_gid) const private
Definition at line 823 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::multimesh::MultiMeshManager::parent_global_cid().
Referenced by operator()().
parent_local_fid()
int64_t wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_local_fid (const attribute::Accessor< int64_t, Mesh, Eigen::Dynamic > & parent_to_child, int64_t parent_gid) const private
Definition at line 830 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::multimesh::MultiMeshManager::parent_local_fid().
Referenced by operator()().
update_all_hashes()
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_all_hashes (Mesh & m, const std::vector< std::vector< std::tuple< int64_t, std::vector< Tuple >>>> & simplices_to_update, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 >>> & split_cell_maps = {}) const private
Definition at line 23 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::Mesh::m_multi_mesh_manager, wmtk::PE, PF, PT, wmtk::PV, and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
Referenced by operator()().
update_ear_replacement() [1/2]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_ear_replacement (TetMesh & m, const tet_mesh::EdgeOperationData & tmoe) const private
Definition at line 129 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::multimesh::MultiMeshManager::child_id(), wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::Edge, wmtk::Mesh::get_child_meshes(), wmtk::Mesh::get_index_access(), wmtk::TetMesh::id_edge(), wmtk::TetMesh::id_vertex(), wmtk::operations::tet_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tet_mesh::EdgeOperationData::incident_tet_datas(), wmtk::Tuple::is_null(), wmtk::Mesh::m_multi_mesh_manager, wmtk::Mesh::parent_scope(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::Triangle, wmtk::TetMesh::tuple_from_global_ids(), and wmtk::multimesh::utils::vectors_to_tuples().
update_ear_replacement() [2/2]
void wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_ear_replacement (TriMesh & m, const tri_mesh::EdgeOperationData & fmoe) const private
Definition at line 38 of file UpdateEdgeOperationMultiMeshMapFunctor.cpp.
References wmtk::MeshCRTP< Derived >::create_accessor(), wmtk::Edge, wmtk::Mesh::get_child_meshes(), wmtk::Mesh::get_index_access(), wmtk::TriMesh::id_vertex(), wmtk::operations::tri_mesh::EdgeOperationData::incident_face_datas(), wmtk::operations::tri_mesh::EdgeOperationData::incident_vids(), wmtk::Tuple::is_null(), wmtk::Mesh::m_multi_mesh_manager, wmtk::Mesh::parent_scope(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::TriMesh::tuple_from_global_ids(), and wmtk::multimesh::utils::vectors_to_tuples().
Referenced by operator()().
The documentation for this class was generated from the following files:
src/wmtk/operations/utils/UpdateEdgeOperationMultiMeshMapFunctor.hpp
src/wmtk/operations/utils/UpdateEdgeOperationMultiMeshMapFunctor.cpp