Wildmeshing Toolkit: wmtk::operations::internal::SplitAlternateFacetData Class Reference
wmtk::operations::internal::SplitAlternateFacetData Class Reference
Given a global id returns global ids.
#include <SplitAlternateFacetData.hpp>
Public Types
using Data = SplitAlternateFacetOptionData
using AltData = std::vector< Data >
Public Member Functions
const Data & add_facet (const wmtk::Mesh &mesh, const wmtk::Tuple &edge_tuple, const std::array< int64_t, 2 > &new_facet_indices)
const Data & add_facet (wmtk::Mesh &mesh, const wmtk::Tuple &edge_tuple)
void sort ()
const std::array< int64_t, 2 > & get_alternative_facets (const int64_t &input_facet) const
AltData::const_iterator get_alternative_facets_it (const int64_t &input_facet) const
Tuple get_alternative (const PrimitiveType mesh_pt, const Tuple &t, const PrimitiveType simplex_dimension) const
Public Attributes
AltData m_facet_maps
Detailed Description
Given a global id returns global ids.
Definition at line 14 of file SplitAlternateFacetData.hpp.
Member Typedef Documentation
AltData
using wmtk::operations::internal::SplitAlternateFacetData::AltData = std::vector<Data>
Definition at line 18 of file SplitAlternateFacetData.hpp.
Data
using wmtk::operations::internal::SplitAlternateFacetData::Data = SplitAlternateFacetOptionData
Definition at line 17 of file SplitAlternateFacetData.hpp.
Member Function Documentation
add_facet() [1/2]
auto wmtk::operations::internal::SplitAlternateFacetData::add_facet (const wmtk::Mesh & mesh, const wmtk::Tuple & edge_tuple, const std::array< int64_t, 2 > & new_facet_indices)
Definition at line 52 of file SplitAlternateFacetData.cpp.
References wmtk::autogen::SimplexDart::get_singleton().
add_facet() [2/2]
auto wmtk::operations::internal::SplitAlternateFacetData::add_facet (wmtk::Mesh & mesh, const wmtk::Tuple & edge_tuple)
Definition at line 43 of file SplitAlternateFacetData.cpp.
References wmtk::operations::EdgeOperationData::request_simplex_indices().
get_alternative()
auto wmtk::operations::internal::SplitAlternateFacetData::get_alternative (const PrimitiveType mesh_pt, const Tuple & t, const PrimitiveType simplex_dimension) const
Definition at line 67 of file SplitAlternateFacetData.cpp.
References wmtk::autogen::SimplexDart::get_singleton(), wmtk::utils::TupleInspector::global_cid(), wmtk::utils::TupleInspector::local_eid(), wmtk::utils::TupleInspector::local_fid(), wmtk::utils::TupleInspector::local_vid(), and wmtk::Vertex.
get_alternative_facets()
auto wmtk::operations::internal::SplitAlternateFacetData::get_alternative_facets (const int64_t & input_facet) const
Definition at line 60 of file SplitAlternateFacetData.cpp.
get_alternative_facets_it()
auto wmtk::operations::internal::SplitAlternateFacetData::get_alternative_facets_it (const int64_t & input_facet) const
Definition at line 29 of file SplitAlternateFacetData.cpp.
sort()
void wmtk::operations::internal::SplitAlternateFacetData::sort ()
Definition at line 23 of file SplitAlternateFacetData.cpp.
References m_facet_maps.
Member Data Documentation
m_facet_maps
AltData wmtk::operations::internal::SplitAlternateFacetData::m_facet_maps
Definition at line 19 of file SplitAlternateFacetData.hpp.
Referenced by sort().
The documentation for this class was generated from the following files:
src/wmtk/operations/internal/SplitAlternateFacetData.hpp
src/wmtk/operations/internal/SplitAlternateFacetData.cpp