Wildmeshing Toolkit: wmtk::io::CachedMultiMesh Class Reference
wmtk::io::CachedMultiMesh Class Reference
#include <CachedMultiMesh.hpp>
Public Member Functions
CachedMultiMesh (const std::string &name, std::map< std::string, std::vector< int64_t >> multimesh_names, std::shared_ptr< Mesh > root=nullptr)
~CachedMultiMesh ()
void load (const std::filesystem::path &path)
void load (std::shared_ptr< Mesh > root)
void flush ()
std::shared_ptr< Mesh > get_from_path (const std::string &name)
std::shared_ptr< Mesh > get (const std::string &name)
std::shared_ptr< Mesh > get_root ()
const std::vector< int64_t > & get_id (const std::string &name) const
const std::vector< int64_t > & get_id_from_path (const std::string &name) const
const std::map< std::string, std::vector< int64_t > > & get_multimesh_names () const
CachedMultiMesh (CachedMultiMesh &&)
CachedMultiMesh & operator= (CachedMultiMesh &&)
Private Attributes
std::string m_name
std::shared_ptr< Mesh > m_root
std::map< std::string, std::vector< int64_t > > m_multimesh_names
Detailed Description
Definition at line 13 of file CachedMultiMesh.hpp.
Constructor & Destructor Documentation
CachedMultiMesh() [1/2]
wmtk::io::CachedMultiMesh::CachedMultiMesh (const std::string & name, std::map< std::string, std::vector< int64_t >> multimesh_names, std::shared_ptr< Mesh > root = nullptr)
Definition at line 12 of file CachedMultiMesh.cpp.
~CachedMultiMesh()
wmtk::io::CachedMultiMesh::~CachedMultiMesh () default
CachedMultiMesh() [2/2]
wmtk::io::CachedMultiMesh::CachedMultiMesh (CachedMultiMesh &&) default
Member Function Documentation
flush()
void wmtk::io::CachedMultiMesh::flush ()
Definition at line 32 of file CachedMultiMesh.cpp.
References m_root.
get()
std::shared_ptr< Mesh > wmtk::io::CachedMultiMesh::get (const std::string & name)
Definition at line 51 of file CachedMultiMesh.cpp.
References wmtk::logger(), m_multimesh_names, and m_root.
Referenced by get_from_path().
get_from_path()
std::shared_ptr< Mesh > wmtk::io::CachedMultiMesh::get_from_path (const std::string & name)
Definition at line 37 of file CachedMultiMesh.cpp.
References get(), get_root(), and m_name.
get_id()
const std::vector< int64_t > & wmtk::io::CachedMultiMesh::get_id (const std::string & name) const
Definition at line 67 of file CachedMultiMesh.cpp.
References m_multimesh_names, and m_name.
Referenced by get_id_from_path().
get_id_from_path()
const std::vector< int64_t > & wmtk::io::CachedMultiMesh::get_id_from_path (const std::string & name) const
Definition at line 82 of file CachedMultiMesh.cpp.
References get_id(), and m_name.
get_multimesh_names()
const std::map< std::string, std::vector< int64_t > > & wmtk::io::CachedMultiMesh::get_multimesh_names () const
Definition at line 96 of file CachedMultiMesh.cpp.
References m_multimesh_names.
get_root()
std::shared_ptr< Mesh > wmtk::io::CachedMultiMesh::get_root ()
Definition at line 59 of file CachedMultiMesh.cpp.
References m_root.
Referenced by get_from_path().
load() [1/2]
void wmtk::io::CachedMultiMesh::load (const std::filesystem::path & path)
Definition at line 23 of file CachedMultiMesh.cpp.
References wmtk::read_mesh().
load() [2/2]
void wmtk::io::CachedMultiMesh::load (std::shared_ptr< Mesh > root)
Definition at line 28 of file CachedMultiMesh.cpp.
References m_root.
operator=()
CachedMultiMesh & wmtk::io::CachedMultiMesh::operator= (CachedMultiMesh &&) default
Member Data Documentation
m_multimesh_names
std::map<std::string, std::vector<int64_t> > wmtk::io::CachedMultiMesh::m_multimesh_names private
Definition at line 46 of file CachedMultiMesh.hpp.
Referenced by get(), get_id(), and get_multimesh_names().
m_name
std::string wmtk::io::CachedMultiMesh::m_name private
Definition at line 42 of file CachedMultiMesh.hpp.
Referenced by get_from_path(), get_id(), and get_id_from_path().
m_root
std::shared_ptr<Mesh> wmtk::io::CachedMultiMesh::m_root private
Definition at line 43 of file CachedMultiMesh.hpp.
Referenced by flush(), get(), get_root(), and load().
The documentation for this class was generated from the following files:
src/wmtk/io/CachedMultiMesh.hpp
src/wmtk/io/CachedMultiMesh.cpp