Wildmeshing Toolkit: wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T > Class Template Reference
wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T > Class Template Reference
#include <BasicSplitNewAttributeStrategy.hpp>
Public Types
using VecType = VectorX< T >
using SplitRibFuncType = std::function< VecType(const VecType &, const VecType &)>
using SplitFuncType = std::function< std::array< VecType, 2 >(const VecType &)>
Public Types inherited from wmtk::operations::SplitNewAttributeStrategy
using ReturnData = wmtk::multimesh::operations::SplitReturnData
using ReturnVariant = ReturnData::ReturnVariant
using OperationTupleData = wmtk::multimesh::operations::OperationTupleData
Public Types inherited from wmtk::operations::NewAttributeStrategy
enum class CollapseBasicStrategy {
Default , CopyTuple , CopyOther , CopyFromPredicate ,
Mean , Throw , None
}
enum class SplitBasicStrategy {
Default , Copy , Half , Throw ,
None
}
enum class BasicSimplexPredicate { Default , IsInterior }
using SplitRibBasicStrategy = CollapseBasicStrategy
template<typename T >
using VecType = VectorX< T >
template<typename T , typename VT = VecType<T>>
using SplitFuncType = std::function< std::array< VT, 2 >(const VT &)>
template<typename T , typename VT = VecType<T>>
using SplitRibFuncType = std::function< VT(const VT &, const VT &)>
using SimplexPredicateType = std::function< bool(const simplex::Simplex &)>
template<typename T , typename VT = VecType<T>>
using CollapseFuncType = std::function< VT(const VT &, const VT &)>
Public Member Functions
BasicSplitNewAttributeStrategy (const wmtk::attribute::MeshAttributeHandle< T > &h)
void assign_split (PrimitiveType pt, const Tuple &input_simplex, const std::array< Tuple, 2 > &split_simplices) override
void assign_split_ribs (PrimitiveType pt, const std::array< Tuple, 2 > &input_ears, const Tuple &final_simplex) override
void set_split_rib_strategy (SplitRibFuncType &&f)
void set_split_strategy (SplitFuncType &&f)
void set_standard_split_rib_strategy (SplitRibBasicStrategy t) override
void set_standard_split_strategy (SplitBasicStrategy t) override
Mesh & mesh () override
PrimitiveType primitive_type () const override
void update_handle_mesh (Mesh &m) override
bool matches_attribute (const attribute::MeshAttributeHandleVariant &) const override
Public Member Functions inherited from wmtk::operations::tri_mesh::SplitNewAttributeStrategy
SplitNewAttributeStrategy (TriMesh &)
TriMesh & tri_mesh ()
const TriMesh & tri_mesh () const
Public Member Functions inherited from wmtk::operations::SplitNewAttributeStrategy
void update (const ReturnData &ret_data, const OperationTupleData &op_data)
Public Member Functions inherited from wmtk::operations::NewAttributeStrategy
virtual ~NewAttributeStrategy ()
const Mesh & mesh () const
template<typename T >
auto standard_collapse_strategy (CollapseBasicStrategy optype) -> CollapseFuncType< T >
template<typename T >
auto standard_split_strategy (SplitBasicStrategy optype) -> SplitFuncType< T >
template<typename T >
auto standard_split_rib_strategy (SplitRibBasicStrategy optype) -> SplitRibFuncType< T >
Private Attributes
wmtk::attribute::MeshAttributeHandle< T > m_handle
SplitRibFuncType m_split_rib_op
SplitFuncType m_split_op
Additional Inherited Members
Static Public Member Functions inherited from wmtk::operations::NewAttributeStrategy
template<typename T >
static CollapseFuncType< T > standard_collapse_strategy (CollapseBasicStrategy=CollapseBasicStrategy::Default)
template<typename T >
static SplitFuncType< T > standard_split_strategy (SplitBasicStrategy=SplitBasicStrategy::Default)
template<typename T >
static SplitRibFuncType< T > standard_split_rib_strategy (SplitRibBasicStrategy=SplitRibBasicStrategy::Default)
Detailed Description
template<typename T>
class wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >
Definition at line 8 of file BasicSplitNewAttributeStrategy.hpp.
Member Typedef Documentation
SplitFuncType
template<typename T > using wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::SplitFuncType = std::function<std::array<VecType, 2>(const VecType&)>
Definition at line 13 of file BasicSplitNewAttributeStrategy.hpp.
SplitRibFuncType
template<typename T > using wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::SplitRibFuncType = std::function<VecType(const VecType&, const VecType&)>
Definition at line 12 of file BasicSplitNewAttributeStrategy.hpp.
VecType
template<typename T > using wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::VecType = VectorX<T>
Definition at line 11 of file BasicSplitNewAttributeStrategy.hpp.
Constructor & Destructor Documentation
BasicSplitNewAttributeStrategy()
template<typename T > wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::BasicSplitNewAttributeStrategy (const wmtk::attribute::MeshAttributeHandle< T > & h)
Definition at line 20 of file BasicSplitNewAttributeStrategy.cpp.
References wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_standard_split_rib_strategy(), wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_standard_split_strategy(), and wmtk::operations::NewAttributeStrategy::Throw.
Member Function Documentation
assign_split()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::assign_split (PrimitiveType pt, const Tuple & input_simplex, const std::array< Tuple, 2 > & split_simplices) override virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 59 of file BasicSplitNewAttributeStrategy.cpp.
assign_split_ribs()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::assign_split_ribs (PrimitiveType pt, const std::array< Tuple, 2 > & input_ears, const Tuple & final_simplex) override virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 33 of file BasicSplitNewAttributeStrategy.cpp.
matches_attribute()
template<typename T > bool wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::matches_attribute (const attribute::MeshAttributeHandleVariant & attr) const override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 107 of file BasicSplitNewAttributeStrategy.cpp.
mesh()
template<typename T > Mesh & wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::mesh override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 91 of file BasicSplitNewAttributeStrategy.cpp.
primitive_type()
template<typename T > PrimitiveType wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::primitive_type override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 96 of file BasicSplitNewAttributeStrategy.cpp.
set_split_rib_strategy()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_split_rib_strategy (SplitRibFuncType && f)
Definition at line 79 of file BasicSplitNewAttributeStrategy.cpp.
set_split_strategy()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_split_strategy (SplitFuncType && f)
Definition at line 84 of file BasicSplitNewAttributeStrategy.cpp.
set_standard_split_rib_strategy()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_standard_split_rib_strategy (SplitRibBasicStrategy t) override virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 10 of file BasicSplitNewAttributeStrategy.cpp.
Referenced by wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::BasicSplitNewAttributeStrategy().
set_standard_split_strategy()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::set_standard_split_strategy (SplitBasicStrategy t) override virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 15 of file BasicSplitNewAttributeStrategy.cpp.
Referenced by wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::BasicSplitNewAttributeStrategy().
update_handle_mesh()
template<typename T > void wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::update_handle_mesh (Mesh & m) override virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 101 of file BasicSplitNewAttributeStrategy.cpp.
Member Data Documentation
m_handle
template<typename T > wmtk::attribute::MeshAttributeHandle<T> wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::m_handle private
Definition at line 40 of file BasicSplitNewAttributeStrategy.hpp.
m_split_op
template<typename T > SplitFuncType wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::m_split_op private
Definition at line 42 of file BasicSplitNewAttributeStrategy.hpp.
m_split_rib_op
template<typename T > SplitRibFuncType wmtk::operations::tri_mesh::BasicSplitNewAttributeStrategy< T >::m_split_rib_op private
Definition at line 41 of file BasicSplitNewAttributeStrategy.hpp.
The documentation for this class was generated from the following files:
src/wmtk/attribute/AttributeInitializationHandle.hpp
src/wmtk/operations/tri_mesh/BasicSplitNewAttributeStrategy.hpp
src/wmtk/operations/tri_mesh/BasicSplitNewAttributeStrategy.cpp