Wildmeshing Toolkit: wmtk::operations::SplitNewAttributeStrategy< T > Class Template Reference
wmtk::operations::SplitNewAttributeStrategy< T > Class Template Reference
#include <SplitNewAttributeStrategy.hpp>
Public Types
using VecType = VectorX< T >
using ReturnData = BaseSplitNewAttributeStrategy::ReturnData
using OperationInOutData = BaseSplitNewAttributeStrategy::OperationInOutData
using ReturnVariant = ReturnData::ReturnVariant
using SplitRibFuncType = std::function< VecType(const VecType &, const VecType &, const std::bitset< 2 > &)>
using SplitFuncType = std::function< std::array< VecType, 2 >(const VecType &, const std::bitset< 2 > &)>
Public Types inherited from wmtk::operations::BaseSplitNewAttributeStrategy
using ReturnData = wmtk::multimesh::operations::SplitReturnData
using OperationInOutData = wmtk::multimesh::operations::OperationInOutData
Public Types inherited from wmtk::operations::NewAttributeStrategy
using SimplexPredicateType = std::function< bool(const simplex::Simplex &)>
Public Member Functions
SplitNewAttributeStrategy (const wmtk::attribute::MeshAttributeHandle &h)
void update (Mesh &m, const ReturnData &ret_data, const OperationInOutData &op_data) const final override
void set_rib_strategy (SplitRibFuncType &&f)
void set_strategy (SplitFuncType &&f)
void set_rib_strategy (SplitRibBasicStrategy t)
void set_strategy (SplitBasicStrategy t)
Mesh & mesh () override
PrimitiveType primitive_type () const override
void update_handle_mesh (Mesh &m) override
bool matches_attribute (const attribute::MeshAttributeHandle &) const override
std::vector< wmtk::attribute::MeshAttributeHandle > targets () const final override
bool invalid_state () const final override
std::string name () const final override
virtual Mesh & mesh ()=0
const Mesh & mesh () const
Public Member Functions inherited from wmtk::operations::NewAttributeStrategy
virtual ~NewAttributeStrategy ()
const Mesh & mesh () const
void set_simplex_predicate (SimplexPredicateType &&f)
void set_simplex_predicate (BasicSimplexPredicate f)
std::bitset< 2 > evaluate_predicate (PrimitiveType pt, const std::array< Tuple, 2 > &simplices) const
std::vector< wmtk::attribute::MeshAttributeHandle > sources () const final override
Public Member Functions inherited from wmtk::operations::AttributeTransferEdge
virtual ~AttributeTransferEdge ()=0
Private Member Functions
void assign_split (wmtk::attribute::Accessor< T > &accessor, const Tuple &input_simplex, const std::array< Tuple, 2 > &split_simplices) const
void assign_split_ribs (wmtk::attribute::Accessor< T > &accessor, const std::array< Tuple, 2 > &input_ears, const Tuple &final_simplex) const
SplitNewAttributeStrategy< Rational >::SplitFuncType standard_split_strategy (SplitBasicStrategy optype, const std::string_view &name)
SplitNewAttributeStrategy< Rational >::SplitRibFuncType standard_split_rib_strategy (SplitRibBasicStrategy optype, const std::string_view &name)
Static Private Member Functions
static SplitFuncType standard_split_strategy (SplitBasicStrategy optype, const std::string_view &={})
static SplitRibFuncType standard_split_rib_strategy (SplitRibBasicStrategy optype, const std::string_view &={})
Private Attributes
wmtk::attribute::MeshAttributeHandle m_handle
SplitRibFuncType m_split_rib_op
SplitFuncType m_split_op
bool m_will_throw = false
bool m_will_throw_rib = false
std::unique_ptr< SplitNewAttributeTopoInfo > m_topo_info
Detailed Description
template<typename T>
class wmtk::operations::SplitNewAttributeStrategy< T >
Definition at line 25 of file SplitNewAttributeStrategy.hpp.
Member Typedef Documentation
OperationInOutData
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::OperationInOutData = BaseSplitNewAttributeStrategy::OperationInOutData
Definition at line 30 of file SplitNewAttributeStrategy.hpp.
ReturnData
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::ReturnData = BaseSplitNewAttributeStrategy::ReturnData
Definition at line 29 of file SplitNewAttributeStrategy.hpp.
ReturnVariant
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::ReturnVariant = ReturnData::ReturnVariant
Definition at line 31 of file SplitNewAttributeStrategy.hpp.
SplitFuncType
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::SplitFuncType = std::function<std::array<VecType, 2>(const VecType&, const std::bitset<2>&)>
Definition at line 39 of file SplitNewAttributeStrategy.hpp.
SplitRibFuncType
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::SplitRibFuncType = std::function<VecType(const VecType&, const VecType&, const std::bitset<2>&)>
Definition at line 34 of file SplitNewAttributeStrategy.hpp.
VecType
template<typename T > using wmtk::operations::SplitNewAttributeStrategy< T >::VecType = VectorX<T>
Definition at line 28 of file SplitNewAttributeStrategy.hpp.
Constructor & Destructor Documentation
SplitNewAttributeStrategy()
template<typename T > wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy (const wmtk::attribute::MeshAttributeHandle & h)
Definition at line 187 of file SplitNewAttributeStrategy.cpp.
References wmtk::Edge, wmtk::attribute::MeshAttributeHandle::holds(), wmtk::Mesh::is_free(), wmtk::log_and_throw_error(), wmtk::operations::SplitNewAttributeStrategy< T >::m_handle, wmtk::operations::SplitNewAttributeStrategy< T >::m_topo_info, wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::operations::SplitNewAttributeStrategy< T >::mesh(), wmtk::attribute::MeshAttributeHandle::primitive_type(), wmtk::operations::SplitNewAttributeStrategy< T >::set_rib_strategy(), wmtk::operations::SplitNewAttributeStrategy< T >::set_strategy(), wmtk::Tetrahedron, wmtk::operations::Throw, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
Member Function Documentation
assign_split()
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::assign_split (wmtk::attribute::Accessor< T > & accessor, const Tuple & input_simplex, const std::array< Tuple, 2 > & split_simplices) const private
Definition at line 308 of file SplitNewAttributeStrategy.cpp.
References wmtk::attribute::Accessor< T, MeshType, Dim >::const_vector_attribute(), wmtk::attribute::Accessor< T, MeshType, Dim >::primitive_type(), and wmtk::attribute::Accessor< T, MeshType, Dim >::vector_attribute().
assign_split_ribs()
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::assign_split_ribs (wmtk::attribute::Accessor< T > & accessor, const std::array< Tuple, 2 > & input_ears, const Tuple & final_simplex) const private
Definition at line 282 of file SplitNewAttributeStrategy.cpp.
References wmtk::attribute::Accessor< T, MeshType, Dim >::const_vector_attribute(), wmtk::attribute::Accessor< T, MeshType, Dim >::primitive_type(), and wmtk::attribute::Accessor< T, MeshType, Dim >::vector_attribute().
invalid_state()
template<typename T > bool wmtk::operations::SplitNewAttributeStrategy< T >::invalid_state final override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 13 of file SplitNewAttributeStrategy.cpp.
matches_attribute()
template<typename T > bool wmtk::operations::SplitNewAttributeStrategy< T >::matches_attribute (const attribute::MeshAttributeHandle & handle) const override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 374 of file SplitNewAttributeStrategy.cpp.
mesh() [1/3]
template<typename T > const Mesh & wmtk::operations::NewAttributeStrategy::mesh virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 34 of file NewAttributeStrategy.cpp.
mesh() [2/3]
template<typename T > Mesh & wmtk::operations::SplitNewAttributeStrategy< T >::mesh override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 356 of file SplitNewAttributeStrategy.cpp.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy().
mesh() [3/3]
template<typename T > virtual Mesh& wmtk::operations::NewAttributeStrategy::mesh virtual
Implements wmtk::operations::NewAttributeStrategy.
name()
template<typename T > std::string wmtk::operations::SplitNewAttributeStrategy< T >::name final override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 18 of file SplitNewAttributeStrategy.cpp.
primitive_type()
template<typename T > PrimitiveType wmtk::operations::SplitNewAttributeStrategy< T >::primitive_type override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 362 of file SplitNewAttributeStrategy.cpp.
set_rib_strategy() [1/2]
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::set_rib_strategy (SplitRibBasicStrategy t)
Definition at line 330 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::Throw.
set_rib_strategy() [2/2]
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::set_rib_strategy (SplitRibFuncType && f)
Definition at line 343 of file SplitNewAttributeStrategy.cpp.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy().
set_strategy() [1/2]
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::set_strategy (SplitBasicStrategy t)
Definition at line 336 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::Throw.
set_strategy() [2/2]
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::set_strategy (SplitFuncType && f)
Definition at line 349 of file SplitNewAttributeStrategy.cpp.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy().
standard_split_rib_strategy() [1/2]
template<typename T > SplitNewAttributeStrategy< T >::SplitRibFuncType wmtk::operations::SplitNewAttributeStrategy< T >::standard_split_rib_strategy (SplitRibBasicStrategy optype, const std::string_view & name = {}) static private
Definition at line 82 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::CopyOther, wmtk::operations::CopyTuple, wmtk::operations::Default, wmtk::log_and_throw_error(), wmtk::operations::Mean, wmtk::operations::None, wmtk::operations::SplitNewAttributeStrategy< T >::standard_split_rib_strategy(), and wmtk::operations::Throw.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::standard_split_rib_strategy().
standard_split_rib_strategy() [2/2]
SplitNewAttributeStrategy< Rational >::SplitRibFuncType wmtk::operations::SplitNewAttributeStrategy< Rational >::standard_split_rib_strategy (SplitRibBasicStrategy optype, const std::string_view & name) private
Definition at line 135 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::CopyOther, wmtk::operations::CopyTuple, wmtk::operations::Default, wmtk::log_and_throw_error(), wmtk::operations::Mean, wmtk::operations::None, and wmtk::operations::Throw.
standard_split_strategy() [1/2]
template<typename T > SplitNewAttributeStrategy< T >::SplitFuncType wmtk::operations::SplitNewAttributeStrategy< T >::standard_split_strategy (SplitBasicStrategy optype, const std::string_view & name = {}) static private
Definition at line 25 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::Copy, wmtk::operations::Default, wmtk::operations::Half, wmtk::log_and_throw_error(), wmtk::operations::None, and wmtk::operations::Throw.
standard_split_strategy() [2/2]
SplitNewAttributeStrategy< Rational >::SplitFuncType wmtk::operations::SplitNewAttributeStrategy< Rational >::standard_split_strategy (SplitBasicStrategy optype, const std::string_view & name) private
Definition at line 53 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::Copy, wmtk::operations::Default, wmtk::operations::Half, wmtk::log_and_throw_error(), wmtk::operations::None, and wmtk::operations::Throw.
targets()
template<typename T > std::vector<wmtk::attribute::MeshAttributeHandle> wmtk::operations::SplitNewAttributeStrategy< T >::targets () const inline final override virtual
Implements wmtk::operations::AttributeTransferEdge.
Definition at line 61 of file SplitNewAttributeStrategy.hpp.
References wmtk::operations::SplitNewAttributeStrategy< T >::m_handle.
update()
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::update (Mesh & m, const ReturnData & ret_data, const OperationInOutData & op_data) const final override virtual
Implements wmtk::operations::BaseSplitNewAttributeStrategy.
Definition at line 217 of file SplitNewAttributeStrategy.cpp.
References wmtk::Mesh::create_accessor(), wmtk::simplex::NavigatableSimplex::tuple(), and wmtk::Vertex.
update_handle_mesh()
template<typename T > void wmtk::operations::SplitNewAttributeStrategy< T >::update_handle_mesh (Mesh & m) override virtual
Implements wmtk::operations::NewAttributeStrategy.
Definition at line 368 of file SplitNewAttributeStrategy.cpp.
Member Data Documentation
m_handle
template<typename T > wmtk::attribute::MeshAttributeHandle wmtk::operations::SplitNewAttributeStrategy< T >::m_handle private
Definition at line 70 of file SplitNewAttributeStrategy.hpp.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy(), and wmtk::operations::SplitNewAttributeStrategy< T >::targets().
m_split_op
template<typename T > SplitFuncType wmtk::operations::SplitNewAttributeStrategy< T >::m_split_op private
Definition at line 72 of file SplitNewAttributeStrategy.hpp.
m_split_rib_op
template<typename T > SplitRibFuncType wmtk::operations::SplitNewAttributeStrategy< T >::m_split_rib_op private
Definition at line 71 of file SplitNewAttributeStrategy.hpp.
m_topo_info
template<typename T > std::unique_ptr<SplitNewAttributeTopoInfo> wmtk::operations::SplitNewAttributeStrategy< T >::m_topo_info private
Definition at line 75 of file SplitNewAttributeStrategy.hpp.
Referenced by wmtk::operations::SplitNewAttributeStrategy< T >::SplitNewAttributeStrategy().
m_will_throw
template<typename T > bool wmtk::operations::SplitNewAttributeStrategy< T >::m_will_throw = false private
Definition at line 73 of file SplitNewAttributeStrategy.hpp.
m_will_throw_rib
template<typename T > bool wmtk::operations::SplitNewAttributeStrategy< T >::m_will_throw_rib = false private
Definition at line 74 of file SplitNewAttributeStrategy.hpp.
The documentation for this class was generated from the following files:
src/wmtk/operations/attribute_new/SplitNewAttributeStrategy.hpp
src/wmtk/operations/attribute_new/SplitNewAttributeStrategy.cpp