Wildmeshing Toolkit: wmtk::invariants::CollapseSoftEnergyBeforeInvariant Class Reference
wmtk::invariants::CollapseSoftEnergyBeforeInvariant Class Reference
#include <CollapseSoftEnergyBeforeInvariant.hpp>
Public Member Functions
CollapseSoftEnergyBeforeInvariant (const Mesh &m, const attribute::TypedAttributeHandle< Rational > &coordinate, const attribute::TypedAttributeHandle< double > &energy, const attribute::TypedAttributeHandle< double > &edge_length, const attribute::TypedAttributeHandle< double > &target_edge_length, int64_t collapse_type=0, double eps=0.1)
bool before (const simplex::Simplex &s) const override
Invariant (const Mesh &m)
Invariant (const Mesh &m, bool use_before, bool use_old_state_in_after, bool use_new_state_in_after)
Public Member Functions inherited from wmtk::invariants::Invariant
virtual bool after (const std::vector< Tuple > &top_dimension_tuples_before, const std::vector< Tuple > &top_dimension_tuples_after) const
Invariant (const Mesh &m)
Invariant (const Mesh &m, bool use_before, bool use_old_state_in_after, bool use_new_state_in_after)
virtual ~Invariant ()
const Mesh & mesh () const
virtual bool directly_modified_after (const std::vector< simplex::Simplex > &simplices_before, const std::vector< simplex::Simplex > &simplices_after) const
bool use_before () const
bool use_after () const
bool use_old_state_in_after () const
bool use_new_state_in_after () const
Private Attributes
const attribute::TypedAttributeHandle< Rational > m_coordinate_handle
const attribute::TypedAttributeHandle< double > m_energy_handle
const attribute::TypedAttributeHandle< double > m_edge_length_handle
const attribute::TypedAttributeHandle< double > m_target_edge_length_handle
const int64_t m_collapse_type
const double m_eps
Detailed Description
Definition at line 7 of file CollapseSoftEnergyBeforeInvariant.hpp.
Constructor & Destructor Documentation
CollapseSoftEnergyBeforeInvariant()
wmtk::invariants::CollapseSoftEnergyBeforeInvariant::CollapseSoftEnergyBeforeInvariant (const Mesh & m, const attribute::TypedAttributeHandle< Rational > & coordinate, const attribute::TypedAttributeHandle< double > & energy, const attribute::TypedAttributeHandle< double > & edge_length, const attribute::TypedAttributeHandle< double > & target_edge_length, int64_t collapse_type = 0, double eps = 0.1)
Definition at line 10 of file CollapseSoftEnergyBeforeInvariant.cpp.
Member Function Documentation
before()
bool wmtk::invariants::CollapseSoftEnergyBeforeInvariant::before (const simplex::Simplex & s) const override virtual
Reimplemented from wmtk::invariants::Invariant.
Definition at line 27 of file CollapseSoftEnergyBeforeInvariant.cpp.
References wmtk::Mesh::create_const_accessor(), wmtk::Edge, wmtk::Mesh::is_ccw(), m_collapse_type, m_coordinate_handle, m_edge_length_handle, m_energy_handle, m_eps, m_target_edge_length_handle, wmtk::invariants::Invariant::mesh(), wmtk::PE, PF, PT, wmtk::PV, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::function::utils::Tet_AMIPS_energy(), wmtk::Tetrahedron, wmtk::simplex::top_dimension_cofaces(), wmtk::Triangle, wmtk::simplex::Simplex::tuple(), wmtk::Vertex, wmtk::simplex::Simplex::vertex(), and wmtk::utils::wmtk_orient3d().
Invariant() [1/2]
wmtk::invariants::Invariant::Invariant
Definition at line 23 of file Invariant.cpp.
Invariant() [2/2]
wmtk::invariants::Invariant::Invariant
Definition at line 24 of file Invariant.cpp.
Member Data Documentation
m_collapse_type
const int64_t wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_collapse_type private
Definition at line 27 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
m_coordinate_handle
const attribute::TypedAttributeHandle<Rational> wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_coordinate_handle private
Definition at line 23 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
m_edge_length_handle
const attribute::TypedAttributeHandle<double> wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_edge_length_handle private
Definition at line 25 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
m_energy_handle
const attribute::TypedAttributeHandle<double> wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_energy_handle private
Definition at line 24 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
m_eps
const double wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_eps private
Definition at line 28 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
m_target_edge_length_handle
const attribute::TypedAttributeHandle<double> wmtk::invariants::CollapseSoftEnergyBeforeInvariant::m_target_edge_length_handle private
Definition at line 26 of file CollapseSoftEnergyBeforeInvariant.hpp.
Referenced by before().
The documentation for this class was generated from the following files:
src/wmtk/invariants/CollapseSoftEnergyBeforeInvariant.hpp
src/wmtk/invariants/CollapseSoftEnergyBeforeInvariant.cpp