Wildmeshing Toolkit: wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo Class Reference
wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo Class Reference
#include <SplitNewAttributeTopoInfo.hpp>
Public Member Functions
SplitNewAttributeTopoInfo (EdgeMesh &m)
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
std::vector< Tuple > output_rib_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< std::array< Tuple, 2 > > output_split_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< Tuple > input_split_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
std::vector< std::array< int64_t, 2 > > output_duplicated_free_simplices (const ReturnVariant &ret_data, PrimitiveType pt) const final override
Public Member Functions inherited from wmtk::operations::SplitNewAttributeTopoInfo
virtual ~SplitNewAttributeTopoInfo ()=default
Private Member Functions
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
std::vector< Tuple > output_rib_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< std::array< Tuple, 2 > > output_split_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< Tuple > input_split_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
std::vector< std::array< int64_t, 2 > > output_duplicated_free_simplices (const EdgeOperationData &ret_data, PrimitiveType pt) const
Private Attributes
EdgeMesh & m_mesh
Additional Inherited Members
Public Types inherited from wmtk::operations::SplitNewAttributeTopoInfo
using ReturnData = wmtk::multimesh::operations::SplitReturnData
using ReturnVariant = ReturnData::ReturnVariant
Detailed Description
Definition at line 6 of file SplitNewAttributeTopoInfo.hpp.
Constructor & Destructor Documentation
SplitNewAttributeTopoInfo()
wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::SplitNewAttributeTopoInfo (EdgeMesh & m)
Definition at line 6 of file SplitNewAttributeTopoInfo.cpp.
Member Function Documentation
input_ear_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::input_ear_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 90 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::edge_mesh::EdgeOperationData::input_endpoints(), m_mesh, and wmtk::Mesh::parent_scope().
input_ear_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::input_ear_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 19 of file SplitNewAttributeTopoInfo.cpp.
input_split_simplices() [1/2]
std::vector< Tuple > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::input_split_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 77 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id().
input_split_simplices() [2/2]
std::vector< Tuple > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::input_split_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 44 of file SplitNewAttributeTopoInfo.cpp.
output_duplicated_free_simplices() [1/2]
std::vector< std::array< int64_t, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_duplicated_free_simplices (const EdgeOperationData & ret_data, PrimitiveType pt) const private
Definition at line 119 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), wmtk::Mesh::is_free(), wmtk::operations::edge_mesh::EdgeOperationData::m_free_split_v, and m_mesh.
output_duplicated_free_simplices() [2/2]
std::vector< std::array< int64_t, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_duplicated_free_simplices (const ReturnVariant & ret_data, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 52 of file SplitNewAttributeTopoInfo.cpp.
output_rib_simplices() [1/2]
std::vector< Tuple > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_rib_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 106 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id().
output_rib_simplices() [2/2]
std::vector< Tuple > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_rib_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 28 of file SplitNewAttributeTopoInfo.cpp.
output_split_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_split_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 59 of file SplitNewAttributeTopoInfo.cpp.
References wmtk::get_primitive_type_id(), m_mesh, wmtk::Mesh::parent_scope(), and wmtk::operations::edge_mesh::EdgeOperationData::split_output_edges().
output_split_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::output_split_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override virtual
Implements wmtk::operations::SplitNewAttributeTopoInfo.
Definition at line 35 of file SplitNewAttributeTopoInfo.cpp.
Member Data Documentation
m_mesh
EdgeMesh& wmtk::operations::edge_mesh::SplitNewAttributeTopoInfo::m_mesh private
Definition at line 79 of file SplitNewAttributeTopoInfo.hpp.
Referenced by input_ear_simplices(), output_duplicated_free_simplices(), and output_split_simplices().
The documentation for this class was generated from the following files:
src/wmtk/operations/edge_mesh/SplitNewAttributeTopoInfo.hpp
src/wmtk/operations/edge_mesh/SplitNewAttributeTopoInfo.cpp