Wildmeshing Toolkit: wmtk::attribute::TypedAttributeHandle< T > Class Template Reference
wmtk::attribute::TypedAttributeHandle< T > Class Template Reference
Handle that represents attributes for some mesh.
#include <TypedAttributeHandle.hpp>
Public Types
using Type = T
using value_type = T
Public Member Functions
TypedAttributeHandle ()=default
TypedAttributeHandle (const TypedAttributeHandle &)=default
TypedAttributeHandle (TypedAttributeHandle &&)=default
TypedAttributeHandle & operator= (const TypedAttributeHandle &)=default
TypedAttributeHandle & operator= (TypedAttributeHandle &&)=default
template<typename U >
bool operator== (const TypedAttributeHandle< U > &o) const
bool operator< (const TypedAttributeHandle< T > &o) const
bool is_valid () const
PrimitiveType primitive_type () const
const AttributeHandle & base_handle () const
Private Member Functions
TypedAttributeHandle (AttributeHandle ah, PrimitiveType pt)
TypedAttributeHandle (int64_t index, PrimitiveType pt)
TypedAttributeHandle (const MeshAttributeHandle &)
Private Attributes
wmtk::attribute::AttributeHandle m_base_handle
wmtk::PrimitiveType m_primitive_type
Friends
class wmtk::Mesh
class MeshAttributes< T >
template<typename U , int Dim>
class AccessorBase
template<typename U , typename MeshType , int Dim>
class Accessor
class AttributeManager
class wmtk::hash< TypedAttributeHandle< T > >
template<int D>
class utils::HybridRationalAttribute
Detailed Description
template<typename T>
class wmtk::attribute::TypedAttributeHandle< T >
Handle that represents attributes for some mesh.
In conjunction with the mesh that constructed it, specifies a particular attribute. NOTE: with multimesh around, you ideally want to store a MeshAttribteHandle, which also hides the templating used here.
Definition at line 32 of file TypedAttributeHandle.hpp.
Member Typedef Documentation
Type
template<typename T > using wmtk::attribute::TypedAttributeHandle< T >::Type = T
Definition at line 35 of file TypedAttributeHandle.hpp.
value_type
template<typename T > using wmtk::attribute::TypedAttributeHandle< T >::value_type = T
Definition at line 62 of file TypedAttributeHandle.hpp.
Constructor & Destructor Documentation
TypedAttributeHandle() [1/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle (AttributeHandle ah, PrimitiveType pt) inline private
Definition at line 51 of file TypedAttributeHandle.hpp.
TypedAttributeHandle() [2/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle (int64_t index, PrimitiveType pt) inline private
Definition at line 55 of file TypedAttributeHandle.hpp.
TypedAttributeHandle() [3/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle (const MeshAttributeHandle & h) private
Definition at line 16 of file TypedAttributeHandle.cpp.
References wmtk::attribute::MeshAttributeHandle::holds().
TypedAttributeHandle() [4/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle () default
TypedAttributeHandle() [5/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle (const TypedAttributeHandle< T > &) default
TypedAttributeHandle() [6/6]
template<typename T > wmtk::attribute::TypedAttributeHandle< T >::TypedAttributeHandle (TypedAttributeHandle< T > &&) default
Member Function Documentation
base_handle()
template<typename T > const AttributeHandle& wmtk::attribute::TypedAttributeHandle< T >::base_handle () const inline
Definition at line 78 of file TypedAttributeHandle.hpp.
References wmtk::attribute::TypedAttributeHandle< T >::m_base_handle.
is_valid()
template<typename T > bool wmtk::attribute::TypedAttributeHandle< T >::is_valid () const inline
Definition at line 76 of file TypedAttributeHandle.hpp.
References wmtk::attribute::AttributeHandle::is_valid(), and wmtk::attribute::TypedAttributeHandle< T >::m_base_handle.
Referenced by wmtk::attribute::AttributeManager::get_attribute_default_value(), wmtk::attribute::AttributeManager::get_attribute_dimension(), and wmtk::multimesh::MultiMeshManager::map_handles().
operator<()
template<typename T > bool wmtk::attribute::TypedAttributeHandle< T >::operator< (const TypedAttributeHandle< T > & o) const
Definition at line 10 of file TypedAttributeHandle.cpp.
References wmtk::attribute::TypedAttributeHandle< T >::m_base_handle, and wmtk::attribute::TypedAttributeHandle< T >::m_primitive_type.
operator=() [1/2]
template<typename T > TypedAttributeHandle& wmtk::attribute::TypedAttributeHandle< T >::operator= (const TypedAttributeHandle< T > &) default
operator=() [2/2]
template<typename T > TypedAttributeHandle& wmtk::attribute::TypedAttributeHandle< T >::operator= (TypedAttributeHandle< T > &&) default
operator==()
template<typename T > template<typename U > bool wmtk::attribute::TypedAttributeHandle< T >::operator== (const TypedAttributeHandle< U > & o) const inline
Definition at line 70 of file TypedAttributeHandle.hpp.
References wmtk::attribute::TypedAttributeHandle< T >::m_base_handle, and wmtk::attribute::TypedAttributeHandle< T >::m_primitive_type.
primitive_type()
template<typename T > PrimitiveType wmtk::attribute::TypedAttributeHandle< T >::primitive_type () const inline
Definition at line 77 of file TypedAttributeHandle.hpp.
References wmtk::attribute::TypedAttributeHandle< T >::m_primitive_type.
Referenced by wmtk::TodoInvariant::before(), wmtk::TodoLargerInvariant::before(), wmtk::TodoSmallerInvariant::before(), wmtk::multimesh::utils::internal::TupleTag::extract_and_register_child_mesh_from_tag_handle(), wmtk::attribute::utils::HybridRationalAttribute< D >::register_attribute_from_double(), and wmtk::attribute::utils::HybridRationalAttribute< D >::register_attribute_from_rational().
Friends And Related Function Documentation
Accessor
template<typename T > template<typename U , typename MeshType , int Dim> friend class Accessor friend
Definition at line 43 of file TypedAttributeHandle.hpp.
AccessorBase
template<typename T > template<typename U , int Dim> friend class AccessorBase friend
Definition at line 41 of file TypedAttributeHandle.hpp.
AttributeManager
template<typename T > friend class AttributeManager friend
Definition at line 44 of file TypedAttributeHandle.hpp.
MeshAttributes< T >
template<typename T > friend class MeshAttributes< T > friend
Definition at line 38 of file TypedAttributeHandle.hpp.
utils::HybridRationalAttribute
template<typename T > template<int D> friend class utils::HybridRationalAttribute friend
Definition at line 47 of file TypedAttributeHandle.hpp.
wmtk::hash< TypedAttributeHandle< T > >
template<typename T > friend class wmtk::hash< TypedAttributeHandle< T > > friend
Definition at line 44 of file TypedAttributeHandle.hpp.
wmtk::Mesh
template<typename T > friend class wmtk::Mesh friend
Definition at line 38 of file TypedAttributeHandle.hpp.
Member Data Documentation
m_base_handle
template<typename T > wmtk::attribute::AttributeHandle wmtk::attribute::TypedAttributeHandle< T >::m_base_handle private
Definition at line 48 of file TypedAttributeHandle.hpp.
Referenced by wmtk::attribute::TypedAttributeHandle< T >::base_handle(), wmtk::attribute::AttributeManager::get_all_attributes(), wmtk::attribute::AttributeManager::get_attribute_default_value(), wmtk::attribute::AttributeManager::get_attribute_dimension(), wmtk::Mesh::get_attribute_handle_typed(), wmtk::attribute::AttributeManager::get_name(), wmtk::attribute::TypedAttributeHandle< T >::is_valid(), wmtk::attribute::TypedAttributeHandle< T >::operator<(), wmtk::attribute::TypedAttributeHandle< T >::operator==(), wmtk::attribute::AttributeManager::register_attribute(), and wmtk::attribute::AttributeManager::set_name().
m_primitive_type
template<typename T > wmtk::PrimitiveType wmtk::attribute::TypedAttributeHandle< T >::m_primitive_type private
Definition at line 49 of file TypedAttributeHandle.hpp.
Referenced by wmtk::attribute::AttributeManager::get(), wmtk::attribute::AttributeManager::get_all_attributes(), wmtk::Mesh::get_attribute_handle_typed(), wmtk::attribute::TypedAttributeHandle< T >::operator<(), wmtk::attribute::TypedAttributeHandle< T >::operator==(), wmtk::attribute::TypedAttributeHandle< T >::primitive_type(), and wmtk::attribute::AttributeManager::register_attribute().
The documentation for this class was generated from the following files:
src/wmtk/attribute/AttributeHandle.hpp
src/wmtk/attribute/TypedAttributeHandle.hpp
src/wmtk/attribute/TypedAttributeHandle.cpp