Wildmeshing Toolkit: wmtk::components::multimesh::utils::detail::attribute_ambiguous_error Class Reference
wmtk::components::multimesh::utils::detail::attribute_ambiguous_error Class Reference
#include <attribute_ambiguous_error.hpp>
Public Member Functions
attribute_ambiguous_error (const AttributeDescription &d, const std::vector< AttributeDescription > &possibilities)
Public Member Functions inherited from wmtk::components::multimesh::utils::detail::attribute_error
template<typename... Args>
attribute_error (const std::string_view &message, Args &&... args)
Static Public Member Functions
static std::string make_message (const AttributeDescription &description, const std::vector< AttributeDescription > &possibilities)
template<typename... Args>
static attribute_ambiguous_error make (const std::vector< AttributeDescription > &possiblities, Args &&... args)
Additional Inherited Members
Public Attributes inherited from wmtk::components::multimesh::utils::detail::attribute_error
AttributeDescription description
Detailed Description
Definition at line 9 of file attribute_ambiguous_error.hpp.
Constructor & Destructor Documentation
attribute_ambiguous_error()
wmtk::components::multimesh::utils::detail::attribute_ambiguous_error::attribute_ambiguous_error (const AttributeDescription & d, const std::vector< AttributeDescription > & possibilities) inline
Definition at line 15 of file attribute_ambiguous_error.hpp.
Referenced by make().
Member Function Documentation
make()
template<typename... Args> static attribute_ambiguous_error wmtk::components::multimesh::utils::detail::attribute_ambiguous_error::make (const std::vector< AttributeDescription > & possiblities, Args &&... args) inline static
Definition at line 21 of file attribute_ambiguous_error.hpp.
References attribute_ambiguous_error().
Referenced by wmtk::components::multimesh::utils::detail::get_attribute().
make_message()
std::string wmtk::components::multimesh::utils::detail::attribute_ambiguous_error::make_message (const AttributeDescription & description, const std::vector< AttributeDescription > & possibilities) static
Definition at line 10 of file attribute_ambiguous_error.cpp.
References wmtk::components::multimesh::utils::detail::make_named_error_string().
The documentation for this class was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/utils/detail/attribute_ambiguous_error.hpp
components/multimesh/src/wmtk/components/multimesh/utils/detail/attribute_ambiguous_error.cpp