Wildmeshing Toolkit: wmtk::simplex::IdSimplex Class Reference
wmtk::simplex::IdSimplex Class Reference
#include <IdSimplex.hpp>
Public Member Functions
IdSimplex ()=default
IdSimplex (const NavigatableSimplex &s)
bool valid () const
PrimitiveType primitive_type () const
int64_t dimension () const
bool operator< (const IdSimplex &o) const
bool operator== (const IdSimplex &o) const
bool operator!= (const IdSimplex &o) const
int64_t index () const
Protected Member Functions
IdSimplex (PrimitiveType pt, int64_t index)
Static Protected Member Functions
static int64_t id (const Mesh &m, PrimitiveType pt, const Tuple &t)
Private Member Functions
decltype(auto) as_tuple () const
Private Attributes
PrimitiveType m_primitive_type = PrimitiveType::Vertex
int64_t m_index = -1
Friends
class wmtk::Mesh
class NavigatableSimplex
Detailed Description
Definition at line 14 of file IdSimplex.hpp.
Constructor & Destructor Documentation
IdSimplex() [1/3]
wmtk::simplex::IdSimplex::IdSimplex () default
IdSimplex() [2/3]
wmtk::simplex::IdSimplex::IdSimplex (const NavigatableSimplex & s)
Definition at line 6 of file IdSimplex.cpp.
IdSimplex() [3/3]
wmtk::simplex::IdSimplex::IdSimplex (PrimitiveType pt, int64_t index) inline protected
Definition at line 33 of file IdSimplex.hpp.
Member Function Documentation
as_tuple()
decltype(auto) wmtk::simplex::IdSimplex::as_tuple () const inline private
Definition at line 45 of file IdSimplex.hpp.
References m_index, and m_primitive_type.
Referenced by operator!=(), operator<(), and operator==().
dimension()
int64_t wmtk::simplex::IdSimplex::dimension () const inline
Definition at line 24 of file IdSimplex.hpp.
References wmtk::get_primitive_type_id(), and m_primitive_type.
id()
int64_t wmtk::simplex::IdSimplex::id (const Mesh & m, PrimitiveType pt, const Tuple & t) static protected
Definition at line 10 of file IdSimplex.cpp.
References wmtk::Mesh::id().
index()
int64_t wmtk::simplex::IdSimplex::index () const inline
Definition at line 30 of file IdSimplex.hpp.
References m_index.
Referenced by wmtk::Mesh::get_simplex(), wmtk::Mesh::get_tuple_from_id_simplex(), wmtk::Mesh::id(), and wmtk::Mesh::id().
operator!=()
bool wmtk::simplex::IdSimplex::operator!= (const IdSimplex & o) const inline
Definition at line 56 of file IdSimplex.hpp.
References as_tuple().
operator<()
bool wmtk::simplex::IdSimplex::operator< (const IdSimplex & o) const inline
Definition at line 48 of file IdSimplex.hpp.
References as_tuple().
operator==()
bool wmtk::simplex::IdSimplex::operator== (const IdSimplex & o) const inline
Definition at line 52 of file IdSimplex.hpp.
References as_tuple().
primitive_type()
PrimitiveType wmtk::simplex::IdSimplex::primitive_type () const inline
Definition at line 23 of file IdSimplex.hpp.
References m_primitive_type.
Referenced by wmtk::Mesh::get_simplex(), wmtk::Mesh::get_tuple_from_id_simplex(), and wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::index().
valid()
bool wmtk::simplex::IdSimplex::valid () const inline
Definition at line 21 of file IdSimplex.hpp.
References m_index.
Friends And Related Symbol Documentation
NavigatableSimplex
friend class NavigatableSimplex friend
Definition at line 18 of file IdSimplex.hpp.
wmtk::Mesh
friend class wmtk::Mesh friend
Definition at line 17 of file IdSimplex.hpp.
Member Data Documentation
m_index
int64_t wmtk::simplex::IdSimplex::m_index = -1 private
Definition at line 42 of file IdSimplex.hpp.
Referenced by as_tuple(), index(), and valid().
m_primitive_type
PrimitiveType wmtk::simplex::IdSimplex::m_primitive_type = PrimitiveType::Vertex private
Definition at line 41 of file IdSimplex.hpp.
Referenced by as_tuple(), dimension(), and primitive_type().
The documentation for this class was generated from the following files:
src/wmtk/simplex/IdSimplex.hpp
src/wmtk/simplex/IdSimplex.cpp