Wildmeshing Toolkit: wmtk::attribute::FlagAccessor< MeshType > Class Template Reference
wmtk::attribute::FlagAccessor< MeshType > Class Template Reference
#include <FlagAccessor.hpp>
Public Types
enum class FlagBit : char { Active = 1 }
using IndexBaseType = IndexFlagAccessor< MeshType >
Public Member Functions
template<typename MeshType2 >
FlagAccessor (const FlagAccessor< MeshType2 > &o)
template<typename T >
bool is_active (const T &t) const
template<typename T >
void activate (const T &t)
template<typename T >
void deactivate (const T &t)
const IndexBaseType & index_access () const
IndexBaseType & index_access ()
BaseAccessor & base_accessor ()
const BaseAccessor & base_accessor () const
Additional Inherited Members
Private Types inherited from wmtk::attribute::IndexFlagAccessor< wmtk::Mesh >
enum class FlagBit
using BaseAccessor = Accessor< char, wmtk::Mesh, 1 >
Private Member Functions inherited from wmtk::attribute::IndexFlagAccessor< wmtk::Mesh >
IndexFlagAccessor (BaseAccessor acc)
IndexFlagAccessor (const IndexFlagAccessor< MeshType2 > &o)
bool is_active (int64_t t) const
void activate (int64_t t)
void deactivate (int64_t t)
BaseAccessor & base_accessor ()
const BaseAccessor & base_accessor () const
operator BaseAccessor () const
IndexFlagAccessor index_access () const
Static Private Member Functions inherited from wmtk::attribute::IndexFlagAccessor< wmtk::Mesh >
static bool _is_active (char value)
static void _activate (char &value)
static void _deactivate (char &value)
constexpr static char inverse_mask (FlagBit bit)
Private Attributes inherited from wmtk::attribute::IndexFlagAccessor< wmtk::Mesh >
BaseAccessor m_base_accessor
Detailed Description
template<typename MeshType = wmtk::Mesh>
class wmtk::attribute::FlagAccessor< MeshType >
Definition at line 54 of file FlagAccessor.hpp.
Member Typedef Documentation
IndexBaseType
template<typename MeshType = wmtk::Mesh> using wmtk::attribute::FlagAccessor< MeshType >::IndexBaseType = IndexFlagAccessor<MeshType>
Definition at line 58 of file FlagAccessor.hpp.
Member Enumeration Documentation
FlagBit
template<typename MeshType = wmtk::Mesh> enum wmtk::attribute::FlagAccessor::FlagBit : char strong
Enumerator
Active
Definition at line 57 of file FlagAccessor.hpp.
Constructor & Destructor Documentation
FlagAccessor()
template<typename MeshType = wmtk::Mesh> template<typename MeshType2 > wmtk::attribute::FlagAccessor< MeshType >::FlagAccessor (const FlagAccessor< MeshType2 > & o) inline
Definition at line 64 of file FlagAccessor.hpp.
Member Function Documentation
activate()
template<typename MeshType = wmtk::Mesh> template<typename T > void wmtk::attribute::FlagAccessor< MeshType >::activate (const T & t) inline
Definition at line 74 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_activate(), and wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
base_accessor() [1/2]
template<typename MeshType = wmtk::Mesh> BaseAccessor& wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor inline
Definition at line 42 of file FlagAccessor.hpp.
Referenced by wmtk::Mesh::request_simplex_indices().
base_accessor() [2/2]
template<typename MeshType = wmtk::Mesh> const BaseAccessor& wmtk::attribute::IndexFlagAccessor< MeshType >::base_accessor inline
Definition at line 43 of file FlagAccessor.hpp.
deactivate()
template<typename MeshType = wmtk::Mesh> template<typename T > void wmtk::attribute::FlagAccessor< MeshType >::deactivate (const T & t) inline
Definition at line 79 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_deactivate(), and wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
index_access() [1/2]
template<typename MeshType = wmtk::Mesh> IndexBaseType& wmtk::attribute::FlagAccessor< MeshType >::index_access () inline
Definition at line 86 of file FlagAccessor.hpp.
index_access() [2/2]
template<typename MeshType = wmtk::Mesh> const IndexBaseType& wmtk::attribute::FlagAccessor< MeshType >::index_access () const inline
Definition at line 85 of file FlagAccessor.hpp.
Referenced by wmtk::Mesh::consolidate(), wmtk::Mesh::get_all(), wmtk::Mesh::get_all_id_simplex(), wmtk::EdgeMesh::initialize(), wmtk::TriMesh::initialize(), wmtk::TetMesh::initialize(), wmtk::PointMesh::initialize(), wmtk::TetMesh::is_connectivity_valid(), wmtk::TriMesh::is_connectivity_valid(), wmtk::EdgeMesh::is_connectivity_valid(), and wmtk::Mesh::request_simplex_indices().
is_active()
template<typename MeshType = wmtk::Mesh> template<typename T > bool wmtk::attribute::FlagAccessor< MeshType >::is_active (const T & t) const inline
Definition at line 69 of file FlagAccessor.hpp.
References wmtk::attribute::IndexFlagAccessor< MeshType >::_is_active(), and wmtk::attribute::IndexFlagAccessor< MeshType >::m_base_accessor.
The documentation for this class was generated from the following file:
src/wmtk/attribute/FlagAccessor.hpp