Wildmeshing Toolkit: wmtk::operations::internal::CollapseAlternateFacetData Class Reference
wmtk::operations::internal::CollapseAlternateFacetData Class Reference
#include <CollapseAlternateFacetData.hpp>
Public Types
using Data = CollapseAlternateFacetOptionData
using AltData = std::vector< Data >
Public Member Functions
CollapseAlternateFacetData ()
~CollapseAlternateFacetData ()
void add (const Mesh &m, const Tuple &input_tuple)
std::array< Tuple, 2 > get_alternatives (const PrimitiveType mesh_pt, const Tuple &t, const PrimitiveType simplex_dimension) const
Tuple get_alternative (const PrimitiveType mesh_pt, const Tuple &t, const PrimitiveType simplex_dimension) const
void sort ()
const Data & get_alternatives_data (const Tuple &t) const
AltData::const_iterator get_alternative_data_it (const int64_t &input_facet) const
Public Attributes
AltData m_data
Detailed Description
Definition at line 14 of file CollapseAlternateFacetData.hpp.
Member Typedef Documentation
AltData
using wmtk::operations::internal::CollapseAlternateFacetData::AltData = std::vector<Data>
Definition at line 32 of file CollapseAlternateFacetData.hpp.
Data
using wmtk::operations::internal::CollapseAlternateFacetData::Data = CollapseAlternateFacetOptionData
Definition at line 17 of file CollapseAlternateFacetData.hpp.
Constructor & Destructor Documentation
CollapseAlternateFacetData()
wmtk::operations::internal::CollapseAlternateFacetData::CollapseAlternateFacetData () default
~CollapseAlternateFacetData()
wmtk::operations::internal::CollapseAlternateFacetData::~CollapseAlternateFacetData () default
Member Function Documentation
add()
void wmtk::operations::internal::CollapseAlternateFacetData::add (const Mesh & m, const Tuple & input_tuple)
Definition at line 26 of file CollapseAlternateFacetData.cpp.
References m_data.
get_alternative()
Tuple wmtk::operations::internal::CollapseAlternateFacetData::get_alternative (const PrimitiveType mesh_pt, const Tuple & t, const PrimitiveType simplex_dimension) const
Definition at line 94 of file CollapseAlternateFacetData.cpp.
References get_alternatives().
get_alternative_data_it()
auto wmtk::operations::internal::CollapseAlternateFacetData::get_alternative_data_it (const int64_t & input_facet) const
Definition at line 42 of file CollapseAlternateFacetData.cpp.
get_alternatives()
std::array< Tuple, 2 > wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives (const PrimitiveType mesh_pt, const Tuple & t, const PrimitiveType simplex_dimension) const
Definition at line 63 of file CollapseAlternateFacetData.cpp.
References wmtk::autogen::SimplexDart::dart_from_tuple(), wmtk::multimesh::utils::find_local_dart_action(), get_alternatives_data(), and wmtk::autogen::SimplexDart::get_singleton().
Referenced by get_alternative().
get_alternatives_data()
auto wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives_data (const Tuple & t) const
Definition at line 57 of file CollapseAlternateFacetData.cpp.
Referenced by get_alternatives().
sort()
void wmtk::operations::internal::CollapseAlternateFacetData::sort ()
Definition at line 33 of file CollapseAlternateFacetData.cpp.
References m_data.
Member Data Documentation
m_data
AltData wmtk::operations::internal::CollapseAlternateFacetData::m_data
Definition at line 33 of file CollapseAlternateFacetData.hpp.
Referenced by add(), and sort().
The documentation for this class was generated from the following files:
src/wmtk/operations/internal/CollapseAlternateFacetData.hpp
src/wmtk/operations/internal/CollapseAlternateFacetData.cpp