Wildmeshing Toolkit: wmtk::SimplicialComplex Class Reference
wmtk::SimplicialComplex Class Reference
#include <SimplicialComplex.hpp>
Public Member Functions
const internal::SimplexSet & get_simplices () const
internal::SimplexSet get_simplices (const PrimitiveType &ptype) const
internal::SimplexSet get_vertices () const
internal::SimplexSet get_edges () const
internal::SimplexSet get_faces () const
internal::SimplexSet get_tetrahedra () const
std::vector< Simplex > get_simplex_vector () const
bool add_simplex (const Simplex &s)
Add simplex to the complex if it is not already in it.
void unify_with_complex (const SimplicialComplex &other)
bool operator== (const SimplicialComplex &other) const
SimplicialComplex (const Mesh &mm)
SimplicialComplex (const internal::SimplexLessFunctor &slf)
SimplicialComplex (const std::vector< Simplex > &ss, const Mesh &mm)
auto key_comp () const
Static Public Member Functions
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex get_union (const SimplicialComplex &sc1, const SimplicialComplex &sc2)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex get_intersection (const SimplicialComplex &A, const SimplicialComplex &B)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex boundary (const Mesh &m, const Simplex &s)
DEPRECATED Get the boundary of a simplex.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex simplex_with_boundary (const Mesh &m, const Simplex &s)
DEPRECATED the union of a simplex and its boundary.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION bool simplices_w_boundary_intersect (const Mesh &m, const Simplex &s1, const Simplex &s2)
DEPRECATED check if the intersection of simplices with their boundary is an empty set.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex top_coface_simplex (const Mesh &m, const Simplex &s)
DEPRECATED get all the the top_simplex of m which is a coface of Simplex s, this function can be used in computing closed_star and open_star.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex closed_star (const Mesh &m, const Simplex &s)
DEPRECATED The union of all simplices with boundary that have s in their boundary.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex link (const Mesh &m, const Simplex &s)
DEPRECATED The boundary of the closed star.
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION SimplicialComplex open_star (const Mesh &m, const Simplex &s)
DEPRECATED The closed star without its boundary.
static SimplicialComplex open_star (const TriMesh &m, const Simplex &s)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION bool link_cond (const Mesh &m, Tuple t)
static bool link_cond_bd_2d (const Mesh &m, Tuple t)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION bool link_cond_bd_1d (const Mesh &m, Tuple t)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION bool edge_collapse_possible_2d (const TriMesh &m, const Tuple &t)
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION std::vector< Simplex > vertex_one_ring (const Mesh &m, Tuple t)
DEPRECATED get one ring vertex neighbors of vertex in t
static WMTK_WARN_SIMPLICIAL_COMPLEX_DEPRECATION std::vector< Simplex > vertex_one_ring (const TriMesh &m, Tuple t)
DEPRECATED get one ring vertex neighbors of vertex in t
static std::vector< Simplex > k_ring (const Mesh &m, Tuple t, int k)
Private Attributes
internal::SimplexLessFunctor _slf
internal::SimplexSet _simplices
Detailed Description
Definition at line 27 of file SimplicialComplex.hpp.
Constructor & Destructor Documentation
SimplicialComplex() [1/3]
wmtk::SimplicialComplex::SimplicialComplex (const Mesh & mm) inline
Definition at line 61 of file SimplicialComplex.hpp.
Referenced by boundary(), closed_star(), link(), open_star(), simplex_with_boundary(), and top_coface_simplex().
SimplicialComplex() [2/3]
wmtk::SimplicialComplex::SimplicialComplex (const internal::SimplexLessFunctor & slf) inline
Definition at line 66 of file SimplicialComplex.hpp.
SimplicialComplex() [3/3]
wmtk::SimplicialComplex::SimplicialComplex (const std::vector< Simplex > & ss, const Mesh & mm) inline
Definition at line 71 of file SimplicialComplex.hpp.
References add_simplex().
Member Function Documentation
add_simplex()
bool wmtk::SimplicialComplex::add_simplex (const Simplex & s)
Add simplex to the complex if it is not already in it.
Returns
false if simplex is already in the complex
Definition at line 32 of file SimplicialComplex.cpp.
References _simplices.
Referenced by get_intersection(), SimplicialComplex(), and unify_with_complex().
boundary()
SimplicialComplex wmtk::SimplicialComplex::boundary (const Mesh & m, const Simplex & s) static
DEPRECATED Get the boundary of a simplex.
The boundary of a simplex are all incident lower dimensional simplices.
Tetrahedron: 4 faces, 6 edges, 4 vertices
Triange: 3 edges, 3 vertices
Edge: 2 vertices
Vertex: none
Definition at line 88 of file SimplicialComplex.cpp.
References wmtk::simplex::faces(), wmtk::simplex::SimplexCollection::simplex_vector(), and SimplicialComplex().
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::get_incident_tet_data().
closed_star()
SimplicialComplex wmtk::SimplicialComplex::closed_star (const Mesh & m, const Simplex & s) static
DEPRECATED The union of all simplices with boundary that have s in their boundary.
Example: The closed star of a vertex in a triangular mesh contains all triangles incident to the vertex and all vertices and edges incident to those triangles.
Definition at line 119 of file SimplicialComplex.cpp.
References wmtk::simplex::closed_star(), wmtk::simplex::SimplexCollection::simplex_vector(), and SimplicialComplex().
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::collapse_edge(), wmtk::TriMesh::TriMeshOperationExecutor::collapse_edge_single_mesh(), wmtk::mesh_utils::compute_vertex_normal(), wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::operations::utils::update_vertex_operation_hashes(), and wmtk::MultiMeshManager::update_vertex_operation_hashes_internal().
edge_collapse_possible_2d()
bool wmtk::SimplicialComplex::edge_collapse_possible_2d (const TriMesh & m, const Tuple & t) static
Definition at line 231 of file SimplicialComplex.cpp.
References wmtk::TriMesh::is_boundary_edge(), wmtk::TriMesh::is_boundary_vertex(), wmtk::TriMesh::next_edge(), wmtk::Mesh::switch_face(), and wmtk::Mesh::switch_vertex().
get_edges()
internal::SimplexSet wmtk::SimplicialComplex::get_edges () const inline
Definition at line 39 of file SimplicialComplex.hpp.
References wmtk::Edge, and get_simplices().
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::get_incident_tet_data(), wmtk::operations::utils::update_vertex_operation_hashes(), and wmtk::MultiMeshManager::update_vertex_operation_hashes_internal().
get_faces()
internal::SimplexSet wmtk::SimplicialComplex::get_faces () const inline
Definition at line 40 of file SimplicialComplex.hpp.
References wmtk::Face, and get_simplices().
Referenced by wmtk::TriMesh::TriMeshOperationExecutor::collapse_edge_single_mesh(), wmtk::TetMesh::is_boundary_vertex(), wmtk::operations::utils::update_vertex_operation_hashes(), and wmtk::MultiMeshManager::update_vertex_operation_hashes_internal().
get_intersection()
SimplicialComplex wmtk::SimplicialComplex::get_intersection (const SimplicialComplex & A, const SimplicialComplex & B) static
Definition at line 71 of file SimplicialComplex.cpp.
References add_simplex(), get_simplices(), and key_comp().
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), link_cond(), and simplices_w_boundary_intersect().
get_simplex_vector()
std::vector< Simplex > wmtk::SimplicialComplex::get_simplex_vector () const
Definition at line 27 of file SimplicialComplex.cpp.
References _simplices.
get_simplices() [1/2]
const internal::SimplexSet& wmtk::SimplicialComplex::get_simplices () const inline
Definition at line 34 of file SimplicialComplex.hpp.
References _simplices.
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), get_edges(), get_faces(), get_intersection(), wmtk::TetMesh::TetMeshOperationExecutor::get_split_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_split_simplices_to_delete(), get_tetrahedra(), get_vertices(), k_ring(), link_cond_bd_2d(), simplices_w_boundary_intersect(), unify_with_complex(), wmtk::operations::utils::update_vertex_operation_multimesh_map_hash(), and wmtk::MultiMeshManager::update_vertex_operation_multimesh_map_hash_internal().
get_simplices() [2/2]
internal::SimplexSet wmtk::SimplicialComplex::get_simplices (const PrimitiveType & ptype) const
Definition at line 15 of file SimplicialComplex.cpp.
References _simplices.
get_tetrahedra()
internal::SimplexSet wmtk::SimplicialComplex::get_tetrahedra () const inline
Definition at line 41 of file SimplicialComplex.hpp.
References get_simplices(), and wmtk::Tetrahedron.
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::collapse_edge(), wmtk::operations::utils::update_vertex_operation_hashes(), and wmtk::MultiMeshManager::update_vertex_operation_hashes_internal().
get_union()
SimplicialComplex wmtk::SimplicialComplex::get_union (const SimplicialComplex & sc1, const SimplicialComplex & sc2) static
Definition at line 62 of file SimplicialComplex.cpp.
References unify_with_complex().
get_vertices()
internal::SimplexSet wmtk::SimplicialComplex::get_vertices () const inline
Definition at line 38 of file SimplicialComplex.hpp.
References get_simplices(), and wmtk::Vertex.
Referenced by wmtk::operations::utils::update_vertex_operation_hashes(), and wmtk::MultiMeshManager::update_vertex_operation_hashes_internal().
k_ring()
std::vector< Simplex > wmtk::SimplicialComplex::k_ring (const Mesh & m, Tuple t, int k) static
Definition at line 305 of file SimplicialComplex.cpp.
References get_simplices(), unify_with_complex(), wmtk::Vertex, and vertex_one_ring().
key_comp()
auto wmtk::SimplicialComplex::key_comp () const inline
Definition at line 80 of file SimplicialComplex.hpp.
References _simplices.
Referenced by get_intersection().
link()
SimplicialComplex wmtk::SimplicialComplex::link (const Mesh & m, const Simplex & s) static
DEPRECATED The boundary of the closed star.
Example: The link of a vertex in a triangle mesh is the ring of edges and vertices surrounding it.
Definition at line 125 of file SimplicialComplex.cpp.
References wmtk::simplex::link(), wmtk::simplex::SimplexCollection::simplex_vector(), and SimplicialComplex().
Referenced by link_cond().
link_cond()
bool wmtk::SimplicialComplex::link_cond (const Mesh & m, Tuple t) static
Definition at line 142 of file SimplicialComplex.cpp.
References wmtk::Edge, get_intersection(), link(), wmtk::Mesh::switch_tuple(), and wmtk::Vertex.
Referenced by link_cond_bd_2d().
link_cond_bd_1d()
bool wmtk::SimplicialComplex::link_cond_bd_1d (const Mesh & m, Tuple t) static
Definition at line 214 of file SimplicialComplex.cpp.
References wmtk::simplex::utils::SimplexComparisons::equal(), wmtk::Mesh::is_boundary(), wmtk::Mesh::switch_tuple(), wmtk::Mesh::top_cell_dimension(), and wmtk::Vertex.
link_cond_bd_2d()
bool wmtk::SimplicialComplex::link_cond_bd_2d (const Mesh & m, Tuple t) static
Definition at line 155 of file SimplicialComplex.cpp.
References wmtk::Edge, wmtk::simplex::utils::SimplexComparisons::equal(), get_simplices(), wmtk::Mesh::is_boundary(), link_cond(), open_star(), wmtk::Mesh::switch_tuple(), wmtk::Mesh::top_cell_dimension(), and wmtk::Vertex.
open_star() [1/2]
SimplicialComplex wmtk::SimplicialComplex::open_star (const Mesh & m, const Simplex & s) static
DEPRECATED The closed star without its boundary.
For performance reasons, closed_star should be used whenever possible.
Definition at line 131 of file SimplicialComplex.cpp.
References wmtk::simplex::open_star(), wmtk::simplex::SimplexCollection::simplex_vector(), and SimplicialComplex().
Referenced by wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TetMesh::TetMeshOperationExecutor::get_split_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_split_simplices_to_delete(), wmtk::TetMesh::is_boundary_vertex(), and link_cond_bd_2d().
open_star() [2/2]
SimplicialComplex wmtk::SimplicialComplex::open_star (const TriMesh & m, const Simplex & s) static
Definition at line 136 of file SimplicialComplex.cpp.
References wmtk::simplex::open_star(), wmtk::simplex::SimplexCollection::simplex_vector(), and SimplicialComplex().
operator==()
bool wmtk::SimplicialComplex::operator== (const SimplicialComplex & other) const
Definition at line 46 of file SimplicialComplex.cpp.
References _simplices.
simplex_with_boundary()
SimplicialComplex wmtk::SimplicialComplex::simplex_with_boundary (const Mesh & m, const Simplex & s) static
DEPRECATED the union of a simplex and its boundary.
Definition at line 94 of file SimplicialComplex.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::simplex::faces(), wmtk::simplex::SimplexCollection::simplex_vector(), SimplicialComplex(), and wmtk::simplex::SimplexCollection::sort_and_clean().
Referenced by simplices_w_boundary_intersect().
simplices_w_boundary_intersect()
bool wmtk::SimplicialComplex::simplices_w_boundary_intersect (const Mesh & m, const Simplex & s1, const Simplex & s2) static
DEPRECATED check if the intersection of simplices with their boundary is an empty set.
Definition at line 102 of file SimplicialComplex.cpp.
References get_intersection(), get_simplices(), and simplex_with_boundary().
top_coface_simplex()
SimplicialComplex wmtk::SimplicialComplex::top_coface_simplex (const Mesh & m, const Simplex & s) static
DEPRECATED get all the the top_simplex of m which is a coface of Simplex s, this function can be used in computing closed_star and open_star.
Definition at line 113 of file SimplicialComplex.cpp.
References wmtk::simplex::SimplexCollection::simplex_vector(), SimplicialComplex(), and wmtk::simplex::top_dimension_cofaces().
unify_with_complex()
void wmtk::SimplicialComplex::unify_with_complex (const SimplicialComplex & other)
Definition at line 38 of file SimplicialComplex.cpp.
References add_simplex(), and get_simplices().
Referenced by get_union(), and k_ring().
vertex_one_ring() [1/2]
std::vector< Simplex > wmtk::SimplicialComplex::vertex_one_ring (const Mesh & m, Tuple t) static
DEPRECATED get one ring vertex neighbors of vertex in t
The vertex one ring does not include the vertex of the tuple itself.
Definition at line 270 of file SimplicialComplex.cpp.
References wmtk::simplex::link(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
Referenced by wmtk::operations::VertexLaplacianSmooth::execute(), wmtk::function::EdgeValenceEnergy::get_value(), and k_ring().
vertex_one_ring() [2/2]
std::vector< Simplex > wmtk::SimplicialComplex::vertex_one_ring (const TriMesh & m, Tuple t) static
DEPRECATED get one ring vertex neighbors of vertex in t
The vertex one ring does not include the vertex of the tuple itself.
Definition at line 276 of file SimplicialComplex.cpp.
References wmtk::TriMesh::is_boundary_edge(), wmtk::Mesh::switch_edge(), wmtk::Mesh::switch_face(), wmtk::Mesh::switch_vertex(), and wmtk::simplex::Simplex::vertex().
Member Data Documentation
_simplices
internal::SimplexSet wmtk::SimplicialComplex::_simplices private
Definition at line 31 of file SimplicialComplex.hpp.
Referenced by add_simplex(), get_simplex_vector(), get_simplices(), key_comp(), and operator==().
_slf
internal::SimplexLessFunctor wmtk::SimplicialComplex::_slf private
Definition at line 30 of file SimplicialComplex.hpp.
The documentation for this class was generated from the following files:
src/wmtk/SimplicialComplex.hpp
src/wmtk/SimplicialComplex.cpp