Wildmeshing Toolkit: wmtk::attribute::AttributeScope< T > Class Template Reference
wmtk::attribute::AttributeScope< T > Class Template Reference
#include <AttributeScope.hpp>
Public Member Functions
AttributeScope ()
~AttributeScope ()
AttributeScope (std::unique_ptr< AttributeScope< T >> &&parent)
Public Member Functions inherited from wmtk::attribute::AttributeCache< T >
AttributeCache ()
~AttributeCache ()
std::pair< typename DataStorage::iterator, bool > load_it (int64_t index) const
void clear ()
void flush_to (Attribute< T > &attribute)
void flush_to (AttributeCache< T > &other)
void flush_to (const Attribute< T > &attribute, std::vector< T > &other) const
Private Types
using MapResult = typename AttributeCache< T >::MapResult
using ConstMapResult = typename AttributeCache< T >::ConstMapResult
using DataStorage = typename AttributeCache< T >::DataStorage
Private Member Functions
MapResult load_cached_vector_value (AccessorBase< T > &accessor, int64_t index)
ConstMapResult load_const_cached_vector_value (const AccessorBase< T > &accessor, int64_t index) const
T & load_cached_scalar_value (AccessorBase< T > &accessor, int64_t index)
T load_const_cached_scalar_value (const AccessorBase< T > &accessor, int64_t index) const
DataStorage::iterator load_it (const AccessorBase< T > &accessor, AttributeAccessMode mode, int64_t index, bool mark_dirty=false) const
AttributeCache< T > & get_cache ()
void flush (Attribute< T > &attr)
void flush_changes_to_vector (const Attribute< T > &attr, std::vector< T > &data)
std::unique_ptr< AttributeScope< T > > pop_parent ()
MapResult vector_attribute (AccessorBase< T > &accessor, AttributeAccessMode mode, int64_t index)
ConstMapResult const_vector_attribute (const AccessorBase< T > &accessor, AttributeAccessMode mode, int64_t index) const
T & scalar_attribute (AccessorBase< T > &accessor, AttributeAccessMode mode, int64_t index)
T const_scalar_attribute (const AccessorBase< T > &accessor, AttributeAccessMode mode, int64_t index) const
int64_t depth () const
int64_t checkpoint_index () const
const AttributeScope< T > * parent () const
AttributeScope< T > * parent ()
Private Attributes
std::unique_ptr< AttributeScope< T > > m_parent
int64_t m_checkpoint_index = -1
Friends
class CachingAccessor< T >
class AttributeScopeStack< T >
Additional Inherited Members
Public Types inherited from wmtk::attribute::AttributeCache< T >
using Data = AttributeCacheData< T >
using DataStorage = std::map< int64_t, Data, std::less< int64_t > >
using MapResult = typename AccessorBase< T >::MapResult
using ConstMapResult = typename AccessorBase< T >::ConstMapResult
Protected Attributes inherited from wmtk::attribute::AttributeCache< T >
DataStorage m_data
Detailed Description
template<typename T>
class wmtk::attribute::AttributeScope< T >
Definition at line 18 of file AttributeScope.hpp.
Member Typedef Documentation
ConstMapResult
template<typename T > using wmtk::attribute::AttributeScope< T >::ConstMapResult = typename AttributeCache<T>::ConstMapResult private
Definition at line 30 of file AttributeScope.hpp.
DataStorage
template<typename T > using wmtk::attribute::AttributeScope< T >::DataStorage = typename AttributeCache<T>::DataStorage private
Definition at line 31 of file AttributeScope.hpp.
MapResult
template<typename T > using wmtk::attribute::AttributeScope< T >::MapResult = typename AttributeCache<T>::MapResult private
Definition at line 29 of file AttributeScope.hpp.
Constructor & Destructor Documentation
AttributeScope() [1/2]
template<typename T > wmtk::attribute::AttributeScope< T >::AttributeScope () default
~AttributeScope()
template<typename T > wmtk::attribute::AttributeScope< T >::~AttributeScope () default
AttributeScope() [2/2]
template<typename T > wmtk::attribute::AttributeScope< T >::AttributeScope (std::unique_ptr< AttributeScope< T >> && parent)
Member Function Documentation
checkpoint_index()
template<typename T > int64_t wmtk::attribute::AttributeScope< T >::checkpoint_index () const inline private
Definition at line 72 of file AttributeScope.hpp.
References wmtk::attribute::AttributeScope< T >::m_checkpoint_index.
const_scalar_attribute()
template<typename T > auto wmtk::attribute::AttributeScope< T >::const_scalar_attribute (const AccessorBase< T > & accessor, AttributeAccessMode mode, int64_t index) const private
Definition at line 128 of file AttributeScope.cpp.
const_vector_attribute()
template<typename T > auto wmtk::attribute::AttributeScope< T >::const_vector_attribute (const AccessorBase< T > & accessor, AttributeAccessMode mode, int64_t index) const private
Definition at line 109 of file AttributeScope.cpp.
depth()
template<typename T > int64_t wmtk::attribute::AttributeScope< T >::depth private
Definition at line 155 of file AttributeScope.cpp.
References wmtk::attribute::AttributeScope< T >::depth().
Referenced by wmtk::attribute::AttributeScope< T >::depth().
flush()
template<typename T > void wmtk::attribute::AttributeScope< T >::flush (Attribute< T > & attr) private
Definition at line 137 of file AttributeScope.cpp.
flush_changes_to_vector()
template<typename T > void wmtk::attribute::AttributeScope< T >::flush_changes_to_vector (const Attribute< T > & attr, std::vector< T > & data) private
Definition at line 146 of file AttributeScope.cpp.
References wmtk::attribute::AttributeScope< T >::flush_changes_to_vector().
Referenced by wmtk::attribute::AttributeScope< T >::flush_changes_to_vector().
get_cache()
template<typename T > AttributeCache<T>& wmtk::attribute::AttributeScope< T >::get_cache () inline private
Definition at line 45 of file AttributeScope.hpp.
load_cached_scalar_value()
template<typename T > auto wmtk::attribute::AttributeScope< T >::load_cached_scalar_value (AccessorBase< T > & accessor, int64_t index) private
Definition at line 38 of file AttributeScope.cpp.
load_cached_vector_value()
template<typename T > auto wmtk::attribute::AttributeScope< T >::load_cached_vector_value (AccessorBase< T > & accessor, int64_t index) private
Definition at line 53 of file AttributeScope.cpp.
load_const_cached_scalar_value()
template<typename T > auto wmtk::attribute::AttributeScope< T >::load_const_cached_scalar_value (const AccessorBase< T > & accessor, int64_t index) const private
Definition at line 22 of file AttributeScope.cpp.
load_const_cached_vector_value()
template<typename T > auto wmtk::attribute::AttributeScope< T >::load_const_cached_vector_value (const AccessorBase< T > & accessor, int64_t index) const private
Definition at line 66 of file AttributeScope.cpp.
load_it()
template<typename T > auto wmtk::attribute::AttributeScope< T >::load_it (const AccessorBase< T > & accessor, AttributeAccessMode mode, int64_t index, bool mark_dirty = false) const private
Definition at line 80 of file AttributeScope.cpp.
parent() [1/2]
template<typename T > AttributeScope<T>* wmtk::attribute::AttributeScope< T >::parent () inline private
Definition at line 75 of file AttributeScope.hpp.
References wmtk::attribute::AttributeScope< T >::m_parent.
parent() [2/2]
template<typename T > const AttributeScope<T>* wmtk::attribute::AttributeScope< T >::parent () const inline private
Definition at line 74 of file AttributeScope.hpp.
References wmtk::attribute::AttributeScope< T >::m_parent.
pop_parent()
template<typename T > std::unique_ptr< AttributeScope< T > > wmtk::attribute::AttributeScope< T >::pop_parent private
Definition at line 16 of file AttributeScope.cpp.
scalar_attribute()
template<typename T > auto wmtk::attribute::AttributeScope< T >::scalar_attribute (AccessorBase< T > & accessor, AttributeAccessMode mode, int64_t index) private
Definition at line 119 of file AttributeScope.cpp.
vector_attribute()
template<typename T > auto wmtk::attribute::AttributeScope< T >::vector_attribute (AccessorBase< T > & accessor, AttributeAccessMode mode, int64_t index) private
Definition at line 99 of file AttributeScope.cpp.
Friends And Related Function Documentation
AttributeScopeStack< T >
template<typename T > friend class AttributeScopeStack< T > friend
Definition at line 1 of file AttributeScope.hpp.
CachingAccessor< T >
template<typename T > friend class CachingAccessor< T > friend
Definition at line 1 of file AttributeScope.hpp.
Member Data Documentation
m_checkpoint_index
template<typename T > int64_t wmtk::attribute::AttributeScope< T >::m_checkpoint_index = -1 private
Definition at line 79 of file AttributeScope.hpp.
Referenced by wmtk::attribute::AttributeScope< T >::checkpoint_index().
m_parent
template<typename T > std::unique_ptr<AttributeScope<T> > wmtk::attribute::AttributeScope< T >::m_parent private
Definition at line 78 of file AttributeScope.hpp.
Referenced by wmtk::attribute::AttributeScope< T >::parent().
The documentation for this class was generated from the following files:
src/wmtk/attribute/AttributeScope.hpp
src/wmtk/attribute/AttributeScope.cpp