Wildmeshing Toolkit: wmtk::operations::AttributesUpdateBase Class Reference
wmtk::operations::AttributesUpdateBase Class Reference
#include <AttributesUpdateBase.hpp>
Public Member Functions
AttributesUpdateBase (Mesh &m)
virtual PrimitiveType primitive_type () const override
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
std::vector< Simplex > operator() (const Simplex &simplex)
virtual std::vector< double > priority (const Simplex &simplex) const
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< std::vector< double >(const Simplex &)> &func)
std::shared_ptr< operations::NewAttributeStrategy > get_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void set_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::NewAttributeStrategy > &other)
std::shared_ptr< operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void add_transfer_strategy (const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
virtual bool before (const Simplex &simplex) const
virtual bool after (const std::vector< Simplex > &unmods, const std::vector< Simplex > &mods) const
void update_cell_hashes (const std::vector< Tuple > &cells)
utility for subclasses
Tuple resurrect_tuple (const Tuple &tuple) const
utility for subclasses
Accessor< long > hash_accessor ()
utility for subclasses
ConstAccessor< long > hash_accessor () const
utility for subclasses
void apply_attribute_transfer (const std::vector< Simplex > &direct_mods)
Protected Member Functions
virtual std::vector< Simplex > unmodified_primitives (const Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
virtual std::vector< Simplex > execute (const Simplex &simplex) override
returns an empty vector in case of failure
Additional Inherited Members
Protected Attributes inherited from wmtk::operations::Operation
InvariantCollection m_invariants
std::vector< std::shared_ptr< operations::NewAttributeStrategy > > m_new_attr_strategies
std::vector< std::shared_ptr< operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Definition at line 7 of file AttributesUpdateBase.hpp.
Constructor & Destructor Documentation
AttributesUpdateBase()
wmtk::operations::AttributesUpdateBase::AttributesUpdateBase (Mesh & m)
Definition at line 8 of file AttributesUpdateBase.cpp.
Member Function Documentation
execute()
std::vector< Simplex > wmtk::operations::AttributesUpdateBase::execute (const Simplex & simplex) override protected virtual
returns an empty vector in case of failure
Implements wmtk::operations::Operation.
Reimplemented in wmtk::operations::VertexTangentialLaplacianSmooth, wmtk::operations::VertexLaplacianSmooth, and wmtk::operations::OptimizationSmoothing.
Definition at line 18 of file AttributesUpdateBase.cpp.
References wmtk::simplex::closed_star(), wmtk::operations::Operation::hash_accessor(), wmtk::operations::Operation::mesh(), wmtk::simplex::Simplex::primitive_type(), primitive_type(), wmtk::operations::Operation::resurrect_tuple(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::simplex::Simplex::tuple(), and wmtk::Mesh::update_vertex_operation_hashes().
Referenced by wmtk::operations::OptimizationSmoothing::execute(), and wmtk::operations::VertexLaplacianSmooth::execute().
primitive_type()
virtual PrimitiveType wmtk::operations::AttributesUpdateBase::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 12 of file AttributesUpdateBase.hpp.
References wmtk::Vertex.
Referenced by execute().
unmodified_primitives()
std::vector< Simplex > wmtk::operations::AttributesUpdateBase::unmodified_primitives (const Simplex & simplex) const override protected virtual
Returns all simplices that will be potentially affected by the operation.
Implements wmtk::operations::Operation.
Definition at line 12 of file AttributesUpdateBase.cpp.
The documentation for this class was generated from the following files:
src/wmtk/operations/AttributesUpdateBase.hpp
src/wmtk/operations/AttributesUpdateBase.cpp