Wildmeshing Toolkit: wmtk::operations::EdgeCollapse Class Reference
wmtk::operations::EdgeCollapse Class Reference
#include <EdgeCollapse.hpp>
Public Member Functions
EdgeCollapse (Mesh &m)
PrimitiveType primitive_type () const override
void set_standard_strategy (const attribute::MeshAttributeHandleVariant &attribute, const wmtk::operations::NewAttributeStrategy::CollapseBasicStrategy &strategy=wmtk::operations::NewAttributeStrategy::CollapseBasicStrategy::Default)
Public Member Functions inherited from wmtk::operations::MeshOperation
MeshOperation (Mesh &m)
~MeshOperation ()=default
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
std::vector< Simplex > operator() (const Simplex &simplex)
virtual std::vector< double > priority (const Simplex &simplex) const
const bool use_random_priority () const
bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< std::vector< double >(const Simplex &)> &func)
std::shared_ptr< operations::NewAttributeStrategy > get_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void set_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::NewAttributeStrategy > &other)
std::shared_ptr< operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void add_transfer_strategy (const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
virtual bool before (const Simplex &simplex) const
virtual bool after (const std::vector< Simplex > &unmods, const std::vector< Simplex > &mods) const
void update_cell_hashes (const std::vector< Tuple > &cells)
utility for subclasses
Tuple resurrect_tuple (const Tuple &tuple) const
utility for subclasses
Accessor< long > hash_accessor ()
utility for subclasses
ConstAccessor< long > hash_accessor () const
utility for subclasses
void apply_attribute_transfer (const std::vector< Simplex > &direct_mods)
Protected Member Functions
std::vector< Simplex > execute (EdgeMesh &mesh, const Simplex &simplex) override
std::vector< Simplex > unmodified_primitives (const EdgeMesh &mesh, const Simplex &simplex) const override
std::vector< Simplex > execute (TriMesh &mesh, const Simplex &simplex) override
std::vector< Simplex > unmodified_primitives (const TriMesh &mesh, const Simplex &simplex) const override
std::vector< Simplex > execute (TetMesh &mesh, const Simplex &simplex) override
std::vector< Simplex > unmodified_primitives (const TetMesh &mesh, const Simplex &simplex) const override
Protected Member Functions inherited from wmtk::operations::MeshOperation
std::vector< Simplex > execute (const Simplex &simplex) override
returns an empty vector in case of failure
std::vector< Simplex > unmodified_primitives (const Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
Additional Inherited Members
Protected Attributes inherited from wmtk::operations::Operation
InvariantCollection m_invariants
std::vector< std::shared_ptr< operations::NewAttributeStrategy > > m_new_attr_strategies
std::vector< std::shared_ptr< operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
Definition at line 6 of file EdgeCollapse.hpp.
Constructor & Destructor Documentation
EdgeCollapse()
wmtk::operations::EdgeCollapse::EdgeCollapse (Mesh & m)
Definition at line 14 of file EdgeCollapse.cpp.
References wmtk::Mesh::m_attributes, wmtk::operations::Operation::m_new_attr_strategies, and wmtk::Mesh::top_cell_dimension().
Member Function Documentation
execute() [1/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::execute (EdgeMesh & mesh, const Simplex & simplex) override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 41 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::m_new_attr_strategies, wmtk::operations::EdgeOperationData::m_output_tuple, wmtk::operations::Operation::mesh(), wmtk::operations::utils::multi_mesh_edge_collapse(), wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
execute() [2/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::execute (TetMesh & mesh, const Simplex & simplex) override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 87 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::m_new_attr_strategies, wmtk::operations::EdgeOperationData::m_output_tuple, wmtk::operations::Operation::mesh(), wmtk::operations::utils::multi_mesh_edge_collapse(), wmtk::simplex::Simplex::tuple(), and wmtk::simplex::Simplex::vertex().
execute() [3/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::execute (TriMesh & mesh, const Simplex & simplex) override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 64 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::m_new_attr_strategies, wmtk::operations::EdgeOperationData::m_output_tuple, wmtk::operations::Operation::mesh(), wmtk::operations::utils::multi_mesh_edge_collapse(), wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
primitive_type()
PrimitiveType wmtk::operations::EdgeCollapse::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 12 of file EdgeCollapse.hpp.
References wmtk::Edge.
Referenced by wmtk::operations::composite::TetEdgeSwap::execute(), and wmtk::operations::composite::TriEdgeSwap::execute().
set_standard_strategy()
void wmtk::operations::EdgeCollapse::set_standard_strategy (const attribute::MeshAttributeHandleVariant & attribute, const wmtk::operations::NewAttributeStrategy::CollapseBasicStrategy & strategy = wmtk::operations::NewAttributeStrategy::CollapseBasicStrategy::Default)
Definition at line 107 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::mesh(), and wmtk::operations::Operation::set_strategy().
unmodified_primitives() [1/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::unmodified_primitives (const EdgeMesh & mesh, const Simplex & simplex) const override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 51 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::mesh(), wmtk::Mesh::parent_scope(), wmtk::Mesh::switch_vertex(), wmtk::simplex::Simplex::tuple(), and wmtk::simplex::Simplex::vertex().
unmodified_primitives() [2/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::unmodified_primitives (const TetMesh & mesh, const Simplex & simplex) const override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 95 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::mesh(), wmtk::Mesh::parent_scope(), wmtk::Mesh::switch_vertex(), wmtk::simplex::Simplex::tuple(), and wmtk::simplex::Simplex::vertex().
unmodified_primitives() [3/3]
std::vector< Simplex > wmtk::operations::EdgeCollapse::unmodified_primitives (const TriMesh & mesh, const Simplex & simplex) const override protected virtual
Implements wmtk::operations::MeshOperation.
Definition at line 74 of file EdgeCollapse.cpp.
References wmtk::operations::Operation::mesh(), wmtk::Mesh::parent_scope(), wmtk::Mesh::switch_vertex(), wmtk::simplex::Simplex::tuple(), and wmtk::simplex::Simplex::vertex().
The documentation for this class was generated from the following files:
src/wmtk/operations/EdgeCollapse.hpp
src/wmtk/operations/EdgeCollapse.cpp