Wildmeshing Toolkit: wmtk::utils::EigenMatrixWriter Class Reference
wmtk::utils::EigenMatrixWriter Class Reference
#include <EigenMatrixWriter.hpp>
Public Member Functions
EigenMatrixWriter ()=default
~EigenMatrixWriter ()=default
void get_position_matrix (MatrixX< double > &matrix)
void get_TV_matrix (MatrixX< int64_t > &matrix)
void get_FV_matrix (MatrixX< int64_t > &matrix)
void get_EV_matrix (MatrixX< int64_t > &matrix)
void get_double_matrix (const std::string &name, const PrimitiveType type, MatrixX< double > &matrix)
void get_int64_t_matrix (const std::string &name, const PrimitiveType type, MatrixX< int64_t > &matrix)
void get_char_matrix (const std::string &name, const PrimitiveType type, MatrixX< char > &matrix)
void get_Rational_matrix (const std::string &name, const PrimitiveType type, MatrixX< Rational > &matrix)
void write_top_simplex_type (const PrimitiveType type) override
void write_absolute_id (const std::vector< int64_t > &id) override
void write_capacities (const std::vector< int64_t > &capacities) override
bool write (const int dim) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< char > &val, const char default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< int64_t > &val, const int64_t default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< double > &val, const double default_val) override
void write (const std::string &name, const int64_t type, const int64_t stride, const std::vector< Rational > &val, const Rational &default_val) override
Public Member Functions inherited from wmtk::MeshWriter
virtual ~MeshWriter ()
Private Member Functions
template<typename T >
void write_internal (std::map< std::pair< std::string, PrimitiveType >, MatrixX< T >> &Ts, const std::string &name, const int64_t type, const int64_t stride, const std::vector< T > &val, const T &default_val)
Private Attributes
std::map< std::pair< std::string, PrimitiveType >, MatrixX< double > > doubles
std::map< std::pair< std::string, PrimitiveType >, MatrixX< int64_t > > int64_ts
std::map< std::pair< std::string, PrimitiveType >, MatrixX< char > > chars
std::map< std::pair< std::string, PrimitiveType >, MatrixX< Rational > > Rationals
Additional Inherited Members
Protected Attributes inherited from wmtk::MeshWriter
int64_t m_mm_level = 0
Detailed Description
Definition at line 8 of file EigenMatrixWriter.hpp.
Constructor & Destructor Documentation
EigenMatrixWriter()
wmtk::utils::EigenMatrixWriter::EigenMatrixWriter () default
~EigenMatrixWriter()
wmtk::utils::EigenMatrixWriter::~EigenMatrixWriter () default
Member Function Documentation
get_char_matrix()
void wmtk::utils::EigenMatrixWriter::get_char_matrix (const std::string & name, const PrimitiveType type, MatrixX< char > & matrix)
Definition at line 49 of file EigenMatrixWriter.cpp.
References chars.
get_double_matrix()
void wmtk::utils::EigenMatrixWriter::get_double_matrix (const std::string & name, const PrimitiveType type, MatrixX< double > & matrix)
Definition at line 25 of file EigenMatrixWriter.cpp.
References doubles.
Referenced by get_position_matrix(), and wmtk::components::triangle_insertion().
get_EV_matrix()
void wmtk::utils::EigenMatrixWriter::get_EV_matrix (MatrixX< int64_t > & matrix)
Definition at line 20 of file EigenMatrixWriter.cpp.
References wmtk::Edge, and get_int64_t_matrix().
get_FV_matrix()
void wmtk::utils::EigenMatrixWriter::get_FV_matrix (MatrixX< int64_t > & matrix)
Definition at line 15 of file EigenMatrixWriter.cpp.
References get_int64_t_matrix(), and wmtk::Triangle.
Referenced by wmtk::components::fusion(), TEST_CASE(), and wmtk::components::triangle_insertion().
get_int64_t_matrix()
void wmtk::utils::EigenMatrixWriter::get_int64_t_matrix (const std::string & name, const PrimitiveType type, MatrixX< int64_t > & matrix)
Definition at line 37 of file EigenMatrixWriter.cpp.
References int64_ts.
Referenced by get_EV_matrix(), get_FV_matrix(), and get_TV_matrix().
get_position_matrix()
void wmtk::utils::EigenMatrixWriter::get_position_matrix (MatrixX< double > & matrix)
Definition at line 5 of file EigenMatrixWriter.cpp.
References get_double_matrix(), and wmtk::Vertex.
Referenced by wmtk::components::fusion(), and TEST_CASE().
get_Rational_matrix()
void wmtk::utils::EigenMatrixWriter::get_Rational_matrix (const std::string & name, const PrimitiveType type, MatrixX< Rational > & matrix)
Definition at line 61 of file EigenMatrixWriter.cpp.
References Rationals.
get_TV_matrix()
void wmtk::utils::EigenMatrixWriter::get_TV_matrix (MatrixX< int64_t > & matrix)
Definition at line 10 of file EigenMatrixWriter.cpp.
References get_int64_t_matrix(), and wmtk::Tetrahedron.
Referenced by wmtk::components::fusion(), and wmtk::components::triangle_insertion().
write() [1/5]
bool wmtk::utils::EigenMatrixWriter::write (const int dim) inline override virtual
Implements wmtk::MeshWriter.
Definition at line 33 of file EigenMatrixWriter.hpp.
write() [2/5]
void wmtk::utils::EigenMatrixWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< char > & val, const char default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 88 of file EigenMatrixWriter.cpp.
References chars, and write_internal().
write() [3/5]
void wmtk::utils::EigenMatrixWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< double > & val, const double default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 108 of file EigenMatrixWriter.cpp.
References doubles, and write_internal().
write() [4/5]
void wmtk::utils::EigenMatrixWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< int64_t > & val, const int64_t default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 98 of file EigenMatrixWriter.cpp.
References int64_ts, and write_internal().
write() [5/5]
void wmtk::utils::EigenMatrixWriter::write (const std::string & name, const int64_t type, const int64_t stride, const std::vector< Rational > & val, const Rational & default_val) override virtual
Implements wmtk::MeshWriter.
Definition at line 118 of file EigenMatrixWriter.cpp.
References Rationals, and write_internal().
write_absolute_id()
void wmtk::utils::EigenMatrixWriter::write_absolute_id (const std::vector< int64_t > & id) override virtual
Implements wmtk::MeshWriter.
Definition at line 134 of file EigenMatrixWriter.cpp.
References wmtk::MeshWriter::m_mm_level.
write_capacities()
void wmtk::utils::EigenMatrixWriter::write_capacities (const std::vector< int64_t > & capacities) override virtual
Implements wmtk::MeshWriter.
Definition at line 138 of file EigenMatrixWriter.cpp.
write_internal()
template<typename T > void wmtk::utils::EigenMatrixWriter::write_internal (std::map< std::pair< std::string, PrimitiveType >, MatrixX< T >> & Ts, const std::string & name, const int64_t type, const int64_t stride, const std::vector< T > & val, const T & default_val) private
Definition at line 74 of file EigenMatrixWriter.cpp.
References wmtk::MeshWriter::m_mm_level.
Referenced by write().
write_top_simplex_type()
void wmtk::utils::EigenMatrixWriter::write_top_simplex_type (const PrimitiveType type) override virtual
Implements wmtk::MeshWriter.
Definition at line 130 of file EigenMatrixWriter.cpp.
Member Data Documentation
chars
std::map<std::pair<std::string, PrimitiveType>, MatrixX<char> > wmtk::utils::EigenMatrixWriter::chars private
Definition at line 67 of file EigenMatrixWriter.hpp.
Referenced by get_char_matrix(), and write().
doubles
std::map<std::pair<std::string, PrimitiveType>, MatrixX<double> > wmtk::utils::EigenMatrixWriter::doubles private
Definition at line 65 of file EigenMatrixWriter.hpp.
Referenced by get_double_matrix(), and write().
int64_ts
std::map<std::pair<std::string, PrimitiveType>, MatrixX<int64_t> > wmtk::utils::EigenMatrixWriter::int64_ts private
Definition at line 66 of file EigenMatrixWriter.hpp.
Referenced by get_int64_t_matrix(), and write().
Rationals
std::map<std::pair<std::string, PrimitiveType>, MatrixX<Rational> > wmtk::utils::EigenMatrixWriter::Rationals private
Definition at line 68 of file EigenMatrixWriter.hpp.
Referenced by get_Rational_matrix(), and write().
The documentation for this class was generated from the following files:
src/wmtk/utils/EigenMatrixWriter.hpp
src/wmtk/utils/EigenMatrixWriter.cpp