Wildmeshing Toolkit: wmtk::attribute::TypedAttributeManager< T > Class Template Reference
wmtk::attribute::TypedAttributeManager< T > Class Template Reference
Contains all attributes of type T for a single mesh.
#include <TypedAttributeManager.hpp>
Public Member Functions
TypedAttributeManager ()=default
TypedAttributeManager (const TypedAttributeManager &o)=delete
TypedAttributeManager (TypedAttributeManager &&o)=default
TypedAttributeManager & operator= (const TypedAttributeManager &o)=delete
TypedAttributeManager & operator= (TypedAttributeManager &&o)=default
void serialize (const int dim, MeshWriter &writer) const
std::map< std::string, const wmtk::utils::Hashable * > child_hashables () const override
std::map< std::string, std::size_t > child_hashes () const override
AttributeHandle register_attribute (const std::string &name, int64_t dimension, bool replace=false, T default_value=T(0))
int64_t reserved_size () const
void reserve (const int64_t size)
void reserve_more (int64_t size)
void guarantee_at_least (int64_t size)
void remove_attributes (const std::vector< AttributeHandle > &attributes)
Remove all passed in attributes.
void remove_attribute (const AttributeHandle &attribute)
Remove a single attribute.
bool operator== (const TypedAttributeManager< T > &other) const
void push_scope ()
void pop_scope (bool apply_updates=true)
void rollback_current_scope ()
void change_to_parent_scope () const
void change_to_child_scope () const
int64_t dimension (const AttributeHandle &handle) const
const T & default_value (const AttributeHandle &handle) const
std::string get_name (const AttributeHandle &handle) const
void set_name (const AttributeHandle &handle, const std::string &name)
bool has_attribute (const std::string &name) const
size_t attribute_count () const
std::vector< AttributeHandle > active_attributes () const
void assert_capacity_valid (int64_t cap) const
CachingAttribute< T > & attribute (const AttributeHandle &handle)
const CachingAttribute< T > & attribute (const AttributeHandle &handle) const
AttributeHandle attribute_handle (const std::string &name) const
bool is_active (const AttributeHandle &handle) const
void set (const AttributeHandle &handle, std::vector< T > val)
bool validate_handle (const AttributeHandle &handle) const
Public Member Functions inherited from wmtk::utils::Hashable
Hashable ()
Hashable (const Hashable &)
Hashable (Hashable &&)
Hashable & operator= (const Hashable &)
Hashable & operator= (Hashable &&)
virtual ~Hashable ()
virtual std::size_t hash () const
Protected Member Functions
void clear_dead_attributes ()
Clears and compactifies the attribute list. This invalidates all existing handles.
size_t attribute_size (const AttributeHandle &handle) const
Private Types
typedef Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, 1 > > MapResult
typedef Eigen::Map< const Eigen::Matrix< T, Eigen::Dynamic, 1 > > ConstMapResult
Private Attributes
int64_t m_reserved_size = -1
std::vector< std::unique_ptr< CachingAttribute< T > > > m_attributes
Detailed Description
template<typename T>
class wmtk::attribute::TypedAttributeManager< T >
Contains all attributes of type T for a single mesh.
It also stores a map so that attributes can be accessed through a name.
Definition at line 25 of file TypedAttributeManager.hpp.
Member Typedef Documentation
ConstMapResult
template<typename T > typedef Eigen::Map<const Eigen::Matrix<T, Eigen::Dynamic, 1> > wmtk::attribute::TypedAttributeManager< T >::ConstMapResult private
Definition at line 28 of file TypedAttributeManager.hpp.
MapResult
template<typename T > typedef Eigen::Map<Eigen::Matrix<T, Eigen::Dynamic, 1> > wmtk::attribute::TypedAttributeManager< T >::MapResult private
Definition at line 27 of file TypedAttributeManager.hpp.
Constructor & Destructor Documentation
TypedAttributeManager() [1/3]
template<typename T > wmtk::attribute::TypedAttributeManager< T >::TypedAttributeManager () default
TypedAttributeManager() [2/3]
template<typename T > wmtk::attribute::TypedAttributeManager< T >::TypedAttributeManager (const TypedAttributeManager< T > & o) delete
TypedAttributeManager() [3/3]
template<typename T > wmtk::attribute::TypedAttributeManager< T >::TypedAttributeManager (TypedAttributeManager< T > && o) default
Member Function Documentation
active_attributes()
template<typename T > auto wmtk::attribute::TypedAttributeManager< T >::active_attributes () const
Definition at line 259 of file TypedAttributeManager.cpp.
assert_capacity_valid()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::assert_capacity_valid (int64_t cap) const
Definition at line 173 of file TypedAttributeManager.cpp.
attribute() [1/2]
template<typename T > CachingAttribute< T > & wmtk::attribute::TypedAttributeManager< T >::attribute (const AttributeHandle & handle) inline
Definition at line 131 of file TypedAttributeManager.hpp.
References wmtk::attribute::AttributeHandle::index().
Referenced by wmtk::attribute::TypedAttributeManager< T >::operator=().
attribute() [2/2]
template<typename T > const CachingAttribute< T > & wmtk::attribute::TypedAttributeManager< T >::attribute (const AttributeHandle & handle) const inline
Definition at line 137 of file TypedAttributeManager.hpp.
References wmtk::attribute::AttributeHandle::index().
attribute_count()
template<typename T > size_t wmtk::attribute::TypedAttributeManager< T >::attribute_count () const
Definition at line 254 of file TypedAttributeManager.cpp.
attribute_handle()
template<typename T > AttributeHandle wmtk::attribute::TypedAttributeManager< T >::attribute_handle (const std::string & name) const
Definition at line 182 of file TypedAttributeManager.cpp.
References wmtk::log_and_throw_error().
attribute_size()
template<typename T > size_t wmtk::attribute::TypedAttributeManager< T >::attribute_size (const AttributeHandle & handle) const protected
Definition at line 240 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index().
change_to_child_scope()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::change_to_child_scope () const
Definition at line 131 of file TypedAttributeManager.cpp.
change_to_parent_scope()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::change_to_parent_scope () const
Definition at line 121 of file TypedAttributeManager.cpp.
child_hashables()
template<typename T > std::map< std::string, const wmtk::utils::Hashable * > wmtk::attribute::TypedAttributeManager< T >::child_hashables () const override virtual
Implements wmtk::utils::MerkleTreeInteriorNode.
Definition at line 73 of file TypedAttributeManager.cpp.
child_hashes()
template<typename T > std::map< std::string, std::size_t > wmtk::attribute::TypedAttributeManager< T >::child_hashes () const override virtual
Reimplemented from wmtk::utils::MerkleTreeInteriorNode.
Definition at line 56 of file TypedAttributeManager.cpp.
References wmtk::utils::MerkleTreeInteriorNode::child_hashes().
clear_dead_attributes()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::clear_dead_attributes () protected
Clears and compactifies the attribute list. This invalidates all existing handles.
Definition at line 342 of file TypedAttributeManager.cpp.
default_value()
template<typename T > const T & wmtk::attribute::TypedAttributeManager< T >::default_value (const AttributeHandle & handle) const inline
Definition at line 149 of file TypedAttributeManager.hpp.
dimension()
template<typename T > int64_t wmtk::attribute::TypedAttributeManager< T >::dimension (const AttributeHandle & handle) const inline
Definition at line 144 of file TypedAttributeManager.hpp.
References wmtk::attribute::Attribute< T >::dimension().
get_name()
template<typename T > std::string wmtk::attribute::TypedAttributeManager< T >::get_name (const AttributeHandle & handle) const
Definition at line 356 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index().
guarantee_at_least()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::guarantee_at_least (int64_t size)
Definition at line 297 of file TypedAttributeManager.cpp.
has_attribute()
template<typename T > bool wmtk::attribute::TypedAttributeManager< T >::has_attribute (const std::string & name) const
Definition at line 196 of file TypedAttributeManager.cpp.
is_active()
template<typename T > bool wmtk::attribute::TypedAttributeManager< T >::is_active (const AttributeHandle & handle) const
Definition at line 272 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index().
operator=() [1/2]
template<typename T > TypedAttributeManager & wmtk::attribute::TypedAttributeManager< T >::operator= (const TypedAttributeManager< T > & o) delete
operator=() [2/2]
template<typename T > TypedAttributeManager & wmtk::attribute::TypedAttributeManager< T >::operator= (TypedAttributeManager< T > && o) default
References wmtk::attribute::TypedAttributeManager< T >::attribute().
operator==()
template<typename T > bool wmtk::attribute::TypedAttributeManager< T >::operator== (const TypedAttributeManager< T > & other) const
Definition at line 211 of file TypedAttributeManager.cpp.
References wmtk::attribute::TypedAttributeManager< T >::m_attributes.
pop_scope()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::pop_scope (bool apply_updates = true)
Definition at line 103 of file TypedAttributeManager.cpp.
References wmtk::attribute::TypedAttributeManager< T >::pop_scope().
Referenced by wmtk::attribute::TypedAttributeManager< T >::pop_scope().
push_scope()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::push_scope ()
Definition at line 94 of file TypedAttributeManager.cpp.
References wmtk::attribute::TypedAttributeManager< T >::push_scope().
Referenced by wmtk::attribute::TypedAttributeManager< T >::push_scope().
register_attribute()
template<typename T > AttributeHandle wmtk::attribute::TypedAttributeManager< T >::register_attribute (const std::string & name, int64_t dimension, bool replace = false, T default_value = T(0))
Definition at line 141 of file TypedAttributeManager.cpp.
References wmtk::log_and_throw_error().
remove_attribute()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::remove_attribute (const AttributeHandle & attribute)
Remove a single attribute.
Parameters
attribute the attribute being deleted
Definition at line 315 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index(), and wmtk::logger().
remove_attributes()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::remove_attributes (const std::vector< AttributeHandle > & attributes)
Remove all passed in attributes.
Parameters
attributes Vector of attributes that should be removed.
invalidate_handles invalidates all handles. If true this garbage collects old handles
Definition at line 306 of file TypedAttributeManager.cpp.
reserve()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::reserve (const int64_t size)
Definition at line 280 of file TypedAttributeManager.cpp.
References wmtk::attribute::TypedAttributeManager< T >::reserve().
Referenced by wmtk::attribute::TypedAttributeManager< T >::reserve().
reserve_more()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::reserve_more (int64_t size)
Definition at line 291 of file TypedAttributeManager.cpp.
reserved_size()
template<typename T > int64_t wmtk::attribute::TypedAttributeManager< T >::reserved_size () const
Definition at line 248 of file TypedAttributeManager.cpp.
rollback_current_scope()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::rollback_current_scope ()
Definition at line 112 of file TypedAttributeManager.cpp.
References wmtk::attribute::TypedAttributeManager< T >::rollback_current_scope().
Referenced by wmtk::attribute::TypedAttributeManager< T >::rollback_current_scope().
serialize()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::serialize (const int dim, MeshWriter & writer) const
Definition at line 21 of file TypedAttributeManager.cpp.
set()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::set (const AttributeHandle & handle, std::vector< T > val)
Definition at line 230 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index().
set_name()
template<typename T > void wmtk::attribute::TypedAttributeManager< T >::set_name (const AttributeHandle & handle, const std::string & name)
Definition at line 367 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index().
validate_handle()
template<typename T > bool wmtk::attribute::TypedAttributeManager< T >::validate_handle (const AttributeHandle & handle) const
Definition at line 327 of file TypedAttributeManager.cpp.
References wmtk::attribute::AttributeHandle::index(), and wmtk::logger().
Member Data Documentation
m_attributes
template<typename T > std::vector<std::unique_ptr<CachingAttribute<T> > > wmtk::attribute::TypedAttributeManager< T >::m_attributes private
Definition at line 128 of file TypedAttributeManager.hpp.
Referenced by wmtk::attribute::TypedAttributeManager< T >::operator==().
m_reserved_size
template<typename T > int64_t wmtk::attribute::TypedAttributeManager< T >::m_reserved_size = -1 private
Definition at line 126 of file TypedAttributeManager.hpp.
The documentation for this class was generated from the following files:
src/wmtk/attribute/AttributeHandle.hpp
src/wmtk/attribute/TypedAttributeManager.hpp
src/wmtk/attribute/TypedAttributeManager.cpp