Wildmeshing Toolkit: wmtk::attribute::TupleAccessor< MeshType, Dim > Class Template Reference
wmtk::attribute::TupleAccessor< MeshType, Dim > Class Template Reference
#include <TupleAccessor.hpp>
Public Types
template<int D = Dim>
using MapResult = MapResult< Tuple, D >
template<int D = Dim>
using ConstMapResult = ConstMapResult< Tuple, D >
Public Member Functions
TupleAccessor (MeshType &m, const TypedAttributeHandle< int64_t > &handle)
TupleAccessor (const MeshType &m, const TypedAttributeHandle< int64_t > &handle)
template<int Dim2>
TupleAccessor (const Accessor< int64_t, MeshType, CachingAttribute< int64_t >, Dim2 > &accessor)
const Tuple & const_scalar_attribute (const Tuple &t) const
Tuple & scalar_attribute (const Tuple &t)
template<int D = Dim>
ConstMapResult< D > const_vector_attribute (const Tuple &t) const
template<int D = Dim>
MapResult< D > vector_attribute (const Tuple &t)
Eigen::Index dimension () const
template<int D>
auto const_vector_attribute (const Tuple &t) const -> ConstMapResult< D >
template<int D>
auto vector_attribute (const Tuple &t) -> MapResult< D >
Private Attributes
Accessor< int64_t, MeshType > m_base_accessor
Eigen::Index m_dimension
Detailed Description
template<typename MeshType, int Dim = Eigen::Dynamic>
class wmtk::attribute::TupleAccessor< MeshType, Dim >
Definition at line 11 of file TupleAccessor.hpp.
Member Typedef Documentation
ConstMapResult
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D = Dim> using wmtk::attribute::TupleAccessor< MeshType, Dim >::ConstMapResult = ConstMapResult<Tuple, D>
Definition at line 24 of file TupleAccessor.hpp.
MapResult
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D = Dim> using wmtk::attribute::TupleAccessor< MeshType, Dim >::MapResult = MapResult<Tuple, D>
Definition at line 21 of file TupleAccessor.hpp.
Constructor & Destructor Documentation
TupleAccessor() [1/3]
template<typename MeshType , int Dim> wmtk::attribute::TupleAccessor< MeshType, Dim >::TupleAccessor (MeshType & m, const TypedAttributeHandle< int64_t > & handle)
Definition at line 10 of file TupleAccessor.hxx.
TupleAccessor() [2/3]
template<typename MeshType , int Dim> wmtk::attribute::TupleAccessor< MeshType, Dim >::TupleAccessor (const MeshType & m, const TypedAttributeHandle< int64_t > & handle)
Definition at line 17 of file TupleAccessor.hxx.
TupleAccessor() [3/3]
template<typename MeshType , int Dim> template<int Dim2> wmtk::attribute::TupleAccessor< MeshType, Dim >::TupleAccessor (const Accessor< int64_t, MeshType, CachingAttribute< int64_t >, Dim2 > & accessor)
Definition at line 24 of file TupleAccessor.hxx.
Member Function Documentation
const_scalar_attribute()
template<typename MeshType , int Dim> auto wmtk::attribute::TupleAccessor< MeshType, Dim >::const_scalar_attribute (const Tuple & t) const
Definition at line 62 of file TupleAccessor.hxx.
const_vector_attribute() [1/2]
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D = Dim> ConstMapResult< D > wmtk::attribute::TupleAccessor< MeshType, Dim >::const_vector_attribute (const Tuple & t) const
Referenced by wmtk::multimesh::utils::read_tuple_map_attribute().
const_vector_attribute() [2/2]
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D> auto wmtk::attribute::TupleAccessor< MeshType, Dim >::const_vector_attribute (const Tuple & t) const -> ConstMapResult<D>
Definition at line 33 of file TupleAccessor.hxx.
dimension()
template<typename MeshType , int Dim = Eigen::Dynamic> Eigen::Index wmtk::attribute::TupleAccessor< MeshType, Dim >::dimension () const inline
Definition at line 35 of file TupleAccessor.hpp.
References wmtk::attribute::TupleAccessor< MeshType, Dim >::m_dimension.
Referenced by wmtk::multimesh::utils::read_tuple_map_attribute(), and wmtk::multimesh::utils::write_tuple_map_attribute().
scalar_attribute()
template<typename MeshType , int Dim> auto wmtk::attribute::TupleAccessor< MeshType, Dim >::scalar_attribute (const Tuple & t)
Definition at line 53 of file TupleAccessor.hxx.
vector_attribute() [1/2]
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D = Dim> MapResult< D > wmtk::attribute::TupleAccessor< MeshType, Dim >::vector_attribute (const Tuple & t)
Referenced by wmtk::multimesh::utils::write_tuple_map_attribute().
vector_attribute() [2/2]
template<typename MeshType , int Dim = Eigen::Dynamic> template<int D> auto wmtk::attribute::TupleAccessor< MeshType, Dim >::vector_attribute (const Tuple & t) -> MapResult<D>
Definition at line 44 of file TupleAccessor.hxx.
Member Data Documentation
m_base_accessor
template<typename MeshType , int Dim = Eigen::Dynamic> Accessor<int64_t, MeshType> wmtk::attribute::TupleAccessor< MeshType, Dim >::m_base_accessor private
Definition at line 38 of file TupleAccessor.hpp.
m_dimension
template<typename MeshType , int Dim = Eigen::Dynamic> Eigen::Index wmtk::attribute::TupleAccessor< MeshType, Dim >::m_dimension private
Definition at line 39 of file TupleAccessor.hpp.
Referenced by wmtk::attribute::TupleAccessor< MeshType, Dim >::dimension().
The documentation for this class was generated from the following files:
src/wmtk/attribute/TupleAccessor.hpp
src/wmtk/attribute/TupleAccessor.hxx