Wildmeshing Toolkit: wmtk::multimesh::utils::internal::TupleTag Class Reference
wmtk::multimesh::utils::internal::TupleTag Class Reference
TupleTag is a util helper class for tagging edges in a triangle mesh.
#include <TupleTag.hpp>
Public Member Functions
TupleTag (Mesh &mesh, const std::set< int64_t > &critical_points)
const Mesh & mesh () const
Mesh & mesh ()
void initialize ()
Go through edges of the parent mesh (triangle mesh) and initialize all the vertex tags to be -1.
std::set< int64_t > run ()
bool is_critical_vertex (const Tuple &v) const
Check if a vertex is a critical point.
bool vertex_is_root (const Tuple &v) const
int64_t vertex_get_root (const Tuple &v) const
void vertex_set_root (const Tuple &v, int64_t root)
void vertex_sets_unify (const Tuple &v1, const Tuple &v2)
Given two vertex tuple, join the sets that contain them.
void run (const Tuple &e)
Given an edge, join the sets that contains the two end vertices.
int64_t get_vertex_tag (const Tuple &tuple) const
int64_t get_edge_tag (const Tuple &tuple) const
void set_vertex_tag (const Tuple &tuple, int64_t tag)
void set_edge_tag (const Tuple &tuple, int64_t tag)
int64_t vid (const Tuple &tuple) const
Tuple v_tuple (int64_t vid) const
Static Public Member Functions
template<typename T >
static std::shared_ptr< Mesh > extract_and_register_child_mesh_from_tag_handle (Mesh &m, const wmtk::attribute::TypedAttributeHandle< T > &tag_handle, const T &tag_value, bool child_is_free)
Public Attributes
Mesh & m_mesh
std::set< int64_t > m_critical_points
wmtk::attribute::Accessor< int64_t > m_vertex_tag_acc
wmtk::attribute::Accessor< int64_t > m_edge_tag_acc
Detailed Description
TupleTag is a util helper class for tagging edges in a triangle mesh.
These tags can then be used to extract edge meshes as child mesh for multimesh.
The tagging algorithm is based on the union-find algorithm. It first tags all vertices by grouping them into disjoint sets. Then it creates edge tags based on the vertex tags. Vertex tag and edge tags are stored as mesh attributes of the parent triangle mesh, and can be accessed through "vertex_tag_handle" and "edge_tag_handle" respectively.
Definition at line 16 of file TupleTag.hpp.
Constructor & Destructor Documentation
TupleTag()
wmtk::multimesh::utils::internal::TupleTag::TupleTag (Mesh & mesh, const std::set< int64_t > & critical_points)
Definition at line 5 of file TupleTag.cpp.
References wmtk::Edge, initialize(), and wmtk::Vertex.
Member Function Documentation
extract_and_register_child_mesh_from_tag_handle()
template<typename T > std::shared_ptr< Mesh > wmtk::multimesh::utils::internal::TupleTag::extract_and_register_child_mesh_from_tag_handle (Mesh & m, const wmtk::attribute::TypedAttributeHandle< T > & tag_handle, const T & tag_value, bool child_is_free) static
Definition at line 22 of file extract_child_mesh_from_tag.cpp.
References wmtk::Mesh::create_const_accessor(), wmtk::Edge, wmtk::Mesh::get_all(), wmtk::Mesh::id(), wmtk::attribute::TypedAttributeHandle< T >::primitive_type(), wmtk::Mesh::register_child_mesh(), wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag(), and wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag_handle().
get_edge_tag()
int64_t wmtk::multimesh::utils::internal::TupleTag::get_edge_tag (const Tuple & tuple) const
Definition at line 87 of file TupleTag.cpp.
References wmtk::attribute::Accessor< T, MeshType, Dim >::const_scalar_attribute(), and m_edge_tag_acc.
get_vertex_tag()
int64_t wmtk::multimesh::utils::internal::TupleTag::get_vertex_tag (const Tuple & tuple) const
Definition at line 83 of file TupleTag.cpp.
References wmtk::attribute::Accessor< T, MeshType, Dim >::const_scalar_attribute(), and m_vertex_tag_acc.
Referenced by vertex_get_root(), vertex_is_root(), and vertex_set_root().
initialize()
void wmtk::multimesh::utils::internal::TupleTag::initialize ()
Go through edges of the parent mesh (triangle mesh) and initialize all the vertex tags to be -1.
Definition at line 16 of file TupleTag.cpp.
References wmtk::Edge, wmtk::Mesh::get_all(), mesh(), set_edge_tag(), set_vertex_tag(), wmtk::Vertex, and vid().
Referenced by TupleTag().
is_critical_vertex()
bool wmtk::multimesh::utils::internal::TupleTag::is_critical_vertex (const Tuple & v) const
Check if a vertex is a critical point.
Parameters
critical_points
v The vertex tuple
Returns
true if v is a critical point
false if v is not a critival point
Definition at line 78 of file TupleTag.cpp.
References m_critical_points, and vid().
Referenced by run(), and vertex_sets_unify().
mesh() [1/2]
Mesh& wmtk::multimesh::utils::internal::TupleTag::mesh () inline
Definition at line 21 of file TupleTag.hpp.
References m_mesh.
mesh() [2/2]
const Mesh& wmtk::multimesh::utils::internal::TupleTag::mesh () const inline
Definition at line 20 of file TupleTag.hpp.
References m_mesh.
Referenced by initialize(), run(), v_tuple(), and vid().
run() [1/2]
std::set< int64_t > wmtk::multimesh::utils::internal::TupleTag::run ()
Definition at line 34 of file TupleTag.cpp.
References wmtk::Mesh::capacity(), wmtk::Edge, wmtk::Mesh::get_all(), is_critical_vertex(), mesh(), set_edge_tag(), wmtk::Mesh::switch_tuple(), wmtk::Vertex, and vertex_get_root().
Referenced by wmtk::multimesh::utils::create_tags().
run() [2/2]
void wmtk::multimesh::utils::internal::TupleTag::run (const Tuple & e)
Given an edge, join the sets that contains the two end vertices.
Parameters
critical_vids The sets of vertices that are the intersections of edges belong to different sets (for example T junction vertices for an edge mesh)
e
Definition at line 156 of file TupleTag.cpp.
References is_critical_vertex(), mesh(), wmtk::Mesh::switch_tuple(), wmtk::Vertex, vertex_sets_unify(), and vid().
set_edge_tag()
void wmtk::multimesh::utils::internal::TupleTag::set_edge_tag (const Tuple & tuple, int64_t tag)
Definition at line 97 of file TupleTag.cpp.
References m_edge_tag_acc, and wmtk::attribute::Accessor< T, MeshType, Dim >::scalar_attribute().
Referenced by initialize(), and run().
set_vertex_tag()
void wmtk::multimesh::utils::internal::TupleTag::set_vertex_tag (const Tuple & tuple, int64_t tag)
Definition at line 92 of file TupleTag.cpp.
References m_vertex_tag_acc, and wmtk::attribute::Accessor< T, MeshType, Dim >::scalar_attribute().
Referenced by initialize(), and vertex_set_root().
v_tuple()
Tuple wmtk::multimesh::utils::internal::TupleTag::v_tuple (int64_t vid) const
Definition at line 107 of file TupleTag.cpp.
References mesh(), wmtk::Mesh::tuple_from_id(), wmtk::Vertex, and vid().
Referenced by vertex_get_root(), and vertex_set_root().
vertex_get_root()
int64_t wmtk::multimesh::utils::internal::TupleTag::vertex_get_root (const Tuple & v) const
Definition at line 119 of file TupleTag.cpp.
References get_vertex_tag(), v_tuple(), and vertex_is_root().
Referenced by run(), and vertex_sets_unify().
vertex_is_root()
bool wmtk::multimesh::utils::internal::TupleTag::vertex_is_root (const Tuple & v) const
Definition at line 113 of file TupleTag.cpp.
References get_vertex_tag(), and vid().
Referenced by vertex_get_root(), and vertex_set_root().
vertex_set_root()
void wmtk::multimesh::utils::internal::TupleTag::vertex_set_root (const Tuple & v, int64_t root)
Definition at line 129 of file TupleTag.cpp.
References get_vertex_tag(), set_vertex_tag(), v_tuple(), and vertex_is_root().
Referenced by vertex_sets_unify().
vertex_sets_unify()
void wmtk::multimesh::utils::internal::TupleTag::vertex_sets_unify (const Tuple & v1, const Tuple & v2)
Given two vertex tuple, join the sets that contain them.
Parameters
v1
v2
Definition at line 140 of file TupleTag.cpp.
References is_critical_vertex(), vertex_get_root(), and vertex_set_root().
Referenced by run().
vid()
int64_t wmtk::multimesh::utils::internal::TupleTag::vid (const Tuple & tuple) const
Definition at line 102 of file TupleTag.cpp.
References wmtk::Mesh::id(), mesh(), and wmtk::Vertex.
Referenced by initialize(), is_critical_vertex(), run(), v_tuple(), and vertex_is_root().
Member Data Documentation
m_critical_points
std::set<int64_t> wmtk::multimesh::utils::internal::TupleTag::m_critical_points
Definition at line 66 of file TupleTag.hpp.
Referenced by is_critical_vertex().
m_edge_tag_acc
wmtk::attribute::Accessor<int64_t> wmtk::multimesh::utils::internal::TupleTag::m_edge_tag_acc
Definition at line 68 of file TupleTag.hpp.
Referenced by get_edge_tag(), and set_edge_tag().
m_mesh
Mesh& wmtk::multimesh::utils::internal::TupleTag::m_mesh
Definition at line 65 of file TupleTag.hpp.
Referenced by mesh().
m_vertex_tag_acc
wmtk::attribute::Accessor<int64_t> wmtk::multimesh::utils::internal::TupleTag::m_vertex_tag_acc
Definition at line 67 of file TupleTag.hpp.
Referenced by get_vertex_tag(), and set_vertex_tag().
The documentation for this class was generated from the following files:
src/wmtk/multimesh/utils/internal/TupleTag.hpp
src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
src/wmtk/multimesh/utils/internal/TupleTag.cpp