Wildmeshing Toolkit: wmtk::components::adaptive_tessellation::image::SamplingBicubic Class Reference
wmtk::components::adaptive_tessellation::image::SamplingBicubic Class Reference
#include <Sampling.hpp>
Public Types
using Super = SamplingImage< SamplingBicubic >
Public Types inherited from wmtk::components::adaptive_tessellation::image::Sampling
using DScalar = DScalar2< double, Eigen::Matrix< double, -1, 1 >, Eigen::Matrix< double, -1, -1 > >
Public Member Functions
template<class T >
T sample_T (T u, T v) const
double sample (const double u, const double v) const override
DScalar sample (const DScalar &u, const DScalar &v) const override
Public Member Functions inherited from wmtk::components::adaptive_tessellation::image::SamplingImage< SamplingBicubic >
SamplingImage (const Image &img)
double sample (const double u, const double v) const override
DScalar sample (const DScalar &u, const DScalar &v) const override
Public Member Functions inherited from wmtk::components::adaptive_tessellation::image::Sampling
virtual ~Sampling ()
Additional Inherited Members
Protected Attributes inherited from wmtk::components::adaptive_tessellation::image::SamplingImage< SamplingBicubic >
const Image & m_image
Detailed Description
Definition at line 99 of file Sampling.hpp.
Member Typedef Documentation
Super
using wmtk::components::adaptive_tessellation::image::SamplingBicubic::Super = SamplingImage<SamplingBicubic>
Definition at line 102 of file Sampling.hpp.
Member Function Documentation
sample() [1/2]
double wmtk::components::adaptive_tessellation::image::SamplingBicubic::sample (const double u, const double v) const inline override virtual
Implements wmtk::components::adaptive_tessellation::image::Sampling.
Definition at line 125 of file Sampling.hpp.
sample() [2/2]
DScalar wmtk::components::adaptive_tessellation::image::SamplingBicubic::sample (const DScalar & u, const DScalar & v) const inline override virtual
Implements wmtk::components::adaptive_tessellation::image::Sampling.
Definition at line 126 of file Sampling.hpp.
sample_T()
template<class T > T wmtk::components::adaptive_tessellation::image::SamplingBicubic::sample_T (T u, T v) const inline
Definition at line 105 of file Sampling.hpp.
References wmtk::components::adaptive_tessellation::image::eval_bicubic_coeffs(), wmtk::components::adaptive_tessellation::image::extract_samples(), wmtk::components::adaptive_tessellation::image::get_bicubic_matrix(), wmtk::components::adaptive_tessellation::image::Image::get_raw_image(), wmtk::components::adaptive_tessellation::image::Image::get_wrapping_mode_x(), wmtk::components::adaptive_tessellation::image::Image::get_wrapping_mode_y(), wmtk::components::adaptive_tessellation::image::Image::height(), wmtk::components::adaptive_tessellation::image::SamplingImage< SamplingBicubic >::m_image, and wmtk::components::adaptive_tessellation::image::Image::width().
The documentation for this class was generated from the following file:
components/adaptive_tessellation/wmtk/components/adaptive_tessellation/image/Sampling.hpp