Wildmeshing Toolkit: wmtk::attribute::utils::HybridRationalAccessor< D, MeshType > Class Template Reference
wmtk::attribute::utils::HybridRationalAccessor< D, MeshType > Class Template Reference
#include <HybridRationalAccessor.hpp>
Public Types
using Base = attribute::internal::CompoundAccessor< 3, MeshType, char, wmtk::Rational, double >
Public Types inherited from wmtk::attribute::internal::CompoundAccessor< 3, wmtk::Mesh, char, wmtk::Rational, double >
using Type = std::tuple< AttributeType... >
using AccessorTuple = std::tuple< Accessor< AttributeType, wmtk::Mesh >... >
using ValueType = std::tuple< MapResult< AttributeType >... >
using ConstValueType = std::tuple< ConstMapResult< AttributeType >... >
Public Member Functions
HybridRationalAccessor (MeshType &m, const HybridRationalAttribute< D > &attr)
HybridRationalAccessor (const MeshAttributeHandle &handle)
PrimitiveType primitive_type () const
void round (const Tuple &t, bool enable_double=false)
void lift (const Tuple &t, bool enable_double=false)
auto & get_char_accessor ()
const auto & get_char_const_accessor () const
auto & get_rational_accessor ()
const auto & get_rational_const_accessor () const
auto & get_double_accessor ()
const auto & get_double_const_accessor () const
auto char_value (const Tuple &t)
auto char_const_value (const Tuple &t) const
auto rational_value (const Tuple &t)
auto rational_const_value (const Tuple &t) const
auto double_value (const Tuple &t)
auto double_const_value (const Tuple &t) const
bool is_rounded (const Tuple &t) const
template<typename Iterable >
bool are_all_rounded (const Iterable &tuples) const
ConstValueType const_value (const Tuple &t) const
template<size_t Index>
const auto & get () const
template<size_t Index>
auto & get ()
ValueType value (const Tuple &t)
Public Member Functions inherited from wmtk::attribute::internal::CompoundAccessor< 3, wmtk::Mesh, char, wmtk::Rational, double >
CompoundAccessor (wmtk::Mesh &m, const TypedAttributeHandle< AttributeType > &... handle)
CompoundAccessor (const wmtk::Mesh &m, const TypedAttributeHandle< AttributeType > &... handle)
CompoundAccessor (const Accessor< FirstAcc, wmtk::Mesh, FirstDim > &, const Accessor< AccTypes, wmtk::Mesh, Dims > &...)
CompoundAccessor (const Accessor< FirstAccType, wmtk::Mesh, FirstDim > &acc, const Accessor< AccTypes, wmtk::Mesh, Dims > &... accs)
ValueType _value (const Tuple &t, std::integer_sequence< size_t, Ns... >)
ValueType value (const Tuple &t)
ConstValueType _const_value (const Tuple &t, std::integer_sequence< size_t, Ns... >) const
ConstValueType const_value (const Tuple &t) const
const auto & get () const
auto & get ()
PrimitiveType primitive_type () const
returns the primitive type of the Index'th type
Detailed Description
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh>
class wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >
Definition at line 13 of file HybridRationalAccessor.hpp.
Member Typedef Documentation
Base
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> using wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::Base = attribute::internal::CompoundAccessor<3, MeshType, char, wmtk::Rational, double>
Definition at line 17 of file HybridRationalAccessor.hpp.
Constructor & Destructor Documentation
HybridRationalAccessor() [1/2]
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::HybridRationalAccessor (MeshType & m, const HybridRationalAttribute< D > & attr) inline
Definition at line 26 of file HybridRationalAccessor.hpp.
HybridRationalAccessor() [2/2]
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::HybridRationalAccessor (const MeshAttributeHandle & handle) inline
Definition at line 30 of file HybridRationalAccessor.hpp.
References wmtk::attribute::MeshAttributeHandle::holds_from_held_type(), and wmtk::attribute::MeshAttributeHandle::HybridRational.
Member Function Documentation
are_all_rounded()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> template<typename Iterable > bool wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::are_all_rounded (const Iterable & tuples) const inline
Definition at line 92 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::is_rounded().
char_const_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::char_const_value (const Tuple & t) const inline
Definition at line 71 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_char_const_accessor().
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::is_rounded().
char_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::char_value (const Tuple & t) inline
Definition at line 70 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_char_accessor().
const_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> ConstValueType wmtk::attribute::internal::CompoundAccessor< N, MeshType, AttributeType >::const_value inline
Definition at line 38 of file CompoundAccessor.hpp.
double_const_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::double_const_value (const Tuple & t) const inline
Definition at line 83 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_double_const_accessor().
double_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::double_value (const Tuple & t) inline
Definition at line 82 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_double_accessor().
get() [1/2]
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> template<size_t Index> auto& wmtk::attribute::internal::CompoundAccessor< N, MeshType, AttributeType >::get (size_t Index) inline
Definition at line 49 of file CompoundAccessor.hpp.
get() [2/2]
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> template<size_t Index> const auto& wmtk::attribute::internal::CompoundAccessor< N, MeshType, AttributeType >::get (size_t Index) inline
Definition at line 44 of file CompoundAccessor.hpp.
get_char_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_char_accessor () inline
Definition at line 61 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::char_value().
get_char_const_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> const auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_char_const_accessor () const inline
Definition at line 62 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::char_const_value().
get_double_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_double_accessor () inline
Definition at line 67 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::double_value().
get_double_const_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> const auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_double_const_accessor () const inline
Definition at line 68 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::double_const_value().
get_rational_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_rational_accessor () inline
Definition at line 64 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::rational_value().
get_rational_const_accessor()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> const auto& wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_rational_const_accessor () const inline
Definition at line 65 of file HybridRationalAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::rational_const_value().
is_rounded()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> bool wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::is_rounded (const Tuple & t) const inline
Definition at line 88 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::char_const_value().
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::are_all_rounded().
lift()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> void wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::lift (const Tuple & t, bool enable_double = false) inline
Definition at line 51 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::value().
Referenced by wmtk::attribute::utils::HybridRationalAttribute< D >::register_attribute_from_double().
primitive_type()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> PrimitiveType wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::primitive_type () const inline
Definition at line 39 of file HybridRationalAccessor.hpp.
Referenced by wmtk::operations::utils::RoundRationalToDouble::primitive_type().
rational_const_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::rational_const_value (const Tuple & t) const inline
Definition at line 77 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_rational_const_accessor().
rational_value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> auto wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::rational_value (const Tuple & t) inline
Definition at line 76 of file HybridRationalAccessor.hpp.
References wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::get_rational_accessor().
round()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> void wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::round (const Tuple & t, bool enable_double = false) inline
Definition at line 42 of file HybridRationalAccessor.hpp.
References wmtk::Rational::to_double(), and wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::value().
Referenced by wmtk::operations::utils::RoundRationalToDouble::execute(), and wmtk::attribute::utils::HybridRationalAttribute< D >::register_attribute_from_rational().
value()
template<int D = Eigen::Dynamic, typename MeshType = wmtk::Mesh> ValueType wmtk::attribute::internal::CompoundAccessor< N, MeshType, AttributeType >::value inline
Definition at line 31 of file CompoundAccessor.hpp.
Referenced by wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::lift(), and wmtk::attribute::utils::HybridRationalAccessor< D, MeshType >::round().
The documentation for this class was generated from the following file:
src/wmtk/attribute/utils/HybridRationalAccessor.hpp