Wildmeshing Toolkit: wmtk::operations::tet_mesh::SplitNewAttributeStrategy Class Reference
wmtk::operations::tet_mesh::SplitNewAttributeStrategy Class Reference
#include <SplitNewAttributeStrategy.hpp>
Public Member Functions
SplitNewAttributeStrategy (TetMesh &)
TetMesh & tet_mesh ()
const TetMesh & tet_mesh () const
Public Member Functions inherited from wmtk::operations::SplitNewAttributeStrategy
void update (const ReturnData &ret_data, const OperationTupleData &op_data)
virtual void update_handle_mesh (Mesh &m)=0
virtual void set_standard_split_rib_strategy (SplitRibBasicStrategy t)=0
virtual void set_standard_split_strategy (SplitBasicStrategy t)=0
Public Member Functions inherited from wmtk::operations::NewAttributeStrategy
virtual ~NewAttributeStrategy ()
virtual bool matches_attribute (const attribute::MeshAttributeHandleVariant &) const =0
virtual PrimitiveType primitive_type () const =0
virtual Mesh & mesh ()=0
const Mesh & mesh () const
template<typename T >
auto standard_collapse_strategy (CollapseBasicStrategy optype) -> CollapseFuncType< T >
template<typename T >
auto standard_split_strategy (SplitBasicStrategy optype) -> SplitFuncType< T >
template<typename T >
auto standard_split_rib_strategy (SplitRibBasicStrategy optype) -> SplitRibFuncType< T >
Private Member Functions
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
std::vector< Tuple > output_rib_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< std::array< Tuple, 2 > > output_split_simplices (const ReturnVariant &ret_data, const Tuple &output_tuple, PrimitiveType pt) const final override
std::vector< Tuple > input_split_simplices (const ReturnVariant &ret_data, const Tuple &input_tuple, PrimitiveType pt) const final override
std::vector< std::array< Tuple, 2 > > input_ear_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
std::vector< Tuple > output_rib_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< std::array< Tuple, 2 > > output_split_simplices (const EdgeOperationData &ret_data, const Tuple &output_tuple, PrimitiveType pt) const
std::vector< Tuple > input_split_simplices (const EdgeOperationData &ret_data, const Tuple &input_tuple, PrimitiveType pt) const
Additional Inherited Members
Public Types inherited from wmtk::operations::SplitNewAttributeStrategy
using ReturnData = wmtk::multimesh::operations::SplitReturnData
using ReturnVariant = ReturnData::ReturnVariant
using OperationTupleData = wmtk::multimesh::operations::OperationTupleData
Public Types inherited from wmtk::operations::NewAttributeStrategy
enum class CollapseBasicStrategy {
Default , CopyTuple , CopyOther , CopyFromPredicate ,
Mean , Throw , None
}
enum class SplitBasicStrategy {
Default , Copy , Half , Throw ,
None
}
enum class BasicSimplexPredicate { Default , IsInterior }
using SplitRibBasicStrategy = CollapseBasicStrategy
template<typename T >
using VecType = VectorX< T >
template<typename T , typename VT = VecType<T>>
using SplitFuncType = std::function< std::array< VT, 2 >(const VT &)>
template<typename T , typename VT = VecType<T>>
using SplitRibFuncType = std::function< VT(const VT &, const VT &)>
using SimplexPredicateType = std::function< bool(const simplex::Simplex &)>
template<typename T , typename VT = VecType<T>>
using CollapseFuncType = std::function< VT(const VT &, const VT &)>
Static Public Member Functions inherited from wmtk::operations::NewAttributeStrategy
template<typename T >
static CollapseFuncType< T > standard_collapse_strategy (CollapseBasicStrategy=CollapseBasicStrategy::Default)
template<typename T >
static SplitFuncType< T > standard_split_strategy (SplitBasicStrategy=SplitBasicStrategy::Default)
template<typename T >
static SplitRibFuncType< T > standard_split_rib_strategy (SplitRibBasicStrategy=SplitRibBasicStrategy::Default)
Protected Member Functions inherited from wmtk::operations::SplitNewAttributeStrategy
virtual void assign_split (PrimitiveType pt, const Tuple &input_simplex, const std::array< Tuple, 2 > &split_simplices)=0
virtual void assign_split_ribs (PrimitiveType pt, const std::array< Tuple, 2 > &input_ears, const Tuple &final_simplex)=0
Detailed Description
Definition at line 7 of file SplitNewAttributeStrategy.hpp.
Constructor & Destructor Documentation
SplitNewAttributeStrategy()
wmtk::operations::tet_mesh::SplitNewAttributeStrategy::SplitNewAttributeStrategy (TetMesh &)
Definition at line 4 of file SplitNewAttributeStrategy.cpp.
Member Function Documentation
input_ear_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_ear_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 98 of file SplitNewAttributeStrategy.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::tet_mesh::EdgeOperationData::input_endpoints(), wmtk::operations::NewAttributeStrategy::mesh(), wmtk::Mesh::parent_scope(), and tet_mesh().
input_ear_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_ear_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override private virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 23 of file SplitNewAttributeStrategy.cpp.
input_split_simplices() [1/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_split_simplices (const EdgeOperationData & ret_data, const Tuple & input_tuple, PrimitiveType pt) const private
Definition at line 81 of file SplitNewAttributeStrategy.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::NewAttributeStrategy::mesh(), and tet_mesh().
input_split_simplices() [2/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::input_split_simplices (const ReturnVariant & ret_data, const Tuple & input_tuple, PrimitiveType pt) const final override private virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 48 of file SplitNewAttributeStrategy.cpp.
output_rib_simplices() [1/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_rib_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 119 of file SplitNewAttributeStrategy.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::NewAttributeStrategy::mesh(), and tet_mesh().
output_rib_simplices() [2/2]
std::vector< Tuple > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_rib_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override private virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 32 of file SplitNewAttributeStrategy.cpp.
output_split_simplices() [1/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_split_simplices (const EdgeOperationData & ret_data, const Tuple & output_tuple, PrimitiveType pt) const private
Definition at line 57 of file SplitNewAttributeStrategy.cpp.
References wmtk::get_primitive_type_id(), wmtk::operations::tet_mesh::EdgeOperationData::input_endpoints(), wmtk::operations::NewAttributeStrategy::mesh(), wmtk::Mesh::parent_scope(), and tet_mesh().
output_split_simplices() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::operations::tet_mesh::SplitNewAttributeStrategy::output_split_simplices (const ReturnVariant & ret_data, const Tuple & output_tuple, PrimitiveType pt) const final override private virtual
Implements wmtk::operations::SplitNewAttributeStrategy.
Definition at line 39 of file SplitNewAttributeStrategy.cpp.
tet_mesh() [1/2]
TetMesh & wmtk::operations::tet_mesh::SplitNewAttributeStrategy::tet_mesh ()
Definition at line 5 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::NewAttributeStrategy::mesh().
Referenced by input_ear_simplices(), input_split_simplices(), output_rib_simplices(), and output_split_simplices().
tet_mesh() [2/2]
const TetMesh & wmtk::operations::tet_mesh::SplitNewAttributeStrategy::tet_mesh () const
Definition at line 9 of file SplitNewAttributeStrategy.cpp.
References wmtk::operations::NewAttributeStrategy::mesh().
The documentation for this class was generated from the following files:
src/wmtk/operations/tet_mesh/SplitNewAttributeStrategy.hpp
src/wmtk/operations/tet_mesh/SplitNewAttributeStrategy.cpp