Wildmeshing Toolkit: wmtk::MshReader Class Reference
wmtk::MshReader Class Reference
#include <MshReader.hpp>
Public Member Functions
std::shared_ptr< Mesh > read (const std::filesystem::path &filename, const bool ignore_z=false, const std::vector< std::string > &attrs={})
Private Member Functions
void set_vertex (size_t i, double x, double y, double z)
void set_edge (size_t i, int i0, int i1)
void set_face (size_t i, int i0, int i1, int i2)
void set_tet (size_t i, int i0, int i1, int i2, int i3)
size_t get_num_edge_vertices () const
size_t get_num_face_vertices () const
size_t get_num_tet_vertices () const
size_t get_num_edges () const
size_t get_num_faces () const
size_t get_num_tets () const
void extract_tet_vertices ()
void extract_face_vertices ()
void extract_edge_vertices ()
void extract_edges ()
void extract_faces ()
void extract_tets ()
const mshio::NodeBlock * get_vertex_block (int DIM) const
const mshio::ElementBlock * get_simplex_element_block (int DIM) const
template<int DIM>
size_t get_num_vertices () const
template<int DIM>
size_t get_num_simplex_elements () const
template<int DIM>
void extract_vertices ()
template<int DIM>
void extract_simplex_elements ()
void extract_element_attribute (std::shared_ptr< wmtk::TetMesh > m, const std::string &attr_name, int DIM)
Private Attributes
mshio::MshSpec m_spec
bool m_ignore_z
Eigen::MatrixXd V
Eigen::Matrix< int64_t, -1, -1 > S
Detailed Description
Definition at line 12 of file MshReader.hpp.
Member Function Documentation
extract_edge_vertices()
void wmtk::MshReader::extract_edge_vertices () private
Definition at line 165 of file MshReader.cpp.
Referenced by read().
extract_edges()
void wmtk::MshReader::extract_edges () private
Definition at line 170 of file MshReader.cpp.
Referenced by read().
extract_element_attribute()
void wmtk::MshReader::extract_element_attribute (std::shared_ptr< wmtk::TetMesh > m, const std::string & attr_name, int DIM) private
Definition at line 420 of file MshReader.cpp.
References get_simplex_element_block(), m_spec, and wmtk::Tetrahedron.
Referenced by read().
extract_face_vertices()
void wmtk::MshReader::extract_face_vertices () private
Definition at line 160 of file MshReader.cpp.
Referenced by read().
extract_faces()
void wmtk::MshReader::extract_faces () private
Definition at line 175 of file MshReader.cpp.
Referenced by read().
extract_simplex_elements()
template<int DIM> void wmtk::MshReader::extract_simplex_elements private
Definition at line 305 of file MshReader.cpp.
References get_simplex_element_block(), get_vertex_block(), set_edge(), set_face(), and set_tet().
extract_tet_vertices()
void wmtk::MshReader::extract_tet_vertices () private
Definition at line 155 of file MshReader.cpp.
Referenced by read().
extract_tets()
void wmtk::MshReader::extract_tets () private
Definition at line 180 of file MshReader.cpp.
Referenced by read().
extract_vertices()
template<int DIM> void wmtk::MshReader::extract_vertices private
Definition at line 289 of file MshReader.cpp.
References get_vertex_block(), and set_vertex().
get_num_edge_vertices()
size_t wmtk::MshReader::get_num_edge_vertices () const inline private
Definition at line 38 of file MshReader.hpp.
get_num_edges()
size_t wmtk::MshReader::get_num_edges () const inline private
Definition at line 42 of file MshReader.hpp.
Referenced by read().
get_num_face_vertices()
size_t wmtk::MshReader::get_num_face_vertices () const inline private
Definition at line 39 of file MshReader.hpp.
Referenced by read().
get_num_faces()
size_t wmtk::MshReader::get_num_faces () const inline private
Definition at line 43 of file MshReader.hpp.
Referenced by read().
get_num_simplex_elements()
template<int DIM> size_t wmtk::MshReader::get_num_simplex_elements private
Definition at line 278 of file MshReader.cpp.
References get_simplex_element_block().
get_num_tet_vertices()
size_t wmtk::MshReader::get_num_tet_vertices () const inline private
Definition at line 40 of file MshReader.hpp.
Referenced by read().
get_num_tets()
size_t wmtk::MshReader::get_num_tets () const inline private
Definition at line 44 of file MshReader.hpp.
Referenced by read().
get_num_vertices()
template<int DIM> size_t wmtk::MshReader::get_num_vertices private
Definition at line 267 of file MshReader.cpp.
References get_vertex_block().
get_simplex_element_block()
const mshio::ElementBlock * wmtk::MshReader::get_simplex_element_block (int DIM) const private
Definition at line 256 of file MshReader.cpp.
References m_spec.
Referenced by extract_element_attribute(), extract_simplex_elements(), and get_num_simplex_elements().
get_vertex_block()
const mshio::NodeBlock * wmtk::MshReader::get_vertex_block (int DIM) const private
Definition at line 246 of file MshReader.cpp.
References m_spec.
Referenced by extract_simplex_elements(), extract_vertices(), and get_num_vertices().
read()
std::shared_ptr< Mesh > wmtk::MshReader::read (const std::filesystem::path & filename, const bool ignore_z = false, const std::vector< std::string > & attrs = {})
Definition at line 20 of file MshReader.cpp.
References wmtk::utils::exactinit(), extract_edge_vertices(), extract_edges(), extract_element_attribute(), extract_face_vertices(), extract_faces(), extract_tet_vertices(), extract_tets(), get_num_edges(), get_num_face_vertices(), get_num_faces(), get_num_tet_vertices(), get_num_tets(), wmtk::log_and_throw_error(), wmtk::logger(), m_ignore_z, m_spec, S, wmtk::mesh_utils::set_matrix_attribute(), V, wmtk::Vertex, and wmtk::utils::wmtk_orient3d().
Referenced by wmtk::read_mesh().
set_edge()
void wmtk::MshReader::set_edge (size_t i, int i0, int i1) inline private
Definition at line 29 of file MshReader.hpp.
References S.
Referenced by extract_simplex_elements().
set_face()
void wmtk::MshReader::set_face (size_t i, int i0, int i1, int i2) inline private
Definition at line 30 of file MshReader.hpp.
References S.
Referenced by extract_simplex_elements().
set_tet()
void wmtk::MshReader::set_tet (size_t i, int i0, int i1, int i2, int i3) inline private
Definition at line 35 of file MshReader.hpp.
References S.
Referenced by extract_simplex_elements().
set_vertex()
void wmtk::MshReader::set_vertex (size_t i, double x, double y, double z) inline private
Definition at line 21 of file MshReader.hpp.
References m_ignore_z, and V.
Referenced by extract_vertices().
Member Data Documentation
m_ignore_z
bool wmtk::MshReader::m_ignore_z private
Definition at line 117 of file MshReader.hpp.
Referenced by read(), and set_vertex().
m_spec
mshio::MshSpec wmtk::MshReader::m_spec private
Definition at line 116 of file MshReader.hpp.
Referenced by extract_element_attribute(), get_simplex_element_block(), get_vertex_block(), and read().
S
Eigen::Matrix<int64_t, -1, -1> wmtk::MshReader::S private
Definition at line 121 of file MshReader.hpp.
Referenced by read(), set_edge(), set_face(), and set_tet().
V
Eigen::MatrixXd wmtk::MshReader::V private
Definition at line 120 of file MshReader.hpp.
Referenced by read(), and set_vertex().
The documentation for this class was generated from the following files:
src/wmtk/io/MshReader.hpp
src/wmtk/io/MshReader.cpp