Wildmeshing Toolkit: wmtk::utils::TupleInspector Class Reference
wmtk::utils::TupleInspector Class Reference
#include <TupleInspector.hpp>
Static Public Member Functions
static int8_t local_vid (const Tuple &t)
static int8_t local_eid (const Tuple &t)
static int8_t local_fid (const Tuple &t)
static int8_t local_id (const Tuple &t, const PrimitiveType pt)
static int8_t local_id (const PrimitiveType pt, const Tuple &t)
static int64_t global_cid (const Tuple &t)
static std::string as_string (const Tuple &t)
Detailed Description
Definition at line 10 of file TupleInspector.hpp.
Member Function Documentation
as_string()
std::string wmtk::utils::TupleInspector::as_string (const Tuple & t) static
Definition at line 6 of file TupleInspector.cpp.
References global_cid(), local_eid(), local_fid(), and local_vid().
Referenced by wmtk::multimesh::utils::MapValidator::check_child_map_attributes_valid(), wmtk::multimesh::MultiMeshManager::check_child_map_valid(), wmtk::multimesh::utils::MapValidator::check_child_switch_homomorphism(), and wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid().
global_cid()
static int64_t wmtk::utils::TupleInspector::global_cid (const Tuple & t) inline static
Definition at line 39 of file TupleInspector.hpp.
References wmtk::Tuple::m_global_cid.
Referenced by wmtk::simplex::TopDimensionCofacesIterable::Iterator::add_neighbors_to_queue(), as_string(), wmtk::autogen::SimplexDart::dart_from_tuple(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), wmtk::simplex::TopDimensionCofacesIterable::Iterator::init(), wmtk::autogen::edge_mesh::local_switch_tuple(), wmtk::autogen::tri_mesh::local_switch_tuple(), wmtk::autogen::tet_mesh::local_switch_tuple(), wmtk::multimesh::utils::tuple_to_vector5(), and wmtk::autogen::SimplexDart::update_tuple_from_valid_index().
local_eid()
static int8_t wmtk::utils::TupleInspector::local_eid (const Tuple & t) inline static
Definition at line 14 of file TupleInspector.hpp.
References wmtk::Tuple::m_local_eid.
Referenced by as_string(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), local_id(), wmtk::autogen::tet_mesh::local_id_table_offset(), wmtk::autogen::tri_mesh::local_id_table_offset(), wmtk::TetMesh::TetMeshOperationExecutor::split_edge(), and wmtk::multimesh::utils::tuple_to_vector5().
local_fid()
static int8_t wmtk::utils::TupleInspector::local_fid (const Tuple & t) inline static
Definition at line 15 of file TupleInspector.hpp.
References wmtk::Tuple::m_local_fid.
Referenced by as_string(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), local_id(), wmtk::autogen::tet_mesh::local_id_table_offset(), wmtk::TetMesh::TetMeshOperationExecutor::split_edge(), and wmtk::multimesh::utils::tuple_to_vector5().
local_id() [1/2]
static int8_t wmtk::utils::TupleInspector::local_id (const PrimitiveType pt, const Tuple & t) inline static
Definition at line 28 of file TupleInspector.hpp.
References wmtk::Edge, local_eid(), local_fid(), local_vid(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
local_id() [2/2]
static int8_t wmtk::utils::TupleInspector::local_id (const Tuple & t, const PrimitiveType pt) inline static
Definition at line 16 of file TupleInspector.hpp.
References wmtk::Edge, local_eid(), local_fid(), local_vid(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::find_local_switch_sequence_to_face().
local_vid()
static int8_t wmtk::utils::TupleInspector::local_vid (const Tuple & t) inline static
Definition at line 13 of file TupleInspector.hpp.
References wmtk::Tuple::m_local_vid.
Referenced by as_string(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), local_id(), wmtk::autogen::edge_mesh::local_id_table_offset(), wmtk::autogen::tet_mesh::local_id_table_offset(), wmtk::autogen::tri_mesh::local_id_table_offset(), wmtk::TetMesh::TetMeshOperationExecutor::split_edge(), and wmtk::multimesh::utils::tuple_to_vector5().
The documentation for this class was generated from the following files:
src/wmtk/utils/TupleInspector.hpp
src/wmtk/utils/TupleInspector.cpp