Wildmeshing Toolkit: wmtk::invariants::EnvelopeInvariant Class Reference
wmtk::invariants::EnvelopeInvariant Class Reference
#include <EnvelopeInvariant.hpp>
Public Member Functions
EnvelopeInvariant (const Mesh &m, const TypedAttributeHandle< double > &coordinate, const TypedAttributeHandle< int64_t > &tag, int64_t value, const Eigen::MatrixXd &vertices, const Eigen::MatrixXi &faces, double envelope_size)
EnvelopeInvariant (const Mesh &m, const TypedAttributeHandle< double > &coordinate, const TypedAttributeHandle< int64_t > &tag, int64_t value, const Mesh &envelope_mesh, const TypedAttributeHandle< double > &envelope_mesh_coordinate, double envelope_size)
bool after (const std::vector< Tuple > &top_dimension_tuples_before, const std::vector< Tuple > &top_dimension_tuples_after) const override
Public Member Functions inherited from wmtk::invariants::Invariant
virtual bool before (const simplex::Simplex &t) const
Invariant (const Mesh &m)
virtual ~Invariant ()
const Mesh & mesh () const
virtual bool directly_modified_after (const std::vector< simplex::Simplex > &simplices_before, const std::vector< simplex::Simplex > &simplices_after) const
Private Attributes
std::shared_ptr< fastEnvelope::FastEnvelope > m_envelope = nullptr
std::shared_ptr< SimpleBVH::BVH > m_bvh = nullptr
const TypedAttributeHandle< double > m_coordinate_handle
const TypedAttributeHandle< int64_t > m_tag
const int64_t m_value
const double m_envelope_size
Detailed Description
Definition at line 18 of file EnvelopeInvariant.hpp.
Constructor & Destructor Documentation
EnvelopeInvariant() [1/2]
wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant (const Mesh & m, const TypedAttributeHandle< double > & coordinate, const TypedAttributeHandle< int64_t > & tag, int64_t value, const Eigen::MatrixXd & vertices, const Eigen::MatrixXi & faces, double envelope_size)
Definition at line 15 of file EnvelopeInvariant.cpp.
References wmtk::simplex::faces(), wmtk::logger(), m_bvh, m_envelope, and wmtk::simplex::vertices().
EnvelopeInvariant() [2/2]
wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant (const Mesh & m, const TypedAttributeHandle< double > & coordinate, const TypedAttributeHandle< int64_t > & tag, int64_t value, const Mesh & envelope_mesh, const TypedAttributeHandle< double > & envelope_mesh_coordinate, double envelope_size)
Definition at line 51 of file EnvelopeInvariant.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::simplex::edges(), wmtk::Face, wmtk::simplex::faces(), wmtk::Mesh::get_all(), wmtk::logger(), m_bvh, m_envelope, wmtk::Mesh::switch_edge(), wmtk::Mesh::switch_vertex(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::vertices().
Member Function Documentation
after()
bool wmtk::invariants::EnvelopeInvariant::after (const std::vector< Tuple > & top_dimension_tuples_before, const std::vector< Tuple > & top_dimension_tuples_after) const override virtual
Reimplemented from wmtk::invariants::Invariant.
Definition at line 126 of file EnvelopeInvariant.cpp.
References wmtk::Mesh::create_accessor(), wmtk::Edge, wmtk::Face, wmtk::simplex::faces(), wmtk::simplex::faces_single_dimension_tuples(), m_bvh, m_coordinate_handle, m_envelope, m_envelope_size, m_tag, m_value, wmtk::invariants::Invariant::mesh(), wmtk::simplex::SimplexCollection::simplex_vector_tuples(), wmtk::Mesh::top_cell_dimension(), wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector(), and wmtk::Vertex.
Member Data Documentation
m_bvh
std::shared_ptr<SimpleBVH::BVH> wmtk::invariants::EnvelopeInvariant::m_bvh = nullptr private
Definition at line 45 of file EnvelopeInvariant.hpp.
Referenced by after(), and EnvelopeInvariant().
m_coordinate_handle
const TypedAttributeHandle<double> wmtk::invariants::EnvelopeInvariant::m_coordinate_handle private
Definition at line 46 of file EnvelopeInvariant.hpp.
Referenced by after().
m_envelope
std::shared_ptr<fastEnvelope::FastEnvelope> wmtk::invariants::EnvelopeInvariant::m_envelope = nullptr private
Definition at line 44 of file EnvelopeInvariant.hpp.
Referenced by after(), and EnvelopeInvariant().
m_envelope_size
const double wmtk::invariants::EnvelopeInvariant::m_envelope_size private
Definition at line 49 of file EnvelopeInvariant.hpp.
Referenced by after().
m_tag
const TypedAttributeHandle<int64_t> wmtk::invariants::EnvelopeInvariant::m_tag private
Definition at line 47 of file EnvelopeInvariant.hpp.
Referenced by after().
m_value
const int64_t wmtk::invariants::EnvelopeInvariant::m_value private
Definition at line 48 of file EnvelopeInvariant.hpp.
Referenced by after().
The documentation for this class was generated from the following files:
src/wmtk/invariants/EnvelopeInvariant.hpp
src/wmtk/invariants/EnvelopeInvariant.cpp