Wildmeshing Toolkit: wmtk::operations::composite::TetCellSplit Class Reference
wmtk::operations::composite::TetCellSplit Class Reference
TetCellSplit.
#include <TetCellSplit.hpp>
Public Member Functions
TetCellSplit (Mesh &m)
PrimitiveType primitive_type () const override
EdgeSplit & split ()
EdgeCollapse & collapse ()
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
std::vector< Simplex > operator() (const Simplex &simplex)
virtual std::vector< double > priority (const Simplex &simplex) const
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< std::vector< double >(const Simplex &)> &func)
std::shared_ptr< operations::NewAttributeStrategy > get_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void set_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::NewAttributeStrategy > &other)
std::shared_ptr< operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute)
void add_transfer_strategy (const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandleVariant &attribute, const std::shared_ptr< operations::AttributeTransferStrategyBase > &other)
virtual bool before (const Simplex &simplex) const
virtual bool after (const std::vector< Simplex > &unmods, const std::vector< Simplex > &mods) const
void update_cell_hashes (const std::vector< Tuple > &cells)
utility for subclasses
Tuple resurrect_tuple (const Tuple &tuple) const
utility for subclasses
Accessor< long > hash_accessor ()
utility for subclasses
ConstAccessor< long > hash_accessor () const
utility for subclasses
void apply_attribute_transfer (const std::vector< Simplex > &direct_mods)
Protected Member Functions
std::vector< Simplex > execute (const Simplex &simplex) override
returns an empty vector in case of failure
std::vector< Simplex > unmodified_primitives (const Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
Private Attributes
EdgeSplit m_split
EdgeCollapse m_collapse
Additional Inherited Members
Protected Attributes inherited from wmtk::operations::Operation
InvariantCollection m_invariants
std::vector< std::shared_ptr< operations::NewAttributeStrategy > > m_new_attr_strategies
std::vector< std::shared_ptr< operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Detailed Description
TetCellSplit.
This class is used to split a tetrahedra into 4 parts, we did this by only using two atomic operations, EdgeSplit and EdgeCollapse in order to make our lib more reliable.
return tuple: the return tuple is the original tuple, arrowing to the new vertex, the face belongs to the original (original_vertex,new vertex,switch_vertex(original_vertex)) the tetrahedra is the most front one.
Definition at line 18 of file TetCellSplit.hpp.
Constructor & Destructor Documentation
TetCellSplit()
wmtk::operations::composite::TetCellSplit::TetCellSplit (Mesh & m)
Definition at line 8 of file TetCellSplit.cpp.
Member Function Documentation
collapse()
EdgeCollapse& wmtk::operations::composite::TetCellSplit::collapse () inline
Definition at line 26 of file TetCellSplit.hpp.
References m_collapse.
execute()
std::vector< Simplex > wmtk::operations::composite::TetCellSplit::execute (const Simplex & simplex) override protected virtual
returns an empty vector in case of failure
Implements wmtk::operations::Operation.
Definition at line 14 of file TetCellSplit.cpp.
References wmtk::simplex::Simplex::edge(), m_collapse, m_split, wmtk::operations::Operation::mesh(), wmtk::Mesh::switch_edge(), wmtk::Mesh::switch_face(), wmtk::simplex::Simplex::tuple(), and wmtk::simplex::Simplex::vertex().
primitive_type()
PrimitiveType wmtk::operations::composite::TetCellSplit::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 23 of file TetCellSplit.hpp.
References wmtk::Tetrahedron.
split()
EdgeSplit& wmtk::operations::composite::TetCellSplit::split () inline
Definition at line 25 of file TetCellSplit.hpp.
References m_split.
unmodified_primitives()
std::vector< Simplex > wmtk::operations::composite::TetCellSplit::unmodified_primitives (const Simplex & simplex) const override protected virtual
Returns all simplices that will be potentially affected by the operation.
Implements wmtk::operations::Operation.
Definition at line 53 of file TetCellSplit.cpp.
Member Data Documentation
m_collapse
EdgeCollapse wmtk::operations::composite::TetCellSplit::m_collapse private
Definition at line 35 of file TetCellSplit.hpp.
Referenced by collapse(), and execute().
m_split
EdgeSplit wmtk::operations::composite::TetCellSplit::m_split private
Definition at line 34 of file TetCellSplit.hpp.
Referenced by execute(), and split().
The documentation for this class was generated from the following files:
src/wmtk/operations/composite/TetCellSplit.hpp
src/wmtk/operations/composite/TetCellSplit.cpp