Wildmeshing Toolkit: wmtk::simplex::HalfClosedStarIterable::Iterator Class Reference
wmtk::simplex::HalfClosedStarIterable::Iterator Class Reference
#include <HalfClosedStarIterable.hpp>
Public Member Functions
Iterator (HalfClosedStarIterable &container, const Tuple &t=Tuple())
Iterator & operator++ ()
bool operator!= (const Iterator &other) const
IdSimplex operator* ()
const IdSimplex operator* () const
Private Member Functions
Iterator & step_tri_mesh ()
Iterator & step_tet_mesh ()
bool step_faces ()
Private Attributes
HalfClosedStarIterable & m_container
const Mesh & m_mesh
TopDimensionCofacesIterable::Iterator m_it
Tuple m_t
int8_t m_pt = -1
int8_t m_face_counter = 0
IteratorPhase m_phase = IteratorPhase::Faces
Detailed Description
Definition at line 26 of file HalfClosedStarIterable.hpp.
Constructor & Destructor Documentation
Iterator()
wmtk::simplex::HalfClosedStarIterable::Iterator::Iterator (HalfClosedStarIterable & container, const Tuple & t = Tuple())
Definition at line 20 of file HalfClosedStarIterable.cpp.
References wmtk::Tuple::is_null(), m_pt, and m_t.
Member Function Documentation
operator!=()
bool wmtk::simplex::HalfClosedStarIterable::Iterator::operator!= (const Iterator & other) const
Definition at line 65 of file HalfClosedStarIterable.cpp.
References m_pt, and m_t.
operator*() [1/2]
IdSimplex wmtk::simplex::HalfClosedStarIterable::Iterator::operator* ()
Definition at line 70 of file HalfClosedStarIterable.cpp.
References wmtk::get_primitive_type_from_id().
operator*() [2/2]
const IdSimplex wmtk::simplex::HalfClosedStarIterable::Iterator::operator* () const
Definition at line 75 of file HalfClosedStarIterable.cpp.
References wmtk::get_primitive_type_from_id().
operator++()
HalfClosedStarIterable::Iterator & wmtk::simplex::HalfClosedStarIterable::Iterator::operator++ ()
Definition at line 33 of file HalfClosedStarIterable.cpp.
References wmtk::Edge, wmtk::simplex::HalfClosedStarIterable::m_mesh, wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
step_faces()
bool wmtk::simplex::HalfClosedStarIterable::Iterator::step_faces () private
Definition at line 149 of file HalfClosedStarIterable.cpp.
step_tet_mesh()
HalfClosedStarIterable::Iterator & wmtk::simplex::HalfClosedStarIterable::Iterator::step_tet_mesh () private
Definition at line 108 of file HalfClosedStarIterable.cpp.
References wmtk::Edge, wmtk::simplex::HalfClosedStarIterable::m_mesh, wmtk::PE, PF, wmtk::PV, wmtk::Mesh::switch_tuples(), wmtk::Triangle, and wmtk::Vertex.
step_tri_mesh()
HalfClosedStarIterable::Iterator & wmtk::simplex::HalfClosedStarIterable::Iterator::step_tri_mesh () private
Definition at line 80 of file HalfClosedStarIterable.cpp.
References wmtk::Edge, wmtk::simplex::HalfClosedStarIterable::m_mesh, wmtk::PE, wmtk::PV, wmtk::Mesh::switch_tuple(), and wmtk::Vertex.
Member Data Documentation
m_container
HalfClosedStarIterable& wmtk::simplex::HalfClosedStarIterable::Iterator::m_container private
Definition at line 42 of file HalfClosedStarIterable.hpp.
m_face_counter
int8_t wmtk::simplex::HalfClosedStarIterable::Iterator::m_face_counter = 0 private
Definition at line 48 of file HalfClosedStarIterable.hpp.
m_it
TopDimensionCofacesIterable::Iterator wmtk::simplex::HalfClosedStarIterable::Iterator::m_it private
Definition at line 45 of file HalfClosedStarIterable.hpp.
m_mesh
const Mesh& wmtk::simplex::HalfClosedStarIterable::Iterator::m_mesh private
Definition at line 43 of file HalfClosedStarIterable.hpp.
m_phase
IteratorPhase wmtk::simplex::HalfClosedStarIterable::Iterator::m_phase = IteratorPhase::Faces private
Definition at line 49 of file HalfClosedStarIterable.hpp.
m_pt
int8_t wmtk::simplex::HalfClosedStarIterable::Iterator::m_pt = -1 private
Definition at line 47 of file HalfClosedStarIterable.hpp.
Referenced by Iterator(), and operator!=().
m_t
Tuple wmtk::simplex::HalfClosedStarIterable::Iterator::m_t private
Definition at line 46 of file HalfClosedStarIterable.hpp.
Referenced by Iterator(), and operator!=().
The documentation for this class was generated from the following files:
src/wmtk/simplex/iterable/HalfClosedStarIterable.hpp
src/wmtk/simplex/iterable/HalfClosedStarIterable.cpp