Wildmeshing Toolkit: components/multimesh/tests/get_attributes.cpp File Reference
get_attributes.cpp File Reference
#include <fmt/ranges.h>
#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>
#include <wmtk/Mesh.hpp>
#include <wmtk/components/input/input.hpp>
#include <wmtk/components/multimesh/NamedMultiMesh.hpp>
#include <wmtk/components/multimesh/utils/AttributeDescription.hpp>
#include <wmtk/components/multimesh/utils/detail/attribute_ambiguous_error.hpp>
#include <wmtk/components/multimesh/utils/detail/attribute_missing_error.hpp>
#include <wmtk/components/multimesh/utils/get_attribute.hpp>
#include <wmtk/utils/Logger.hpp>
#include "wmtk/components/multimesh/MeshCollection.hpp"
#include "utils.hpp"
Typedefs
using json = nlohmann::json
using AT = wmtk::attribute::AttributeType
using AD = wmtk::components::multimesh::utils::AttributeDescription
Functions
TEST_CASE ("multimesh_attribute_description_json", "[components][multimesh]")
TEST_CASE ("named_multimesh_parse_attributes", "[components][multimesh]")
Typedef Documentation
AD
using AD = wmtk::components::multimesh::utils::AttributeDescription
Definition at line 19 of file get_attributes.cpp.
AT
using AT = wmtk::attribute::AttributeType
Definition at line 17 of file get_attributes.cpp.
json
using json = nlohmann::json
Definition at line 16 of file get_attributes.cpp.
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("multimesh_attribute_description_json" , "" [components][multimesh])
Definition at line 28 of file get_attributes.cpp.
References wmtk::attribute::Rational.
TEST_CASE() [2/2]
TEST_CASE ("named_multimesh_parse_attributes" , "" [components][multimesh])
Definition at line 87 of file get_attributes.cpp.
References wmtk::Edge, wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::utils::get_attribute(), wmtk::components::multimesh::NamedMultiMesh::get_id(), make_child(), make_mesh(), wmtk::attribute::Rational, wmtk::components::multimesh::NamedMultiMesh::set_mesh(), wmtk::components::multimesh::NamedMultiMesh::set_names(), wmtk::Triangle, and wmtk::Vertex.