Wildmeshing Toolkit: wmtk::multimesh Namespace Reference
wmtk::multimesh Namespace Reference
Namespaces
attribute
operations
utils
Classes
class MultiMeshSimplexVisitor
class MultiMeshVisitor
class MultiMeshSimplexVisitorExecutor
class MultiMeshVisitorExecutor
class BoundaryChecker
class Mappable
class MappableContainer
class MultiMeshManager
Implementation details for how the Mesh class implements multiple meshes.
class MultiMeshSimplexEventVisitor
Functions
void consolidate (Mesh &mesh)
template<int64_t cell_dimension, typename Functor >
MultiMeshSimplexEventVisitor (const MultiMeshSimplexVisitor< cell_dimension, Functor > &visitor) -> MultiMeshSimplexEventVisitor< cell_dimension, Functor >
template<int64_t cell_dimension, typename NodeFunctor >
MultiMeshSimplexVisitor (std::integral_constant< int64_t, cell_dimension >, NodeFunctor &&) -> MultiMeshSimplexVisitor< cell_dimension, NodeFunctor >
template<typename NodeFunctor >
MultiMeshSimplexVisitor (NodeFunctor &&) -> MultiMeshSimplexVisitor< 0, NodeFunctor >
template<typename NodeFunctor >
MultiMeshVisitor (NodeFunctor &&) -> MultiMeshVisitor< NodeFunctor >
std::vector< std::array< Tuple, 2 > > same_simplex_dimension_bijection (const Mesh &parent, const Mesh &child)
std::vector< std::array< Tuple, 2 > > same_simplex_dimension_surjection (const Mesh &parent, const Mesh &child, const std::vector< int64_t > &parent_simplices)
Function Documentation
consolidate()
void wmtk::multimesh::consolidate (Mesh & mesh)
Definition at line 13 of file consolidate.cpp.
References wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root().
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), wmtk::components::internal::periodic_optimization(), wmtk::components::shortest_edge_collapse::shortest_edge_collapse(), wmtk::components::wildmeshing(), wmtk::components::internal::wildmeshing2d(), and wmtk::components::internal::wildmeshing3d().
MultiMeshSimplexEventVisitor()
template<int64_t cell_dimension, typename Functor > wmtk::multimesh::MultiMeshSimplexEventVisitor (const MultiMeshSimplexVisitor< cell_dimension, Functor > & visitor) -> MultiMeshSimplexEventVisitor< cell_dimension, Functor >
MultiMeshSimplexVisitor() [1/2]
template<typename NodeFunctor > wmtk::multimesh::MultiMeshSimplexVisitor (NodeFunctor &&) -> MultiMeshSimplexVisitor< 0, NodeFunctor >
MultiMeshSimplexVisitor() [2/2]
template<int64_t cell_dimension, typename NodeFunctor > wmtk::multimesh::MultiMeshSimplexVisitor (std::integral_constant< int64_t, cell_dimension > , NodeFunctor &&) -> MultiMeshSimplexVisitor< cell_dimension, NodeFunctor >
MultiMeshVisitor()
template<typename NodeFunctor > wmtk::multimesh::MultiMeshVisitor (NodeFunctor &&) -> MultiMeshVisitor< NodeFunctor >
Referenced by wmtk::multimesh::attribute::AttributeScopeHandle::AttributeScopeHandle(), wmtk::operations::utils::multi_mesh_edge_collapse(), and wmtk::operations::utils::multi_mesh_edge_split().
same_simplex_dimension_bijection()
std::vector< std::array< Tuple, 2 > > wmtk::multimesh::same_simplex_dimension_bijection (const Mesh & parent, const Mesh & child)
Definition at line 9 of file same_simplex_dimension_bijection.cpp.
References wmtk::Mesh::capacity(), same_simplex_dimension_surjection(), and wmtk::Mesh::top_simplex_type().
Referenced by wmtk::components::multimesh::axis_aligned_fusion(), wmtk::components::multimesh::from_facet_bijection(), and wmtk::components::multimesh::multimesh().
same_simplex_dimension_surjection()
std::vector< std::array< Tuple, 2 > > wmtk::multimesh::same_simplex_dimension_surjection (const Mesh & parent, const Mesh & child, const std::vector< int64_t > & parent_simplices)
Definition at line 8 of file same_simplex_dimension_surjection.cpp.
References wmtk::multimesh::MultiMeshManager::same_simplex_dimension_surjection().
Referenced by same_simplex_dimension_bijection().