Wildmeshing Toolkit: wmtk::operations::utils Namespace Reference
wmtk::operations::utils Namespace Reference
Classes
class MultiMeshEdgeCollapseFunctor
class MultiMeshEdgeSplitFunctor
class UpdateEdgeOperationMultiMeshMapFunctor
Typedefs
using CollapseReturnData = wmtk::multimesh::operations::CollapseReturnData
using SplitReturnData = wmtk::multimesh::operations::SplitReturnData
Functions
std::shared_ptr< invariants::InvariantCollection > multimesh_edge_collapse_invariants (const Mesh &m)
CollapseReturnData multi_mesh_edge_collapse (Mesh &mesh, const simplex::NavigatableSimplex &t, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > &new_attr_strategies)
std::vector< simplex::Simplex > multi_mesh_edge_collapse_with_modified_simplices (Mesh &mesh, const simplex::Simplex &simplex, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > &new_attr_strategies)
CollapseReturnData multi_mesh_edge_collapse (Mesh &mesh, const Tuple &t, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > &new_attr_strategies)
std::shared_ptr< invariants::InvariantCollection > multimesh_edge_split_invariants (const Mesh &m)
SplitReturnData multi_mesh_edge_split (Mesh &mesh, const simplex::NavigatableSimplex &t, const std::vector< std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > > &new_attr_strategies)
std::vector< simplex::Simplex > multi_mesh_edge_split_with_modified_simplices (Mesh &mesh, const simplex::Simplex &simplex, const std::vector< std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > > &new_attr_strategies)
Typedef Documentation
CollapseReturnData
using wmtk::operations::utils::CollapseReturnData = typedef wmtk::multimesh::operations::CollapseReturnData
Definition at line 32 of file multi_mesh_edge_collapse.hpp.
SplitReturnData
using wmtk::operations::utils::SplitReturnData = typedef wmtk::multimesh::operations::SplitReturnData
Definition at line 21 of file multi_mesh_edge_split.hpp.
Function Documentation
multi_mesh_edge_collapse() [1/2]
CollapseReturnData wmtk::operations::utils::multi_mesh_edge_collapse (Mesh & mesh, const simplex::NavigatableSimplex & t, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > & new_attr_strategies)
Definition at line 24 of file multi_mesh_edge_collapse.cpp.
References wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root(), wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::execute_from_root(), wmtk::multimesh::operations::extract_operation_in_out(), and wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::run_on_nodes().
Referenced by multi_mesh_edge_collapse_with_modified_simplices().
multi_mesh_edge_collapse() [2/2]
CollapseReturnData wmtk::operations::utils::multi_mesh_edge_collapse (Mesh & mesh, const Tuple & t, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > & new_attr_strategies)
multi_mesh_edge_collapse_with_modified_simplices()
std::vector< simplex::Simplex > wmtk::operations::utils::multi_mesh_edge_collapse_with_modified_simplices (Mesh & mesh, const simplex::Simplex & simplex, const std::vector< std::shared_ptr< const operations::BaseCollapseNewAttributeStrategy > > & new_attr_strategies)
Definition at line 56 of file multi_mesh_edge_collapse.cpp.
References wmtk::Mesh::is_free(), multi_mesh_edge_collapse(), and wmtk::simplex::Simplex::vertex().
Referenced by wmtk::operations::EdgeCollapse::execute().
multi_mesh_edge_split()
SplitReturnData wmtk::operations::utils::multi_mesh_edge_split (Mesh & mesh, const simplex::NavigatableSimplex & t, const std::vector< std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > > & new_attr_strategies)
Definition at line 25 of file multi_mesh_edge_split.cpp.
References wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root(), wmtk::multimesh::MultiMeshSimplexVisitor< cell_dimension_, NodeFunctor_ >::execute_from_root(), wmtk::multimesh::operations::extract_operation_in_out(), wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::run_on_edges(), and wmtk::multimesh::MultiMeshSimplexEventVisitor< cell_dimension, Functor >::run_on_nodes().
Referenced by multi_mesh_edge_split_with_modified_simplices().
multi_mesh_edge_split_with_modified_simplices()
std::vector< simplex::Simplex > wmtk::operations::utils::multi_mesh_edge_split_with_modified_simplices (Mesh & mesh, const simplex::Simplex & simplex, const std::vector< std::shared_ptr< const operations::BaseSplitNewAttributeStrategy > > & new_attr_strategies)
Definition at line 59 of file multi_mesh_edge_split.cpp.
References wmtk::Mesh::is_free(), and multi_mesh_edge_split().
Referenced by wmtk::operations::EdgeSplit::execute().
multimesh_edge_collapse_invariants()
std::shared_ptr< invariants::InvariantCollection > wmtk::operations::utils::multimesh_edge_collapse_invariants (const Mesh & m)
Definition at line 17 of file multi_mesh_edge_collapse.cpp.
multimesh_edge_split_invariants()
std::shared_ptr< invariants::InvariantCollection > wmtk::operations::utils::multimesh_edge_split_invariants (const Mesh & m)
Definition at line 18 of file multi_mesh_edge_split.cpp.