Wildmeshing Toolkit: wmtk::components::multimesh::utils::detail Namespace Reference
wmtk::components::multimesh::utils::detail Namespace Reference
Classes
class attribute_ambiguous_error
class attribute_error
class attribute_missing_error
Functions
std::string make_named_error_string (const std::string_view &path, const std::optional< uint8_t > &dimension, const std::optional< attribute::AttributeType > &type)
std::string make_named_error_string (const AttributeDescription &ad)
auto decompose_attribute_path (std::string_view attribute_path)
auto decompose_attribute_path (const AttributeDescription &description)
template<typename T >
wmtk::attribute::MeshAttributeHandle get_attribute (const Mesh &mesh, const std::string_view &name, PrimitiveType pt)
wmtk::attribute::MeshAttributeHandle get_attribute (const Mesh &mesh, const std::string_view &name, PrimitiveType pt, wmtk::attribute::AttributeType type)
wmtk::attribute::MeshAttributeHandle get_attribute (const Mesh &mesh, const std::string_view &name, std::optional< PrimitiveType > pt, std::optional< wmtk::attribute::AttributeType > type)
Function Documentation
decompose_attribute_path() [1/2]
auto wmtk::components::multimesh::utils::detail::decompose_attribute_path (const AttributeDescription & description)
Definition at line 63 of file get_attribute.cpp.
References decompose_attribute_path(), and wmtk::components::multimesh::utils::AttributeDescription::path.
decompose_attribute_path() [2/2]
auto wmtk::components::multimesh::utils::detail::decompose_attribute_path (std::string_view attribute_path)
Definition at line 19 of file get_attribute.cpp.
Referenced by decompose_attribute_path(), and wmtk::components::multimesh::utils::get_attribute().
get_attribute() [1/3]
template<typename T > wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::detail::get_attribute (const Mesh & mesh, const std::string_view & name, PrimitiveType pt)
Definition at line 69 of file get_attribute.cpp.
References wmtk::Mesh::get_attribute_handle(), wmtk::get_primitive_type_id(), wmtk::Mesh::has_attribute(), and wmtk::components::multimesh::utils::detail::attribute_missing_error::make().
Referenced by get_attribute(), and wmtk::components::multimesh::utils::get_attribute().
get_attribute() [2/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::detail::get_attribute (const Mesh & mesh, const std::string_view & name, PrimitiveType pt, wmtk::attribute::AttributeType type)
Definition at line 81 of file get_attribute.cpp.
References ENTRY, and wmtk::attribute::Rational.
get_attribute() [3/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::detail::get_attribute (const Mesh & mesh, const std::string_view & name, std::optional< PrimitiveType > pt, std::optional< wmtk::attribute::AttributeType > type)
Definition at line 104 of file get_attribute.cpp.
References get_attribute(), wmtk::get_primitive_type_id(), wmtk::attribute::MeshAttributeHandle::is_valid(), wmtk::components::multimesh::utils::detail::attribute_missing_error::make(), wmtk::components::multimesh::utils::detail::attribute_ambiguous_error::make(), wmtk::utils::primitive_below(), wmtk::attribute::Rational, and wmtk::Mesh::top_simplex_type().
make_named_error_string() [1/2]
std::string wmtk::components::multimesh::utils::detail::make_named_error_string (const AttributeDescription & ad)
Definition at line 32 of file named_error_text.cpp.
References wmtk::components::multimesh::utils::AttributeDescription::dimension, make_named_error_string(), wmtk::components::multimesh::utils::AttributeDescription::path, and wmtk::components::multimesh::utils::AttributeDescription::type.
make_named_error_string() [2/2]
std::string wmtk::components::multimesh::utils::detail::make_named_error_string (const std::string_view & path, const std::optional< uint8_t > & dimension, const std::optional< attribute::AttributeType > & type)
Definition at line 10 of file named_error_text.cpp.
Referenced by wmtk::components::multimesh::utils::detail::attribute_missing_error::make_message(), wmtk::components::multimesh::utils::detail::attribute_ambiguous_error::make_message(), and make_named_error_string().