Wildmeshing Toolkit: wmtk::autogen::utils Namespace Reference
wmtk::autogen::utils Namespace Reference
Functions
auto largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
int8_t largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
auto local_id_table_offset (PrimitiveType mesh_type, const Tuple &t) -> int8_t
int8_t relative_face_index (const SimplexDart &sd, int8_t current_orientation, PrimitiveType target_type, int8_t target_index)
: Returns the relative local index of a simplex with respect to an orientation When we switch a dart to lie on a specific simplex we need to find some action that maps to that simplex.
auto simplex_index_from_valid_index (const PrimitiveType mesh_type, int8_t valid_index, wmtk::PrimitiveType type) -> int8_t
auto subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> std::array< int8_t, 2 >
auto subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
auto subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
int8_t subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
int8_t subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
std::array< int8_t, 2 > subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
int8_t valid_index_to_simplex_index (PrimitiveType mesh_type, int8_t current_orientation, PrimitiveType target_type)
Function Documentation
largest_shared_subdart_size() [1/2]
int8_t wmtk::autogen::utils::largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 8 of file largest_shared_subdart_size.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_size(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by largest_shared_subdart_size(), and wmtk::operations::internal::SplitAlternateFacetOptionData::new_gid().
largest_shared_subdart_size() [2/2]
int8_t wmtk::autogen::utils::largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 36 of file largest_shared_subdart_size.cpp.
References wmtk::get_primitive_type_id(), and largest_shared_subdart_size().
local_id_table_offset()
int8_t wmtk::autogen::utils::local_id_table_offset (PrimitiveType mesh_type, const Tuple & t) -> int8_t
Definition at line 7 of file local_id_table_offset.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::local_id_table_offset(), wmtk::autogen::tet_mesh::local_id_table_offset(), wmtk::autogen::tri_mesh::local_id_table_offset(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
relative_face_index()
int8_t wmtk::autogen::utils::relative_face_index (const SimplexDart & sd, int8_t current_orientation, PrimitiveType target_type, int8_t target_index)
: Returns the relative local index of a simplex with respect to an orientation When we switch a dart to lie on a specific simplex we need to find some action that maps to that simplex.
We typically encode these target simplices in terms of indices used in the identity orientation, so this function rewrites an index with repsect to the identity orientation to the given input orientation
Parameters
sd the context for the type of simplex we are in
current_orientation the orientation we want to get the relative ilocal index of
target_type the type of simplex we are trying to get the relative index of
the global index of a simplex with respect to the identity dart
Definition at line 9 of file relative_face_index.cpp.
References wmtk::autogen::SimplexDart::inverse(), wmtk::autogen::SimplexDart::product(), and wmtk::autogen::SimplexDart::simplex_index().
simplex_index_from_valid_index()
auto wmtk::autogen::utils::simplex_index_from_valid_index (const PrimitiveType mesh_type, int8_t valid_index, wmtk::PrimitiveType type) -> int8_t
Definition at line 7 of file simplex_index_from_valid_index.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::simplex_index_from_valid_index(), wmtk::autogen::tet_mesh::simplex_index_from_valid_index(), wmtk::autogen::tri_mesh::simplex_index_from_valid_index(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
subdart_maximal_action_to_face() [1/2]
std::array< int8_t, 2 > wmtk::autogen::utils::subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> std::array< int8_t, 2 >
Definition at line 8 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by subdart_maximal_action_to_face().
subdart_maximal_action_to_face() [2/2]
std::array< int8_t, 2 > wmtk::autogen::utils::subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 109 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face().
subdart_maximal_action_to_face_action() [1/2]
int8_t wmtk::autogen::utils::subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 36 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_action(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_action(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_action(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_action() [2/2]
int8_t wmtk::autogen::utils::subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 91 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_size() [1/2]
auto wmtk::autogen::utils::subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 63 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_size(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by subdart_maximal_action_to_face_size().
subdart_maximal_action_to_face_size() [2/2]
int8_t wmtk::autogen::utils::subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 100 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face_size().
valid_index_to_simplex_index()
int8_t wmtk::autogen::utils::valid_index_to_simplex_index (PrimitiveType mesh_type, int8_t current_orientation, PrimitiveType target_type)
Definition at line 11 of file valid_index_to_simplex_index.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::simplex_index_from_valid_index(), wmtk::autogen::tet_mesh::simplex_index_from_valid_index(), wmtk::autogen::tri_mesh::simplex_index_from_valid_index(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.