Wildmeshing Toolkit: wmtk::components::procedural Namespace Reference
wmtk::components::procedural Namespace Reference
Classes
class DiskOptions
class Grid2Options
class Grid3Options
class GridOptions
struct ProceduralOptions
class TriangleFanOptions
Functions
std::shared_ptr< TriMesh > make_mesh (const DiskOptions &opt)
std::shared_ptr< TriMesh > make_mesh (const Grid2Options &opt)
std::shared_ptr< TetMesh > make_mesh (const Grid3Options &opt)
int64_t grid_index (const std::array< int64_t, 3 > &d, const std::array< int64_t, 3 > &i)
int64_t grid_index (const std::array< int64_t, 2 > &d, const std::array< int64_t, 2 > &i)
std::shared_ptr< Mesh > make_mesh (const GridOptions &m)
std::shared_ptr< TriMesh > make_mesh (const TriangleFanOptions &)
Function Documentation
grid_index() [1/2]
int64_t wmtk::components::procedural::grid_index (const std::array< int64_t, 2 > & d, const std::array< int64_t, 2 > & i)
Definition at line 20 of file grid_utils.cpp.
grid_index() [2/2]
int64_t wmtk::components::procedural::grid_index (const std::array< int64_t, 3 > & d, const std::array< int64_t, 3 > & i)
Definition at line 16 of file grid_utils.cpp.
make_mesh() [1/5]
std::shared_ptr< TriMesh > wmtk::components::procedural::make_mesh (const DiskOptions & opt)
Definition at line 10 of file DiskOptions.cpp.
References wmtk::components::procedural::DiskOptions::coordinates, wmtk::TriMesh::initialize(), wmtk::mesh_utils::set_matrix_attribute(), wmtk::components::procedural::DiskOptions::size, and wmtk::Vertex.
make_mesh() [2/5]
std::shared_ptr< TriMesh > wmtk::components::procedural::make_mesh (const Grid2Options & opt)
Definition at line 79 of file Grid2Options.cpp.
References wmtk::components::procedural::Grid2Options::BCC, wmtk::components::procedural::Grid2Options::Diagonal, and wmtk::components::procedural::Grid2Options::tiling_type.
make_mesh() [3/5]
std::shared_ptr< TetMesh > wmtk::components::procedural::make_mesh (const Grid3Options & opt)
Definition at line 94 of file Grid3Options.cpp.
References wmtk::components::procedural::Grid3Options::BCC, wmtk::components::procedural::Grid3Options::Freudenthal, and wmtk::components::procedural::Grid3Options::tiling_type.
make_mesh() [4/5]
std::shared_ptr< Mesh > wmtk::components::procedural::make_mesh (const GridOptions & m)
Definition at line 12 of file GridOptions.cpp.
References make_mesh(), and wmtk::components::procedural::GridOptions::opts.
make_mesh() [5/5]
std::shared_ptr< TriMesh > wmtk::components::procedural::make_mesh (const TriangleFanOptions & opt)
Definition at line 10 of file TriangleFanOptions.cpp.
References wmtk::components::procedural::TriangleFanOptions::coordinates, wmtk::TriMesh::initialize(), wmtk::mesh_utils::set_matrix_attribute(), wmtk::components::procedural::TriangleFanOptions::size, and wmtk::Vertex.