Wildmeshing Toolkit: wmtk::components::triangle_insertion Namespace Reference
wmtk::components::triangle_insertion Namespace Reference
Classes
class ChildMeshes
Functions
std::tuple< std::shared_ptr< wmtk::TetMesh >, ChildMeshes > triangle_insertion (const TetMesh &bg_mesh, const std::string &bg_position, const TriMesh &mesh_in, const std::string &in_position, bool round, bool track_submeshes, bool make_child_free)
Function Documentation
triangle_insertion()
std::tuple< std::shared_ptr< wmtk::TetMesh >, ChildMeshes > wmtk::components::triangle_insertion::triangle_insertion (const TetMesh & bg_mesh, const std::string & bg_position, const TriMesh & mesh_in, const std::string & in_position, bool round, bool track_submeshes, bool make_child_free)
Definition at line 27 of file triangle_insertion.cpp.
References wmtk::components::triangle_insertion::ChildMeshes::bbox_mesh, wmtk::components::internal::MultiMeshFromTag::compute_substructure_mesh(), wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag_handle(), wmtk::utils::generate_raw_tetmesh_from_input_surface(), wmtk::utils::EigenMatrixWriter::get_double_matrix(), wmtk::utils::EigenMatrixWriter::get_FV_matrix(), wmtk::utils::EigenMatrixWriter::get_TV_matrix(), wmtk::logger(), wmtk::components::triangle_insertion::ChildMeshes::nonmanifold_edge_mesh, wmtk::components::triangle_insertion::ChildMeshes::open_boundary_mesh, wmtk::PE, PF, PT, wmtk::PV, wmtk::components::internal::MultiMeshFromTag::remove_soup(), wmtk::operations::AttributeTransferStrategyBase::run_on_all(), wmtk::Scheduler::run_operation_on_all(), wmtk::Mesh::serialize(), wmtk::components::triangle_insertion::ChildMeshes::surface_mesh, wmtk::Tetrahedron, wmtk::Triangle, wmtk::Vertex, and wmtk::simplex::Simplex::vertex().