Wildmeshing Toolkit: wmtk::autogen Namespace Reference
wmtk::autogen Namespace Reference
Namespaces
namespace edge_mesh
namespace internal
namespace point_mesh
namespace subgroup
namespace tet_mesh
namespace tri_mesh
namespace utils
Classes
class Dart
class SimplexDart
Typedefs
using DynamicIntMap = VectorX< int8_t >::ConstMapType
Functions
int8_t find_local_dart_action (const SimplexDart &sd, int8_t source, int8_t target)
bool is_ccw (PrimitiveType pt, const Tuple &t)
bool tuple_is_valid_for_ccw (PrimitiveType pt, const Tuple &t)
int8_t local_dart_action (const SimplexDart &sd, int8_t s, int8_t action)
Dart local_dart_action (const SimplexDart &sd, const Dart &d, int8_t action)
Tuple local_switch_tuple (PrimitiveType mesh_type, const Tuple &t, PrimitiveType pt)
Tuple local_switch_tuple (PrimitiveType mesh_type, const Tuple &t, int8_t valid_tuple_index)
int8_t simplex_index_from_valid_index (PrimitiveType mesh_type, int8_t valid_tuple_index, PrimitiveType simplex_type)
Tuple tuple_from_valid_index (PrimitiveType mesh_type, const int64_t global_cid, int8_t valid_tuple_index)
int8_t valid_index_from_tuple (PrimitiveType mesh_type, const Tuple &t)
Typedef Documentation
DynamicIntMap
using wmtk::autogen::DynamicIntMap = typedef VectorX<int8_t>::ConstMapType
Definition at line 68 of file SimplexDart.cpp.
Function Documentation
find_local_dart_action()
int8_t wmtk::autogen::find_local_dart_action (const SimplexDart & sd, int8_t source, int8_t target) inline
Definition at line 6 of file find_local_dart_action.hpp.
References wmtk::autogen::SimplexDart::inverse(), and wmtk::autogen::SimplexDart::product().
Referenced by wmtk::multimesh::utils::find_local_dart_action(), wmtk::multimesh::utils::find_local_dart_action(), and wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action().
is_ccw()
bool wmtk::autogen::is_ccw (PrimitiveType pt, const Tuple & t)
Definition at line 8 of file is_ccw.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::is_ccw(), wmtk::autogen::tet_mesh::is_ccw(), wmtk::autogen::tri_mesh::is_ccw(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::operations::AMIPSOptimizationSmoothing::execute(), and wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute().
local_dart_action() [1/2]
Dart wmtk::autogen::local_dart_action (const SimplexDart & sd, const Dart & d, int8_t action)
Definition at line 11 of file local_dart_action.cpp.
References wmtk::autogen::Dart::global_id(), local_dart_action(), and wmtk::autogen::Dart::local_orientation().
local_dart_action() [2/2]
int8_t wmtk::autogen::local_dart_action (const SimplexDart & sd, int8_t s, int8_t action)
Definition at line 7 of file local_dart_action.cpp.
References wmtk::autogen::SimplexDart::product().
Referenced by local_dart_action().
local_switch_tuple() [1/2]
Tuple wmtk::autogen::local_switch_tuple (PrimitiveType mesh_type, const Tuple & t, int8_t valid_tuple_index)
Definition at line 17 of file local_switch_tuple.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::local_switch_tuple(), wmtk::autogen::tet_mesh::local_switch_tuple(), wmtk::autogen::tri_mesh::local_switch_tuple(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
local_switch_tuple() [2/2]
Tuple wmtk::autogen::local_switch_tuple (PrimitiveType mesh_type, const Tuple & t, PrimitiveType pt)
Definition at line 6 of file local_switch_tuple.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::local_switch_tuple(), wmtk::autogen::tet_mesh::local_switch_tuple(), wmtk::autogen::tri_mesh::local_switch_tuple(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action().
simplex_index_from_valid_index()
int8_t wmtk::autogen::simplex_index_from_valid_index (PrimitiveType mesh_type, int8_t valid_tuple_index, PrimitiveType simplex_type)
Definition at line 7 of file simplex_index_from_valid_index.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::simplex_index_from_valid_index(), wmtk::autogen::tet_mesh::simplex_index_from_valid_index(), wmtk::autogen::tri_mesh::simplex_index_from_valid_index(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::autogen::SimplexDart::simplex_index().
tuple_from_valid_index()
Tuple wmtk::autogen::tuple_from_valid_index (PrimitiveType mesh_type, const int64_t global_cid, int8_t valid_tuple_index)
Definition at line 8 of file tuple_from_valid_index.cpp.
References wmtk::Edge, wmtk::Tetrahedron, wmtk::Triangle, wmtk::autogen::edge_mesh::tuple_from_valid_index(), wmtk::autogen::tet_mesh::tuple_from_valid_index(), wmtk::autogen::tri_mesh::tuple_from_valid_index(), and wmtk::Vertex.
Referenced by wmtk::autogen::SimplexDart::tuple_from_valid_index(), and wmtk::autogen::SimplexDart::update_tuple_from_valid_index().
tuple_is_valid_for_ccw()
bool wmtk::autogen::tuple_is_valid_for_ccw (PrimitiveType pt, const Tuple & t)
Definition at line 21 of file is_ccw.cpp.
References wmtk::Edge, wmtk::Tetrahedron, wmtk::Triangle, wmtk::autogen::edge_mesh::tuple_is_valid_for_ccw(), wmtk::autogen::tet_mesh::tuple_is_valid_for_ccw(), wmtk::autogen::tri_mesh::tuple_is_valid_for_ccw(), and wmtk::Vertex.
valid_index_from_tuple()
int8_t wmtk::autogen::valid_index_from_tuple (PrimitiveType mesh_type, const Tuple & t)
Definition at line 10 of file valid_index_from_tuple.cpp.
References wmtk::Edge, wmtk::Tetrahedron, wmtk::Triangle, wmtk::autogen::edge_mesh::valid_index_from_tuple(), wmtk::autogen::tet_mesh::valid_index_from_tuple(), wmtk::autogen::tri_mesh::valid_index_from_tuple(), and wmtk::Vertex.
Referenced by wmtk::autogen::SimplexDart::dart_from_tuple(), and wmtk::autogen::SimplexDart::valid_index_from_tuple().