Wildmeshing Toolkit: wmtk::mesh_utils Namespace Reference
wmtk::mesh_utils Namespace Reference
Functions
Eigen::Vector3d compute_face_normal_area_weighted (const TriMesh &m, const attribute::Accessor< double > &pos, const Tuple &f)
compute area vector of face
Eigen::Vector3d compute_face_normal (const TriMesh &m, const attribute::Accessor< double > &pos, const Tuple &f)
compute the normalized face normal based on the vertex positions
Eigen::Vector3d compute_vertex_normal (const TriMesh &m, const attribute::Accessor< double > &pos, const Tuple &v)
compute the normalized vertex normal from the incident area weighted face normals
template<typename Mat >
attribute::MeshAttributeHandle set_matrix_attribute (const Mat &data, const std::string &name, const PrimitiveType &type, Mesh &mesh)
Function Documentation
compute_face_normal()
Eigen::Vector3d wmtk::mesh_utils::compute_face_normal (const TriMesh & m, const attribute::Accessor< double > & pos, const Tuple & f)
compute the normalized face normal based on the vertex positions
Definition at line 23 of file mesh_utils.cpp.
References compute_face_normal_area_weighted().
compute_face_normal_area_weighted()
Eigen::Vector3d wmtk::mesh_utils::compute_face_normal_area_weighted (const TriMesh & m, const attribute::Accessor< double > & pos, const Tuple & f)
compute area vector of face
Definition at line 7 of file mesh_utils.cpp.
References wmtk::attribute::Accessor< T, MeshType, Dim >::const_vector_attribute(), wmtk::TriMesh::switch_edge(), and wmtk::TriMesh::switch_vertex().
Referenced by compute_face_normal(), and compute_vertex_normal().
compute_vertex_normal()
Eigen::Vector3d wmtk::mesh_utils::compute_vertex_normal (const TriMesh & m, const attribute::Accessor< double > & pos, const Tuple & v)
compute the normalized vertex normal from the incident area weighted face normals
Definition at line 29 of file mesh_utils.cpp.
References wmtk::simplex::closed_star(), compute_face_normal_area_weighted(), wmtk::TriMesh::is_ccw(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::TriMesh::switch_vertex(), wmtk::Triangle, and wmtk::simplex::Simplex::vertex().
Referenced by wmtk::operations::VertexTangentialLaplacianSmooth::operator()().
set_matrix_attribute()
template<typename Mat > attribute::MeshAttributeHandle wmtk::mesh_utils::set_matrix_attribute (const Mat & data, const std::string & name, const PrimitiveType & type, Mesh & mesh) inline
Definition at line 9 of file mesh_utils.hpp.
References wmtk::attribute::MeshAttributeHandle::as(), wmtk::Mesh::create_accessor(), and wmtk::Mesh::get_all().
Referenced by wmtk::components::multimesh::axis_aligned_fusion(), wmtk::components::internal::CDT_internal(), wmtk::components::delaunay_exec(), wmtk::components::edge_insertion(), wmtk::io::MshReader::generate(), wmtk::utils::generate_raw_tetmesh_from_input_surface(), wmtk::components::procedural::make_mesh(), wmtk::components::input::mesh_with_tag_from_image(), TEST_CASE(), wmtk::components::tetwild_simplification(), and wmtk::components::to_points().