Wildmeshing Toolkit: wmtk::simplex::utils Namespace Reference
wmtk::simplex::utils Namespace Reference
Classes
class MeshSimplexComparator
class SimplexComparisons
Functions
std::vector< Simplex > make_unique (const Mesh &m, const std::vector< Simplex > &s)
std::vector< Tuple > make_unique_tuples (const Mesh &m, const std::vector< Tuple > &ts, PrimitiveType primitive)
std::vector< Simplex > tuple_vector_to_homogeneous_simplex_vector (const std::vector< Tuple > &tups, PrimitiveType primitive)
std::vector< Tuple > unique_homogeneous_simplices (const Mesh &m, PrimitiveType pt, const std::vector< Tuple > &tups)
void unique_homogeneous_simplices_inline (const Mesh &m, PrimitiveType pt, std::vector< Tuple > &tups)
Function Documentation
make_unique()
std::vector< Simplex > wmtk::simplex::utils::make_unique (const Mesh & m, const std::vector< Simplex > & s)
Definition at line 8 of file make_unique.cpp.
Referenced by make_unique_tuples(), and wmtk::attribute::MeshAttributes< T >::register_attribute().
make_unique_tuples()
std::vector< Tuple > wmtk::simplex::utils::make_unique_tuples (const Mesh & m, const std::vector< Tuple > & ts, PrimitiveType primitive)
Definition at line 18 of file make_unique.cpp.
References make_unique().
Referenced by wmtk::multimesh::MultiMeshManager::map_to_child_tuples().
tuple_vector_to_homogeneous_simplex_vector()
std::vector< Simplex > wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector (const std::vector< Tuple > & tups, PrimitiveType primitive)
Definition at line 7 of file tuple_vector_to_homogeneous_simplex_vector.cpp.
Referenced by wmtk::simplex::boundary(), wmtk::simplex::internal::boundary_with_preserved_face_simplices(), wmtk::simplex::cofaces_single_dimension_simplices(), wmtk::multimesh::MultiMeshManager::lub_map(), wmtk::multimesh::MultiMeshManager::map(), wmtk::multimesh::MultiMeshManager::map_to_child(), wmtk::simplex::neighbors_single_dimension(), wmtk::Scheduler::run_operation_on_all(), and wmtk::simplex::top_dimension_cofaces().
unique_homogeneous_simplices()
std::vector< Tuple > wmtk::simplex::utils::unique_homogeneous_simplices (const Mesh & m, PrimitiveType pt, const std::vector< Tuple > & tups)
Definition at line 8 of file unique_homogeneous_simplices.cpp.
References unique_homogeneous_simplices_inline().
unique_homogeneous_simplices_inline()
void wmtk::simplex::utils::unique_homogeneous_simplices_inline (const Mesh & m, PrimitiveType pt, std::vector< Tuple > & tups)
Definition at line 14 of file unique_homogeneous_simplices.cpp.
Referenced by wmtk::operations::AttributeTransferStrategyBase::get_parent_simplices(), and unique_homogeneous_simplices().