Wildmeshing Toolkit: wmtk::function Namespace Reference
wmtk::function Namespace Reference
Namespaces
utils
Classes
class Function
class LocalNeighborsSumFunction
class PerSimplexAutodiffFunction
This is an extension of the PerSimplexFunction class that uses autodiff encoding for differentiations.
class PerSimplexFunction
class AMIPS
class EdgeValenceEnergy
class PositionMapAMIPS2D
2D TriangleAMIPS uses uv and position map to get the 3d cooridnates then evaluate
class TriangleAMIPS
This is the implementation of the AMIPS energy function of a triangle mesh that can be embedded in 2d or 3d.
Typedefs
using DScalar = typename PerSimplexAutodiffFunction::DScalar
using DSVec2 = Eigen::Vector2< DScalar >
using DSVec3 = Eigen::Vector3< DScalar >
Functions
double Tet_AMIPS_energy_aux (const std::array< double, 12 > &T)
void Tet_AMIPS_jacobian (const std::array< double, 12 > &T, Eigen::Vector3d &result_0)
void Tet_AMIPS_hessian (const std::array< double, 12 > &T, Eigen::Matrix3d &result_0)
double Tet_AMIPS_energy (const std::array< double, 12 > &T)
double Tri_AMIPS_energy (const std::array< double, 6 > &T)
void Tri_AMIPS_jacobian (const std::array< double, 6 > &T, Eigen::Vector2d &result_0)
void Tri_AMIPS_hessian (const std::array< double, 6 > &T, Eigen::Matrix2d &result_0)
template<int64_t NV, int64_t DIM>
std::array< double, NV *DIM > unbox (const std::vector< std::decay_t< typename attribute::ConstMapResult< double >>> &data, const int64_t index)
template<int64_t NV, int64_t DIM>
std::array< Rational, NV *DIM > unbox (const std::vector< std::decay_t< typename attribute::ConstMapResult< Rational >>> &data, const int64_t index)
Typedef Documentation
DScalar
using wmtk::function::DScalar = typedef typename PerSimplexAutodiffFunction::DScalar
Definition at line 17 of file TriangleAMIPS.cpp.
DSVec2
using wmtk::function::DSVec2 = typedef Eigen::Vector2<DScalar>
Definition at line 18 of file TriangleAMIPS.cpp.
DSVec3
using wmtk::function::DSVec3 = typedef Eigen::Vector3<DScalar>
Definition at line 19 of file TriangleAMIPS.cpp.
Function Documentation
Tet_AMIPS_energy()
double wmtk::function::Tet_AMIPS_energy (const std::array< double, 12 > & T)
Definition at line 374 of file AMIPS.cpp.
References wmtk::pow(), and Tet_AMIPS_energy_aux().
Referenced by wmtk::function::AMIPS::get_value(), wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::value(), and wmtk::components::wildmeshing().
Tet_AMIPS_energy_aux()
double wmtk::function::Tet_AMIPS_energy_aux (const std::array< double, 12 > & T)
Definition at line 11 of file AMIPS.cpp.
Referenced by Tet_AMIPS_energy().
Tet_AMIPS_hessian()
void wmtk::function::Tet_AMIPS_hessian (const std::array< double, 12 > & T, Eigen::Matrix3d & result_0)
Definition at line 171 of file AMIPS.cpp.
References wmtk::pow().
Referenced by wmtk::function::AMIPS::get_hessian(), and wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::hessian().
Tet_AMIPS_jacobian()
void wmtk::function::Tet_AMIPS_jacobian (const std::array< double, 12 > & T, Eigen::Vector3d & result_0)
Definition at line 74 of file AMIPS.cpp.
References wmtk::pow().
Referenced by wmtk::function::AMIPS::get_gradient(), and wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::gradient().
Tri_AMIPS_energy()
double wmtk::function::Tri_AMIPS_energy (const std::array< double, 6 > & T)
Definition at line 434 of file AMIPS.cpp.
References wmtk::abs().
Referenced by wmtk::function::AMIPS::get_value(), wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::value(), and wmtk::components::wildmeshing().
Tri_AMIPS_hessian()
void wmtk::function::Tri_AMIPS_hessian (const std::array< double, 6 > & T, Eigen::Matrix2d & result_0)
Definition at line 509 of file AMIPS.cpp.
References wmtk::pow().
Referenced by wmtk::function::AMIPS::get_hessian(), and wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::hessian().
Tri_AMIPS_jacobian()
void wmtk::function::Tri_AMIPS_jacobian (const std::array< double, 6 > & T, Eigen::Vector2d & result_0)
Definition at line 470 of file AMIPS.cpp.
Referenced by wmtk::function::AMIPS::get_gradient(), and wmtk::operations::AMIPSOptimizationSmoothing::WMTKAMIPSProblem< S >::gradient().
unbox() [1/2]
template<int64_t NV, int64_t DIM> std::array<double, NV * DIM> wmtk::function::unbox (const std::vector< std::decay_t< typename attribute::ConstMapResult< double >>> & data, const int64_t index)
Definition at line 560 of file AMIPS.cpp.
unbox() [2/2]
template<int64_t NV, int64_t DIM> std::array<Rational, NV * DIM> wmtk::function::unbox (const std::vector< std::decay_t< typename attribute::ConstMapResult< Rational >>> & data, const int64_t index)
Definition at line 582 of file AMIPS.cpp.