Wildmeshing Toolkit: wmtk::autogen::tet_mesh Namespace Reference
wmtk::autogen::tet_mesh Namespace Reference
Namespaces
internal
Classes
class SimplexDart
Functions
bool is_ccw (const Tuple &t)
bool tuple_is_valid_for_ccw (const Tuple &t)
int64_t local_id_table_offset (const Tuple &t)
std::array< int64_t, 3 > lvid_leid_lfid_from_table_offset (int64_t table_offset)
Tuple local_switch_tuple (const Tuple &t, PrimitiveType pt)
Tuple local_switch_tuple (const Tuple &t, int8_t valid_tuple_index)
int8_t simplex_index_from_valid_index (int8_t valid_index, wmtk::PrimitiveType type)
int8_t subdart_maximal_action_to_face_action (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
int8_t subdart_maximal_action_to_face_size (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
std::array< int8_t, 2 > subdart_maximal_action_to_face (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Returns a dart action that maximizes the number of sub-darts preserved.
Tuple tuple_from_valid_index (int64_t global_cid, int8_t valid_tuple_index)
int8_t valid_index_from_tuple (const Tuple &t)
Variables
const int64_t auto_3d_edges [6][2] = {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}}
const int64_t auto_3d_faces [4][3] = {{1, 2, 3}, {0, 2, 3}, {0, 1, 3}, {0, 1, 2}}
const int64_t auto_3d_table_vertex [96][3]
const int64_t auto_3d_table_edge [96][3]
const int64_t auto_3d_table_face [96][3]
const int64_t auto_3d_table_ccw [96]
const int64_t auto_3d_table_complete_vertex [4][3] = {{0, 0, 2}, {1, 0, 3}, {2, 1, 1}, {3, 2, 2}}
const int64_t auto_3d_table_complete_edge [6][3]
const int64_t auto_3d_table_complete_face [4][3] = {{1, 3, 0}, {0, 2, 1}, {0, 0, 2}, {0, 1, 3}}
const int8_t auto_valid_tuples [24][3]
const int8_t auto_valid_tuple_indices [24]
const int8_t auto_all_to_valid_tuple_indices [96]
const int8_t auto_valid_switch_table [24][3]
const int8_t auto_valid_switch_product_table [24][24]
const int8_t auto_valid_switch_inverse_table [24]
const int8_t auto_valid_tuple_switch_indices [5] = {7, 3, 0, 1, 22}
const int8_t subdart_preserving_action_1 [24][6]
const int8_t max_subdart_preservation_dimension_1 [24][6]
const int8_t subdart_preserving_action_2 [24][4]
const int8_t max_subdart_preservation_dimension_2 [24][4]
Function Documentation
is_ccw()
bool wmtk::autogen::tet_mesh::is_ccw (const Tuple & t) inline
Definition at line 10 of file is_ccw.hxx.
References auto_3d_table_ccw, local_id_table_offset(), and tuple_is_valid_for_ccw().
Referenced by wmtk::TetMesh::is_ccw(), and wmtk::autogen::is_ccw().
local_id_table_offset()
int64_t wmtk::autogen::tet_mesh::local_id_table_offset (const Tuple & t) inline
Definition at line 6 of file local_id_table_offset.hxx.
References wmtk::utils::TupleInspector::local_eid(), wmtk::utils::TupleInspector::local_fid(), and wmtk::utils::TupleInspector::local_vid().
Referenced by is_ccw(), wmtk::autogen::utils::local_id_table_offset(), local_switch_tuple(), tuple_is_valid_for_ccw(), and valid_index_from_tuple().
local_switch_tuple() [1/2]
Tuple wmtk::autogen::tet_mesh::local_switch_tuple (const Tuple & t, int8_t valid_tuple_index) inline
Definition at line 46 of file local_switch_tuple.hxx.
References auto_valid_switch_product_table, wmtk::utils::TupleInspector::global_cid(), tuple_from_valid_index(), and valid_index_from_tuple().
local_switch_tuple() [2/2]
Tuple wmtk::autogen::tet_mesh::local_switch_tuple (const Tuple & t, PrimitiveType pt) inline
Definition at line 12 of file local_switch_tuple.hxx.
References auto_3d_table_edge, auto_3d_table_face, auto_3d_table_vertex, wmtk::Edge, local_id_table_offset(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::local_switch_tuple(), wmtk::autogen::local_switch_tuple(), and wmtk::TetMesh::switch_tuple().
lvid_leid_lfid_from_table_offset()
std::array< int64_t, 3 > wmtk::autogen::tet_mesh::lvid_leid_lfid_from_table_offset (int64_t table_offset) inline
Definition at line 18 of file local_id_table_offset.hxx.
simplex_index_from_valid_index()
int8_t wmtk::autogen::tet_mesh::simplex_index_from_valid_index (int8_t valid_index, wmtk::PrimitiveType type) inline
Definition at line 7 of file simplex_index_from_valid_index.hxx.
References auto_valid_tuples, and wmtk::get_primitive_type_id().
Referenced by wmtk::autogen::utils::simplex_index_from_valid_index(), wmtk::autogen::simplex_index_from_valid_index(), and wmtk::autogen::utils::valid_index_to_simplex_index().
subdart_maximal_action_to_face()
std::array< int8_t, 2 > wmtk::autogen::tet_mesh::subdart_maximal_action_to_face (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Returns a dart action that maximizes the number of sub-darts preserved.
Definition at line 41 of file subdart_maximal_action_to_face.cpp.
References wmtk::autogen::tet_mesh::SimplexDart::identity(), max_subdart_preservation_dimension_1, max_subdart_preservation_dimension_2, subdart_preserving_action_1, and subdart_preserving_action_2.
Referenced by wmtk::autogen::utils::subdart_maximal_action_to_face().
subdart_maximal_action_to_face_action()
int8_t wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_action (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Definition at line 7 of file subdart_maximal_action_to_face.cpp.
References wmtk::autogen::tet_mesh::SimplexDart::identity(), subdart_preserving_action_1, and subdart_preserving_action_2.
Referenced by wmtk::autogen::utils::subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_size()
int8_t wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_size (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Definition at line 24 of file subdart_maximal_action_to_face.cpp.
References max_subdart_preservation_dimension_1, and max_subdart_preservation_dimension_2.
Referenced by wmtk::autogen::utils::largest_shared_subdart_size(), and wmtk::autogen::utils::subdart_maximal_action_to_face_size().
tuple_from_valid_index()
Tuple wmtk::autogen::tet_mesh::tuple_from_valid_index (int64_t global_cid, int8_t valid_tuple_index) inline
Definition at line 7 of file tuple_from_valid_index.hxx.
References auto_valid_tuples.
Referenced by local_switch_tuple(), and wmtk::autogen::tuple_from_valid_index().
tuple_is_valid_for_ccw()
bool wmtk::autogen::tet_mesh::tuple_is_valid_for_ccw (const Tuple & t) inline
Definition at line 17 of file is_ccw.hxx.
References auto_3d_table_ccw, and local_id_table_offset().
Referenced by is_ccw(), wmtk::TetMesh::is_valid(), and wmtk::autogen::tuple_is_valid_for_ccw().
valid_index_from_tuple()
int8_t wmtk::autogen::tet_mesh::valid_index_from_tuple (const Tuple & t) inline
Definition at line 7 of file valid_index_from_tuple.hxx.
References auto_all_to_valid_tuple_indices, and local_id_table_offset().
Referenced by local_switch_tuple(), and wmtk::autogen::valid_index_from_tuple().
Variable Documentation
auto_3d_edges
const int64_t wmtk::autogen::tet_mesh::auto_3d_edges = {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}}
Definition at line 6 of file autogenerated_tables.cpp.
Referenced by wmtk::tetmesh_topology_initialization().
auto_3d_faces
const int64_t wmtk::autogen::tet_mesh::auto_3d_faces = {{1, 2, 3}, {0, 2, 3}, {0, 1, 3}, {0, 1, 2}}
Definition at line 8 of file autogenerated_tables.cpp.
Referenced by wmtk::tetmesh_topology_initialization().
auto_3d_table_ccw
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_ccw
Initial value:
= {
    -1, -1, 1,  0,  -1, 0,  -1, 1,  -1, 1,  0,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, 0,  1,  -1, -1, -1, -1, -1, -1, -1, -1, 1,  -1, -1, 0,  0,  -1, 1,  -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, 1,  -1, 0,  -1, -1, -1, -1, 0,  -1, -1, 1,  -1, -1, -1, -1, 1,  0,  -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  1,  -1, -1, -1, -1, -1, 1,  -1, 0,  -1, 0,  1,  -1, -1}
Definition at line 64 of file autogenerated_tables.cpp.
Referenced by is_ccw(), and tuple_is_valid_for_ccw().
auto_3d_table_complete_edge
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_complete_edge
Initial value:
=
    {{0, 0, 2}, {0, 1, 3}, {0, 2, 1}, {1, 3, 0}, {1, 4, 2}, {2, 5, 0}}
Definition at line 72 of file autogenerated_tables.cpp.
Referenced by wmtk::TetMesh::edge_tuple_from_id().
auto_3d_table_complete_face
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_complete_face = {{1, 3, 0}, {0, 2, 1}, {0, 0, 2}, {0, 1, 3}}
Definition at line 75 of file autogenerated_tables.cpp.
Referenced by wmtk::TetMesh::face_tuple_from_id().
auto_3d_table_complete_vertex
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_complete_vertex = {{0, 0, 2}, {1, 0, 3}, {2, 1, 1}, {3, 2, 2}}
Definition at line 70 of file autogenerated_tables.cpp.
Referenced by wmtk::TetMesh::tet_tuple_from_id(), and wmtk::TetMesh::vertex_tuple_from_id().
auto_3d_table_edge
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_edge
Initial value:
= {
    {-1, -1, -1}, {-1, -1, -1}, {0, 2, 2},    {0, 1, 3},    {-1, -1, -1}, {0, 2, 1},
    {-1, -1, -1}, {0, 0, 3},    {-1, -1, -1}, {0, 1, 1},    {0, 0, 2},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {1, 4, 2},    {1, 3, 3},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {1, 4, 0},    {-1, -1, -1}, {-1, -1, -1}, {1, 0, 3},    {1, 3, 0},    {-1, -1, -1},
    {1, 0, 2},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {2, 5, 1},
    {-1, -1, -1}, {2, 3, 3},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {2, 5, 0},    {-1, -1, -1}, {-1, -1, -1}, {2, 1, 3},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {2, 3, 0},    {2, 1, 1},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {3, 5, 1},    {3, 4, 2},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {3, 5, 0},    {-1, -1, -1},
    {3, 2, 2},    {-1, -1, -1}, {3, 4, 0},    {3, 2, 1},    {-1, -1, -1}, {-1, -1, -1}}
Definition at line 28 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple().
auto_3d_table_face
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_face
Initial value:
= {
    {-1, -1, -1}, {-1, -1, -1}, {0, 0, 3},    {0, 0, 2},    {-1, -1, -1}, {0, 1, 3},
    {-1, -1, -1}, {0, 1, 1},    {-1, -1, -1}, {0, 2, 2},    {0, 2, 1},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {1, 0, 3},    {1, 0, 2},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {1, 3, 3},    {-1, -1, -1}, {-1, -1, -1}, {1, 3, 0},    {1, 4, 2},    {-1, -1, -1},
    {1, 4, 0},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {2, 1, 3},
    {-1, -1, -1}, {2, 1, 1},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {2, 3, 3},    {-1, -1, -1}, {-1, -1, -1}, {2, 3, 0},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {2, 5, 1},    {2, 5, 0},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {3, 2, 2},    {3, 2, 1},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {3, 4, 2},    {-1, -1, -1},
    {3, 4, 0},    {-1, -1, -1}, {3, 5, 1},    {3, 5, 0},    {-1, -1, -1}, {-1, -1, -1}}
Definition at line 46 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple().
auto_3d_table_vertex
const int64_t wmtk::autogen::tet_mesh::auto_3d_table_vertex
Initial value:
= {
    {-1, -1, -1}, {-1, -1, -1}, {1, 0, 2},    {1, 0, 3},    {-1, -1, -1}, {2, 1, 1},
    {-1, -1, -1}, {2, 1, 3},    {-1, -1, -1}, {3, 2, 1},    {3, 2, 2},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {0, 0, 2},    {0, 0, 3},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {2, 3, 0},    {-1, -1, -1}, {-1, -1, -1}, {2, 3, 3},    {3, 4, 0},    {-1, -1, -1},
    {3, 4, 2},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {0, 1, 1},
    {-1, -1, -1}, {0, 1, 3},    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {1, 3, 0},    {-1, -1, -1}, {-1, -1, -1}, {1, 3, 3},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {3, 5, 0},    {3, 5, 1},    {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {0, 2, 1},    {0, 2, 2},    {-1, -1, -1},
    {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {-1, -1, -1}, {1, 4, 0},    {-1, -1, -1},
    {1, 4, 2},    {-1, -1, -1}, {2, 5, 0},    {2, 5, 1},    {-1, -1, -1}, {-1, -1, -1}}
Definition at line 10 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple().
auto_all_to_valid_tuple_indices
const int8_t wmtk::autogen::tet_mesh::auto_all_to_valid_tuple_indices
Initial value:
= {
    -1, -1, 0,  1,  -1, 2,  -1, 3,  -1, 4,  5,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, 6,  7,  -1, -1, -1, -1, -1, -1, -1, -1, 8,  -1, -1, 9,  10, -1, 11, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, 12, -1, 13, -1, -1, -1, -1, 14, -1, -1, 15, -1, -1, -1, -1, 16, 17, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, 18, 19, -1, -1, -1, -1, -1, 20, -1, 21, -1, 22, 23, -1, -1}
Definition at line 85 of file autogenerated_tables.cpp.
Referenced by valid_index_from_tuple().
auto_valid_switch_inverse_table
const int8_t wmtk::autogen::tet_mesh::auto_valid_switch_inverse_table
Initial value:
= {0,  1, 5,  3,  4,  2,  6,  7, 19, 13, 18, 12,
                                                    11, 9, 21, 15, 23, 17, 10, 8, 20, 14, 22, 16}
Definition at line 123 of file autogenerated_tables.cpp.
Referenced by wmtk::autogen::tet_mesh::SimplexDart::inverse().
auto_valid_switch_product_table
const int8_t wmtk::autogen::tet_mesh::auto_valid_switch_product_table
Initial value:
= {
    {1, 0, 4, 5, 2, 3, 7, 6, 10, 11, 8, 9, 18, 19, 20, 21, 22, 23, 12, 13, 14, 15, 16, 17},
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
    {3, 2, 5, 4, 0, 1, 13, 12, 16, 17, 14, 15, 19, 18, 22, 23, 20, 21, 6, 7, 8, 9, 10, 11},
    {2, 3, 0, 1, 5, 4, 12, 13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11, 19, 18, 22, 23, 20, 21},
    {5, 4, 3, 2, 1, 0, 19, 18, 22, 23, 20, 21, 13, 12, 16, 17, 14, 15, 7, 6, 10, 11, 8, 9},
    {4, 5, 1, 0, 3, 2, 18, 19, 20, 21, 22, 23, 7, 6, 10, 11, 8, 9, 13, 12, 16, 17, 14, 15},
    {7, 6, 10, 11, 8, 9, 1, 0, 4, 5, 2, 3, 20, 21, 18, 19, 23, 22, 14, 15, 12, 13, 17, 16},
    {6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 14, 15, 12, 13, 17, 16, 20, 21, 18, 19, 23, 22},
    {9, 8, 11, 10, 6, 7, 15, 14, 17, 16, 12, 13, 21, 20, 23, 22, 18, 19, 0, 1, 2, 3, 4, 5},
    {8, 9, 6, 7, 11, 10, 14, 15, 12, 13, 17, 16, 0, 1, 2, 3, 4, 5, 21, 20, 23, 22, 18, 19},
    {11, 10, 9, 8, 7, 6, 21, 20, 23, 22, 18, 19, 15, 14, 17, 16, 12, 13, 1, 0, 4, 5, 2, 3},
    {10, 11, 7, 6, 9, 8, 20, 21, 18, 19, 23, 22, 1, 0, 4, 5, 2, 3, 15, 14, 17, 16, 12, 13},
    {13, 12, 16, 17, 14, 15, 3, 2, 5, 4, 0, 1, 22, 23, 19, 18, 21, 20, 8, 9, 6, 7, 11, 10},
    {12, 13, 14, 15, 16, 17, 2, 3, 0, 1, 5, 4, 8, 9, 6, 7, 11, 10, 22, 23, 19, 18, 21, 20},
    {15, 14, 17, 16, 12, 13, 9, 8, 11, 10, 6, 7, 23, 22, 21, 20, 19, 18, 2, 3, 0, 1, 5, 4},
    {14, 15, 12, 13, 17, 16, 8, 9, 6, 7, 11, 10, 2, 3, 0, 1, 5, 4, 23, 22, 21, 20, 19, 18},
    {17, 16, 15, 14, 13, 12, 23, 22, 21, 20, 19, 18, 9, 8, 11, 10, 6, 7, 3, 2, 5, 4, 0, 1},
    {16, 17, 13, 12, 15, 14, 22, 23, 19, 18, 21, 20, 3, 2, 5, 4, 0, 1, 9, 8, 11, 10, 6, 7},
    {19, 18, 22, 23, 20, 21, 5, 4, 3, 2, 1, 0, 16, 17, 13, 12, 15, 14, 10, 11, 7, 6, 9, 8},
    {18, 19, 20, 21, 22, 23, 4, 5, 1, 0, 3, 2, 10, 11, 7, 6, 9, 8, 16, 17, 13, 12, 15, 14},
    {21, 20, 23, 22, 18, 19, 11, 10, 9, 8, 7, 6, 17, 16, 15, 14, 13, 12, 4, 5, 1, 0, 3, 2},
    {20, 21, 18, 19, 23, 22, 10, 11, 7, 6, 9, 8, 4, 5, 1, 0, 3, 2, 17, 16, 15, 14, 13, 12},
    {23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
    {22, 23, 19, 18, 21, 20, 16, 17, 13, 12, 15, 14, 5, 4, 3, 2, 1, 0, 11, 10, 9, 8, 7, 6}}
Definition at line 97 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple(), and wmtk::autogen::tet_mesh::SimplexDart::product().
auto_valid_switch_table
const int8_t wmtk::autogen::tet_mesh::auto_valid_switch_table
Initial value:
= {
    {6, 5, 1},   {7, 3, 0},   {12, 4, 3},   {13, 1, 2},   {18, 2, 5},   {19, 0, 4},
    {0, 11, 7},  {1, 9, 6},   {14, 10, 9},  {15, 7, 8},   {20, 8, 11},  {21, 6, 10},
    {2, 17, 13}, {3, 15, 12}, {8, 16, 15},  {9, 13, 14},  {22, 14, 17}, {23, 12, 16},
    {4, 23, 19}, {5, 21, 18}, {10, 22, 21}, {11, 19, 20}, {16, 20, 23}, {17, 18, 22}}
Definition at line 91 of file autogenerated_tables.cpp.
auto_valid_tuple_indices
const int8_t wmtk::autogen::tet_mesh::auto_valid_tuple_indices
Initial value:
= {2,  3,  5,  7,  9,  10, 26, 27, 36, 39, 40, 42,
                                             53, 55, 60, 63, 68, 69, 81, 82, 88, 90, 92, 93}
Definition at line 82 of file autogenerated_tables.cpp.
Referenced by wmtk::autogen::tet_mesh::SimplexDart::size(), wmtk::autogen::tet_mesh::SimplexDart::valid_indices(), and wmtk::autogen::tet_mesh::SimplexDart::valid_indices_dynamic().
auto_valid_tuple_switch_indices
const int8_t wmtk::autogen::tet_mesh::auto_valid_tuple_switch_indices = {7, 3, 0, 1, 22}
Definition at line 126 of file autogenerated_tables.cpp.
Referenced by wmtk::autogen::tet_mesh::SimplexDart::identity(), wmtk::autogen::tet_mesh::SimplexDart::opposite(), wmtk::autogen::tet_mesh::SimplexDart::primitive_to_index(), and wmtk::autogen::tet_mesh::internal::switch_primitive_to_valid_tuple_index().
auto_valid_tuples
const int8_t wmtk::autogen::tet_mesh::auto_valid_tuples
Initial value:
= {
    {0, 0, 2}, {0, 0, 3}, {0, 1, 1}, {0, 1, 3}, {0, 2, 1}, {0, 2, 2}, {1, 0, 2}, {1, 0, 3},
    {1, 3, 0}, {1, 3, 3}, {1, 4, 0}, {1, 4, 2}, {2, 1, 1}, {2, 1, 3}, {2, 3, 0}, {2, 3, 3},
    {2, 5, 0}, {2, 5, 1}, {3, 2, 1}, {3, 2, 2}, {3, 4, 0}, {3, 4, 2}, {3, 5, 0}, {3, 5, 1}}
Definition at line 77 of file autogenerated_tables.cpp.
Referenced by wmtk::autogen::tet_mesh::SimplexDart::simplex_index(), simplex_index_from_valid_index(), and tuple_from_valid_index().
max_subdart_preservation_dimension_1
const int8_t wmtk::autogen::tet_mesh::max_subdart_preservation_dimension_1
Initial value:
= {
    {3, 1, 1, 0, 0, 0}, {3, 1, 1, 0, 0, 0}, {1, 3, 1, 0, 0, 0}, {1, 3, 1, 0, 0, 0},
    {1, 1, 3, 0, 0, 0}, {1, 1, 3, 0, 0, 0}, {3, 0, 0, 1, 1, 0}, {3, 0, 0, 1, 1, 0},
    {1, 0, 0, 3, 1, 0}, {1, 0, 0, 3, 1, 0}, {1, 0, 0, 1, 3, 0}, {1, 0, 0, 1, 3, 0},
    {0, 3, 0, 1, 0, 1}, {0, 3, 0, 1, 0, 1}, {0, 1, 0, 3, 0, 1}, {0, 1, 0, 3, 0, 1},
    {0, 1, 0, 1, 0, 3}, {0, 1, 0, 1, 0, 3}, {0, 0, 3, 0, 1, 1}, {0, 0, 3, 0, 1, 1},
    {0, 0, 1, 0, 3, 1}, {0, 0, 1, 0, 3, 1}, {0, 0, 1, 0, 1, 3}, {0, 0, 1, 0, 1, 3}}
Definition at line 136 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_size().
max_subdart_preservation_dimension_2
const int8_t wmtk::autogen::tet_mesh::max_subdart_preservation_dimension_2
Initial value:
= {
    {0, 1, 3, 2}, {0, 1, 2, 3}, {0, 3, 1, 2}, {0, 2, 1, 3}, {0, 3, 2, 1}, {0, 2, 3, 1},
    {1, 0, 3, 2}, {1, 0, 2, 3}, {3, 0, 1, 2}, {2, 0, 1, 3}, {3, 0, 2, 1}, {2, 0, 3, 1},
    {1, 3, 0, 2}, {1, 2, 0, 3}, {3, 1, 0, 2}, {2, 1, 0, 3}, {3, 2, 0, 1}, {2, 3, 0, 1},
    {1, 3, 2, 0}, {1, 2, 3, 0}, {3, 1, 2, 0}, {2, 1, 3, 0}, {3, 2, 1, 0}, {2, 3, 1, 0}}
Definition at line 150 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_size().
subdart_preserving_action_1
const int8_t wmtk::autogen::tet_mesh::subdart_preserving_action_1
Initial value:
= {
    {1, 5, 3, 21, 15, 23}, {1, 3, 5, 15, 21, 23}, {5, 1, 3, 21, 23, 15}, {3, 1, 5, 15, 23, 21},
    {5, 3, 1, 23, 21, 15}, {3, 5, 1, 23, 15, 21}, {1, 21, 15, 5, 3, 23}, {1, 15, 21, 3, 5, 23},
    {5, 21, 23, 1, 3, 15}, {3, 15, 23, 1, 5, 21}, {5, 23, 21, 3, 1, 15}, {3, 23, 15, 5, 1, 21},
    {21, 1, 15, 5, 23, 3}, {15, 1, 21, 3, 23, 5}, {21, 5, 23, 1, 15, 3}, {15, 3, 23, 1, 21, 5},
    {23, 5, 21, 3, 15, 1}, {23, 3, 15, 5, 21, 1}, {21, 15, 1, 23, 5, 3}, {15, 21, 1, 23, 3, 5},
    {21, 23, 5, 15, 1, 3}, {15, 23, 3, 21, 1, 5}, {23, 21, 5, 15, 3, 1}, {23, 15, 3, 21, 5, 1}}
Definition at line 128 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_action().
subdart_preserving_action_2
const int8_t wmtk::autogen::tet_mesh::subdart_preserving_action_2
Initial value:
= {
    {22, 4, 1, 0}, {22, 4, 0, 1}, {22, 1, 4, 0}, {22, 0, 4, 1}, {22, 1, 0, 4}, {22, 0, 1, 4},
    {4, 22, 1, 0}, {4, 22, 0, 1}, {1, 22, 4, 0}, {0, 22, 4, 1}, {1, 22, 0, 4}, {0, 22, 1, 4},
    {4, 1, 22, 0}, {4, 0, 22, 1}, {1, 4, 22, 0}, {0, 4, 22, 1}, {1, 0, 22, 4}, {0, 1, 22, 4},
    {4, 1, 0, 22}, {4, 0, 1, 22}, {1, 4, 0, 22}, {0, 4, 1, 22}, {1, 0, 4, 22}, {0, 1, 4, 22}}
Definition at line 144 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_action().