Wildmeshing Toolkit: wmtk::simplex Namespace Reference
wmtk::simplex Namespace Reference
Namespaces
internal
utils
Classes
class ClosedStarIterable
class FacesIterable
class LinkIterable
class OpenStarIterable
class TopDimensionCofacesIterable
class RawSimplex
A meshless implementation of the simplex that just stores an array of ids.
class RawSimplexCollection
class Simplex
class SimplexCollection
Functions
std::vector< Tuple > boundary_tuples (const Mesh &m, const Tuple &t, PrimitiveType pt)
std::vector< Tuple > boundary_tuples (const Mesh &mesh, const Simplex &simplex)
SimplexCollection boundary (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean=true)
Returns all boundary simplices of a simplex.
SimplexCollection closed_star (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean=true)
The closed star contains the input simplex, all its top dimension cofaces, and their faces.
ClosedStarIterable closed_star_iterable (const Mesh &mesh, const Simplex &simplex)
std::vector< Tuple > cofaces_single_dimension_tuples (const Mesh &mesh, const Simplex &my_simplex, PrimitiveType cofaces_type)
std::vector< Simplex > cofaces_single_dimension_simplices (const Mesh &mesh, const Simplex &simplex, PrimitiveType cofaces_type)
SimplexCollection cofaces_single_dimension (const Mesh &mesh, const Simplex &my_simplex, PrimitiveType cofaces_type, bool sort_and_clean=true)
Returns all cofaces of a simplex that are of the provided primitive type.
SimplexCollection faces (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean=true)
Returns all faces of a simplex.
void faces (SimplexCollection &simplex_collection, const Simplex &simplex, const bool sort_and_clean)
FacesIterable faces_iterable (const Mesh &mesh, const Simplex &simplex)
std::vector< Tuple > vertices (const Mesh &m, const Simplex &simplex)
void vertices (SimplexCollection &simplex_collection, const Simplex &simplex)
std::vector< Tuple > edges (const Mesh &m, const Simplex &simplex)
void edges (SimplexCollection &simplex_collection, const Simplex &simplex)
std::vector< Tuple > faces (const Mesh &m, const Simplex &simplex)
void faces (SimplexCollection &simplex_collection, const Simplex &simplex)
SimplexCollection faces_single_dimension (const Mesh &mesh, const Simplex &simplex, const PrimitiveType face_type)
Returns a vector with all faces in the boundary of a simplex of the given dimension.
void faces_single_dimension (SimplexCollection &simplex_collection, const Simplex &simplex, const PrimitiveType face_type)
std::vector< Tuple > faces_single_dimension_tuples (const Mesh &mesh, const Simplex &simplex, const PrimitiveType face_type)
std::vector< Tuple > coface_preserving_boundary_tuples (const Mesh &mesh, const Tuple &t, PrimitiveType pt, PrimtiiveType coface_pt)
SimplexCollection k_ring (const Mesh &mesh, const Simplex &simplex, int64_t k)
SimplexCollection link (const Mesh &mesh, const simplex::Simplex &simplex, const bool sort_and_clean)
SimplexCollection link (const TriMesh &mesh, const simplex::Simplex &simplex, const bool sort_and_clean)
SimplexCollection link (const TetMesh &mesh, const simplex::Simplex &simplex, const bool sort_and_clean)
SimplexCollection link_slow (const Mesh &mesh, const simplex::Simplex &simplex, const bool sort_and_clean)
bool link_condition_closed_trimesh (const TriMesh &mesh, const Tuple &edge)
bool link_condition (const EdgeMesh &mesh, const Tuple &edge)
Check if the edge to collapse satisfying the link condition.
bool link_condition (const TriMesh &mesh, const Tuple &edge)
bool link_condition_closed_tetmesh (const TetMesh &mesh, const Tuple &edge)
bool link_condition (const TetMesh &mesh, const Tuple &edge)
bool link_condition (const Mesh &mesh, const Tuple &edge)
LinkIterable link_iterable (const Mesh &mesh, const Simplex &simplex)
SimplexCollection link_single_dimension (const Mesh &mesh, const simplex::Simplex &simplex, const PrimitiveType link_type, const bool sort_and_clean)
SimplexCollection link_single_dimension (const TriMesh &mesh, const simplex::Simplex &simplex, const PrimitiveType link_type, const bool sort_and_clean)
SimplexCollection link_single_dimension (const TetMesh &mesh, const simplex::Simplex &simplex, const PrimitiveType link_type, const bool sort_and_clean)
SimplexCollection link_single_dimension_slow (const Mesh &mesh, const simplex::Simplex &simplex, const PrimitiveType link_type, const bool sort_and_clean)
std::vector< Simplex > neighbors_single_dimension (const Mesh &m, const Simplex &s, const PrimitiveType pt)
std::vector< Tuple > neighbors_single_dimension_tuples (const Mesh &m, const Simplex &s, const PrimitiveType tpt)
SimplexCollection open_star (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean)
SimplexCollection open_star (const TriMesh &mesh, const Simplex &simplex, const bool sort_and_clean)
SimplexCollection open_star (const TetMesh &mesh, const Simplex &simplex, const bool sort_and_clean)
SimplexCollection open_star_slow (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean)
OpenStarIterable open_star_iterable (const Mesh &mesh, const Simplex &simplex)
void top_dimension_cofaces (const Simplex &simplex, SimplexCollection &simplex_collection, const bool sort_and_clean=true)
Get all top dimension cofaces of the given simplex.
void top_dimension_cofaces_tuples (const EdgeMesh &mesh, const Simplex &simplex, SimplexCollection &collection)
void top_dimension_cofaces_tuples (const TriMesh &mesh, const Simplex &simplex, SimplexCollection &collection)
void top_dimension_cofaces_tuples (const TetMesh &mesh, const Simplex &simplex, SimplexCollection &collection)
void top_dimension_cofaces_tuples (const Mesh &mesh, const Simplex &simplex, SimplexCollection &collection)
The same as top_dimension_cofaces but it appends to a vector of tuples.
void top_dimension_cofaces_tuples (const EdgeMesh &mesh, const Simplex &simplex, std::vector< Tuple > &collection)
void top_dimension_cofaces_tuples (const TriMesh &mesh, const Simplex &simplex, std::vector< Tuple > &collection)
void top_dimension_cofaces_tuples (const TetMesh &mesh, const Simplex &simplex, std::vector< Tuple > &collection)
void top_dimension_cofaces_tuples (const Mesh &mesh, const Simplex &simplex, std::vector< Tuple > &tuples)
SimplexCollection top_dimension_cofaces (const TriMesh &mesh, const Simplex &simplex, const bool sort_and_clean)
SimplexCollection top_dimension_cofaces (const TetMesh &mesh, const Simplex &simplex, const bool sort_and_clean)
SimplexCollection top_dimension_cofaces (const Mesh &mesh, const Simplex &simplex, const bool sort_and_clean=true)
Get all top dimension cofaces of the given simplex.
std::vector< Tuple > top_dimension_cofaces_tuples (const EdgeMesh &mesh, const Simplex &simplex)
std::vector< Tuple > top_dimension_cofaces_tuples (const TriMesh &mesh, const Simplex &simplex)
std::vector< Tuple > top_dimension_cofaces_tuples (const TetMesh &mesh, const Simplex &simplex)
std::vector< Tuple > top_dimension_cofaces_tuples (const Mesh &mesh, const Simplex &simplex)
The same as top_dimension_cofaces but it returns only a vector of tuples.
TopDimensionCofacesIterable top_dimension_cofaces_iterable (const Mesh &mesh, const Simplex &simplex)
std::vector< Tuple > tuples_preserving_primitive_types (const Mesh &mesh, const Tuple &t, const PrimitiveType ptype1, const PrimitiveType ptype2)
Compute all tuples that contain simplex(ptype1, t) and that are contained by simplex(ptype2, t).
Function Documentation
boundary()
SimplexCollection wmtk::simplex::boundary (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean = true)
Returns all boundary simplices of a simplex.
The boundary simplices are the k-1 simplices that bound the given k-simplex. This does not include the given simplex itself!
tetrahedron: 4 faces
face: 3 edges
edge: 2 vertices
vertex: nothing
Parameters
mesh The mesh containing the simplex
simplex The simplex
sort_and_clean Call SimplexCollection::sort_and_clean before returning
Returns
SimplexCollection holding the boundary
Definition at line 44 of file boundary.cpp.
References boundary_tuples(), wmtk::get_primitive_type_from_id(), wmtk::get_primitive_type_id(), wmtk::simplex::Simplex::primitive_type(), wmtk::simplex::SimplexCollection::sort_and_clean(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
boundary_tuples() [1/2]
std::vector< Tuple > wmtk::simplex::boundary_tuples (const Mesh & m, const Tuple & t, PrimitiveType pt)
Definition at line 7 of file boundary.cpp.
References wmtk::Edge, wmtk::PE, PF, PT, wmtk::PV, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by boundary(), and boundary_tuples().
boundary_tuples() [2/2]
std::vector< Tuple > wmtk::simplex::boundary_tuples (const Mesh & mesh, const Simplex & simplex)
Definition at line 39 of file boundary.cpp.
References boundary_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::Simplex::tuple().
closed_star()
SimplexCollection wmtk::simplex::closed_star (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean = true)
The closed star contains the input simplex, all its top dimension cofaces, and their faces.
Parameters
mesh The mesh to which the simplex and its closed star belong.
simplex The simplex of which the closed star is computed.
Returns
A SimplexCollection with the closed star.
Definition at line 12 of file closed_star.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::Edge, faces(), wmtk::Mesh::is_valid(), wmtk::log_and_throw_error(), wmtk::simplex::SimplexCollection::reserve(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::Tetrahedron, top_dimension_cofaces(), wmtk::Mesh::top_simplex_type(), wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Referenced by wmtk::operations::Operation::apply_attribute_transfer(), wmtk::TriMesh::TriMeshOperationExecutor::collapse_edge_single_mesh(), wmtk::mesh_utils::compute_vertex_normal(), wmtk::operations::composite::TetEdgeSwap::execute(), wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), link_single_dimension_slow(), and link_slow().
closed_star_iterable()
ClosedStarIterable wmtk::simplex::closed_star_iterable (const Mesh & mesh, const Simplex & simplex)
Definition at line 5 of file closed_star_iterable.cpp.
coface_preserving_boundary_tuples()
std::vector<Tuple> wmtk::simplex::coface_preserving_boundary_tuples (const Mesh & mesh, const Tuple & t, PrimitiveType pt, PrimtiiveType coface_pt)
Definition at line 6 of file boundary_with_preserved_coface.cpp.
References wmtk::Edge, wmtk::PE, PF, PT, wmtk::PV, wmtk::Tetrahedron, and wmtk::Vertex.
cofaces_single_dimension()
SimplexCollection wmtk::simplex::cofaces_single_dimension (const Mesh & mesh, const Simplex & my_simplex, PrimitiveType cofaces_type, bool sort_and_clean = true)
Returns all cofaces of a simplex that are of the provided primitive type.
The coface tuples are guaranteed to contain the provided simplex in their tuple.
Parameters
mesh The mesh containing the simplex.
my_simplex The simplex whose cofaces we are computing.
cofaces_type The primitive type of the cofaces.
Returns
A SimplexCollection that contains the cofaces.
Definition at line 83 of file cofaces_single_dimension.cpp.
References cofaces_single_dimension_simplices(), and wmtk::simplex::SimplexCollection::sort_and_clean().
Referenced by link_condition().
cofaces_single_dimension_simplices()
std::vector< Simplex > wmtk::simplex::cofaces_single_dimension_simplices (const Mesh & mesh, const Simplex & simplex, PrimitiveType cofaces_type)
Definition at line 72 of file cofaces_single_dimension.cpp.
References cofaces_single_dimension_tuples(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::invariants::TetMeshSubstructureTopologyPreservingInvariant::before(), wmtk::invariants::TriMeshSubstructureTopologyPreservingInvariant::before(), cofaces_single_dimension(), wmtk::function::LocalNeighborsSumFunction::domain(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), and wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute().
cofaces_single_dimension_tuples()
std::vector< Tuple > wmtk::simplex::cofaces_single_dimension_tuples (const Mesh & mesh, const Simplex & my_simplex, PrimitiveType cofaces_type)
Definition at line 48 of file cofaces_single_dimension.cpp.
References wmtk::simplex::internal::boundary_with_preserved_face_tuples(), wmtk::utils::primitive_range(), wmtk::simplex::Simplex::primitive_type(), top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::Simplex::tuple().
Referenced by cofaces_single_dimension_simplices(), wmtk::TetMesh::is_boundary_edge(), wmtk::multimesh::MultiMeshManager::map_to_child_tuples(), neighbors_single_dimension_tuples(), and wmtk::components::internal::Marching::process().
edges() [1/2]
std::vector<Tuple> wmtk::simplex::edges (const Mesh & m, const Simplex & simplex)
Definition at line 77 of file faces_single_dimension.cpp.
References wmtk::Edge, wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Referenced by wmtk::components::collapsing(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), faces_single_dimension(), faces_single_dimension_tuples(), wmtk::components::shortestedge_collapse(), wmtk::components::swapping(), and TEST_CASE().
edges() [2/2]
void wmtk::simplex::edges (SimplexCollection & simplex_collection, const Simplex & simplex)
Definition at line 104 of file faces_single_dimension.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::Edge, wmtk::simplex::SimplexCollection::mesh(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
faces() [1/4]
std::vector<Tuple> wmtk::simplex::faces (const Mesh & m, const Simplex & simplex)
Definition at line 141 of file faces_single_dimension.cpp.
References wmtk::Edge, wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
faces() [2/4]
SimplexCollection wmtk::simplex::faces (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean = true)
Returns all faces of a simplex.
The faces are all lower dimensional simplices that bound the given k-simplex. This does not include the given simplex itself!
tetrahedron: 4 faces, 6 edges, 4 vertices
face: 3 edges, 3 vertices
edge: 2 vertices
vertex: nothing
Parameters
mesh The mesh containing the simplex
simplex The simplex
sort_and_clean Call SimplexCollection::sort_and_clean before returning
Returns
SimplexCollection holding the faces
Definition at line 10 of file faces.cpp.
Referenced by wmtk::components::AABBWrapper::AABBWrapper(), wmtk::invariants::EnvelopeInvariant::after(), closed_star(), wmtk::components::delaunay_exec(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), faces_single_dimension(), faces_single_dimension_tuples(), wmtk::function::utils::get_simplex_attributes(), link_single_dimension_slow(), link_slow(), open_star_slow(), wmtk::operations::composite::ProjectOperation::ProjectOperation(), wmtk::components::internal::RegularSpace::regularize_tags(), TEST_CASE(), wmtk::components::tetwild_simplification(), and wmtk::components::to_points().
faces() [3/4]
void wmtk::simplex::faces (SimplexCollection & simplex_collection, const Simplex & simplex)
Definition at line 162 of file faces_single_dimension.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::Edge, wmtk::simplex::SimplexCollection::mesh(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
faces() [4/4]
void wmtk::simplex::faces (SimplexCollection & simplex_collection, const Simplex & simplex, const bool sort_and_clean)
Definition at line 19 of file faces.cpp.
References faces_single_dimension(), wmtk::utils::primitive_below(), wmtk::utils::primitive_range(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::SimplexCollection::sort_and_clean().
faces_iterable()
FacesIterable wmtk::simplex::faces_iterable (const Mesh & mesh, const Simplex & simplex)
Definition at line 5 of file faces_iterable.cpp.
faces_single_dimension() [1/2]
SimplexCollection wmtk::simplex::faces_single_dimension (const Mesh & mesh, const Simplex & simplex, const PrimitiveType face_type)
Returns a vector with all faces in the boundary of a simplex of the given dimension.
Assuming the following tetrahedron:
      0
     / \\ .
    /   \  \ .
   /     \   \ .
  /       \     \ .
 /         \      3
/           \    /
/ \ / 1 ----------— 2
Given the tuple representing v(0), e(0,1), f(0,1,2), t(0,1,2,3) we have the following faces:
Tetrahedron:
PrimitiveType::Face { f(0,1,2), f(0,3,1), f(1,3,2), f(2,3,0) }
PrimitiveType::Edge { e(0,1), e(1,2), e(2,0), e(0,3), e(1,3), e(2,3) }
PrimitiveType::Vertex {v(0),v(1),v(2),v(3)}
Triangle:
PrimitiveType::Edge { e(0,1), e(1,2), e(2,0) }
PrimitiveType::Vertex {v(0),v(1),v(2)}
Edge:
PrimitiveType::Vertex {v(0),v(1)}
The order is relative to the orientation of the input tuple and guaranteed to be always the same (i.e. it is independent of the internal indices).
Parameters
mesh The mesh containing the simplex
simplex The simplex
face_type The requested face type
Returns
A vector of vertices sorted according to the tuple orientation of the simplex
Definition at line 189 of file faces_single_dimension.cpp.
Referenced by wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute(), and faces().
faces_single_dimension() [2/2]
void wmtk::simplex::faces_single_dimension (SimplexCollection & simplex_collection, const Simplex & simplex, const PrimitiveType face_type)
Definition at line 198 of file faces_single_dimension.cpp.
References wmtk::Edge, edges(), faces(), wmtk::simplex::SimplexCollection::mesh(), wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, wmtk::Vertex, and vertices().
faces_single_dimension_tuples()
std::vector< Tuple > wmtk::simplex::faces_single_dimension_tuples (const Mesh & mesh, const Simplex & simplex, const PrimitiveType face_type)
Definition at line 214 of file faces_single_dimension.cpp.
References wmtk::Edge, edges(), faces(), wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, wmtk::Vertex, and vertices().
Referenced by wmtk::invariants::EnvelopeInvariant::after(), wmtk::invariants::MinIncidentValenceInvariant::after(), wmtk::invariants::TetMeshSubstructureTopologyPreservingInvariant::before(), wmtk::invariants::TriMeshSubstructureTopologyPreservingInvariant::before(), wmtk::invariants::ValenceImprovementInvariant::before(), wmtk::components::internal::MultiMeshFromTag::build_adjacency_matrix(), wmtk::components::internal::MultiMeshFromTag::compute_substructure_ids(), wmtk::function::utils::get_simplex_attributes(), wmtk::invariants::MinIncidentValenceInvariant::is_greater_min_valence(), neighbors_single_dimension_tuples(), wmtk::operations::composite::ProjectOperation::ProjectOperation(), wmtk::components::internal::RegularSpace::regularize_tags(), and wmtk::components::to_points().
k_ring()
SimplexCollection wmtk::simplex::k_ring (const Mesh & mesh, const Simplex & simplex, int64_t k)
Definition at line 6 of file k_ring.cpp.
References wmtk::simplex::SimplexCollection::add(), link(), wmtk::simplex::SimplexCollection::simplex_vector(), and wmtk::simplex::SimplexCollection::sort_and_clean().
Referenced by wmtk::Scheduler::run_operation_on_all_coloring(), wmtk::components::internal::set_operation_energy_filter(), and wmtk::components::set_operation_energy_filter().
link() [1/3]
SimplexCollection wmtk::simplex::link (const Mesh & mesh, const simplex::Simplex & simplex, const bool sort_and_clean)
Definition at line 13 of file link.cpp.
References wmtk::Edge, link_slow(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::components::internal::adjust_sizing_field(), wmtk::components::adjust_sizing_field(), wmtk::invariants::TetMeshSubstructureTopologyPreservingInvariant::before(), wmtk::invariants::TriMeshSubstructureTopologyPreservingInvariant::before(), wmtk::invariants::ValenceImprovementInvariant::before(), wmtk::operations::TetWildTangentialLaplacianSmoothing::execute(), wmtk::function::EdgeValenceEnergy::get_value(), wmtk::invariants::MinIncidentValenceInvariant::is_greater_min_valence(), k_ring(), link_condition_closed_tetmesh(), link_condition_closed_trimesh(), wmtk::operations::VertexLaplacianSmooth::operator()(), wmtk::Scheduler::run_operation_on_all_coloring(), wmtk::components::set_operation_energy_filter_after_sizing_field(), and TEST_CASE().
link() [2/3]
SimplexCollection wmtk::simplex::link (const TetMesh & mesh, const simplex::Simplex & simplex, const bool sort_and_clean)
Definition at line 69 of file link.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::simplex::Simplex::face(), wmtk::log_and_throw_error(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), PT, wmtk::PV, wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::TetMesh::switch_vertex(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Triangle, wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
link() [3/3]
SimplexCollection wmtk::simplex::link (const TriMesh & mesh, const simplex::Simplex & simplex, const bool sort_and_clean)
Definition at line 27 of file link.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::log_and_throw_error(), wmtk::PE, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Triangle, wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
link_condition() [1/4]
bool wmtk::simplex::link_condition (const EdgeMesh & mesh, const Tuple & edge)
Check if the edge to collapse satisfying the link condition.
Parameters
mesh Input EdgeMesh, TriMesh, TetMesh
edge The edge tuple to collapse
Returns
true if the edge to collapse satisfying the link condition.
Definition at line 24 of file link_condition.cpp.
References wmtk::simplex::utils::SimplexComparisons::equal(), wmtk::EdgeMesh::is_boundary_vertex(), wmtk::EdgeMesh::switch_tuple(), and wmtk::Vertex.
Referenced by link_condition(), wmtk::components::internal::periodic_optimization(), and wmtk::components::wildmeshing().
link_condition() [2/4]
bool wmtk::simplex::link_condition (const Mesh & mesh, const Tuple & edge)
Definition at line 194 of file link_condition.cpp.
References wmtk::utils::metaprogramming::as_const_mesh_variant(), and link_condition().
link_condition() [3/4]
bool wmtk::simplex::link_condition (const TetMesh & mesh, const Tuple & edge)
Definition at line 119 of file link_condition.cpp.
References cofaces_single_dimension(), wmtk::Edge, wmtk::simplex::utils::SimplexComparisons::equal(), wmtk::TetMesh::is_boundary(), wmtk::TetMesh::is_boundary_edge(), link_condition_closed_tetmesh(), wmtk::TetMesh::switch_edge(), wmtk::TetMesh::switch_tuple(), wmtk::TetMesh::switch_vertex(), wmtk::Triangle, and wmtk::Vertex.
link_condition() [4/4]
bool wmtk::simplex::link_condition (const TriMesh & mesh, const Tuple & edge)
Definition at line 41 of file link_condition.cpp.
References wmtk::Edge, wmtk::simplex::utils::SimplexComparisons::equal(), wmtk::TriMesh::is_boundary(), wmtk::TriMesh::is_boundary_edge(), link_condition_closed_trimesh(), open_star(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::TriMesh::switch_tuple(), and wmtk::Vertex.
link_condition_closed_tetmesh()
bool wmtk::simplex::link_condition_closed_tetmesh (const TetMesh & mesh, const Tuple & edge)
Definition at line 103 of file link_condition.cpp.
References wmtk::simplex::SimplexCollection::are_simplex_collections_equal(), wmtk::simplex::Simplex::edge(), wmtk::simplex::SimplexCollection::get_intersection(), link(), wmtk::TetMesh::switch_vertex(), and wmtk::simplex::Simplex::vertex().
Referenced by link_condition().
link_condition_closed_trimesh()
bool wmtk::simplex::link_condition_closed_trimesh (const TriMesh & mesh, const Tuple & edge)
Definition at line 9 of file link_condition.cpp.
References wmtk::simplex::SimplexCollection::are_simplex_collections_equal(), wmtk::simplex::Simplex::edge(), wmtk::simplex::SimplexCollection::get_intersection(), link(), wmtk::TriMesh::switch_tuple(), wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
Referenced by link_condition().
link_iterable()
LinkIterable wmtk::simplex::link_iterable (const Mesh & mesh, const Simplex & simplex)
Definition at line 5 of file link_iterable.cpp.
link_single_dimension() [1/3]
SimplexCollection wmtk::simplex::link_single_dimension (const Mesh & mesh, const simplex::Simplex & simplex, const PrimitiveType link_type, const bool sort_and_clean)
Definition at line 13 of file link_single_dimension.cpp.
References wmtk::Edge, link_single_dimension_slow(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
link_single_dimension() [2/3]
SimplexCollection wmtk::simplex::link_single_dimension (const TetMesh & mesh, const simplex::Simplex & simplex, const PrimitiveType link_type, const bool sort_and_clean)
Definition at line 92 of file link_single_dimension.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::simplex::Simplex::face(), wmtk::log_and_throw_error(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), PT, wmtk::PV, wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::TetMesh::switch_vertex(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Triangle, wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
link_single_dimension() [3/3]
SimplexCollection wmtk::simplex::link_single_dimension (const TriMesh & mesh, const simplex::Simplex & simplex, const PrimitiveType link_type, const bool sort_and_clean)
Definition at line 38 of file link_single_dimension.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::log_and_throw_error(), wmtk::PE, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Triangle, wmtk::Vertex, and wmtk::simplex::Simplex::vertex().
link_single_dimension_slow()
SimplexCollection wmtk::simplex::link_single_dimension_slow (const Mesh & mesh, const simplex::Simplex & simplex, const PrimitiveType link_type, const bool sort_and_clean)
Definition at line 177 of file link_single_dimension.cpp.
References wmtk::simplex::SimplexCollection::add(), closed_star(), faces(), wmtk::simplex::SimplexCollection::get_intersection(), wmtk::simplex::SimplexCollection::simplex_vector(), and wmtk::simplex::SimplexCollection::sort_and_clean().
Referenced by link_single_dimension().
link_slow()
SimplexCollection wmtk::simplex::link_slow (const Mesh & mesh, const simplex::Simplex & simplex, const bool sort_and_clean)
Definition at line 130 of file link.cpp.
References wmtk::simplex::SimplexCollection::add(), closed_star(), faces(), wmtk::simplex::SimplexCollection::get_intersection(), wmtk::simplex::SimplexCollection::simplex_vector(), and wmtk::simplex::SimplexCollection::sort_and_clean().
Referenced by link().
neighbors_single_dimension()
std::vector< Simplex > wmtk::simplex::neighbors_single_dimension (const Mesh & m, const Simplex & s, const PrimitiveType pt)
Definition at line 9 of file neighbors_single_dimension.cpp.
References neighbors_single_dimension_tuples(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
neighbors_single_dimension_tuples()
std::vector< Tuple > wmtk::simplex::neighbors_single_dimension_tuples (const Mesh & m, const Simplex & s, const PrimitiveType tpt)
Definition at line 17 of file neighbors_single_dimension.cpp.
References cofaces_single_dimension_tuples(), faces_single_dimension_tuples(), wmtk::simplex::Simplex::primitive_type(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::Simplex::tuple().
Referenced by wmtk::operations::AttributeTransferStrategyBase::get_parent_simplices(), and neighbors_single_dimension().
open_star() [1/3]
SimplexCollection wmtk::simplex::open_star (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 12 of file open_star.cpp.
References wmtk::Edge, open_star_slow(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::invariants::TetMeshSubstructureTopologyPreservingInvariant::before(), wmtk::operations::composite::TetEdgeSwap::execute(), wmtk::TetMesh::TetMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_collapse_simplices_to_delete(), wmtk::TetMesh::TetMeshOperationExecutor::get_split_simplices_to_delete(), wmtk::TriMesh::TriMeshOperationExecutor::get_split_simplices_to_delete(), wmtk::TetMesh::is_boundary_vertex(), link_condition(), and wmtk::components::TagIntersection::simplex_is_in_intersection().
open_star() [2/3]
SimplexCollection wmtk::simplex::open_star (const TetMesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 62 of file open_star.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::simplex::Simplex::face(), wmtk::log_and_throw_error(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), PT, wmtk::PV, wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::TetMesh::switch_face(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::Tetrahedron, wmtk::simplex::Simplex::tetrahedron(), top_dimension_cofaces_tuples(), wmtk::Triangle, and wmtk::Vertex.
open_star() [3/3]
SimplexCollection wmtk::simplex::open_star (const TriMesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 25 of file open_star.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::simplex::Simplex::face(), wmtk::simplex::Simplex::primitive_type(), wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::TriMesh::switch_edge(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Triangle, and wmtk::Vertex.
open_star_iterable()
OpenStarIterable wmtk::simplex::open_star_iterable (const Mesh & mesh, const Simplex & simplex)
Definition at line 5 of file open_star_iterable.cpp.
open_star_slow()
SimplexCollection wmtk::simplex::open_star_slow (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 119 of file open_star.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::simplex::SimplexCollection::contains(), faces(), wmtk::simplex::SimplexCollection::simplex_vector(), wmtk::simplex::SimplexCollection::sort_and_clean(), and top_dimension_cofaces().
Referenced by open_star().
top_dimension_cofaces() [1/4]
SimplexCollection wmtk::simplex::top_dimension_cofaces (const Mesh & mesh, const Simplex & simplex, const bool sort_and_clean = true)
Get all top dimension cofaces of the given simplex.
For example, the top dimension cofaces in a TetMesh are all tetrahedra incident to the given simplex.
The tuple held by each Simplex is guaranteed to contain the child simplex (and all other lower order simplices of the tuple) In particular, for any simplex (t, k) for tuple t, dimension k, this function returns simplices (u,m) such that \forall i \leq k, id(t,i) = id(u,i).
Parameters
mesh The mesh to which the simplex and its cofaces belong.
simplex The simplex of which the cofaces are computed.
Returns
A SimplexCollection with all top dimension cofaces.
Definition at line 664 of file top_dimension_cofaces.cpp.
References wmtk::simplex::SimplexCollection::sort_and_clean(), top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
top_dimension_cofaces() [2/4]
void wmtk::simplex::top_dimension_cofaces (const Simplex & simplex, SimplexCollection & simplex_collection, const bool sort_and_clean = true)
Get all top dimension cofaces of the given simplex.
For example, the top dimension cofaces in a TetMesh are all tetrahedra incident to the given simplex.
The tuple held by each Simplex is guaranteed to contain the child simplex (and all other lower order simplices of the tuple) In particular, for any simplex (t, k) for tuple t, dimension k, this function returns simplices (u,m) such that \forall i \leq k, id(t,i) = id(u,i).
Parameters
simplex The simplex of which the cofaces are computed.
simplex_collection The top dimension cofaces are added to this SimplexCollection.
Definition at line 427 of file top_dimension_cofaces.cpp.
References wmtk::simplex::SimplexCollection::mesh(), wmtk::simplex::SimplexCollection::sort_and_clean(), and top_dimension_cofaces_tuples().
Referenced by wmtk::invariants::CollapseEnergyBeforeInvariant::before(), wmtk::invariants::CollapseEnergyBeforeInvariantDouble::before(), wmtk::invariants::CollapseSoftEnergyBeforeInvariant::before(), wmtk::Swap44EnergyBeforeInvariant::before(), wmtk::Swap44EnergyBeforeInvariantDouble::before(), wmtk::Swap56EnergyBeforeInvariant::before(), wmtk::Swap56EnergyBeforeInvariantDouble::before(), closed_star(), wmtk::TetMesh::TetMeshOperationExecutor::collapse_edge(), wmtk::invariants::Invariant::get_top_dimension_cofaces(), and open_star_slow().
top_dimension_cofaces() [3/4]
SimplexCollection wmtk::simplex::top_dimension_cofaces (const TetMesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 648 of file top_dimension_cofaces.cpp.
References wmtk::simplex::SimplexCollection::sort_and_clean(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
top_dimension_cofaces() [4/4]
SimplexCollection wmtk::simplex::top_dimension_cofaces (const TriMesh & mesh, const Simplex & simplex, const bool sort_and_clean)
Definition at line 632 of file top_dimension_cofaces.cpp.
References wmtk::simplex::SimplexCollection::sort_and_clean(), top_dimension_cofaces_tuples(), wmtk::Triangle, and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
top_dimension_cofaces_iterable()
TopDimensionCofacesIterable wmtk::simplex::top_dimension_cofaces_iterable (const Mesh & mesh, const Simplex & simplex)
Definition at line 5 of file top_dimension_cofaces_iterable.cpp.
top_dimension_cofaces_tuples() [1/12]
std::vector< Tuple > wmtk::simplex::top_dimension_cofaces_tuples (const EdgeMesh & mesh, const Simplex & simplex)
Definition at line 680 of file top_dimension_cofaces.cpp.
References top_dimension_cofaces_tuples().
top_dimension_cofaces_tuples() [2/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const EdgeMesh & mesh, const Simplex & simplex, SimplexCollection & collection)
Definition at line 439 of file top_dimension_cofaces.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::Edge, wmtk::EdgeMesh::is_boundary_vertex(), wmtk::log_and_throw_error(), wmtk::simplex::Simplex::primitive_type(), wmtk::EdgeMesh::switch_edge(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Referenced by wmtk::invariants::EdgeValenceInvariant::before(), wmtk::multimesh::utils::check_child_maps_valid(), cofaces_single_dimension_tuples(), link(), link_single_dimension(), wmtk::multimesh::MultiMeshManager::map_tuple_between_meshes(), open_star(), top_dimension_cofaces(), and top_dimension_cofaces_tuples().
top_dimension_cofaces_tuples() [3/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const EdgeMesh & mesh, const Simplex & simplex, std::vector< Tuple > & collection)
Definition at line 534 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::EdgeMesh::is_boundary_vertex(), wmtk::simplex::Simplex::primitive_type(), wmtk::EdgeMesh::switch_edge(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
top_dimension_cofaces_tuples() [4/12]
std::vector< Tuple > wmtk::simplex::top_dimension_cofaces_tuples (const Mesh & mesh, const Simplex & simplex)
The same as top_dimension_cofaces but it returns only a vector of tuples.
As all simplices returned by this function are of the same type, it is often more efficient to just return the vector of tuples instead of creating a SimplexCollection.
Definition at line 701 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
top_dimension_cofaces_tuples() [5/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const Mesh & mesh, const Simplex & simplex, SimplexCollection & collection)
The same as top_dimension_cofaces but it appends to a vector of tuples.
As all simplices returned by this function are of the same type, it is often more efficient to just return the vector of tuples instead of creating a SimplexCollection.
Definition at line 513 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::log_and_throw_error(), wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
top_dimension_cofaces_tuples() [6/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const Mesh & mesh, const Simplex & simplex, std::vector< Tuple > & tuples)
Definition at line 610 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::Tetrahedron, top_dimension_cofaces_tuples(), wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
top_dimension_cofaces_tuples() [7/12]
std::vector< Tuple > wmtk::simplex::top_dimension_cofaces_tuples (const TetMesh & mesh, const Simplex & simplex)
Definition at line 694 of file top_dimension_cofaces.cpp.
References top_dimension_cofaces_tuples().
top_dimension_cofaces_tuples() [8/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const TetMesh & mesh, const Simplex & simplex, SimplexCollection & collection)
Definition at line 487 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
top_dimension_cofaces_tuples() [9/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const TetMesh & mesh, const Simplex & simplex, std::vector< Tuple > & collection)
Definition at line 584 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
top_dimension_cofaces_tuples() [10/12]
std::vector< Tuple > wmtk::simplex::top_dimension_cofaces_tuples (const TriMesh & mesh, const Simplex & simplex)
Definition at line 687 of file top_dimension_cofaces.cpp.
References top_dimension_cofaces_tuples().
top_dimension_cofaces_tuples() [11/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const TriMesh & mesh, const Simplex & simplex, SimplexCollection & collection)
Definition at line 464 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
top_dimension_cofaces_tuples() [12/12]
void wmtk::simplex::top_dimension_cofaces_tuples (const TriMesh & mesh, const Simplex & simplex, std::vector< Tuple > & collection)
Definition at line 561 of file top_dimension_cofaces.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::primitive_type(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
tuples_preserving_primitive_types()
std::vector< Tuple > wmtk::simplex::tuples_preserving_primitive_types (const Mesh & mesh, const Tuple & t, const PrimitiveType ptype1, const PrimitiveType ptype2)
Compute all tuples that contain simplex(ptype1, t) and that are contained by simplex(ptype2, t).
If ptype1 and ptype2 are the same, only the input tuple is returned.
The return tuples are guaranteed to contain both input simplices.
Definition at line 9 of file tuples_preserving_primitive_types.cpp.
References wmtk::utils::primitive_range(), and wmtk::Mesh::switch_tuple().
Referenced by wmtk::components::internal::MultiMeshFromTag::get_connected_region().
vertices() [1/2]
std::vector<Tuple> wmtk::simplex::vertices (const Mesh & m, const Simplex & simplex)
Definition at line 9 of file faces_single_dimension.cpp.
References wmtk::Edge, wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.
Referenced by wmtk::components::AABBWrapper::AABBWrapper(), wmtk::components::internal::adjust_sizing_field(), wmtk::components::adjust_sizing_field(), wmtk::components::delaunay_exec(), wmtk::components::internal::delaunay_geogram(), wmtk::invariants::EnvelopeInvariant::EnvelopeInvariant(), wmtk::operations::AMIPSOptimizationSmoothing::execute(), wmtk::operations::AMIPSOptimizationSmoothingPeriodic::execute(), faces_single_dimension(), faces_single_dimension_tuples(), wmtk::components::internal::periodic_optimization(), wmtk::components::points_to_rowvectors(), wmtk::operations::composite::ProjectOperation::ProjectOperation(), wmtk::simplex::RawSimplex::RawSimplex(), wmtk::components::relative_to_absolute_length(), wmtk::components::internal::set_operation_energy_filter(), wmtk::components::set_operation_energy_filter(), wmtk::components::set_operation_energy_filter_after_sizing_field(), wmtk::components::shortestedge_collapse(), TEST_CASE(), wmtk::components::tetwild_simplification(), wmtk::components::to_points(), and wmtk::components::wildmeshing().
vertices() [2/2]
void wmtk::simplex::vertices (SimplexCollection & simplex_collection, const Simplex & simplex)
Definition at line 38 of file faces_single_dimension.cpp.
References wmtk::simplex::SimplexCollection::add(), wmtk::Edge, wmtk::simplex::SimplexCollection::mesh(), wmtk::PE, PF, wmtk::simplex::Simplex::primitive_type(), wmtk::PV, wmtk::Mesh::switch_tuple(), wmtk::Mesh::switch_tuples(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), and wmtk::Vertex.