Wildmeshing Toolkit: wmtk::components::multimesh Namespace Reference
wmtk::components::multimesh Namespace Reference
Enumerations
enum class MultiMeshType { UV , Boundary , Tag }
Functions
std::shared_ptr< Mesh > axis_aligned_fusion (const Mesh &mesh, const std::vector< bool > &operating_axis, double eps)
std::shared_ptr< Mesh > from_boundary (Mesh &mesh, const PrimitiveType ptype, const std::string &attribute_name, char value, const std::vector< wmtk::attribute::MeshAttributeHandle > &passed_attributes)
void from_facet_bijection (Mesh &parent, Mesh &child)
std::shared_ptr< Mesh > from_tag (const wmtk::attribute::MeshAttributeHandle &handle, const wmtk::attribute::MeshAttributeHandle::ValueVariant &tag_value, const std::vector< wmtk::attribute::MeshAttributeHandle > &passed_attributes)
std::pair< std::shared_ptr< Mesh >, std::shared_ptr< Mesh > > multimesh (const MultiMeshType &type, Mesh &parent, std::shared_ptr< Mesh > child, const attribute::MeshAttributeHandle parent_position_handle, const std::string &tag_name, const int64_t tag_value, const int64_t primitive)
Enumeration Type Documentation
MultiMeshType
enum wmtk::components::multimesh::MultiMeshType strong
Enumerator
UV
Boundary
Tag
Definition at line 8 of file multimesh.hpp.
Function Documentation
axis_aligned_fusion()
std::shared_ptr< Mesh > wmtk::components::multimesh::axis_aligned_fusion (const Mesh & mesh, const std::vector< bool > & operating_axis, double eps)
Definition at line 18 of file axis_aligned_fusion.cpp.
References wmtk::abs(), wmtk::cmp(), wmtk::Mesh::get_all(), wmtk::utils::EigenMatrixWriter::get_FV_matrix(), wmtk::utils::EigenMatrixWriter::get_position_matrix(), wmtk::utils::EigenMatrixWriter::get_TV_matrix(), wmtk::TriMesh::initialize(), wmtk::TetMesh::initialize(), wmtk::logger(), wmtk::multimesh::same_simplex_dimension_bijection(), wmtk::Mesh::serialize(), wmtk::mesh_utils::set_matrix_attribute(), wmtk::Tetrahedron, wmtk::Mesh::top_cell_dimension(), wmtk::Triangle, and wmtk::Vertex.
from_boundary()
std::shared_ptr< Mesh > wmtk::components::multimesh::from_boundary (Mesh & mesh, const PrimitiveType ptype, const std::string & attribute_name, char value, const std::vector< wmtk::attribute::MeshAttributeHandle > & passed_attributes)
Definition at line 10 of file from_boundary.cpp.
References wmtk::Mesh::create_accessor(), from_tag(), wmtk::Mesh::get_all(), wmtk::Mesh::is_boundary(), and wmtk::Mesh::register_attribute().
Referenced by multimesh().
from_facet_bijection()
void wmtk::components::multimesh::from_facet_bijection (Mesh & parent, Mesh & child)
Definition at line 7 of file from_facet_bijection.cpp.
References wmtk::Mesh::register_child_mesh(), and wmtk::multimesh::same_simplex_dimension_bijection().
Referenced by multimesh().
from_tag()
std::shared_ptr< Mesh > wmtk::components::multimesh::from_tag (const wmtk::attribute::MeshAttributeHandle & handle, const wmtk::attribute::MeshAttributeHandle::ValueVariant & tag_value, const std::vector< wmtk::attribute::MeshAttributeHandle > & passed_attributes)
Definition at line 28 of file from_tag.cpp.
Referenced by from_boundary().
multimesh()
std::pair< std::shared_ptr< Mesh >, std::shared_ptr< Mesh > > wmtk::components::multimesh::multimesh (const MultiMeshType & type, Mesh & parent, std::shared_ptr< Mesh > child, const attribute::MeshAttributeHandle parent_position_handle, const std::string & tag_name, const int64_t tag_value, const int64_t primitive)
Definition at line 15 of file multimesh.cpp.
References Boundary, wmtk::Mesh::capacity(), wmtk::Mesh::create_accessor(), wmtk::attribute::MeshAttributeHandle::dimension(), wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag(), from_boundary(), from_facet_bijection(), wmtk::Mesh::get_all(), wmtk::get_primitive_type_from_id(), wmtk::attribute::MeshAttributeHandle::held_type(), wmtk::Mesh::is_boundary(), wmtk::attribute::MeshAttributeHandle::Rational, wmtk::Mesh::register_attribute(), wmtk::Mesh::register_child_mesh(), wmtk::operations::AttributeTransferStrategyBase::run_on_all(), wmtk::multimesh::same_simplex_dimension_bijection(), Tag, wmtk::Mesh::top_cell_dimension(), wmtk::Mesh::top_simplex_type(), UV, and wmtk::Vertex.