Wildmeshing Toolkit: wmtk::components::multimesh::utils::AttributeDescription Struct Reference
wmtk::components::multimesh::utils::AttributeDescription Struct Reference
#include <AttributeDescription.hpp>
Public Member Functions
AttributeDescription ()=default
AttributeDescription (const AttributeDescription &)=default
AttributeDescription (AttributeDescription &&)=default
AttributeDescription & operator= (const AttributeDescription &)=default
AttributeDescription & operator= (AttributeDescription &&)=default
~AttributeDescription ()=default
AttributeDescription (const std::string_view &p, const std::optional< uint8_t > &dim, const std::optional< attribute::AttributeType > &t)
AttributeDescription (const std::string_view &p, const std::optional< PrimitiveType > &pt, const std::optional< attribute::AttributeType > &t)
std::optional< PrimitiveType > primitive_type () const
auto operator<=> (const AttributeDescription &) const -> std::strong_ordering
auto operator== (const AttributeDescription &) const -> bool
Public Attributes
std::string path
std::optional< uint8_t > dimension
std::optional< attribute::AttributeType > type
Detailed Description
Definition at line 16 of file AttributeDescription.hpp.
Constructor & Destructor Documentation
AttributeDescription() [1/5]
wmtk::components::multimesh::utils::AttributeDescription::AttributeDescription () default
AttributeDescription() [2/5]
wmtk::components::multimesh::utils::AttributeDescription::AttributeDescription (const AttributeDescription &) default
AttributeDescription() [3/5]
wmtk::components::multimesh::utils::AttributeDescription::AttributeDescription (AttributeDescription &&) default
~AttributeDescription()
wmtk::components::multimesh::utils::AttributeDescription::~AttributeDescription () default
AttributeDescription() [4/5]
wmtk::components::multimesh::utils::AttributeDescription::AttributeDescription (const std::string_view & p, const std::optional< uint8_t > & dim, const std::optional< attribute::AttributeType > & t) inline
Definition at line 30 of file AttributeDescription.hpp.
AttributeDescription() [5/5]
wmtk::components::multimesh::utils::AttributeDescription::AttributeDescription (const std::string_view & p, const std::optional< PrimitiveType > & pt, const std::optional< attribute::AttributeType > & t) inline explicit
Definition at line 39 of file AttributeDescription.hpp.
References wmtk::get_primitive_type_id().
Member Function Documentation
operator<=>()
auto wmtk::components::multimesh::utils::AttributeDescription::operator<=> (const AttributeDescription &) const -> std::strong_ordering default
operator=() [1/2]
AttributeDescription& wmtk::components::multimesh::utils::AttributeDescription::operator= (AttributeDescription &&) default
operator=() [2/2]
AttributeDescription& wmtk::components::multimesh::utils::AttributeDescription::operator= (const AttributeDescription &) default
operator==()
auto wmtk::components::multimesh::utils::AttributeDescription::operator== (const AttributeDescription &) const -> bool default
primitive_type()
std::optional< PrimitiveType > wmtk::components::multimesh::utils::AttributeDescription::primitive_type () const
Definition at line 58 of file AttributeDescription.cpp.
References dimension, and wmtk::get_primitive_type_from_id().
Referenced by wmtk::components::multimesh::utils::get_attribute().
Member Data Documentation
dimension
std::optional<uint8_t> wmtk::components::multimesh::utils::AttributeDescription::dimension
Definition at line 19 of file AttributeDescription.hpp.
Referenced by wmtk::components::multimesh::utils::detail::make_named_error_string(), and primitive_type().
path
std::string wmtk::components::multimesh::utils::AttributeDescription::path
Definition at line 18 of file AttributeDescription.hpp.
Referenced by wmtk::components::multimesh::utils::detail::decompose_attribute_path(), and wmtk::components::multimesh::utils::detail::make_named_error_string().
type
std::optional<attribute::AttributeType> wmtk::components::multimesh::utils::AttributeDescription::type
Definition at line 20 of file AttributeDescription.hpp.
Referenced by wmtk::components::multimesh::utils::get_attribute(), and wmtk::components::multimesh::utils::detail::make_named_error_string().
The documentation for this struct was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/utils/AttributeDescription.hpp
components/multimesh/src/wmtk/components/multimesh/utils/AttributeDescription.cpp