Wildmeshing Toolkit: components/tests/test_component_delaunay.cpp File Reference
test_component_delaunay.cpp File Reference
#include <random>
#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>
#include <paraviewo/VTUWriter.hpp>
#include <wmtk/components/delaunay/delaunay.hpp>
#include <wmtk/components/delaunay/internal/delaunay_2d.hpp>
#include <wmtk/components/delaunay/internal/delaunay_3d.hpp>
#include <wmtk/components/delaunay/internal/delaunay_geogram.hpp>
#include <wmtk/components/input/input.hpp>
#include <wmtk/components/output/output.hpp>
Typedefs
using json = nlohmann::json
Functions
void check_p_is_contained_in_v (const Eigen::Ref< Eigen::MatrixXd > p, const Eigen::Ref< Eigen::MatrixXd > v)
TEST_CASE ("delaunay_2d_five_points", "[components][delaunay]")
TEST_CASE ("delaunay_2d_random", "[components][delaunay]")
TEST_CASE ("delaunay_3d_nine_points", "[components][delaunay]")
TEST_CASE ("delaunay_3d_random", "[components][delaunay]")
TEST_CASE ("delaunay_throw", "[components][delaunay]")
TEST_CASE ("delaunay_empty_points", "[components][delaunay]")
Variables
const std::filesystem::path data_dir = WMTK_DATA_DIR
Typedef Documentation
json
using json = nlohmann::json
Definition at line 13 of file test_component_delaunay.cpp.
Function Documentation
check_p_is_contained_in_v()
void check_p_is_contained_in_v (const Eigen::Ref< Eigen::MatrixXd > p, const Eigen::Ref< Eigen::MatrixXd > v)
Definition at line 18 of file test_component_delaunay.cpp.
Referenced by TEST_CASE().
TEST_CASE() [1/6]
TEST_CASE ("delaunay_2d_five_points" , "" [components][delaunay])
Definition at line 80 of file test_component_delaunay.cpp.
References wmtk::components::internal::delaunay_2d(), wmtk::simplex::faces(), and wmtk::simplex::vertices().
TEST_CASE() [2/6]
TEST_CASE ("delaunay_2d_random" , "" [components][delaunay])
Definition at line 101 of file test_component_delaunay.cpp.
References check_p_is_contained_in_v(), wmtk::components::internal::delaunay_2d(), wmtk::simplex::faces(), and wmtk::simplex::vertices().
TEST_CASE() [3/6]
TEST_CASE ("delaunay_3d_nine_points" , "" [components][delaunay])
Definition at line 125 of file test_component_delaunay.cpp.
References wmtk::components::internal::delaunay_3d(), wmtk::simplex::faces(), and wmtk::simplex::vertices().
TEST_CASE() [4/6]
TEST_CASE ("delaunay_3d_random" , "" [components][delaunay])
Definition at line 150 of file test_component_delaunay.cpp.
References check_p_is_contained_in_v(), wmtk::components::internal::delaunay_3d(), wmtk::simplex::faces(), and wmtk::simplex::vertices().
TEST_CASE() [5/6]
TEST_CASE ("delaunay_empty_points" , "" [components][delaunay])
Definition at line 192 of file test_component_delaunay.cpp.
References wmtk::components::internal::delaunay_geogram(), wmtk::simplex::faces(), and wmtk::simplex::vertices().
TEST_CASE() [6/6]
TEST_CASE ("delaunay_throw" , "" [components][delaunay])
Definition at line 175 of file test_component_delaunay.cpp.
References wmtk::components::internal::delaunay_geogram().
Variable Documentation
data_dir
const std::filesystem::path data_dir = WMTK_DATA_DIR
Definition at line 15 of file test_component_delaunay.cpp.