
#include "autogenerated_tables.hpp"
// DO NOT MODIFY, autogenerated from the /scripts directory
namespace wmtk::autogen::edge_mesh {

const int8_t auto_valid_tuples[2][1] = {{0}, {1}};

const int8_t auto_valid_tuple_indices[2] = {0, 1};

const int8_t auto_all_to_valid_tuple_indices[2] = {0, 1};

const int8_t auto_valid_switch_table[2][1] = {{1}, {0}};

const int8_t auto_valid_switch_product_table[2][2] = {{0, 1}, {1, 0}};

const int8_t auto_valid_switch_inverse_table[2] = {0, 1};

const int8_t auto_valid_tuple_switch_indices[3] = {1, 0, 1};

} // namespace wmtk::autogen::edge_mesh
