#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include <wmtk/PrimitiveType.hpp>

namespace wmtk::autogen::edge_mesh {
int8_t simplex_index_from_valid_index(int8_t valid_index, wmtk::PrimitiveType type);

}

#include "simplex_index_from_valid_index.hxx"
