#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include <wmtk/Tuple.hpp>

namespace wmtk::autogen::edge_mesh {
int8_t simplex_index_from_valid_index(wmtk::PrimitiveType type, int8_t valid_index);

}

#include "simplex_from_valid_index.hxx"
#