#include "all_valid_local_tuples.hpp"
#include <cassert>
#include <wmtk/autogen/SimplexDart.hpp>
#include <wmtk/autogen/tet_mesh/autogenerated_tables.hpp>
#include <wmtk/autogen/tet_mesh/local_id_table_offset.hpp>
#include <wmtk/autogen/tri_mesh/autogenerated_tables.hpp>
#include <wmtk/autogen/tri_mesh/local_id_table_offset.hpp>

#include <algorithm>
#include <wmtk/autogen/is_ccw.hpp>
#include <wmtk/autogen/tet_mesh/is_ccw.hpp>
#include <wmtk/autogen/tri_mesh/is_ccw.hpp>
using namespace wmtk::autogen;
namespace wmtk::tests {
std::vector<PrimitiveType> primitives_up_to(PrimitiveType pt)
{
    std::vector<PrimitiveType> r;

    switch (pt) {
    case PrimitiveType::Tetrahedron: r.emplace_back(PrimitiveType::Triangle); [[fallthrough]];
    case PrimitiveType::Triangle: r.emplace_back(PrimitiveType::Edge); [[fallthrough]];
    case PrimitiveType::Edge: r.emplace_back(PrimitiveType::Vertex); [[fallthrough]];
    case PrimitiveType::Vertex:
    default: break;
    }
    return r;
}


int64_t max_tuple_count(PrimitiveType pt)
{
    switch (pt) {
    case PrimitiveType::Triangle:
        return int64_t(std::size(wmtk::autogen::tri_mesh::auto_2d_table_ccw));
    case PrimitiveType::Tetrahedron:
        return int64_t(std::size(wmtk::autogen::tet_mesh::auto_3d_table_ccw));
    case PrimitiveType::Edge: return 2;
    case PrimitiveType::Vertex: break;
    }
    return -1;
}

Tuple tuple_from_offset_id(PrimitiveType pt, int offset)
{
    int64_t lvid = -1, leid = -1, lfid = -1, gcid = -1, hash = -1;

    switch (pt) {
    case PrimitiveType::Triangle: {
        // bug in the standard? tie should work :-(
        auto r = tri_mesh::lvid_leid_from_table_offset(offset);
        lvid = r[0];
        leid = r[1];
    } break;
    case PrimitiveType::Tetrahedron: {
        auto r = tet_mesh::lvid_leid_lfid_from_table_offset(offset);
        lvid = r[0];
        leid = r[1];
        lfid = r[2];
    } break;
    case PrimitiveType::Edge: lvid = offset;
    case PrimitiveType::Vertex: break;
    }

    Tuple r(lvid, leid, lfid, gcid, hash);
    // if (!tuple_is_valid_for_ccw(pt, r)) {
    //     r = Tuple();
    // }
    return r;
}

std::vector<Tuple> all_valid_local_tuples(PrimitiveType pt)
{
    wmtk::autogen::SimplexDart sd(pt);
    std::vector<Tuple> tups;
    size_t size = sd.size();
    tups.reserve(size);
    for (int8_t idx = 0; idx < size; ++idx) {
        tups.emplace_back(sd.tuple_from_valid_index(0, idx));
    }

    return tups;
}
} // namespace wmtk::tests
