// Autogenerated by 2d_switch_tables.ipynb

namespace wmtk { namespace autogen {
static long auto_2d_edges[3][2] = {
  {1, 2},
  {0, 2},
  {0, 1}
};
static long auto_2d_table_vertex[9][2] = {
  {-1, -1},
  {2, 1},
  {1, 2},
  {2, 0},
  {-1, -1},
  {0, 2},
  {1, 0},
  {0, 1},
  {-1, -1}
};
static long auto_2d_table_edge[9][2] = {
  {-1, -1},
  {0, 2},
  {0, 1},
  {1, 2},
  {-1, -1},
  {1, 0},
  {2, 1},
  {2, 0},
  {-1, -1}
};
static long auto_2d_table_ccw[9][1] = {
  {-1},
  {0},
  {1},
  {1},
  {-1},
  {0},
  {0},
  {1},
  {-1}
};
static long auto_2d_table_complete_vertex[3][2] = {
  {0, 1},
  {1, 0},
  {2, 0}
};
static long auto_2d_table_complete_edge[3][2] = {
  {1, 0},
  {0, 1},
  {0, 2}
};
}}
