// Autogenerated by 2d_switch_tables.ipynb

static int auto_2d_edges[3][2] = {
  {1, 2},
  {0, 2},
  {0, 1}
};
static int auto_3d_table_vertex[9][2] = {
  {-1, -1},
  {2, 1},
  {1, 2},
  {2, 0},
  {-1, -1},
  {0, 2},
  {1, 0},
  {0, 1},
  {-1, -1}
};
static int auto_3d_table_edge[9][2] = {
  {-1, -1},
  {0, 2},
  {0, 1},
  {1, 2},
  {-1, -1},
  {1, 0},
  {2, 1},
  {2, 0},
  {-1, -1}
};
