#include <Eigen/Dense>

#include "Macros.h"


WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector4d);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector3d);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector2d);

WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector4f);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector3f);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector2f);

WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector4i);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector3i);
WMTK_HIGHFIVE_DECLARE_TYPE(Eigen::Vector2i);

