#include "TriMesh.hpp"

#include <wmtk/utils/trimesh_topology_initialization.h>
#include <wmtk/autogen/autogenerated_2d_tables.hpp>
#include <wmtk/utils/Logger.hpp>

namespace wmtk {
TriMesh::TriMesh()
    : Mesh(3)
    , m_vf_handle(register_attribute<long>("m_vf", PrimitiveType::Vertex, 1))
    , m_ef_handle(register_attribute<long>("m_ef", PrimitiveType::Edge, 1))
    , m_fv_handle(register_attribute<long>("m_fv", PrimitiveType::Face, 3))
    , m_fe_handle(register_attribute<long>("m_fe", PrimitiveType::Face, 3))
    , m_ff_handle(register_attribute<long>("m_ff", PrimitiveType::Face, 3))
{}

void TriMesh::split_edge(const Tuple& t)
{
    // delete star(edge)

    // create new vertex

    // create new edges

    // create new faces

    // glue the topology
}
void TriMesh::collapse_edge(const Tuple& t)
{
    // delete cstar(edge) intersect star(v1(edge))

    // glue the topology
}

long TriMesh::id(const Tuple& tuple, const PrimitiveType& type) const
{
    switch (type) {
    case PrimitiveType::Vertex: {
        ConstAccessor<long> fv_accessor = create_accessor<long>(m_fv_handle);
        auto fv = fv_accessor.vector_attribute(tuple);
        return fv(tuple.m_local_vid);
        break;
    }
    case PrimitiveType::Edge: {
        ConstAccessor<long> fe_accessor = create_accessor<long>(m_fe_handle);
        auto fe = fe_accessor.vector_attribute(tuple);
        return fe(tuple.m_local_eid);
        break;
    }
    case PrimitiveType::Face: {
        return tuple.m_global_cid;
        break;
    }
    default: throw std::runtime_error("Tuple id: Invalid primitive type");
    }
}

bool TriMesh::is_boundary(const Tuple& tuple) const
{
    assert(is_valid(tuple));
    ConstAccessor<long> ff_accessor = create_accessor<long>(m_ff_handle);
    return ff_accessor.vector_attribute(tuple)(tuple.m_local_eid) < 0;
}

Tuple TriMesh::switch_tuple(const Tuple& tuple, const PrimitiveType& type) const
{
    assert(is_valid(tuple));
    bool ccw = is_ccw(tuple);
    int offset = tuple.m_local_vid * 3 + tuple.m_local_eid;

    switch (type) {
    case PrimitiveType::Vertex:
        return Tuple(
            wmtk::autogen::auto_2d_table_vertex[offset][0],
            wmtk::autogen::auto_2d_table_vertex[offset][1],
            tuple.m_local_fid,
            tuple.m_global_cid,
            tuple.m_hash);

    case PrimitiveType::Edge:
        return Tuple(
            wmtk::autogen::auto_2d_table_edge[offset][0],
            wmtk::autogen::auto_2d_table_edge[offset][1],
            tuple.m_local_fid,
            tuple.m_global_cid,
            tuple.m_hash);
    case PrimitiveType::Face: {
        const long gvid = id(tuple, PrimitiveType::Vertex);
        const long geid = id(tuple, PrimitiveType::Edge);

        ConstAccessor<long> ff_accessor = create_accessor<long>(m_ff_handle);
        auto ff = ff_accessor.vector_attribute(tuple);

        long gcid_new = ff(tuple.m_local_eid);
        long lvid_new, leid_new;

        ConstAccessor<long> fv_accessor = create_accessor<long>(m_fv_handle);
        auto fv = fv_accessor.vector_attribute(gcid_new);

        ConstAccessor<long> fe_accessor = create_accessor<long>(m_fe_handle);
        auto fe = fe_accessor.vector_attribute(gcid_new);

        for (long i = 0; i < 3; ++i) {
            if (fe(i) == geid) {
                leid_new = i;
            }
            if (fv(i) == gvid) {
                lvid_new = i;
            }
        }
        const Tuple res(lvid_new, leid_new, tuple.m_local_fid, gcid_new, tuple.m_hash);
        assert(is_valid(res));
        return res;
    }
    default: throw std::runtime_error("Tuple switch: Invalid primitive type"); break;
    }
}

bool TriMesh::is_ccw(const Tuple& tuple) const
{
    assert(is_valid(tuple));
    int offset = tuple.m_local_vid * 3 + tuple.m_local_eid;
    return autogen::auto_2d_table_ccw[offset][0] == 1;
}

void TriMesh::initialize(
    Eigen::Ref<const RowVectors3l> FV,
    Eigen::Ref<const RowVectors3l> FE,
    Eigen::Ref<const RowVectors3l> FF,
    Eigen::Ref<const VectorXl> VF,
    Eigen::Ref<const VectorXl> EF)
{
    // reserve memory for attributes


    std::vector<long> cap{static_cast<long>(VF.rows()),
                          static_cast<long>(EF.rows()),
                          static_cast<long>(FF.rows())};

    set_capacities(cap);
    reserve_attributes_to_fit();

    // get Accessors for topology
    Accessor<long> fv_accessor = create_accessor<long>(m_fv_handle);
    Accessor<long> fe_accessor = create_accessor<long>(m_fe_handle);
    Accessor<long> ff_accessor = create_accessor<long>(m_ff_handle);
    Accessor<long> vf_accessor = create_accessor<long>(m_vf_handle);
    Accessor<long> ef_accessor = create_accessor<long>(m_ef_handle);
    // iterate over the matrices and fill attributes
    for (long i = 0; i < capacity(PrimitiveType::Face); ++i) {
        fv_accessor.vector_attribute(i) = FV.row(i).transpose();
        fe_accessor.vector_attribute(i) = FE.row(i).transpose();
        ff_accessor.vector_attribute(i) = FF.row(i).transpose();
    }
    // m_vf
    for (long i = 0; i < capacity(PrimitiveType::Vertex); ++i) {
        vf_accessor.scalar_attribute(i) = VF(i);
    }
    // m_ef
    for (long i = 0; i < capacity(PrimitiveType::Edge); ++i) {
        ef_accessor.scalar_attribute(i) = EF(i);
    }
}

void TriMesh::initialize(Eigen::Ref<const RowVectors3l> F)
{
    auto [FE, FF, VF, EF] = trimesh_topology_initialization(F);
    initialize(F, FE, FF, VF, EF);
}

long TriMesh::_debug_id(const Tuple& tuple, const PrimitiveType& type) const
{
    // do not remove this warning!
    wmtk::logger().warn("This function must only be used for debugging!!");
    return id(tuple, type);
}

Tuple TriMesh::tuple_from_id(const PrimitiveType type, const long gid) const
{
    switch (type) {
    case PrimitiveType::Vertex: {
        return vertex_tuple_from_id(gid);
        break;
    }
    case PrimitiveType::Edge: {
        return edge_tuple_from_id(gid);
        break;
    }
    case PrimitiveType::Face: {
        return face_tuple_from_id(gid);
        break;
    }
    case PrimitiveType::Tetrahedron: {
        throw std::runtime_error("no tet tuple supported for trimesh");
        break;
    }
    default: throw std::runtime_error("Invalid primitive type");
    }
}

Tuple TriMesh::vertex_tuple_from_id(long id) const
{
    ConstAccessor<long> vf_accessor = create_accessor<long>(m_vf_handle);
    auto f = vf_accessor.scalar_attribute(id);
    ConstAccessor<long> fv_accessor = create_accessor<long>(m_fv_handle);
    auto fv = fv_accessor.vector_attribute(f);
    for (long i = 0; i < 3; ++i) {
        if (fv(i) == id) {
            assert(autogen::auto_2d_table_complete_vertex[i][0] == i);
            const long leid = autogen::auto_2d_table_complete_vertex[i][1];
            Tuple v_tuple = Tuple(i, leid, -1, f, 0);
            assert(is_ccw(v_tuple));
            assert(is_valid(v_tuple));
            return v_tuple;
        }
    }
    throw std::runtime_error("vertex_tuple_from_id failed");
}

Tuple TriMesh::edge_tuple_from_id(long id) const
{
    ConstAccessor<long> ef_accessor = create_accessor<long>(m_ef_handle);
    auto f = ef_accessor.scalar_attribute(id);
    ConstAccessor<long> fe_accessor = create_accessor<long>(m_fe_handle);
    auto fe = fe_accessor.vector_attribute(f);
    for (long i = 0; i < 3; ++i) {
        if (fe(i) == id) {
            assert(autogen::auto_2d_table_complete_edge[i][1] == i);
            const long lvid = autogen::auto_2d_table_complete_edge[i][0];

            Tuple e_tuple = Tuple(lvid, i, -1, f, 0);
            assert(is_ccw(e_tuple));
            assert(is_valid(e_tuple));
            return e_tuple;
        }
    }
    throw std::runtime_error("edge_tuple_from_id failed");
}

Tuple TriMesh::face_tuple_from_id(long id) const
{
    Tuple f_tuple = Tuple(
        autogen::auto_2d_table_complete_vertex[0][0],
        autogen::auto_2d_table_complete_vertex[0][1],
        -1,
        id,
        0);
    assert(is_ccw(f_tuple));
    assert(is_valid(f_tuple));
    return f_tuple;
}

bool TriMesh::is_valid(const Tuple& tuple) const
{
    int offset = tuple.m_local_vid * 3 + tuple.m_local_eid;
    return tuple.m_local_vid >= 0 && tuple.m_local_eid >= 0 && tuple.m_global_cid >= 0 &&
           autogen::auto_2d_table_ccw[offset][0] >= 0;
}

} // namespace wmtk
