#pragma once

// DO NOT MODIFY, autogenerated from the /scripts directory

namespace wmtk::autogen::tet_mesh {
     
    extern const long auto_3d_edges[6][2];
     
    extern const long auto_3d_faces[4][3];
     
    extern const long auto_3d_table_vertex[96][3];
     
    extern const long auto_3d_table_edge[96][3];
     
    extern const long auto_3d_table_face[96][3];
     
    extern const long auto_3d_table_ccw[96];
     
    extern const long auto_3d_table_complete_vertex[4][3];
     
    extern const long auto_3d_table_complete_edge[6][3];
     
    extern const long auto_3d_table_complete_face[4][3];
    
}