
#include "is_ccw.hpp"
#include <wmtk/utils/TupleInspector.hpp>
#include <cassert>
#include <wmtk/Tuple.hpp>
#include "autogenerated_tables.hpp"
#include "local_id_table_offset.hpp"

namespace wmtk::autogen::tet_mesh {
bool is_ccw(const Tuple& tuple)
{
    assert(tuple_is_valid_for_ccw(tuple));
    using namespace utils;
    const long offset = local_id_table_offset(tuple);
    return auto_3d_table_ccw[offset] == 1;
}
bool tuple_is_valid_for_ccw(const Tuple& tuple)
{
    using namespace utils;
    const long offset = local_id_table_offset(tuple);
    return auto_3d_table_ccw[offset] != -1;
}
} // namespace wmtk::autogen::tet_mesh
