
#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include <wmtk/Tuple.hpp>

namespace wmtk::autogen::tet_mesh {
int8_t valid_index_from_tuple(const Tuple& t);

}

#include "valid_index_from_tuple.hxx"
