#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include "autogenerated_tables.hpp"
#include "local_id_table_offset.hpp"
#include "valid_index_from_tuple.hpp"
namespace wmtk::autogen::tet_mesh {
inline int8_t valid_index_from_tuple(const Tuple& t)
{
    {
        const int64_t offset = local_id_table_offset(t);
        const int8_t valid_index = auto_all_to_valid_tuple_indices[offset];
        return valid_index;
    }
}
} // namespace wmtk::autogen::tet_mesh
