#pragma once

// DO NOT MODIFY, autogenerated from the /scripts directory

namespace wmtk::autogen::tri_mesh {
     
    extern const long auto_2d_edges[3][2];
     
    extern const long auto_2d_table_vertex[9][2];
     
    extern const long auto_2d_table_edge[9][2];
     
    extern const long auto_2d_table_ccw[9][1];
     
    extern const long auto_2d_table_complete_vertex[3][2];
     
    extern const long auto_2d_table_complete_edge[3][2];
    
}