
#include "autogenerated_tables.hpp"
// DO NOT MODIFY, autogenerated from the /scripts directory
namespace wmtk::autogen::tri_mesh {

const int64_t auto_2d_edges[3][2] = {{1, 2}, {0, 2}, {0, 1}};

const int64_t auto_2d_table_vertex[9][2] =
    {{-1, -1}, {2, 1}, {1, 2}, {2, 0}, {-1, -1}, {0, 2}, {1, 0}, {0, 1}, {-1, -1}};

const int64_t auto_2d_table_edge[9][2] =
    {{-1, -1}, {0, 2}, {0, 1}, {1, 2}, {-1, -1}, {1, 0}, {2, 1}, {2, 0}, {-1, -1}};

const int64_t auto_2d_table_ccw[9] = {-1, 0, 1, 1, -1, 0, 0, 1, -1};

const int64_t auto_2d_table_complete_vertex[3][2] = {{0, 2}, {1, 0}, {2, 1}};

const int64_t auto_2d_table_complete_edge[3][2] = {{1, 0}, {2, 1}, {0, 2}};

} // namespace wmtk::autogen::tri_mesh