#pragma once

// DO NOT MODIFY, autogenerated from the /scripts directory

#include <cstdint>
namespace wmtk::autogen::tri_mesh {
// lvids for a particular leid
extern const int64_t auto_2d_edges[3][2];

// vertex switch's (tuple_index -> [lvid,leid])
extern const int64_t auto_2d_table_vertex[9][2];

// edge switch's (tuple_index -> [lvid,leid])
extern const int64_t auto_2d_table_edge[9][2];

// (tuple_index) -> is_ccw
extern const int64_t auto_2d_table_ccw[9];

// lvid -> a ccw [lvid,leid]
extern const int64_t auto_2d_table_complete_vertex[3][2];

// leid -> a ccw [lvid,leid]
extern const int64_t auto_2d_table_complete_edge[3][2];


} // namespace wmtk::autogen::tri_mesh