
#include "autogenerated_tables.hpp"
// DO NOT MODIFY, autogenerated from the /scripts directory
namespace wmtk::autogen::tri_mesh {

const int64_t auto_2d_edges[3][2] = {{1, 2}, {0, 2}, {0, 1}};

const int64_t auto_2d_table_vertex[9][2] =
    {{-1, -1}, {2, 1}, {1, 2}, {2, 0}, {-1, -1}, {0, 2}, {1, 0}, {0, 1}, {-1, -1}};

const int64_t auto_2d_table_edge[9][2] =
    {{-1, -1}, {0, 2}, {0, 1}, {1, 2}, {-1, -1}, {1, 0}, {2, 1}, {2, 0}, {-1, -1}};

const int64_t auto_2d_table_ccw[9] = {-1, 0, 1, 1, -1, 0, 0, 1, -1};

const int64_t auto_2d_table_complete_vertex[3][2] = {{0, 2}, {1, 0}, {2, 1}};

const int64_t auto_2d_table_complete_edge[3][2] = {{1, 0}, {2, 1}, {0, 2}};

const int8_t auto_valid_tuples[6][2] = {{0, 1}, {0, 2}, {1, 0}, {1, 2}, {2, 0}, {2, 1}};

const int8_t auto_valid_tuple_indices[6] = {1, 2, 3, 5, 6, 7};

const int8_t auto_all_to_valid_tuple_indices[9] = {-1, 0, 1, 2, -1, 3, 4, 5, -1};

const int8_t auto_valid_switch_table[6][2] = {{5, 1}, {3, 0}, {4, 3}, {1, 2}, {2, 5}, {0, 4}};

const int8_t auto_valid_switch_product_table[6][6] = {
    {1, 0, 4, 5, 2, 3},
    {0, 1, 2, 3, 4, 5},
    {3, 2, 5, 4, 0, 1},
    {2, 3, 0, 1, 5, 4},
    {5, 4, 3, 2, 1, 0},
    {4, 5, 1, 0, 3, 2}};

const int8_t auto_valid_switch_inverse_table[6] = {0, 1, 5, 3, 4, 2};

} // namespace wmtk::autogen::tri_mesh