
#pragma once

#include <cassert>
#include "autogenerated_tables.hpp"
#include "local_id_table_offset.hpp"

namespace wmtk::autogen::tri_mesh {
inline bool is_ccw(const Tuple& tuple)
{
    assert(tuple_is_valid_for_ccw(tuple));
    const int64_t offset = local_id_table_offset(tuple);
    return auto_2d_table_ccw[offset] == 1;
}
inline bool tuple_is_valid_for_ccw(const Tuple& tuple)
{
    if (tuple.is_null()) {
        return false;
    }
    const int64_t offset = local_id_table_offset(tuple);
    return auto_2d_table_ccw[offset] != -1;
}
} // namespace wmtk::autogen::tri_mesh
