
#include "is_ccw.hpp"
#include <wmtk/autogen/utils/TupleInspector.hpp>
#include "autogenerated_tables.hpp"

namespace wmtk::autogen::tri_mesh {
bool is_ccw(const Tuple& t)
{
    using namespace utils;
    int offset = TupleInspector::local_vid(t) * 3 + TupleInspector::local_eid(t);
    return auto_2d_table_ccw[offset][0] == 1;
}
} // namespace wmtk::autogen::tri_mesh
