#pragma once
#include <wmtk/PrimitiveType.hpp>
#include "autogenerated_tables.hpp"

namespace wmtk::autogen::tri_mesh {
class SimplexDart
{
public:
    SimplexDart();

    static int8_t product(int8_t a, int8_t b) { return auto_valid_switch_product_table[a][b]; }
    static int8_t inverse(int8_t a) { return auto_valid_switch_inverse_table[a]; }
    static int8_t primitive_as_index(wmtk::PrimitiveType pt)
    {
        return auto_valid_tuple_switch_indices[get_primitive_type_id(pt)];
    }
    static int8_t identity() { return primitive_as_index(wmtk::PrimitiveType::Triangle); }
};

} // namespace wmtk::autogen::tri_mesh
