// DO NOT MODIFY, autogenerated from the /scripts directory
#pragma once
namespace wmtk::autogen::tri_mesh {

Tuple tuple_from_valid_index(int64_t global_cid, int8_t valid_tuple_index);

} // namespace wmtk::autogen::tri_mesh

#include "tuple_from_valid_index.hxx"
