name: Docs

on:
  push:
    branches: [main]
  pull_request: # for testing only

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: |
          wget "https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.linux.bin.tar.gz"
          tar -xzf "doxygen-1.9.8.linux.bin.tar.gz"
          cd "doxygen-1.9.8"
          sudo make install
          sudo apt-get install graphviz

      - name: Config
        run: |
          mkdir -p build
          cd build
          cmake -DWMTK_BUILD_DOCS=ON ..
          make wmtk_doc_doxygen
          touch docs_doxygen/html/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/docs_doxygen/html/ # The folder the action should deploy.

      - name: Launch JSON Spec Documentation Runner
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.WMTK_DOCS_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'wildmeshing',
              repo: 'wildmeshing.github.io',
              workflow_id: 'build.yml',
              ref: 'docs'
            })
